### ISSUE TITLE
Severe duplication issue

### ISSUE THREAD

**Issue by MathiasYde** [gnembon/fabric-carpet#100]
Hi, I noticed a problem with carpet.
Whenever I Ctrl-Q an item in a crafting table, it will duplicate the item continuously, causing an insane amount of lag and inevitably, crashing the server. This seems to be the cause of all crafted items. See the image below.

![image](https://user-images.githubusercontent.com/35201354/68509836-37910680-0272-11ea-90f3-0acff19b6d06.png)

We are running a server on **19w44a** with carpet mod being on version **1.2.1+v191030**
I think it is caused by carpet because it does not have this effect in singleplayer with pure vanilla.

**Comment by DeadlyMC** [comment]
This happens when only with autoCraftingTable turned on.. A fix is being worked upon.. https://github.com/gnembon/carpet-extra/issues/15

**Comment by gnembon** [comment]
Fix is already merged in. Will be up for grabs next release.

**Comment by gnembon** [comment]
fixed in v1.2.3
