### ISSUE TITLE
 movableBlockEntities option makes some setup unmovable (related with pushLimit)

### ISSUE THREAD

**Issue by aria1th** [gnembon/fabric-carpet#1003]
![2021-07-14_15 56 51](https://user-images.githubusercontent.com/35677394/125577257-3acea285-d000-43d6-8df0-b77e0920d4b3.png)
[cobble26.5k.zip](https://github.com/gnembon/fabric-carpet/files/6814150/cobble26.5k.zip)

used Litematic file + where you can check it
I searched issue tracker but noone has reported it so I think its not fixed at recent version.

Issue  : MBE disables some TNT duping setup in weird way.

How to reproduce:
paste that litematic (or setup the duper)

/carpet  movableBlockEntities false and check it working.
/carpet  movableBlockEntities true then it does not move the setup.

Why it happens?
It seems like messing up pushlimit codes.

do /carpet pushLimit 14, then it works again.

**Comment by James103** [comment]
That is caused by the movable block entities in your piston setup counting towards the piston push limit like regular blocks, which is most likely intended.

**Comment by aria1th** [comment]
it was already a moveable block (grindstone), but seems like its double counted.

**Comment by aria1th** [comment]
Invalid
