### ISSUE TITLE
[Suggestion] renewableBlackstone Requires Soul Sand

### ISSUE THREAD

**Issue by MinecraftSeaTurtle** [gnembon/fabric-carpet#1007]
I'm designing a basalt generator, and the way I stacked it, there is ice above the lava, making it turn into blackstone when renewableBlackstone is true. I like the renewable blackstone, and I think just having it require soul sand (or at least an option perhaps?) would be a good solution, as it would still have normal basalt generation but also still have the renewable blackstone.

**Comment by MinecraftSeaTurtle** [comment]
I'm probably just being selfish and this probably won't be added, so I'm closing this issue. Maybe I'll write a scarpet app...

**Comment by Guimoute** [comment]
@MinecraftSeaTurtle I have not found a way to do something on block/fluid tick in Scarpet. I will ask there but it does not seem possible as of now.
