### ISSUE TITLE
[Scarpet] Default (uninitialized) variable is 0, should probably be `null`

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1012]
Assuming this since `uninitializedVariable == null` is false, and `NumericValue` delegates `equals` to `NullValue`, that only returns `true` if instanceof `NullValue`.

Would it be a (good) idea to change it to null? Or could it break too many things?

**Comment by gnembon** [comment]
default 0 value is perl standard and for counting reasons. As long as `foo += 1` still works, and produces `foo==1` then I don't mind  changing that to `null`

**Comment by Firigion** [comment]
Losts of code relies on adding to unassigned values.

**Comment by altrisi** [comment]
A NullValue is actually a NumericValue of 0 with a few changes, but for most things it works exactly as 0.

Only differences are:
- It's not `== 0` (it's only `== null`). This allows determining if a variable was initialized in a loop, for example
- It has weird handling of comparison (it's < 0 for some reason)
- Opposite of it (`-null`) is `null` (which is the same as `-0` being `0`, no change here)
- `slice()` and `in` (I think `~`) on it returns `null`
- `split()` on it returns an empty list
- Oh and it has a `length()` of `0`

For the rest of operations it's used as a numerical `0`, so `null + 1 == 1`, etc.

**Comment by altrisi** [comment]
Oh and converting it to a string is `"null"`.

**Comment by altrisi** [comment]
Fixed in #1307 (1432f06)
