### ISSUE TITLE
renewableIce rule is causing anvil duping in 1.17

### ISSUE THREAD

**Issue by TimelyToga** [gnembon/fabric-carpet#1013]
Whenever I drop an anvil onto ice blocks, the falling anvil drops as an item. So in the tower of ice blocks that the anvil falls through, I end up getting 3 duped anvil items by the time packed ice is formed.

**Comment by gnembon** [comment]
that should be fixed in 1.17.1

**Comment by TimelyToga** [comment]
Thanks @gnembon 😄
