### ISSUE TITLE
on player right clicks event does not work for fake players

### ISSUE THREAD

**Issue by aria1th** [gnembon/fabric-carpet#1016]
**To Reproduce**
`/script run __on_player_right_clicks_block(player, item_tuple, hand, block, face, hitvec) ->print(item_tuple);`

**Expected behavior**

real player would return item tuple.
fake player would not return item tuple.

`__on_player_places_block` would return item tuple properly tho.

**Environment**
 - Carpet version: 1.4.40 (Was it fixed in 1.4.43? I'm getting crash at 1.17)
 - Minecraft version:1.17 

**Additional context**
**replace_hotbar.sc** is affected by this. simple fix for it is adding on_player_places_block event.

> __on_player_places_block(player, item_tuple, hand, block)->
> 	if (item = player ~ 'holds', refill(player, 'mainhand', item));

**Comment by altrisi** [comment]
I think this is the same as #307.

**Comment by altrisi** [comment]
This is covered by issue #1491.
