### ISSUE TITLE
I lag extremely when turning on Moveable tile entities

### ISSUE THREAD

**Issue by LordM4x** [gnembon/fabric-carpet#1021]
I am using:
Fabric 1.17.1
with these mods:
![image](https://user-images.githubusercontent.com/82895323/126553583-ec13381a-ea7e-4ee2-a21d-2935b0c627d7.png)
As soon as i turn on Moveable tile entities i instantly begin to dive down to 1 FPS from 200+ FPS as long as im looking in the direction of the tile entities(Sodium rendering option).

**Comment by gnembon** [comment]
Would be helpful if you narrowed down the mod combination that causes it, otherwise - don't turn that on

**Comment by LordM4x** [comment]
I found the solution the Sodium mods causes it.
