### ISSUE TITLE
Identical shulker boxes stack to 64 with stackableShulkerBoxes enabled.

### ISSUE THREAD

**Issue by Reavershark** [gnembon/fabric-carpet#1025]
With stackableShulkerBoxes enabled, trying to click together shulker boxes in an inventory will stack *any* identical boxes together, even full ones.

They should only stack if they are the same color and are both empty.
What currently happens is that they can stack if they have the same color and *the same contents*.

This just seems to be the same behaviour as other stackables with nbt have (ex. banners).

![image](https://user-images.githubusercontent.com/22033993/126849755-4bc37a05-865f-41cb-8f58-96166d6fc72a.png)

I believe this was introduced commit 3affa8d.

(This was on a server. I am using a few other mods, the only thing that could interfere is tweakeroo but all shulker settings are disabled.)

**Comment by gnembon** [comment]
And I believe that was fixed right after at https://github.com/gnembon/fabric-carpet/commit/181bfb34bf6e269ebcfbb57ccf34f355959a3f5e

**Comment by gnembon** [comment]
I didn't think that oversight was necessarily wrong just little too overpowered, so that was cleaned up.

**Comment by Reavershark** [comment]
Oh thanks, i'm sorry then for creating a duplicate. Should have tested on the latest version.
