### ISSUE TITLE
[Bug] filping cactus makes hopper work wrongly if lithium is installed 

### ISSUE THREAD

**Issue by YehowahLiu** [gnembon/fabric-carpet#1029]
While using cactus to flip the hopper, it shows that the hopper has changed it's pointing block from A to B, but actually it still pointing to A while working to transfer items.
I'm not sure which to blame, but carpet and lithium just cannot work together.

Minecraft version:1.17.1
Carpet version: 1.4.43-v210714
Lithium: 0.7.3

**Comment by YehowahLiu** [comment]
[Video Showcase](https://youtu.be/3Gk77CTVTvQ)

**Comment by altrisi** [comment]
Probably fixed in latest lithium commit.

**Comment by YehowahLiu** [comment]
sorry for bothering the both side，closed by lithium-fabric 's commit 2f842c6
