### ISSUE TITLE
`fastRedstoneDust` breaks update order

### ISSUE THREAD

**Issue by KyGost** [gnembon/fabric-carpet#1035]
Playing on a server which has this contaption: https://youtu.be/7YWfYCEDeZQ

It relies on update order.

Turning on `fastRedstoneDust` disables that. I'd consider that a non-issue and would file it away as **won't fix** but if the aim is perfect symmetry then this fails that.

**Comment by gnembon** [comment]
acknowledged.

yes, fRD is known for that. Suggest not counting on update order and making a slower contraption that is reliable, non-locational and non-directional. The provided contraption core concept doesn't seem to rely on update order.
