### ISSUE TITLE
Removing or repurposing `combineXPOrbs`

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1041]
Since it basically got added to Vanilla.

Would save half a mixin and a helper class.

**Comment by gnembon** [comment]
The reason it was left was that it allowed to injest more XP than vanilla - actually useful in testing farms where you get more xp than you should, plus it had a cool easter egg that afaik noone found yet. But yeah - vanilla now combines them as well in a non-cheaty way. I guess no-cooldown still exists.

**Comment by altrisi** [comment]
Gotta find it then...

Will take long.
