### ISSUE TITLE
[Expression Optimizer] Incorrectly removing parenthesis/priority

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1046]
Simplest example:
`'a' + (1 + 1) ==> a11`

In my use case one of the numbers comes from a variable, same output.

**Comment by gnembon** [comment]
ok, its the optimizer not taking into account associativity. Should be not that hard. I am AFK for a few more days, but will look into when I am back. Or you would want to have a look at it?

**Comment by altrisi** [comment]
I could try, but since I have almost no idea in how the optimizer (and the internal parsing and loading of Scarpet) works, if I can't find it I'll end up just waiting.

**Comment by gnembon** [comment]
@altrisi You can take a look on the commit to see if that's what you tried
