### ISSUE TITLE
Have considerd haveing your mod on modrinth

### ISSUE THREAD

**Issue by lnee94** [gnembon/fabric-carpet#1055]
https://modrinth.com/

**Comment by CodeF53** [comment]
+, Modrinth has way better discoverability and filters.

Take one look at the mod search screen and you will know what I mean.
It takes nanoseconds to update your search results. You can use more than one filter at a time!

**Comment by sixwheeledbeast** [comment]
I know this issue has been open for a while, I wondered if this was being considered?
I am using Modrinth's API to keep mods up to date, it would be nice to have this available for carpet*.

**Comment by me0wing-katt0** [comment]
would be great!

**Comment by terminalmaid** [comment]
bump

**Comment by lenicyl** [comment]
![mod](https://user-images.githubusercontent.com/73347143/179546540-8639e1a7-3fdf-45ec-974a-48af462d7540.jpg)

**Comment by terminalmaid** [comment]
yeah we def do need modrinth

**Comment by CarbonGhost** [comment]
Bump. Many Carpet extensions are available on Modrinth so seeing Carpet itself would be great!

**Comment by RubixDev** [comment]
I made a [GitHub action](https://github.com/marketplace/actions/upload-to-modrinth) for publishing on Modrinth similar to the `curseforge-upload` action already in use. An example usage can be found [here](https://github.com/RubixDev/EnchantedShulkers/blob/5c23b12b4bd4bdd3f6c69a2be10e991e9d6eb57d/.github/workflows/publish-release.yml#L138-L152). Additionally, I made [modrinth-auto-feature](https://github.com/marketplace/actions/modrinth-auto-feature) for automatically setting what versions are featured like on CurseForge.

**Comment by drakosoldier298** [comment]
Would like to bump this, i use Packiwz for modpack creation and it works well with modrinth more than curseforge.

**Comment by altrisi** [comment]
Soon

**Comment by altrisi** [comment]
Carpet is now on Modrinth!
https://modrinth.com/mod/carpet

**Comment by barokvanzieks** [comment]
fuck yea
