### ISSUE TITLE
Where is carpet.jar?

### ISSUE THREAD

**Issue by arbites** [gnembon/fabric-carpet#106]
This is probably a really dumb issue with a simple solution, but I don't have carpet.jar in the file! I've looked everywhere an ran everything and there is NO carpet.jar. Please help, I really want to use this mod!

If there is any more information needed please say, I will gladly provide it.

**Comment by DeadlyMC** [comment]
You get the jar from here, https://github.com/gnembon/fabric-carpet/releases

**Comment by arbites** [comment]
Sorry About my stupidity. I just realized how to use the mod.

**Comment by DeadlyMC** [comment]
Or from here https://www.curseforge.com/minecraft/mc-mods/carpet
