### ISSUE TITLE
[Feature Request] World specific view distances

### ISSUE THREAD

**Issue by yikesMinty** [gnembon/fabric-carpet#1066]
Although there are other mods that also serve this purpose for fabric I was wondering about the possiblity of having this functionality built into carpet directly as it'd be one less mod to wait for updates for whenever new minecraft patches are released.

**Comment by James103** [comment]
Do you mean _dimension_-specific view distances?
For example:
* Overworld render distance = 10 chunks
* Nether render distance = 6 chunks
* End render distance = 12 chunks

**Comment by yikesMinty** [comment]
That is correct yes, possibly with support for additional dimensions that are added from other mods/datapacks

**Comment by gnembon** [comment]
feels like a ux/ui config nightmare to me. I could see the appeal, but I don't think it's essential, especially if there are mods that do that already.
