### ISSUE TITLE
[Feature suggestion] Backport individual mobcap behavior

### ISSUE THREAD

**Issue by CodeF53** [gnembon/fabric-carpet#1069]
It would be really nice to have a carpet feature to backport the mobcap behavior from 1.18exp3.

**Comment by gnembon** [comment]
it would be very easy to do, but... why?
Asking for a  friend, cause if you need higher mobcaps, carpet allows you to do so, just but increasing the threshold value.

**Comment by CodeF53** [comment]
So one person on the ground doesn't take up the whole mobcap for everyone else.

I have tried to increase the mobcap on the server I host, but with things like squid farms people in the ocean will always take priority.

**Comment by altrisi** [comment]
Closing this as carpet no longer updates to those versions.
