### ISSUE TITLE
I can't use /carpet commands on my server.

### ISSUE THREAD

**Issue by IISzalonnaII** [gnembon/fabric-carpet#1070]
I'am running a fabric minecraft 1.17.1 server and I have OP permissions, but I can't use /carpet command because game says the command is unknown.
![2021-08-20_20 20 45](https://user-images.githubusercontent.com/89262603/130277361-b3107f48-c8e5-4c08-a457-c0fc6d1d13a8.png)

Any idea what is wrong with it?

I'am using these mods:
![image](https://user-images.githubusercontent.com/89262603/130276911-16ff68eb-9d67-4f75-a98b-7f1b0262112c.png)

Thank you for help!

**Comment by Jetlagger** [comment]
Is the mod installed on the server?

**Comment by IISzalonnaII** [comment]
Uhh I forgot to upload server plugins. Yes the mod is installed to server.

**Comment by Ghoulboy78** [comment]
Yo, issue aside, I want the link to that epic looking texture pack! Where did you find it?

**Comment by IISzalonnaII** [comment]
> Yo, issue aside, I want the link to that epic looking texture pack! Where did you find it?
> (EDIT: Is is 64x Faithful?)

This is the Creator Pack resource pack.

**Comment by altrisi** [comment]
Is this still an issue?

**Comment by Ghoulboy78** [comment]
My guess is no, considering that they were talking about plugins, leading me to believe they're on a paper server or something.

**Comment by altrisi** [comment]
I'll close this issue then, feel free to comment otherwise and I'll reopen it, or make a new issue.
