### ISSUE TITLE
Removing or renaming `/test` command

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1079]
It is actually used by the vanilla game testing suite, and fabric api plans to make it available in one of the next versions (fabricmc/fabric#1622), where Carpet could at some point use it (either the test suite or the api), rendering the command useless since it would have conflicts.

**Comment by James103** [comment]
> fabric api plans to make it available in one of the next versions ([FabricMC/fabric#162](https://github.com/FabricMC/fabric/issues/162)),

Did you mean https://github.com/FabricMC/fabric/pull/1622 instead?

**Comment by modmuss50** [comment]
Just a note on this, for now we are only going to be enabling it in dev envs, fabric's game test module will not be shiped in the fat jar that most players use. Its still possible to use outside of a dev env if installed manually however.
