### ISSUE TITLE
Carpet rule suggestion: Option to disable logging of named entity deaths

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1095]
Currently, there appears to be no way to turn off the `Named entity ... died` messages that are logged whenever an entity with a custom name dies. This means that for people that have Scarpet scripts (or even just a datapack like [this](https://www.dropbox.com/s/ubfcz7ywdw822yx/cw_hp_display%28Survival%29.zip?dl=1)) that renames **every** entity that spawns or is loaded, that means that **every** entity that dies is reported in the Minecraft Log. 

Suppose you have a very fast perimeter-based slime farm and it outputs 500,000 slime balls per hour. Just in the smallest size alone, that would be 500,000 slimes killed per hour (assuming no looting). If all 500,000 slimes are renamed (as to be expected from using such a script), that's 500,000 named entity deaths that are recorded into the Minecraft Log. At 180 bytes per log entry, that comes out to **90 MB/hour** of disk space taken up by the Minecraft Log, in a game that should generate maybe only a few KB/hour of log entries (excluding chat) on a vanilla normal playthrough.

**Comment by gnembon** [comment]
what about adding that to 'cleanLogs' setting?

**Comment by James103** [comment]
> what about adding that to 'cleanLogs' setting?

That would work as well, removing the need for an entirely new carpet rule.

**Comment by gnembon** [comment]
just realized there is already `showDeathMessages` gamerule. Will apply that one to this one. It would makes sense to use that rule in vanilla as well.
