### ISSUE TITLE
Is there a way to make 'spawn mobcaps set 200' changes premament (not for one session only)

### ISSUE THREAD

**Issue by swistakk1** [gnembon/fabric-carpet#1097]

**Comment by James103** [comment]
Currently, that would have to be done in a Scarpet app, but I could see `spawn mobcaps setDefault 200` being a possibility. The command would save the hostile mob cap to `carpet.conf`. Then, on load, the `carpet.conf` is read in and if a rule such as `hostileMobCap` is found, then it's value `<N>` is used as the hostile mob cap, as if you ran `spawn mobcaps set <N>` while the world was loading.

**Comment by gnembon** [comment]
I recognize that one would want to set a mobcap in a world to some value, but that is part of the spawn command where you can set a few other things, and mobcap is one of them and they are meant to be temporary.

As James pointed out - you can easily achieve it with a datapack, or a simple scarpet app. Just create a text document in the world scripts folder rename it to like mobcap.sc and edit it to
```
run('spawn mobcaps set 200')
```
and it will load every time you run your world

**Comment by emerald0s** [comment]
is there any way to make the mob cap stay the same no matter how many players/bots are online?
