### ISSUE TITLE
Conflicts with slimeology

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/fabric-carpet#1098]
When this mod is installed alongside [slimeology](https://github.com/LapisLiozuli/Slimeology/issues/4), the game gets in a loop at startup. As soon as the progress bar under "Mojang Studios" reaches the end, it shifts back and continues loading. 

versions: 
- autoconfig1u-3.3.1
- fabric-api-0.40.0+1.17
- fabric-carpet-1.17.1-1.4.45+v210811
- slimeology-0.1.2+1.17.1

**Comment by James103** [comment]
What do you get in the game log when that happens? Can you please post the full game log?

**Comment by supersaiyansubtlety** [comment]
log after a few iterations of the loop:
https://paste.myst.rs/jaot1557

**Comment by altrisi** [comment]
Fixing this from carpet is pretty much impossible, given slimeology is overwriting the entire method, therefore not allowing other mods to exist there. Closing this issue for that, since there's not much we can do.
