### ISSUE TITLE
[1.3.1]When fillUpdates off, command "/clone" and structure blocks won't update some of block entities(containers), sometimes cause game crash

### ISSUE THREAD

**Issue by Harveykang** [gnembon/fabric-carpet#110]

**Comment by gnembon** [comment]
what type of containers, and what is the crash log (stack trace) would be helpful

**Comment by Harveykang** [comment]
[crash-2019-12-14_13.47.26-server.txt](https://github.com/gnembon/fabric-carpet/files/3971938/crash-2019-12-14_13.47.26-server.txt)
Such as hoppers, droppers, chests, all kind of containers has this issue, but not always has. When it happened, they can't be opened. If items go through them, the game crash.

**Comment by gnembon** [comment]
thanks. Issue identified and should be fixed next coming update, possibly sooner than later

**Comment by gnembon** [comment]
https://masa.dy.fi/maven/carpet/dev/fabric-carpet-1.14.4-1.3.1%2Bv191218_ht.jar

this one should have that bug fixed.

**Comment by Harveykang** [comment]
thank you guy, awesome mod^^

**Comment by gnembon** [comment]
reopening, will close when released in v1.3.2
