### ISSUE TITLE
New maxEntityCollisions optimization might break entity cramming at low values

### ISSUE THREAD

**Issue by skerit** [gnembon/fabric-carpet#1105]
Ever since #1038 was implemented, entity cramming no longer works if I set `maxEntityCollisions` lower than 15.

I originally set the value quite low, to 3, because then it seemed to work well enough. Entities were still quite pushable, and gold farms worked as expected.

But after updating to the latest Carpet version, I got reports from players that entity cramming was disabled.
I tested it, and indeed, after raising the cramming from 3 to 15 entities started taking damage again.

Now I see that the #1038 pull request actually fixed certain things. Is it safe to say setting the `maxEntityCollisions` to 15 will provide as-good performance improvements as the previous version had at only 3?

**Comment by skerit** [comment]
Important to add: my world had `maxEntityCramming` set to 16. If I set it to the default vanilla-value of 24, I actually have to set `maxEntityCollisions` to at least 23, so it seems like you can't set the `maxEntityCollisions` lower than `maxEntityCramming`

**Comment by gnembon** [comment]
I will fix it, but it will mean that optimization-wise the benefits will be depending on both maxEntityCollisions as well as maxEntityCramming, whichever is higher.

**Comment by gnembon** [comment]
for all intent and purpose, max entity collisions of 1 give similar perfomance gain as 100, and its good
