### ISSUE TITLE
OnePlayerSleep

### ISSUE THREAD

**Issue by Jawarny** [gnembon/fabric-carpet#1107]
Hi I'v downloaded the 1.17.1 carpet mod for my server and watched most of the tutorial video and I tried to use the OnePlayerSleep command and its not showing and I was wondering if it got removed or if I need to allow it somewhere... 

Thank you 
- Jawarny

**Comment by ch-yx** [comment]
it have been removed as mojang added it into vanilla minecraft. 
IIRC

**Comment by Jawarny** [comment]
Thank you very much, but do you think you  can help me change it or guide me to change that option ?

**Comment by altrisi** [comment]
`/gamerule playersSleepingPercentage 0` is the equivalent to it in vanilla 1.17.

**Comment by Jawarny** [comment]
> `/gamerule playersSleepingPercentage 0` is the equivalent to it in vanilla 1.17.

THANK YOU VERY MUCH!!
