### ISSUE TITLE
Carpet 21w37a-1.4.46 is not working server or client sided

### ISSUE THREAD

**Issue by Woofydude** [gnembon/fabric-carpet#1112]
My game keeps crashing when trying to launch the carpet version posted today both client and server sided. I am launching this on  fabric loader version 0.11.7 and fabric minecraft version 21w37a. Crash logs for server and client are below.

Server:
[2021-09-18-5 -SERVER.log](https://github.com/gnembon/fabric-carpet/files/7190830/2021-09-18-5.-SERVER.log)

Client:
[crash-2021-09-18_20.05.33-client.txt](https://github.com/gnembon/fabric-carpet/files/7190832/crash-2021-09-18_20.05.33-client.txt)

**Comment by altrisi** [comment]
Missing refmap seems to be striking here... (rare-ish loom bug).

**Comment by gnembon** [comment]
I should have added that folks at fabric mentioned that 21w37a fabric state is.... for development most likely. I will add that to the notes and release something else when its stable enough

**Comment by boasbakker** [comment]
I just copied an older refmap file from an other carpet mod in to the jar and it worked! So not to hard to fix this
