### ISSUE TITLE
[bug] dispensers place blocks crops

### ISSUE THREAD

**Issue by jusTinMan** [gnembon/fabric-carpet#113]
Dispensers place blocks allows for planting crops on single player but not the server. 

I designed an automatic nano farm and spent 2 hours on the server discovering that it doesn't work lol (sad face)

**Comment by gnembon** [comment]
this is probably related to carpet-extra, right?

**Comment by jusTinMan** [comment]
Correct... Do you want me to "report" the issue there?

**Comment by gnembon** [comment]
yes, please. Closing this one
