### ISSUE TITLE
getReceivedRedstonePower() returns incorrect values

### ISSUE THREAD

**Issue by CommandLeo** [gnembon/fabric-carpet#1140]
`getReceivedRedstonePower()` is currently used in `/info block` and Scarpet `power()` function.

There are 2 issues with how it works:

1. It should (arguably) not work with blocks that don't have varying signal strengths, as described in the Scarpet docs for `power()`: `Numeric function, returning redstone power level at position`. Therefore it makes sense that it works only with **redstone dust, comparators, daylight sensors and target blocks**. 
![image](https://user-images.githubusercontent.com/51045936/138553671-e6ff935b-c08b-4ff3-99d3-dd47adb746d2.png)
In this example running the command `/info block <x> <y> <z> grep Redstone power` on the powered rail returns `Redstone power level: 15` even though rails don't have different signal strengths, they are either powered or unpowered.

2. This a more serious issue: `power()` **doesn't consider the fact that repeaters and comparators only take an input from behind**. So by, for example, placing a redstone block next to a comparator and running `/info block` on the comparator it will return a power level of 15.
![image](https://user-images.githubusercontent.com/51045936/138553787-dc591d70-46d1-4f7d-8632-4dec9be97345.png)

What's even weirder is what happens when you try to search for `getReceivedRedstonePower` in the mod's code. There are [4 results](https://github.com/gnembon/fabric-carpet/search?q=getReceivedRedstonePower), including the definition of the function. 
But [in line 36 of `RedstoneWireBlockMixin.java`](https://github.com/gnembon/fabric-carpet/blob/85415463cd12856e31f54cd80b25a0b85f3ddba7/src/main/java/carpet/mixins/RedstoneWireBlockMixin.java#L36) apparently the function always returns 0?

Apart from the issues with how the function works, I've found out that `power()` is actually slower than `block_state(b, 'power')`, so in the current state `power()` is completely useless.

**Comment by gnembon** [comment]
`power(...)` is the redstone power for a block at this position. what the block does with its power its up to the block. As altrisi pointed out, power level is not the same as comparators' property of 'power'.
