### ISSUE TITLE
Carpet Players Incompatibility with Floodgate and Geyser

### ISSUE THREAD

**Issue by HarryRich02** [gnembon/fabric-carpet#1142]
Spawning of carpet players does not work with Floodgate Fabric and Geyser Fabric.

**Comment by Camotoy** [comment]
Yes, this was something that we worked around, but we updated our `adventure-platform-fabric` dependency which now has a native locale API that inherits the same issue we fixed.

**Comment by altrisi** [comment]
Is there something that can be done from Carpet to fix the incompatibility or at least help the situation? (without giving complete network handlers to fake players)

**Comment by Camotoy** [comment]
Perhaps set their channel to an EmbeddedChannel or LocalChannel? The latter is used in Minecraft for singleplayer, but the former I believe is used in testing purposes but may be enough for applications not to complain?

**Comment by whes1015** [comment]
> Perhaps set their channel to an EmbeddedChannel or LocalChannel? The latter is used in Minecraft for singleplayer, but the former I believe is used in testing purposes but may be enough for applications not to complain?

This problem happened again in version 1.18

**Comment by whes1015** [comment]
> Perhaps set their channel to an EmbeddedChannel or LocalChannel? The latter is used in Minecraft for singleplayer, but the former I believe is used in testing purposes but may be enough for applications not to complain?

#1205

**Comment by altrisi** [comment]
This issue is already known. Please stop spamming issue trackers.

**Comment by altrisi** [comment]
Does Geyser use anything in the `ChannelHandlerContext` passed to `ClientConnection#channelActive` (yarn name)?

It's the "exposed" way in vanilla to set the connection's channel, I did an aberration with it to set a channel and while it seems like vanilla responds to it correctly, I'd like to make sure that will not cause problems with Geyser at least.

**Comment by zml2008** [comment]
The relevant injection is https://github.com/KyoriPowered/adventure-platform-fabric/blob/5afb656e8a5c66a59e5c7e87633687349d99bc89/src/mixin/java/net/kyori/adventure/platform/fabric/impl/mixin/ServerGamePacketListenerImplMixin.java#L44 -- we grab the channel at the end of the constructor.

The only other place `adventure-platform-fabric` directly touches the channel is at https://github.com/KyoriPowered/adventure-platform-fabric/blob/5afb656e8a5c66a59e5c7e87633687349d99bc89/src/mixin/java/net/kyori/adventure/platform/fabric/impl/mixin/ServerPlayerMixin.java#L140 in respawn handling.

**Comment by altrisi** [comment]
Coming Soon (TM) (if the PR is accepted):
![imagen](https://user-images.githubusercontent.com/17107132/147359448-a9a27487-02b9-4bc9-9505-3e5b53950a6c.png)
(setting up the server and getting the screenshot took over twenty times what the actual fix took, else I wouldn't spam here)

**Comment by whes1015** [comment]
> Coming Soon (TM)（如果 PR 被接受）：（ 設置服務器並獲取屏幕截圖所需的時間是實際修復所需的 20 倍以上，否則我不會在這裡發送垃圾郵件） ![圖像](https://user-images.githubusercontent.com/17107132/147359448-a9a27487-02b9-4bc9-9505-3e5b53950a6c.png)

Great

**Comment by altrisi** [comment]
Preview builds with a potential fix available [here](https://github.com/altrisi/fabric-carpet/releases/tag/adventure-take-two) for those interested in testing the fix, both for 1.17.1 and 1.18(.1).

Updated today with a different approach if someone was using the previous build.

**Comment by whes1015** [comment]
> Preview builds with a potential fix available [here](https://github.com/altrisi/fabric-carpet/releases/tag/adventure-take-two) for those interested in testing the fix, both for 1.17.1 and 1.18(.1).
> 
> Updated today with a different approach if someone was using the previous build.

1.18.1 test Success,thanks
