### ISSUE TITLE
XPnocooldown does not work as intended

### ISSUE THREAD

**Issue by niruvibes** [gnembon/fabric-carpet#1145]
Basically the title, XPnocooldown does not work as its supposed to, it does not instantly transfer to you
1.16.5:
<a href="https://ibb.co/gjHQBMS"><img src="https://i.ibb.co/M2WK3Dc/6v-HISVJ7-Wz.gif" alt="6v-HISVJ7-Wz" border="0"></a>
1.17.1:
bruh is too laggy

**Comment by Crec0** [comment]
in 1.17, with the addition of vanilla combine xp orbs, the xp orbs dont get instantly "absorbed" by the player. they do get absorbed faster than default vanilla speed, however, its still extremely slow compared to vanilla 1.16.5 versions. 
As a side note: they also because extremely laggy

**Comment by James103** [comment]
Basically, fixing this may involving changing `combineXPOrbs` from a boolean to a list of possible options:
* `true` (name to be determined) - Same as old `true`, XP orbs merge into bigger XP orbs.
* `vanilla` - Same as old `false`, XP orbs combine into a single entity, but that entity represents multiple XP orbs.
    * Not recommended for use with `/carpet xpNoCooldown true`.
* `false` - XP orbs do not combine at all. Each XP orb remains a separate entity.

**Comment by Crec0** [comment]
I am actually trying to implement that right now. Although I made a new rule for it to configure vanilla behavior. I will change it to a list as you suggested.

**Comment by Crec0** [comment]
Turns out, it has nothing to do with merging orbs. The player entity class now processes experience orb collisions by randomly selecting one xp orb per tick. instead of a loop which processes all of them. (like it used to earlier)
Code almost ready. Will PR soon
