### ISSUE TITLE
Update Idea pictures for editor

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#1146]
With new IntelliJIDEA updates, the layout of the whole box thing has changed, making it different, and with the addition of {} for maps and [] for lists, that is outdated too.

**Comment by Ghoulboy78** [comment]
Also note to add the hex prefix as well.

**Comment by Ghoulboy78** [comment]
Fine, I'll do it myself

**Comment by altrisi** [comment]
Just realized this got fixed back in the day just not closing, so closing it now. Though maybe it now needs updates again after this much time!
