### ISSUE TITLE
The game will not launch at all with Carpet mod

### ISSUE THREAD

**Issue by DrDoodles** [gnembon/fabric-carpet#1173]
![image](https://user-images.githubusercontent.com/90808174/142301514-769eebee-d14b-4486-9bf4-b96599889e58.png)
This is the error window that I am greeted with when I start the game. My friend is also having this issue but with a slightly different error message but with OpenJDK instead of Java Hotspot
![image](https://user-images.githubusercontent.com/90808174/142301715-f1b7cb66-d167-43bf-be1d-09c562bea86e.png)

**Comment by James103** [comment]
Minecraft 1.18 Pre-release 2 and later requires Java 17, hence the error message.
1. Install Java 17.
2. In the instance settings, change the Java installation reference to point to Java 17 (instead of Java 16).
3. Verify that the Java installation and Minecraft instance works by starting Minecraft.

**Comment by altrisi** [comment]
Assuming you were trying to launch a 1.17 installation:

You likely downloaded the 1.18-pre versions of Carpet, that require Java 17 (and 1.18 snapshots).

**Comment by altrisi** [comment]
Also (we just noticed) Carpet 1.4.54 for 1.17 is currently incompatible with Java 16 (only works with 17+), it will likely be resolved in the next release, but meanwhile you should use 1.4.53 (this may be your issue @Jellxy) for 1.17 unless you are using java 17 anyway.

**Comment by Kinami37** [comment]
Having the same problem, got Java 17 installed, using the 1.17.1 version, just crashes, no error msg or anything
