### ISSUE TITLE
/player attack issue

### ISSUE THREAD

**Issue by SweaterOMG** [gnembon/fabric-carpet#1174]
i used /player SweaterOMG (my name) interval 11 and now i cannot get myself to stop attacking in game no matter if i close out the whole launcher or not
tried using /player SweaterOMG stop does not work either

**Comment by gnembon** [comment]
I don't think that would be possible.

**Comment by altrisi** [comment]
Closing this as there's been no feedback in a while. If it's still an issue, feel free to comment and it can be reopened, or make a new issue.

**Comment by rueedolf** [comment]
> i used /player SweaterOMG (my name) interval 11 and now i cannot get myself to stop attacking in game no matter if i close out the whole launcher or not tried using /player SweaterOMG stop does not work either

I have the same problem on a 1.19.3 server and it also does this in my singleplayer worlds.
Have you fixed the issue?
Pls let me know

**Comment by altrisi** [comment]
Do you have a way to reproduce it with just Carpet? Or could you find a minimal installation.

Please give the exact steps, it'd be very helpful.

I haven't been able to reproduce this, and it's very strange because Carpet doesn't save actions afaik, so they're always reset when reloading.
