### ISSUE TITLE
[Scarpet Suggestion] Support for clickable links in format

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1182]
It would be useful if `format` could create a text fragment that when clicked would open an url.

Suggested prefix (feel free to suggest a better one): `@`

**Comment by altrisi** [comment]
Same for copy to clipboard, suggested using `&` prefix by @Crec0 on discord.

**Comment by Crec0** [comment]
format should add support for all available raw text formatting imo

**Comment by gnembon** [comment]
👍 
go for it

**Comment by altrisi** [comment]
Moved the rest of raw text formatting options to #1241, keeping this for just actions.
