### ISSUE TITLE
Can't run custom scarpet commands in datapacks

### ISSUE THREAD

**Issue by Desynq** [gnembon/fabric-carpet#1184]
I'm trying to use the `playerme.sc` script from the list of downloadable carpet scripts to remotely control fake players without needing to declare their name within the datapack.

Currently, I'm trying to make a fake player named "Steve" eat continuously using `execute as Steve at @s run playerme use continuously`. The datapack, however, fails to the load the function containing the custom command upon doing `/reload`.

I'm currently using version 1.4.43+v210706 of the carpet mod.
[Used carpet script source code link](https://github.com/gnembon/scarpet/blob/master/programs/survival/playerme.sc)

**Comment by James103** [comment]
1. Can you please update to Carpet mod [version 1.4.53](https://github.com/gnembon/fabric-carpet/releases/tag/1.4.53)?
2. You may need to enclose the command in a `script run run('...')` where `...` is the original command line.
In other words, replace the following command: `execute as Steve at @s run playerme use continuously`
With: `execute as Steve at @s run script run run('playerme use continuously')`
Or: `script run run('execute as Steve at @s run playerme use continuously')`

**Comment by Desynq** [comment]
Your suggestion worked, thanks.
