### ISSUE TITLE
not letting game to start

### ISSUE THREAD

**Issue by MateConMonster** [gnembon/fabric-carpet#1191]
this only happend when trying to laod carpet, don't know why, but i have the last version of carpet released and didn't try changing fabric or carpet versions

![Screenshot_1](https://user-images.githubusercontent.com/66202621/143954652-d35a1576-9af8-4b04-8383-5ff583b33d45.jpg)

also these are all the mods that im using, i tried loading only carpet without other mods and it shows the same error.

![Screenshot_3](https://user-images.githubusercontent.com/66202621/143957059-cee04496-7a23-4dbe-af60-8dc15c241f01.jpg)

**Comment by gnembon** [comment]
go down one version. Should be fixed next release
