### ISSUE TITLE
Server crash with scarpet scripts

### ISSUE THREAD

**Issue by Hnaguski** [gnembon/fabric-carpet#1193]
I have 3 scarpet scripts, [keepalive.sc](https://github.com/gnembon/scarpet/blob/master/programs/utilities/keepalive.sc), [cam.sc](https://github.com/gnembon/scarpet/blob/master/programs/survival/cam.sc) (renamed to c.sc), and [pauseEmptyServer.sc](https://git.sr.ht/~hnaguski/pauseEmptyServer/tree/master/item/pauseEmptyServer.sc). The server crashes right after spawning in the fake players. Removing any of the 3 scripts makes the server not crash, as does removing the `__on_server_starts()` section from `pauseEmptyServers.sc`

[log](https://paste.nilsu.org/bb96c9ee4dfe3cae7f245c81ec69edf9fea6b7d6.log)
[crash report](https://paste.nilsu.org/da95082ec58930ee14ac4f1f4dcb848dae0da7ab.txt)

**Comment by altrisi** [comment]
May relates to #889
