### ISSUE TITLE
Error when invoking non existing function could include more helpful information

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1198]
https://github.com/gnembon/fabric-carpet/blob/dc9ba2f83cdac7856646c5d0d1a40d5e67526c35/src/main/java/carpet/script/CarpetScriptHost.java#L737-L738

Maybe something like "couldn't find function (name) [in app (appname)]".

**Comment by James103** [comment]
Expanded suggestion with proper placeholders: "Can't find function A in app B"

**Comment by altrisi** [comment]
Oh lol github stripped them as html tags, they were there.

**Comment by gnembon** [comment]
yeah, why not
