### ISSUE TITLE
perimeterInfo in 1.18 does not search below y=0

### ISSUE THREAD

**Issue by baford25** [gnembon/fabric-carpet#1207]
As stated above.  The perimeterInfo command does not check blocks below y=0

**Comment by James103** [comment]
Does the same apply above the old height limit? In other words,

1. Find some flat terrain below Y=128.
2. Fly above Y=256 in that area and place some blocks there. Example: `/fill ~-10 300 ~-10 ~10 300 ~10 stone`
3. Run `/perimeterinfo` while you are standing on the newly generated platform.

**Comment by baford25** [comment]
It also does not work for any blocks at y>=255.

**Comment by James103** [comment]
Currently, these limits are hard-coded. If they are to be changed, they will need to be dynamically queried with a function instead of remaining hard-coded, as the build height limits are **not** the same in the Overworld, the Nether, and the End.
