### ISSUE TITLE
problem with particles, camera app

### ISSUE THREAD

**Issue by jens1433** [gnembon/fabric-carpet#121]
![2020-01-01_20 29 48](https://user-images.githubusercontent.com/55440348/71645248-b2582a00-2cd5-11ea-8720-c8fdfa92e36e.png)

i'm having a problem with the particle_type variable

**Comment by gnembon** [comment]
could possibly be that 0.0 is not a valid number. If that's the case it needs fixing.

**Comment by gnembon** [comment]
did you change that yourself? What version are you running. Cannot replicate this issue even when manually changing the particle to the values you have.

**Comment by Kotohitsu** [comment]
I'm having the same issue but with different values. 
My values are:
`
dust 0,7 0,2 0,3 1
`

My versions:
* Minecraft 1.15.2
* carpet mod v1.3.9

**Comment by Kotohitsu** [comment]
The error does not exist in version 1.3.16

**Comment by gnembon** [comment]
yes, because it was fixed. Please use the updated version
