### ISSUE TITLE
Add client-side scripts

### ISSUE THREAD

**Issue by XxMicrowavexX** [gnembon/fabric-carpet#1210]
I love how scarpet is basicly a command block users dream, but I have a problem that its server-side. If u could add a client side version it'll be EPIC. Also when I mean client side I mean to use scarpet on a vanilla server

**Comment by gnembon** [comment]
I get that it would be great, but that will never happen, unless someone writes an extension for it.

**Comment by Ghoulboy78** [comment]
I could do it...
