### ISSUE TITLE
Setting absorption amount casts the argument to an integer before applying it as a float.

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1222]
https://github.com/gnembon/fabric-carpet/blob/5dca846363bddd6bc967f0c93f68b0c42d7a75ce/src/main/java/carpet/script/value/EntityValue.java#L1586-L1588

In the above code, even though absorption should be a float as indicated by the `(float)` cast, it is retrieved as a `long` using Scarpet methods. This restricts the domain to just integers and does not allow fractional absorption to be set with Scarpet alone.

You can get fractional absorption in the game by giving yourself the Absorption effect, putting on full armor, taking damage once from a cactus, then checking your `AbsorptionAmount`.

**Comment by Ghoulboy78** [comment]
Oops... I may or may not have checked that code thouroughly...
