### ISSUE TITLE
system_info('world_size') either incorrect or misleading

### ISSUE THREAD

**Issue by GunnyWaffle** [gnembon/fabric-carpet#1225]
The `system_info` option `world_size` is documented as:
`world_size` - Returns size of the world where at this distance from `world_center` world border appears.

But with the world border set to 400 this returns 29999984.
![image](https://user-images.githubusercontent.com/2184320/146849381-0f197677-fce0-48cb-be6c-c5fdad89a4e2.png)

Either `world_size` is returning the incorrect value, or its documentation needs to be changed to something along the lines of:
`world_size` - Returns size of the world where at this distance from `world_center` world border appears **by default**.

**Comment by Ghoulboy78** [comment]
umm... that's weird... I'll check that...
