### ISSUE TITLE
Is Carpet Server Side Only?

### ISSUE THREAD

**Issue by dali99** [gnembon/fabric-carpet#123]
Sorry for the question, but

Can vanilla clients connect to a server running carpet mod?

I would like to use carpet on the server to get diagnostics on farms and villagers and such, but I won't be able to get people to install client side mods very easily..

**Comment by Harveykang** [comment]
yes it can, clients don't need to install carpet mod
if you want to play single-player mode with carpet, you can add it in your client, it up to you^^

**Comment by dali99** [comment]
Very cool! So carpet-extra is where all the clientside-requirements are put?

**Comment by Harveykang** [comment]
carpet-extra also just need server-side

**Comment by gnembon** [comment]
carpet client is being made, but it will not drastically add functionality. All features in carpet extra can work on its own as well (no client mods needed). The only time you may need the same mods on the client if you use auto crafting table, but this one is in its own project, and can be substituted with fully compatible autoCraftingDropper from extra.
