### ISSUE TITLE
[Easy feature request] Print /tick step executions

### ISSUE THREAD

**Issue by aigagror** [gnembon/fabric-carpet#1232]
`/tick step` is a great feature for redstone debugging, but the command runs silently (no print output in chat). A very easy quality of life improvement would be to simply print out the number of ticks stepped in chat everytime you run the command.

Logging tick steps is helpful because it helps debuggers keep track of how many ticks they have stepped through since the beginning of the debug session.

For example, if running `/tick step 2`, could print out `[Timestamp] Stepped 2 game ticks`.

> Printing out the current timestamps would also be helpful in determining whether the log is associated with the current debug session.

**Comment by altrisi** [comment]
Opened #1234 for this. No timestamp though, since they would be inconsistent with every other message, but you can find them in the logs and I'm sure there's mods to add timestamps to every chat message.
