### ISSUE TITLE
Separate `system_info('world_size')` into `system_info('world_max_size')` and `system_info('world_border_size')`

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1237]
Currently, `system_info('world_size')` returns the maximum size of the world border as shown here:
`put("world_size", c-> new NumericValue( c.s.getWorld().getWorldBorder().getMaxRadius()));`

I would like if this was split into two, as described in the title:
```java
put("world_max_size", c -> new NumericValue( c.s.getWorld().getWorldBorder().getMaxRadius()));
put("world_border_size", c -> new NumericValue( c.s.getWorld().getWorldBorder().getSize()));
```

**Comment by altrisi** [comment]
What would you use the max_size though, isn't it a constant anyway? I doubt mojang is considering to expand it anytime soon either.

**Comment by gnembon** [comment]
Yeah, I have the same expectation about the world size - its a technical limit and will not likely change. World border is the actual 'size' and the only one I think
