### ISSUE TITLE
[Unknow-1.3.2Bug]When stackableShulkerBox-on, wash stacked shulker boxes with cauldron, only return one shulker box

### ISSUE THREAD

**Issue by Harveykang** [gnembon/fabric-carpet#124]
stackableShulkerBox-on 
Washing stacked shulker boxs with cauldron, only return one shulker box

**Comment by gnembon** [comment]
sounds like vanilla code defaults to a single output item only, assuming sboxes are not stackable. Needs fixin

**Comment by gnembon** [comment]
will be fixed in 1.3.3. Its a vanilla bug - I will report that as well to the bugtracker.
