### ISSUE TITLE
Carpet crash with optifabric in 1.18

### ISSUE THREAD

**Issue by Vikkavv** [gnembon/fabric-carpet#1247]
When I try to play minecraft with carpet and optifabric with the respective optifine, minecraft crashed, the code of the error is 0, I tried to play without carpet and all works but in the moment when I added carpet minecraft crashed again, the version of minecraft that I have been using is 1.18.

**Comment by altrisi** [comment]
Update optifabric.

**Comment by Vikkavv** [comment]
I have been using the last version of optifabric 1.18

**Comment by altrisi** [comment]
Well, I just know Optifabric recently fixed the carpet conflict they had. Optifine may have updated and broken something again, as usual. Without the crash report logs we can't help, and you should also try asking at optifabric just in case.

**Comment by altrisi** [comment]
I'm quite sure this has already been fixed on Optifabric's side, if it hasn't been make sure to open an issue there (or a new issue here).
