### ISSUE TITLE
Can't use /player

### ISSUE THREAD

**Issue by z0z0r4** [gnembon/fabric-carpet#1249]
This player which input /player has op permission

CommandPlayer was Ture and setDefault
![Screenshot_20211227_230417](https://user-images.githubusercontent.com/78744121/147486123-350e183b-1ba1-4533-abfc-bc0da7859949.jpg)

But I can't use /player , there is an error

![Screenshot_20211227_225159_com tencent mobileqq](https://user-images.githubusercontent.com/78744121/147486025-89c4a555-43c9-4655-a216-98da402ae7aa.jpg)

Carpet returned  : An unexpected error occurred while trying to execute the command

(I use Google , translate Chinese to English , maybe that's difficult to understand

I need to update carpet mod?
The version of server is 1.18 fabric

Who can help me?

**Comment by altrisi** [comment]
I think this is the current incompatibility with adventure-platform (a library some mods use), #1142. 

There's a fix not yet released in #1235, see the last comment there for a jar that should work, or if it doesn't, please provide logs.
