### ISSUE TITLE
[Scarpet Internal] Replacing CarpetContext's `origin` by using the position of the source?

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1255]
Just found that a CarpetContext has two extra parameters from a regular Context: `source` and `origin`, with `source` also containing a position.

Is there a difference between the source's position and the origin that makes it necessary to store both, or could it be changed to just store the source?

**Comment by gnembon** [comment]
origin is only used for /script scan and related to interpret what a position is referring to (offsetting from origin parameter) nothing else

TBH, I would deprecate that in favour of always offsetting from 0,0,0, so a position in the script refers to the actual block in the world

**Comment by altrisi** [comment]
After knowing what `origin` is in `CarpetContext`, this issue is no longer valid. Closing it, deprecation of origin changing should be tracked in a different issue.
