### ISSUE TITLE
[Unknow-1.3.2]command"/player xxx attack interval xxx"doesn't reset the mining time of the fake player 

### ISSUE THREAD

**Issue by Harveykang** [gnembon/fabric-carpet#126]
use command "/player 233 attack interval 30" ,after a few minutes...
it's an obsidian XD
![image](https://user-images.githubusercontent.com/46108547/71695953-a744ed00-2dee-11ea-82ce-47c8106afabe.png)

**Comment by gnembon** [comment]
its technically a vanilla bug that appears in slightly different conditions, but I could take care of that as well 
https://www.youtube.com/watch?v=18u1oom3eig

**Comment by gnembon** [comment]
but only for fake players
