### ISSUE TITLE
[Scarpet Feature Request] query(e, 'item') should return the displayed item of an item frame

### ISSUE THREAD

**Issue by CommandLeo** [gnembon/fabric-carpet#1268]
Currently the only way to get the item inside an item frame is with `query(e, 'nbt', 'Item')`, which is quite computationally expensive. 
Making the query work with item frames would be consistent with the behavior on item entities.

**Comment by ch-yx** [comment]
https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/value/EntityValue.java#L505

u can change it by your self.... but i dont think it is very necessary. there are too many thing that is not exposed **directly**.
cannot see why that is special.

**Comment by ch-yx** [comment]
it is called getHeldItemStack() for itemframes iirc.

**Comment by BisUmTo** [comment]
Related to #1364 1364

**Comment by altrisi** [comment]
This was resolved by #1364, though it wasn't documented there.
