### ISSUE TITLE
[Request] /player command toggle for survival and without cheats 

### ISSUE THREAD

**Issue by AmLaggen** [gnembon/fabric-carpet#1274]
A Option to allow the /player command in survival and without cheats

**Comment by altrisi** [comment]
You can change the commands of all carpet commands, in this case you'd use `/carpet commandPlayer true` (set rule `commandPlayer` to `true`) to allow everyone to use it.

**Comment by AmLaggen** [comment]
thanks

**Comment by altrisi** [comment]
Could you please close the issue if it's solved?
