### ISSUE TITLE
carpet setting fastRedstoneDust bugs

### ISSUE THREAD

**Issue by Garry63566** [gnembon/fabric-carpet#1277]
Description: Carpet setting fastRedstoneDust causing redstone to not function properly with updatesuppression

Game Version: Fabric 0.12.12 (Minecraft 1.18.1)
Carpet Mod Version: 1.4.56
How to reproduce the bug:
The setting fastRedstoneDust is enabled
The update suppressor is from youtube channel tralala's "Auto Reseting Repeaterless Targetless Update Suppressor", video link: https://youtu.be/xgRFr5_vQ1A
And is built with this position in chunks (I haven't tested does the position affect the bug, but this position is what I built it at): Noteblock for activation/reset is positioned in 11,0,12 within a chunk
The update suppressor is pasted in using litematica, and then triggered normally with a block placed beside the rails:
(https://user-images.githubusercontent.com/43532481/149649012-a8c03144-a746-4863-85fe-286f7655fe4a.png)
Then redstone cannot function normally, e.g. redstone signal only propagating when a block update from the player is supplied:
(https://user-images.githubusercontent.com/43532481/149649083-ef497d3b-bd57-4ee9-bea6-08f2cb035b99.png)
(https://user-images.githubusercontent.com/43532481/149649089-bd01f33a-b78b-49b8-95a6-785df2d50c4c.png)
(https://user-images.githubusercontent.com/43532481/149649092-f360ad26-60d8-4322-acff-7897101e8aee.png)
The problem immediately disappears after the setting fastRedstoneDust is disabled in game.

**Comment by fxmorin** [comment]
I mean, there's no real way to fix this. Update suppression is not something that mods should try to keep parity with, since its causing an exception and skipping code

**Comment by altrisi** [comment]
Assuming this was only possible with update suppression this likely is no longer be an issue in 1.19 snapshots, which is what carpet is currently targeting, so I'm closing this issue. If it is feel free to comment and it can be reopened, or make a new issue.
