### ISSUE TITLE
[suggestion]add use "/player xxx move" to stop moving the fake player

### ISSUE THREAD

**Issue by Harveykang** [gnembon/fabric-carpet#128]

**Comment by gnembon** [comment]
you mean without resetting entirely its actions

**Comment by Harveykang** [comment]
just like: 
"/player Alex drop continuous" can drop item continuously
"/player Alex drop" with no follow-up, can stop dropping items

**Comment by gnembon** [comment]
👍

**Comment by gnembon** [comment]
fixed in 1.3.4
