### ISSUE TITLE
[Refactor] Mojmap migration

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1281]
Carpet is going to be migrated to Mojmap Soon :tm:, and this issue will hold the list of stuff that's needed for that to happen (or that I think it is, if more is needed please comment) until the PR is made:

- [x] Run loom's `migrateMappings` to MojMap
       I don't think this migrates mixin targets and that stuff, so that'll be the next step
- [x] Migrate all mixin targets to MojMap
       If possible I'll try to use [MercuryMixin](https://github.com/CadixDev/MercuryMixin) to prevent having to do it manually, though that'd likely need modifying loom unless I want to start my own remapping tool, which... I don't
- [x] Test the game still launches and there are no visible errors
       I've been advised migrateMappings isn't perfect and tends to make some mistakes when remapping
- [ ] Fix existing PRs?
       Pretty much all existing PRs will stop working, given they'll have conflicts everywhere and different mappings. So something will have to be done, either by their authors or from here in Carpet.

**Comment by Ghoulboy78** [comment]
For the existing PRs, maybe wait for the bigger ones to get accepted, and then for the smaller ones let the authors rewrite?
