### ISSUE TITLE
starlight mod is not compatible with carpet mod's command "/log lightQueue"

### ISSUE THREAD

**Issue by haha44444** [gnembon/fabric-carpet#1296]
Carpet mod's command "/log lightQueue" doesn't work when I add starlight mod to server. The values will all become 0 and will not change. Starlight mod completely rewrites minecraft's terrible lighting engine. Maybe this is the problem, can it be fixed, because the starlight mod is a big boost to my server. you know, in 1.18, the optimizations brought by the phosphor mod are not enough. thx.

you can find the starlight mod in here: [https://github.com/PaperMC/Starlight](https://github.com/PaperMC/Starlight)

**Comment by altrisi** [comment]
Light queue is not from Carpet.

Anyway, I'd expect something like that to break with starlight given it rewrites the lighting engine.

**Comment by haha44444** [comment]
> Light queue is not from Carpet.
> 
> Anyway, I'd expect something like that to break with starlight given it rewrites the lighting engine.

sorry, I submitted wrong. very sorry.
