### ISSUE TITLE
[Scarpet Suggestion] Cancelling schedules

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1304]
A way to cancel a `schedule` would be nice.

Maybe schedule() could return some kind of identifier value, and then you could pass that to a function that would cancel it. Haven't really thought of a full-suggestion for it, just that something to do it would be nice to have.

**Comment by gnembon** [comment]
well, you can technically do that yourself by checking some variable when running a scheduled function to continue or not, right?

**Comment by gnembon** [comment]
passing the callback ID as an argument

**Comment by gnembon** [comment]
I wouldn't personally be in favour of skipping adding functinoality that can be easily added in-app
