### ISSUE TITLE
Carpet Crashing on Launch

### ISSUE THREAD

**Issue by skandabhairava** [gnembon/fabric-carpet#1326]
Details:
Windows 10
Minecraft 1.18.1 (Fabric)

Mods installed:
fabric api - 0.45.0
fabric carpet - 1.4.61

Error:
[Crash Log](https://pastebin.com/QTdmfgNi)

**Comment by altrisi** [comment]
I'm closing this given there's been no response in a while, if you're still having issues feel free to make a new issue or join the discord for help.
