### ISSUE TITLE
Items Cause Lag

### ISSUE THREAD

**Issue by DriestLearner** [gnembon/fabric-carpet#133]
The items cause a lot of lag because if I'm not mistaken they check each gametick to see if they are colliding with other blocks (from 1.13 onwards the items lagging 4/5 times more than 1.12)

**Comment by indoorjetpacks** [comment]
Do you have an example world and carpet setup you could share as an example?

**Comment by gnembon** [comment]
I guess the issue is about a general item lag that is caused by having couple hundred item entites in a single spot.

**Comment by shenjackyuanjie** [comment]
maybe we can add anther chose to open or close to make item not more lagge, just like the chose "fast Redstone dust"

**Comment by akhyarrh** [comment]
I think this is can be solved by using tweakeroo disableEntityTicking (or also you can use disableEntityRendering)

**Comment by Megaminx12** [comment]
Use lithium to fix lag.

**Comment by gnembon** [comment]
exactly
