### ISSUE TITLE
fogOff doesn't work

### ISSUE THREAD

**Issue by Little8man** [gnembon/fabric-carpet#1343]
With a brand new copy of fabric 1.18.1 and the mod, you cannot turn fog off. The mod folder only contains Carpet, Architectury, and FabricAPI. When fogOff is turned to true, the fog remains.

**Comment by altrisi** [comment]
Works for me on 22w06a.

Make sure you have Carpet on your client, and that `superSecretSetting` is set to `false`.

**Comment by gnembon** [comment]
and run carpet on a client even if you connect to a carpet server (or vanilla server)

can you provide a screenshot? might be a dependency with that other mod.
