### ISSUE TITLE
Please add /player xxx drop(stack) [slot].

### ISSUE THREAD

**Issue by ch-yx** [gnembon/fabric-carpet#137]
Once fake player pick up some item, i can only get it back if it is on his mainhand.(KeepInventory is on)

Please consider adding a opinion "slot".

**Comment by gnembon** [comment]
makes sense.

but... you can still do that right now:
/script run drop_item(player('<player_name>'), 3, 1)  // drop one item from slot 3 of player <player_name>
/script run drop_item(player('<player_name>'), 3)  // drop everything from slot 3 of player <player_name>

**Comment by gnembon** [comment]
is that sufficient?

**Comment by ch-yx** [comment]
Thanks for your reply!
But, I am not operator and cannot run scripts.

I hope you could add that in the next verson.

Thanks you.

**Comment by gnembon** [comment]
makes sense

**Comment by gnembon** [comment]
added as extra options for drop and dropStack: all, mainhand, offhand or <slot>
