### ISSUE TITLE
Release did not publish: Carpet Mod 1.4.68 for Minecraft 22w12a

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1373]
Carpet Mod 1.4.68 has just released, but it's currently only available for 1.18.2.
It looks like the [release workflow for publishing the snapshot jar](https://github.com/gnembon/fabric-carpet/runs/5683187809?check_suite_focus=true) got canceled because the [release workflow for the latest Minecraft release](https://github.com/gnembon/fabric-carpet/runs/5683187727?check_suite_focus=true) failed with the following error:
```
Error: 400: Bad Request
Response body:
{"errorCode":1009,"errorMessage":"Invalid game version ID: 9016 belongs to an invalid dependency."}
Request body:{"errorCode":1009,"errorMessage":"Invalid game version ID: 9016 belongs to an invalid dependency."}
```

Can you please re-run the release workflow as soon as possible to ensure snapshot versions are available in a timely manner?

**Comment by altrisi** [comment]
It already got published on github.
