### ISSUE TITLE
crash on world load (fabric-1.15.2) possible mod conflict

### ISSUE THREAD

**Issue by SDUBZ** [gnembon/fabric-carpet#138]
fabric-carpet-1.15.2-pre1-1.3.5+v200114
carpet-extra-1.15.2-pre1-1.3.5
log:
https://paste.ee/p/u6rZy

**Comment by gnembon** [comment]
The conflict is with another mod that uses it and requires it. They should raise their priority if its important for them. AFAIK carpet already marks this mixin as optional, so once they make theirs more important all should work.
