### ISSUE TITLE
Remove or repurpose update suppression related rules

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1395]
- [ ] `updateSuppressionCrashFix` is irrelevant now given update suppression is no longer done via exceptions.
      Being removed in #1445 

- [x] ~~`updateSuppressionBlock` should either be removed as well, or be adapted to work with the new system. Right now it probably crashes the game given it throws a `StackOverflowError`. @fxmorin pinging you since you wrote this one.~~ `updateSuppressionBlock` got an update for 1.19 in #1401

**Comment by fxmorin** [comment]
You are correct. I will also be removing the code in carpet-fixes related to update suppression, although maybe not for a bit. Currently I have the rule `reIntroduceInstantBlockUpdates` which brings back the instant block updates using the method that mojang wrote. So I actually still use `updateSuppressionCrashFix` I can move that into carpet-fixes if you don't want it anymore.
As for `updateSuppressionBlock` I will add that into carpet-fixes's debug tools, and write a new tool for the new update 'suppression' technique

**Comment by altrisi** [comment]
Can always keep the block one if it can be updated for the new method, just the crash fix right now is useless given with only carpet given it can no longer cause a crash (afaik at least).
