### ISSUE TITLE
Elder guardians convert to elder guardians when struck by lightning, which resets their HP

### ISSUE THREAD

**Issue by vktec** [gnembon/fabric-carpet#141]
`ElderGuardianEntity` extends `GuardianEntity` and hence inherits the overridden `onStruckByLightning` method. A simple fix would be to mixin to `ElderGuardianEntity` and define an `onStruckByLightning` that calls `Entity`'s `onStruckByLightning` instead.

**Comment by gnembon** [comment]
thanks for pointing that out
