### ISSUE TITLE
Setting Interactionupdates to false does not disable stairs changing shape when blocks/other stairs are placed next to them.

### ISSUE THREAD

**Issue by JackSPD** [gnembon/fabric-carpet#1417]
Setting Interactionupdates to false says it prevents all block updates when blocks are placed/destroyed. However, if you use the debug stick to force a stair to be the 'corner' variant and then place any block next to it with Interactionupdates set to false the stair will revert to it's standard orientation as per it's vanilla behaviour. I suggest adding the capability to disable this into the Interactionupdates command or have a new command that disables the process where stairs check their neighbours to determine their orientation.

**Comment by altrisi** [comment]
Seems to work fine in current versions. It sometimes flickers for a moment but otherwise the blockstate is kept. Tested in singleplayer.
