### ISSUE TITLE
Use Player Shadow to cause the server to collapse

### ISSUE THREAD

**Issue by whes1015** [gnembon/fabric-carpet#1427]
[Server] [00:22:14] [Server thread/ERROR]: Error executing task on Server
[Server] java.lang.IllegalStateException: Cannot remove non-existing user ffd859d9-60d2-4d73-844f-8aabb4fb0808
[Server]        at xyz.jpenilla.tabtps.common.service.UserService.removeUser(UserService.java:160) ~[tabtps-fabric-mc1.18.2-1.3.12.jar:?]
[Server]        at xyz.jpenilla.tabtps.common.service.UserService.handleQuit(UserService.java:193) ~[tabtps-fabric-mc1.18.2-1.3.12.jar:?]
[Server]        at net.minecraft.class_3324.handler$cbj000$injectRemove(class_3324.java:4975) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3324.method_14611(class_3324.java) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_10839(class_3244.java:1166) ~[server-intermediary.jar:?]
[Server]        at carpet.patches.EntityPlayerMPFake.lambda$kill$2(EntityPlayerMPFake.java:125) ~[fabric-carpet-1.18.2-1.4.66+v220228.jar:?]
[Server]        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zbo000$modifiedRunLoop(MinecraftServer.java:3405) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by whes1015** [comment]
![image](https://user-images.githubusercontent.com/44525760/164756237-ebebdc97-5dce-4e39-aeb2-2f756361c896.png)

**Comment by Crec0** [comment]
It's the fault of Tab TPS
<https://github.com/jpenilla/TabTPS/blob/master/common/src/main/java/xyz/jpenilla/tabtps/common/service/UserService.java#L157-L163>

**Comment by whes1015** [comment]
> It's the fault of Tab TPS https://github.com/jpenilla/TabTPS/blob/master/common/src/main/java/xyz/jpenilla/tabtps/common/service/UserService.java#L157-L163 Carpet has `/log tps` and `/carpet setDefault defaultLoggers tps` which you can use to have tps in tab menu.

After I used `/carpet setDefault defaultLoggers tps` Still the same error

**Comment by Crec0** [comment]
You have to remove tabtps. Tabtps mod is causing issues

**Comment by Crec0** [comment]
Carpet has all the commands you using TabTps for.
`/profile health` and `/profile entities` for the tps info command.
`/ping` for the ping command
