### ISSUE TITLE
Typo in release name - Minecraft snapshot "22w171" does not exist; did you mean "22w17a"?

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1435]
The release for Carpet mod version 1.4.73 has "22w171" in the title. A snapshot with that version name does not exist, but Minecraft snapshot 22w17a was released today and should have been the intended target for this release.

https://github.com/gnembon/fabric-carpet/releases/tag/1.4.73

**Comment by altrisi** [comment]
Fixed.
