### ISSUE TITLE
problem of command shadow(1.16.5)

### ISSUE THREAD

**Issue by P31pr** [gnembon/fabric-carpet#1442]
It's known that `/player [player's name] shadow` doesn't work in single player mode and the single player server will stop working if you try to make yourself shadow. I tried to use this command in my single player save and I found that the fake player seems to join the game not with the latest playerdata but the playerdata saved last time. When I opened the save again, I found that the playerdata was not saved but the world was updated. For example, I can duplicate any item by following the process below:

1. get the item you want to duplicate in your inventory
2. save and quit to title
3. open the save again
4. drop the item you want to duplicate on the ground
5. type'/player [your name] shadow' and enter
6. you will see 'you are logged in from another location', click 'back to server list' and then back to title screen
7. open the save again, you'll see the item you want to duplicate both in your inventory and on the ground

**Comment by Ghoulboy78** [comment]
Does this problem persist in newer versions? (I mean, it probably doesn't, but we're not supporting 1.16.5)

**Comment by P31pr** [comment]
> Does this problem persist in newer versions? (I mean, it probably doesn't, but we're not supporting 1.16.5)

I've just tried it in 1.18.2 and found the problem remains

**Comment by Ghoulboy78** [comment]
I mean't doesn't not does, mah bad. Also, I think there are plans to redo /player shadow that may make this problem obsolete.. if not, ig the solution would be if you do /player [shadow] yourself, then we detect that, save your inventory, and then copy the inventory onto the newly spawned player. Tho im not 100% sure that would work in SP.
