### ISSUE TITLE
overlay.sc structure renderer does not recognize structures in datapacks

### ISSUE THREAD

**Issue by liqinyuan1211** [gnembon/fabric-carpet#1447]
`/overlay` command cannot recognize structures in other namespaces containing colon. might be related to [this line](https://github.com/gnembon/fabric-carpet/blob/bbe770184e3af8bb0fac3373466351445015d075/src/main/resources/assets/carpet/scripts/overlay.sc#L47).

Game version: 1.18.2

fabric-carpet version: fabric-carpet-1.18.2-1.4.69+v220331

fabric loader version: fabric-loader-0.13.3

fabric-api version: fabric-api-0.50.0+1.18.2

**Comment by Ghoulboy78** [comment]
True that, tho idk how we would fix it...

**Comment by altrisi** [comment]
I think #1283 should fix this, but I'm unable to test it because I have nothing providing those structures.
