### ISSUE TITLE
Player Login like Quick Carpet

### ISSUE THREAD

**Issue by ChrisHiho1** [gnembon/fabric-carpet#1449]
Quick Carpet has a feature to spawn PlayerBots on the same postion where u killed them using /player xy login .

I am not able to find it in the FabricCarpet mod

**Comment by Ghoulboy78** [comment]
This may have to do with the fact that fabric carpet is not quick carpet...
But here you can use `keepalive.sc` from the scarpet app store: https://github.com/gnembon/scarpet/blob/master/programs/utilities/keepalive.sc

**Comment by gnembon** [comment]
carpet shouldn't store any non-vanilla data if possible. Especially that there is an app that can take all the blame for extra non-vanilla data here.

As per Ghoulboy, you can achieve that with apps. Type `/script download utilities/keepalive.sc` and you should be good.
