### ISSUE TITLE
fake players cannot use critical hits

### ISSUE THREAD

**Issue by Blveberry** [gnembon/fabric-carpet#1478]
when setting a timer for a fake player to jump once, then attack once doesn't preform critical attacks (fake players can use knockback attacks and sweeping attacks just fine)

steps to reproduce:
1. use /player [name] spawn
2. set up a clock with two command blocks
3. set the first command to /player [name] jump once
4. set the second command to / player [name] attack once
5. stand in front of the player in survival
6. player does not preform a critical attack

**Comment by Matt-E173** [comment]
I also see this issue happening in 1.21.4 and 1.21.5 as well, and would like to point out the following as a casual reminder in case this  gets overlooked from the **1.21.5** changelogs:

"The FallDistance field has been changed from float to double and is now called fall_distance" 
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-5
