### ISSUE TITLE
["Contributing"] Support for accurate block placement protocol on Spigot / Paper.

### ISSUE THREAD

**Issue by SzczurekYT** [gnembon/fabric-carpet#1484]
Hello
I would like to try making plugin that would make accurate block placment protocol work on Spigot / Paper servers. From what I understand this works through custom packets, and they can be also implemented on spigot.
Are there any docs about that protocol or if no: where should I look at source code to understand this?

**Comment by replaceitem** [comment]
Accurate block placement is part of carpet-extra.
Here is the mixin for it (it does not use custom packets): https://github.com/gnembon/carpet-extra/blob/master/src/main/java/carpetextra/mixins/BlockItemMixin_accurateBlockPlacement.java
And the implementation is here: https://github.com/gnembon/carpet-extra/blob/6dc7b62eaf64ce05544625533e55f175e8ebf2cb/src/main/java/carpetextra/utils/BlockPlacer.java

**Comment by SzczurekYT** [comment]
> Accurate block placement is part of carpet-extra. Here is the mixin for it (it does not use custom packets): https://github.com/gnembon/carpet-extra/blob/master/src/main/java/carpetextra/mixins/BlockItemMixin_accurateBlockPlacement.java And the implementation is here: https://github.com/gnembon/carpet-extra/blob/6dc7b62eaf64ce05544625533e55f175e8ebf2cb/src/main/java/carpetextra/utils/BlockPlacer.java

Thanks for these informations, I will look into that and see if it's possible do something with that.
I will close this for now.
