### ISSUE TITLE
As of 22w07a (mod version 1.4.61), `sample_noise` always returns null, despite what the documentation says.

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1487]
https://github.com/gnembon/fabric-carpet/blob/74f56c1c7cccbc1dc18da9c9c8fae04a64577fb5/src/main/java/carpet/script/api/WorldAccess.java#L1624-L1626

Exactly as the title says.

According to the documentation, the function should return (one or more properties of the) noise map at a given location.

**Comment by altrisi** [comment]
It was mentioned in the release, but it hasn't been fixed yet. I don't think it was expected to be disabled for so long, that's why docs weren't changed.

**Comment by altrisi** [comment]
Resolved given `sample_noise` has now been replaced by `compute_density_function` in f2c658bf03562a88b1d283729fce3f00b6874b7e
