### ISSUE TITLE
[1.19.1] Backlog

### ISSUE THREAD

**Issue by SoniEx2** [gnembon/fabric-carpet#1489]
Wouldn't it be nice if you could hop on a server and see past messages since your previous login?

What if someone told you Minecraft 1.19.1 is adding that possibility, but the base game doesn't have it?

What if someone told you how to implement it on top of Minecraft 1.19.1?

Attached is a similar mechanism to what 1.19.1 brings to the table. Instead of using a server to relay backlog, one could use a DHT (Distributed Hash Table) instead.

[merkle-tree.md](https://github.com/gnembon/fabric-carpet/files/9081110/merkle-tree.md)

As long as any DHT-enabled player has been online to log the chat messages, any other player can get the full backlog since the last visit. And the carpet mod is popular enough to make client-only backlogging feasible, even if not 100% reliable. It could be boosted to 100% of the time by also installing it on the server, but that should be kept optional.

**Comment by altrisi** [comment]
What

**Comment by SoniEx2** [comment]
1.19.1 adds cryptographically-verifiable chat sequence. you can just grab the messages and verify the sequence.

**Comment by SoniEx2** [comment]
carpet's the cool hacks mod. this sounds like a cool hack.
