### ISSUE TITLE
[bug] crash server 1.19 Fabric

### ISSUE THREAD

**Issue by MrJorman** [gnembon/fabric-carpet#1496]
[crash-2022-07-15_17.57.12-server.txt](https://github.com/gnembon/fabric-carpet/files/9121902/crash-2022-07-15_17.57.12-server.txt)

**Comment by James103** [comment]
Are you able to reproduce this in singleplayer with just Carpet mod and Lootr (plus dependencies) installed?

To reproduce, try blowing up a Lootr chest with an explosion (TNT, creeper, ghast fireball, Wither on spawn, etc). If a vanilla chest would be destroyed by the explosion, so will the Lootr chest, causing the crash.

**Comment by MrJorman** [comment]
sec

**Comment by MrJorman** [comment]
in single player no crash.

**Comment by MrJorman** [comment]
I checked with all the mods again - there is no crash, it decorates randomly or something..

**Comment by MrJorman** [comment]
Please fix it. Crash appears randomly.

**Comment by MrJorman** [comment]
[carpet.txt](https://github.com/gnembon/fabric-carpet/files/9122053/carpet.txt)
[carpet-fixes.txt](https://github.com/gnembon/fabric-carpet/files/9122057/carpet-fixes.txt)

My rules

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/179255813-ed9b6006-717c-4020-8a44-b9fcec1df224.png)
explosion here chest

**Comment by MrJorman** [comment]
https://github.com/noobanidus/Lootr/issues/130 check bro

**Comment by MrJorman** [comment]
Lootr developer wants to contact you about bugs and crashes

**Comment by embeddedt** [comment]
@MrJorman You are using C2ME, which modifies a lot of Minecraft internals to be multithreaded in ways that mods don't expect. I am not sure if this is the reason for this specific crash but I really recommend you avoid it especially if you are using other mods.

**Comment by ishland** [comment]
> You are using C2ME, which modifies a lot of Minecraft internals to be multithreaded in ways that mods don't expect. I am not sure if this is the reason for this specific crash but I really recommend you avoid it especially if you are using other mods.

C2ME do not make any server ticking code run in multithreaded. It is expected to be working with fabric-carpet and I personally don't have any issues with this combination.

**Comment by altrisi** [comment]
Oh this specific crash was caused by a mod mixing into Carpet quite sure, I believe it has been fixed since. Comment or open a new issue if it still happens though.
