### ISSUE TITLE
Scarpet: Add `__on_player_placing_block` (name subject to change)

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1498]
Currently, `__on_player_places_block` is fired _after_ the player places a block, not before. According to #1497, changing this "would involve a significant behaviour change, breaking many scripts".

As a compromise, a new event `__on_player_places_block_pre` should be added, which functions just like `__on_player_places_block`, the only difference being it fires _before_ the block is placed.

By doing this, existing scripts can keep the current behavior, while new scripts can take advantage of the new event and the features in #1497 to block the placement of a block under certain conditions.

**Comment by ch-yx** [comment]
100% support.

**Comment by replaceitem** [comment]
Yeah, adding a new event is probably the way to go, i'm just not sure what name it would have

**Comment by Ghoulboy78** [comment]
maybe `__on_player_placing_block` cos it's right as the player is placing the block, as opposed to after they place it?

**Comment by replaceitem** [comment]
This can be closed now, as of 24b9c386ec2a3527ba4e19c0fb2fbae9f522724c

**Comment by altrisi** [comment]
Was the event added? Or the current one modified?

**Comment by replaceitem** [comment]
It was added in the cancellation PR, triggering before the placing, allowing to cancel. The old event `__on_player_places_block` remained untouched.
