### ISSUE TITLE
[scarpet] Failure to read contents of files containig uppercase characters

### ISSUE THREAD

**Issue by Firigion** [gnembon/fabric-carpet#1502]
Steps to reproduce:

1. Create a script `test.sc` and a corresponding data directory `test.data` in a world's scripts folder.
2. Place a txt file in the data directory with some random contents, `testing`, for example. Crucially: name the file `Test.txt`, mind the uppercase T.
3. Edit `test.sc` to read from the file like so: `print(read_file('Test', 'text'))`
4. When loading the app with `/script load test`, the app prints `null`.

Expected behaviour:
When loading the app, it should print `testing`.

MC version: 1.18.2
Carpet version: 1.4.66

**Comment by CommandLeo** [comment]
I'm unable to reproduce in 1.18.2 1.4.66
![image](https://user-images.githubusercontent.com/51045936/180184493-65afd698-8449-4afb-8cef-8c9a040de5c8.png)

**Comment by altrisi** [comment]
I think this may be the cause, not tested yet though:

https://github.com/gnembon/fabric-carpet/blob/c919a8c4c70455c63e70aa015989352216f2a93a/src/main/java/carpet/script/argument/FileArgument.java#L141-L144
