### ISSUE TITLE
Failed to handle entity type

### ISSUE THREAD

**Issue by LOGICHACK** [gnembon/fabric-carpet#1509]
It Seems Carpet Has An Issue spawning Mod Entities Every Tick basically There is an Error
Failed to handle entity type Mod:mob
It Not Limited To Any Particular Mod Just all Of Them 
Spawned Mobs Are Fine

**Comment by James103** [comment]
Can you please post your latest.log?

**Comment by altrisi** [comment]
This wasn't a carpet issue but it was fixed a while ago in the mod that caused it.
