### ISSUE TITLE
Issue out of nowhere?

### ISSUE THREAD

**Issue by GamerMaggot** [gnembon/fabric-carpet#1510]
Hi!
I have recently experienced issues with this mod after using carpet for a while. Now when i type /carpet in chat i get no response. Neither do i get an option to change for example stackable shulkers to permanent. Is there a setting that I accidentally pressed? I even tried to delete carpet and download it again but with no success. /profile health nor /profile entities commands work either, which they used to. Please help me!

**Comment by James103** [comment]
Can you please post your `latest.log`?

Also test `tick warp 1000` to see if tick warping works, and/or `script run print('Hello World!')` to test the scripting system. Do they still work?

**Comment by altrisi** [comment]
That usually means you (or some datapack or something) has disabled the gamerule `sendCommandFeedback`. Set it back to true with `/gamerule sendCommandFeedback true` and check if it works.

**Comment by GamerMaggot** [comment]
Thanks for quick responses! The problem was the "/gamerule sendCommandFeedback true". 
Carpet is working again, amazing! 
Thanks!!!
