### ISSUE TITLE
Event "__on_player_message" isn't triggered when runs command

### ISSUE THREAD

**Issue by Harveykang** [gnembon/fabric-carpet#1511]
https://github.com/gnembon/fabric-carpet/blob/master/docs/scarpet/api/Events.md#__on_player_messageplayer-message
> ### `__on_player_message(player, message)`
> Triggered when a player sends a chat message or runs a command.

isn't triggered when run command.
test on MC 1.19 + carpet 1.4.79 and MC 1.19.1-rc2 + carpet 1.4.82

**Comment by replaceitem** [comment]
Since 1.19, commands are a seperate from chat messages, which makes this no longer trigger.
Might be a good idea to add a command event

**Comment by ch-yx** [comment]
*adding command event*
some apps accidently cancel every command.
cannot stop it without restarting server.
