### ISSUE TITLE
Errors in currently selected datapacks prevented the world from loading

### ISSUE THREAD

**Issue by EarthMessenger** [gnembon/fabric-carpet#1514]
When I try to load any world with fabric-carpet:  
![image](https://user-images.githubusercontent.com/49364506/181475901-cfbf8c8d-f1e6-4a1d-adac-d16dd8b6428a.png)  
Nothing happens after clicking the "Safe Mode" button.

The log file: [latest.log](https://github.com/gnembon/fabric-carpet/files/9207920/latest.log)

My launcher: [HMCL](https://github.com/huanghongxun/HMCL)
OS: Arch Linux  
Kernel: 5.18.14-arch1-1  
Java: openjdk 18.0.2  
fabricloader: 0.14.8  
carpet: 1.4.82  
minecraft: 1.19

**Comment by altrisi** [comment]
1.4.82 is for 1.19.1-rc2
