### ISSUE TITLE
if player drops the item he received from inventory_set fast enough, it will not trigger vanilla inventory_changed advancement.

### ISSUE THREAD

**Issue by ch-yx** [gnembon/fabric-carpet#1515]
use a repeating command block :
/player chenyuxuan dropStack all

give me many a apple via inventory_set:
/script run inventory_set(player('chenyuxuan'),0,3,'apple')

the advancement is not triggerd at all. neither getting nor dropping triggers the advancement.

but if i give myself apples by /give or picking up item or some thing:
the advancement will be triggerd twice (get&drop). 

_found when testing a bug in my script fakeplayer_inv_editor. that player could use it to clone items._

**Comment by SakuraWald** [comment]
Can confirm in 1.20.1 with carpet-fabric 1.4.112+v230608
