### ISSUE TITLE
Attempting to download a file/version and the wrong file downloads

### ISSUE THREAD

**Issue by wildmanviper** [gnembon/fabric-carpet#1520]
[Carpet Mod v1.4.79 for 1.19](https://www.curseforge.com/minecraft/mc-mods/carpet/files/3820789) states its for version 1.19 but instead downloads "fabric-carpet-1.19.1-1.4.83+v220727"  Just a link to the wrong file.  I was able to successfully pull the file needed from Github and its working without crashing due to the wrong version.

**Comment by altrisi** [comment]
Cannot reproduce, it downloads the correct file for me. If this actually happened and wasn't a confusion, it'd have been curseforge's fault too, there's nothing we can do.
