### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by MrJorman** [gnembon/fabric-carpet#1527]
[crash-2022-08-09_12.34.50-server.txt](https://github.com/gnembon/fabric-carpet/files/9290696/crash-2022-08-09_12.34.50-server.txt)
crash server

**Comment by MrJorman** [comment]
my carpet
[carpet.txt](https://github.com/gnembon/fabric-carpet/files/9290707/carpet.txt)
[carpet-fixes.txt](https://github.com/gnembon/fabric-carpet/files/9290708/carpet-fixes.txt)

**Comment by altrisi** [comment]
This isn't an issue with carpet, but with TIS Addition.
