### ISSUE TITLE
'facing' 'player' in shapes makes them turn with the player turning.

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#1543]

**Comment by ch-yx** [comment]
will fixing that break backwards compatibility?

**Comment by ch-yx** [comment]
i suggest rename current 'facing'='player' to 'eyesight', and add a new facing=player

**Comment by ch-yx** [comment]
this bug has already been fixed.
someone should close it.

**Comment by altrisi** [comment]
Ok
