### ISSUE TITLE
Ctrl+Q fix disabled

### ISSUE THREAD

**Issue by MOOOOs** [gnembon/fabric-carpet#1544]
Carpet disables [MC-135971](https://bugs.mojang.com/browse/MC-135971) fix when its launched with debugify. Any way to make this fix stay? This fix is meant to make Ctrl Q work in worksbench to drop all craftable items on ground

**Comment by Crec0** [comment]
Carpet's mixin is more aggressive however, both do the exact same thing. So, the result shouldn't differ.

**Comment by MOOOOs** [comment]
debugify has that fix but carpet disables it what are you talking about i can't use ctrl q in crafting bench when this happens

**Comment by MOOOOs** [comment]
if carpet disable debugify can i enable it in carpet in some way if it has same fix?

**Comment by Crec0** [comment]
Run the command `/carpet setDefault ctrlQCrafting true`

**Comment by MOOOOs** [comment]
Thanks is this map specific or i need to use this command once in game and it will stay in all maps

**Comment by MOOOOs** [comment]
For some reason carpet says unknown rule

**Comment by MOOOOs** [comment]
oh nvm i just deleted true part and it shown that its /carpet setDefault ctrlQCraftingFix true
