### ISSUE TITLE
Piglin Brutes spawn in air when piglinsSpawningInBastions is turned on

### ISSUE THREAD

**Issue by Ace-tyl** [gnembon/fabric-carpet#1546]
After cleaned the bastion to make a piglin brute farm (it can produce ancient debris in my server), I found the piglin brutes can spawn in air and start falling down immediatly after they are spawned.

**Comment by James103** [comment]
What Carpet mod version is the server running?

**Comment by Ace-tyl** [comment]
the newest version 1.4.83 for Minecraft 1.19.1

**Comment by Ace-tyl** [comment]
> What Carpet mod version is the server running?

The newest version 1.4.83 in Minecraft 1.19.1

**Comment by aria1th** [comment]
This is caused because SpawnPlacements does not have Piglin Brutes registry.
