### ISSUE TITLE
[Bug] Fake players randomly catch on fire after a few seconds of spawning

### ISSUE THREAD

**Issue by KBeiller** [gnembon/fabric-carpet#1548]
Exactly what the title says, heres a clip https://medal.tv/games/minecraft/clips/zFuAnlWh6LyRk/rsGfX9gR78pF?invite=cr-MSxFdmwsNTg1NTUyNCw. Im currently running on fabric-carpet-1.19.1-1.4.83+v220727.
Dunno if this has been fixed yet

**Comment by altrisi** [comment]
Were they on fire before disconnecting?

**Comment by KBeiller** [comment]
Im pretty sure not since i always leave them in an afk spot away from any danger

**Comment by KBeiller** [comment]
mb i forgot i have fire aspect in my sword
