### ISSUE TITLE
Update supressor error

### ISSUE THREAD

**Issue by Foxius** [gnembon/fabric-carpet#1552]
`[09:31:27] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@43d4d3ee, suppressing error          carpetfixes.helpers.UpdateSuppressionException: Update suppression                                                              at net.minecraft.class_7165.handler$zok000$skipCrashReport(class_7165.java:536) ~[server-intermediary.jar:?]            at net.minecraft.class_7165.method_41708(class_7165.java:44) ~[server-intermediary.jar:?]                               at net.minecraft.class_7164.method_41703(class_7164.java:29) ~[server-intermediary.jar:?]                               at net.minecraft.class_7164.method_41704(class_7164.java:24) ~[server-intermediary.jar:?]                               at net.minecraft.class_7164.method_41705(class_7164.java:519) ~[server-intermediary.jar:?]                              at net.minecraft.class_3218.method_8452(class_3218.java:1015) ~[server-intermediary.jar:?]                              at net.minecraft.class_3218.method_8408(class_3218.java:1435) ~[server-intermediary.jar:?]                              at net.minecraft.class_1937.redirect$zzj000$updateNeighborsMaybe(class_1937.java:1069) ~[server-intermediary.jar:?]                                                                                                                             at net.minecraft.class_1937.method_30092(class_1937.java:245) ~[server-intermediary.jar:?]                              at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[server-intermediary.jar:?]                               at net.minecraft.class_2428.method_9534(class_2428.java:77) ~[server-intermediary.jar:?]                                at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964) ~[server-intermediary.jar:?]                   at net.minecraft.class_3225.redirect$zec000$activateWithOptionalCactus(class_3225.java:1029) ~[server-intermediary.jar:?]                                                                                                                       at net.minecraft.class_3225.method_14262(class_3225.java:338) ~[server-intermediary.jar:?]                              at net.minecraft.class_3244.method_12046(class_3244.java:1145) ~[server-intermediary.jar:?]                             at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]                               at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]                                at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]                               at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]                                        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]                              at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]                               at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]             at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]             at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]                              at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]             at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]             at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]                              at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]             at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2894) ~[server-intermediary.jar:?]                                                                                                                  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]             at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]             at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by altrisi** [comment]
That seems to be an issue with an extension (probably carpet fixes from a quick look), you should report it to their author: (https://github.com/fxmorin/carpet-fixes).

It seems like an update suppression (or a bug with it) is preventing packets from being processed or something, though I don't know about it so I may be wrong.
