### ISSUE TITLE
Is there any way to respawn bots when server restarting? 

### ISSUE THREAD

**Issue by SirMishaa** [gnembon/fabric-carpet#1554]
Hello! 

I absolutely love your great work. I'm wondering if there is a way to respawn automatically bots when the server restart / start. 

I'm a developer, so I can make a script if needed, but I'm just starting with carpet. 

Kind regards

**Comment by CommandLeo** [comment]
From the FAQ in the Discord server:
> You can use the keepalive.sc script for that. To install it, just run
`/script download utilities/keepalive.sc`

> Note that this won't keep the actions the bots were doing, like continuous clicking or attacking.
