### ISSUE TITLE
How can I use the carpet module without opening it for cheating?

### ISSUE THREAD

**Issue by QianMuu** [gnembon/fabric-carpet#1555]
In the single player world, I don't want to turn on cheating mode, but I want to use carpet mod. What should I do?

I just need to create a dummy to facilitate loading the block

**Comment by altrisi** [comment]
You can either:
- With cheats once, set the `commandPlayer` rule to `true` permanently (with `/carpet commandPlayer true`)
- Without cheats ever, create a `carpet.conf` file in your world folder and with a line saying `commandPlayer true`
