### ISSUE TITLE
1.19.2 Server crash : Exception in server tick loop

### ISSUE THREAD

**Issue by fluffy-git** [gnembon/fabric-carpet#1562]
Crash report:
[crash-2022-10-05_06.15.29-server.txt](https://github.com/gnembon/fabric-carpet/files/9713302/crash-2022-10-05_06.15.29-server.txt)

Carpet.conf
[carpet.conf.txt](https://github.com/gnembon/fabric-carpet/files/9713307/carpet.conf.txt)
(had to change it to txt so github would allow me to upload it)

**Comment by altrisi** [comment]
What were you doing when this happened? Or did it happen randomly?

**Comment by fluffy-git** [comment]
i restarted the server after chaning the carpet gamerules and it crashed directly on startup

**Comment by altrisi** [comment]
I think I know why this happens, as a workaround try disabling rules that use Scarpet for now (if you know which of them do, else try disabling some of the ones you recently changed until it works again).

**Comment by fluffy-git** [comment]
okay will do

**Comment by altrisi** [comment]
This should now fixed for the next version, if you want you can get the dev build earlier in the Artifacts section of github actions here: https://github.com/gnembon/fabric-carpet/actions/runs/3188327223
