### ISSUE TITLE
How to use /player command in survival singleplayer world without using cheats

### ISSUE THREAD

**Issue by CrazyGamer488** [gnembon/fabric-carpet#1563]
Hi, I have a Hardcore world and I am building a raid farm by Cowking he recommended a carpet mod for the auto clicker but I don't want to use cheats (using LAN) to enable the carpet is there a way to configure the mod in my Hardcore Minecraft world. I tried using an external auto clicker but due to lag it breaks the armor stand so is there a way I can enable /player command without opening LAN or cheats please Thanks!

**Comment by altrisi** [comment]
You can either:
- With cheats once, set the `commandPlayer` rule to `true` permanently (with `/carpet commandPlayer true` then click set permanently)
- Without cheats ever, create a `carpet.conf` text/notepad file in your world folder with a line being `commandPlayer true`

**Comment by CrazyGamer488** [comment]
![carpet mod 1](https://user-images.githubusercontent.com/115106300/194281855-02599cb9-82b4-48a0-81f1-0478f29bc921.PNG)
![carpet mod 2](https://user-images.githubusercontent.com/115106300/194281864-ae1327bd-ad45-4715-8a95-b30c7dc17126.PNG)
I tried it still doesn't work , Have I done it wrong?,Sorry but idk a lot about Minecraft and I just want to use carpet mod for raid farm but don't wanna use cheats even is there a way I can do it without and thanks!

**Comment by altrisi** [comment]
Make sure it's not `carpet.conf.txt`, windows has a tendency to hide the actual file extension (you can enable seeing them in the file explorer View > Show file extensions, or something like that)
