### ISSUE TITLE
Regarding the Carpet mod by gnembon

### ISSUE THREAD

**Issue by CrazyGamer488** [gnembon/fabric-carpet#1564]
Hi again Sorry for troubling but I tried the method @altrisi showed me and still didn't work here are the screenshots can you explain me more . I don't know a lot about Minecraft so can you help me and Thanks!
![carpet mod 1](https://user-images.githubusercontent.com/115106300/194283062-2b8fde00-335c-4884-a7f9-602ca6d3a573.PNG)
![carpet mod 2](https://user-images.githubusercontent.com/115106300/194283068-9d0de847-1c34-46a7-a356-1d16e92c86ae.PNG)

**Comment by CrazyGamer488** [comment]
@altrisi I tried it but it still does not work can I get your Discord to talk on it if you can? and Sorry about it I am new and I want to use it without cheats.and Thanks

**Comment by altrisi** [comment]
You can join the Carpet discord here: [discord.gg/gn99m4QRY4](https://discord.gg/gn99m4QRY4)
