### ISSUE TITLE
IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))

### ISSUE THREAD

**Issue by Hoppingmad9** [gnembon/fabric-carpet#1578]
I get the above error for all 1.19.x versions.

I've got a fabric (0.14.10) server (1.19.2) with fabric api (0.63.0) and that works fine.
When I add carpet (1.4.84+v221018) I get the error.

I have java 17 installed, no other versions on my PC.
`C:\Users\samde>java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)`

Java's in my path variable "C:\Program Files\Java\jdk-17.0.5\bin". User and system PATH.

**Comment by James103** [comment]
Same error as https://github.com/gnembon/fabric-carpet/issues/1464

**Comment by Hoppingmad9** [comment]
oh sorry, nothing showed up on google when i searched the error. I'll close this

Thanks!

**Comment by Hoppingmad9** [comment]
For me replacing the server jar with the one suggested in #1464 worked
