### ISSUE TITLE
player stop post player move doesn't cancel velocity

### ISSUE THREAD

**Issue by epifeny** [gnembon/fabric-carpet#1583]
When a `/player stop` is initiated after `/player move`, the player will decelerate slowly as if he's in fly mode, and doesn't stop instantly when the stop command was executed.

This was discussed on Discord
> https://discord.com/channels/882822986795716608/1037262867860295761/1037262867860295761

and probable reason for it here:
> https://github.com/gnembon/fabric-carpet/blob/c51f59c799c144106b43aaa9d9b33e81ddeb8a8f/src/main/java/carpet/helpers/EntityPlayerActionPack.java#L152

**Comment by Fallen-Breath** [comment]
Duplicated of #1072
