### ISSUE TITLE
Fake player does not take fall damage

### ISSUE THREAD

**Issue by TejasIsCool** [gnembon/fabric-carpet#1586]
**Version:** Testing on **carpet 1.4.84 for 1.19.2** (Although this problem does exists of other older carpet versions)

**Issue**

Fake players, summoned with the `/player name spawn` command do not take fall damage, regardless of the height they fall from.

**Possible reason:** 

Checking in the code, I used this snippet of code:

```java
if(!player.isOnGround()) {
      System.out.println(player.getName().getString()+" : "+player.fallDistance);
}
```

in the `onUpdate` function in the `EntityPlayerActionPack` class in the helpers folder. This code basically just prints the fallDistance attribute(with the name) if the any player is not on ground.

For the normal player, the fallDistance seems to increase anytime they are falling. [Image](https://postimg.cc/hhDyjdVQ)

For the fake player however, it remains at 0. [Image](https://postimg.cc/4mrQz7H5)

I think this also causes #1478 , making the fake player not be able to do critical hits, as critical hits require the fallDistance to be greater than 0.

**Comment by 1schlick** [comment]
Can confirm
