### ISSUE TITLE
Various loggers like /log tnt and /log projectile crashes the game

### ISSUE THREAD

**Issue by Void-Skeleton** [gnembon/fabric-carpet#1595]
In carpet mod for Minecraft 1.19 or above, the game crashes on a TNT explosion when the logger /log tnt or /log explosion is turned on. Similarly, the game also crashes on a projectile landing when the logger /log projectile is on.

**Comment by altrisi** [comment]
Send the crash report, though as far as I remember, many of those crashes were actually caused by extensions, and not an issue with Carpet.

**Comment by Void-Skeleton** [comment]
> Send the crash report, though as far as I remember, many of those crashes were actually caused by extensions, and not an issue with Carpet.

Alright. Since my client has many extension mods, I'll try disabling all mods except for carpet and try to reproduce this crash right now.

**Comment by Void-Skeleton** [comment]
I could not reproduce the bug with carpet mod alone. So it was indeed caused by some extension mod and not carpet itself. Sorry for the inconveniences I brought.

**Comment by altrisi** [comment]
Don't worry, it's OK. Still, if you send the crash report I may be able to tell you what mod caused it, IIRC the one I've seen the most was with Carpet TIS Addition.
