### ISSUE TITLE
shulker box stacking rule has bug.

### ISSUE THREAD

**Issue by ch-yx** [gnembon/fabric-carpet#1596]
details: 
https://discord.com/channels/882822986795716608/894946828980723762/1040993163260731392

box item entities can merge wrongly. they only need to be "empty" and has any tag to be merge.

if i rename empty boxes.  then a box named "hi" can merged with a box named "hello".

and box with loottable is viewed as empty too.(they should not)

so,if i give myself 2 box of spider and zombie:
/give @a minecraft:shulker_box{BlockEntityTag: {LootTable: "minecraft:entities/zombie"}}
/give @a minecraft:shulker_box{BlockEntityTag: {LootTable: "minecraft:entities/spider"}} 

those 2 boxes (and hi and hello) can merge with each others.

**Comment by ch-yx** [comment]
code that only check if they both have tag: 
https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/mixins/ItemEntityMixin.java#L94
code that forget loottable: 
https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/helpers/InventoryHelper.java#L59

**Comment by ch-yx** [comment]
update:    @x1t0m1t0m1x found that shulker box s color is ignored as well.

https://discord.com/channels/882822986795716608/1042722371158683648/1042722371158683648

**Comment by altrisi** [comment]
Cannot repro different color merging
