### ISSUE TITLE
Creative players still make chunks loaded in the end when `creativePlayersLoadChunks` is set to false

### ISSUE THREAD

**Issue by HackerRouter** [gnembon/fabric-carpet#1601]
The game always loads an area of the main end island when the player is in a specific area near the main island. However, it still loads the area even though the player near the main island is in creative mode and `creativePlayersLoadChunks` is set to false.

It can be seen as a vanilla bug, because spectators also make some chunks loaded in the end when `spectatorsGenerateChunks` is set to false.
Also, it is said that "creative players do not load chunks like spectators with gamerule `spectatorsGenerateChunks` false when `creativePlayersLoadChunks` is set to false", which means this bug actually works as intended in a way.

My suggestion is that consider this as a bug.

**Comment by Crec0** [comment]
This is not considered a bug because the rules work as expected. It's the dragon fight loading the main end island as long as there's a player present in the end. Rules specify the player will not load chunks, which they do not. 
A better option would be a addition of rule like `dragonFightLoadChunks` but idk.

**Comment by HackerRouter** [comment]
> This is not considered a bug because the rules work as expected. It's the dragon fight loading the main end island as long as there's a player present in the end. Rules specify the player will not load chunks, which they do not. A better option would be a addition of rule like `dragonFightLoadChunks` but idk.

I see. Alright.
