### ISSUE TITLE
Gamerule "DoDaylightCycle" fails on tick rate

### ISSUE THREAD

**Issue by M4ximumPizza** [gnembon/fabric-carpet#1606]
In 1.19.2 (Have not tested any other version), if i set the DoDaylightCycle to false and then speed up the tps, it cancels the gamerule and will continue the daylight cycle till its back at 20 tps. 

I propose a java feature in the mod that checks the gamerule settings to see if they are true or false.

**Comment by Crec0** [comment]
Not a carpet issue. Tested with carpet 1.4.84 on 1.19.2 and carpet 1.4.91 on 1.19.3. Works as expected in both cases.
Could be an incompatibily issue from any other mods you might have installed.

**Comment by James103** [comment]
Do you have the full mod list? If so, can you please post it here?

**Comment by M4ximumPizza** [comment]
I didnt think about other mods doing it and it worked fine with just Carpet mod anyways. Sorry for the inconvenience and these are the mods. 
![image](https://user-images.githubusercontent.com/109777745/207996031-362bc249-7b20-4e32-88b3-2f31e9358997.png)
