### ISSUE TITLE
[1.19.2] modifiedRunLoop crash

### ISSUE THREAD

**Issue by itsdinkd** [gnembon/fabric-carpet#1623]
1.19.2, carpet installed both server and client. This crash is a common one that isn't reproducible 
https://gist.github.com/itsdinkd/59abc048eac4f3a994ef88c307846d39

**Comment by altrisi** [comment]
Modified run loop only means carpet is installed, because it has to wrap the tick loop to be able to manipulate it with `/tick`

**Comment by altrisi** [comment]
Also this is a watchdog crash, meaning something just "took too long". If you have some more minimal reproducer, feel free to comment and I'll reopen this, or open a new issue.
