### ISSUE TITLE
[Suggestion] Continue updating this mod for 1.17.1

### ISSUE THREAD

**Issue by 1schlick** [gnembon/fabric-carpet#1624]
My reasoning is that I don't like the new terrain generation in 1.18 onwards, including the new world height and depth. Currently there is no mod which forward-ports the 1.17.1 terrain generation into newer versions, and I suspect that there never will be. Mojang could theoretically add an option to keep the old world generation in newer versions, but I also suspect that it will never happen.

So basically I'm stuck playing on 1.17.1. I would appreciate if the 1.17.1 version of carpet mod continued receiving bugfixes and QOL features.

**Comment by altrisi** [comment]
Older versions are not supported, they add a lot of work to something that is already done in free time.

However, if someone codes a backport for newer features and sends it as a PR then I'd consider releasing a new version for those versions. We're not going to port the code though, unless there's some very critical issue.
