### ISSUE TITLE
Carpet mod carpets not dissapearing

### ISSUE THREAD

**Issue by Benkasa** [gnembon/fabric-carpet#1625]
So when i do carpets set default false or just carpets set false when i shift the carpets dont dissapear and i dont know what else i have to do.

**Comment by altrisi** [comment]
Did you for some reason install the `carpets` script (a part from carpet)? Remove it from your `scripts` folder, it shouldn't be there. You should be able delete it by running `/script remove carpets`, or by going to your world's `scripts` folder and removing `carpets.sc`.

Also, do you know how it got there? It's not a thing by default, and it has happened an absurd amount of times that I think we're doing something wrong on our side.

**Comment by altrisi** [comment]
Going to close it as this isn't really a Carpet issue (unless I'm missing something), though if you still need help feel free to comment again or join the discord.
