### ISSUE TITLE
Sync `fillLimit` rule with gamerule instead of mixing the max of both in

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1629]
I think it'd be a good idea to sync the new gamerule (or max of both), so when finally removed the value of fill limit would persist.

Maybe even unset the rule after syncing.

As of 1.4.93, we take the max between our rule and vanilla's and apply that as the limit for commands.

**Comment by altrisi** [comment]
Closes #858, given the gamerule allows them

**Comment by gnembon** [comment]
Hmm, I personally don't think we need any extra work towards a feature that will expire really soon and it is already obsolete. Taking a max was a simple enough solution I thought was sufficient. I would accept it only for the fact that you already have done the effort towards it, but I woudn't bother personally.
