### ISSUE TITLE
[Suggestion]make the chose "update suppression crash fix" back

### ISSUE THREAD

**Issue by shenjackyuanjie** [gnembon/fabric-carpet#163]
maybe we can make this chose back to the carpet , I think this chose is very useful 
sorry I'm a Chinese I can't write English very well #

**Comment by altrisi** [comment]
Is the one that was added last month to Carpet extra the one that you are/were looking for? (via gnembon/carpet-extra#120, [`updateSuppressionCrashFix`](https://github.com/gnembon/carpet-extra#updatesuppressioncrashfix))

**Comment by shenjackyuanjie** [comment]
> Is the one that was added last month to Carpet extra the one that you are/were looking for? (via [gnembon/carpet-extra#120](https://github.com/gnembon/carpet-extra/pull/120), [`updateSuppressionCrashFix`](https://github.com/gnembon/carpet-extra#updatesuppressioncrashfix))

thanks! sorry i forget to look up the feacher in carpet extra!
