### ISSUE TITLE
bonemealing coral plant/fans while renewableCoral = false causes crash

### ISSUE THREAD

**Issue by 909oce** [gnembon/fabric-carpet#1638]
title

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by altrisi** [comment]
Quite sure I've fixed that in a recent version, make sure you're on the latest for your minecraft version, else post a crash report and the version you're running.

**Comment by altrisi** [comment]
Closing as stale and something that was fixed.
