### ISSUE TITLE
[Suggestion] survivalNoPortalDelay

### ISSUE THREAD

**Issue by schuelermine** [gnembon/fabric-carpet#165]
the opposite of creativePortalDelay

**Comment by gnembon** [comment]
its already there. Did you check?

**Comment by gnembon** [comment]
please close when you get his message

**Comment by gnembon** [comment]
use /carpet portalSurvivalDelay 1

**Comment by schuelermine** [comment]
> 
> 
> its already there. Did you check?

sorry
