### ISSUE TITLE
[Suggestion] Make command allowing Wither Skeletons to spawn at light level 11

### ISSUE THREAD

**Issue by JuneTheMistborn** [gnembon/fabric-carpet#1651]
As I learned after deciding to build a wither skeleton portal farm, Mojang reverted their spawning behavior to spawning only at light level 7 and below. It would be quite useful to be able to re-revert that reversion!

**Comment by gnembon** [comment]
I believe this can be done with a datapack, since that part of the code is data driven.

**Comment by JuneTheMistborn** [comment]
As far as I can tell, it can't be done with a datapack without creating a new spawning system. I've done some searches for datapacks that modify spawning behavior and they all use scoreboards and armor stands to implement their own spawning system (I believe, I'm not particularly familiar with the inner workings of the game.)
