### ISSUE TITLE
`system_info` argument `world_min_spawning_light` not present

### ISSUE THREAD

**Issue by rv3r** [gnembon/fabric-carpet#1655]
MC 1.19.3
Carpet 1.4.91

The `world_min_spawning_light` argument for the function `system_info` is listed in the docs, and, as far as my limited Java knowledge can tell, is [defined](https://github.com/gnembon/fabric-carpet/blob/c64a28ff1bf3bf8acb64b6b73e4af80ff5111fde/src/main/java/carpet/script/utils/SystemInfo.java#L185).

However, `system_info('world_min_spawning_light')` throws an "unknown option" error and using `system_info()` matches the docs exactly except for the aforementioned option.

**Comment by Ghoulboy78** [comment]
That's cos `system_info('world_min_spawning_light')` was added in carpet 1.4.95

**Comment by rv3r** [comment]
Oh I'm dumb. Do versions for snapshots also support the previous release?

**Comment by Ghoulboy78** [comment]
Probs not, though there is a 1.19.3 version of carpet 1.4.95
