### ISSUE TITLE
Scarpet x Placeholder API

### ISSUE THREAD

**Issue by LuciusofLegend** [gnembon/fabric-carpet#1656]
I think support for the Placeholder API would be a powerful feature to have in Scarpet.  It would open up a lot of integration with other mods that use the API, and that seems like a worthy goal to me.

If you'd like to see this feature added as well, it would be helpful to leave a comment.  Have a good day everyone :)

**Comment by gnembon** [comment]
scarpet interfacing with its home carpet mod was already a mistake. Any dependency on any other mod is not possible at this moment. Scarpet though can be extended with extensions - prime candidate for such an endeavor.

**Comment by LuciusofLegend** [comment]
Ah.  Yes, I didn't think of the fact that it would require a library to have that functionality.  Thanks for the response :)

**Comment by altrisi** [comment]
How'd you use them? Do you think it'd be a good idea for them to have their own function that you'd pass to `format`, or implicitly in existing format? I _think_ it'd be easier to make them their own function (and also easier to make sure you don't unwillingly use some), but I haven't really used it so I don't know what's the best idea.

**Comment by LuciusofLegend** [comment]
I think you're right, a separate function would be best.  
Actually, while I'm thinking about it, would it be possible to have a sort of "soft dependency" that would simply enable the function if the Placeholder API is loaded?
Sorry, I don't know much about mod development or dependencies or anything.

**Comment by altrisi** [comment]
It is possible yes, but rn carpet is trying to remove as many dependencies as possible so it's unlikely to be added here directly.
