### ISSUE TITLE
Crash on disconnect from server

### ISSUE THREAD

**Issue by silnarm** [gnembon/fabric-carpet#1660]
While testing a fix for falling fake players I experienced client side crashes on disconnecting.

Error is nullptr: `java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2168.method_30497()" because "source" is null`
Stack trace begins `at carpet.CarpetSettings$StructureBlockIgnoredValidator.validate(CarpetSettings.java:1004)` and would appear to be because 5 frames up `at carpet.api.settings.SettingsManager.detachServer(SettingsManager.java:289)` null is deliberately passed down as there is no 'source' to send.

All the other code in and around here is very tolerant of null sources, with null guards all over the place, but a change in bd5dfdbf to CarpetSettings.StructureBlockIgnoredValidator.validate() makes it crashy with a null source.

That commit was 18-01-2023 though, and three commits before current 1.19.3 branch, **and this does not happen on the released version** which I can't figure out, based on what I have looked at it should be happening on any recent build from 1.19.3 or master.

[crash-2023-02-19_10.48.22-client.txt](https://github.com/gnembon/fabric-carpet/files/10775561/crash-2023-02-19_10.48.22-client.txt)

**Comment by altrisi** [comment]
This has been fixed, in the latest 1.19.3 version which is built from `hotfix`, and wasn't an issue on the previous 1.19.3 version as the commit that introduced it wasn't in
