### ISSUE TITLE
Missing April Fools Versions 

### ISSUE THREAD

**Issue by gtbot2007** [gnembon/fabric-carpet#1662]
I was looking for carpet for 22w13oneBlockAtATime when I saw that no April Fool versions have been made

**Comment by gtbot2007** [comment]
Same for 23w13a_or_b

**Comment by altrisi** [comment]
It is correct, they haven't been made, and it's currently not planned to make them. I personally would accept ports if they were contributed (but I think they'd be a lot of work for very little usefulness).
