### ISSUE TITLE
[Feature Suggestion] stackableDecoratedPots setting

### ISSUE THREAD

**Issue by DorkOrc** [gnembon/fabric-carpet#1667]
If true: Decorated Pots with the same shard types can stack when thrown on the ground or when manipulated inside the inventories.

For example, if I have two `decorated_pot` items whos `BlockEntityTag.shards` lists are identical (e.g. both have `{BlockEntityTag:{shards:["minecraft:brick","minecraft:brick","minecraft:brick","minecraft:pottery_shard_archer"]}}`) then they should stack when on the ground or when dragged-and-dropped over one another in the inventory.

**Comment by altrisi** [comment]
Pots were changed in a recent snapshot to stack, so it shouldn't be needed on Carpet anymore.
