### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by DXTN64** [gnembon/fabric-carpet#167]
I'm using the latest carpet, Fabric v0.5.2.39 (0.7.8 build 186) , latest fabric API and MC 1.15.2, and the problem is that every function of the mod that shows info (all the ingame logging such as counter and even the status updates from /tick warp) are not working. I tried reinstalling MC from scratch but no luck. Any suggestions on how to solve that?

**Comment by gnembon** [comment]
works for me. What other mods you have installed?

**Comment by DXTN64** [comment]
at the moment only carpet and the fabric API

**Comment by DXTN64** [comment]
aaaand now all of a sudden just works... I have no clue what happened... Ty for the assistance Gnembon! Love your content and your work for this mod, tysvm.

Oh also, there seems to be a glitch with this+optifabric.... maybe are those hooks that were messing it?
