### ISSUE TITLE
Injection incompatibility with QSL causes its ServerLifeCycleEvents.READY to never fire

### ISSUE THREAD

**Issue by TheGlitch76** [gnembon/fabric-carpet#1682]
This causes other mods to find themselves in illegal states that were supposed to be setup on the server started / ready event, depending on which mixin applies first.

This probably happens because [carpet](https://github.com/gnembon/fabric-carpet/blob/f98c2409be42de6b0b02c2499244dfddd2e9a1e6/src/main/java/carpet/mixins/MinecraftServer_tickspeedMixin.java#L84) is injecting its own tick loop at the same target as [QSL](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19.4/library/core/lifecycle_events/src/main/java/org/quiltmc/qsl/lifecycle/mixin/MinecraftServerMixin.java#L46) does its ready event, making it a race for whoever gets priority on the `@Inject`.

If carpet's tick loop gets priority, the ready event will only ever fire once the server shuts down.

Originally reported at https://github.com/QuiltMC/quilt-standard-libraries/issues/289

**Comment by altrisi** [comment]
Given mixin priorities are weird to get, giving Carpet higher priority means setting it to a value higher than `1000` correct? Such as 1001, or would it be better to give it a higher one?

**Comment by altrisi** [comment]
1ad927da9dabe6e77b067fca6cac676695b67d20

**Comment by ifacodes** [comment]
This still seems to be causing issues with Quilt. Removing Carpet from my server was the only way to allow players to connect without packet errors.

**Comment by ifacodes** [comment]
Actually, forgot to update again, but this still happens, I just forgot to actually replace the files. this is still an issue unfortunately.
