### ISSUE TITLE
Tickwarp causes mobs to clip through terrain

### ISSUE THREAD

**Issue by JupiterSky11** [gnembon/fabric-carpet#1685]
Not sure what's going on here but the villager based farm I'm testing keeps having issues where villagers will go through objects such as farmland and trapdoors.

**Comment by replaceitem** [comment]
This is just a visual thing, since the client smoothes the movement of entities, and when tick warping, they will move very fast,  making it possible that they appear as if they move through blocks, when they actually moved around them.

**Comment by JupiterSky11** [comment]
@replaceitem nah, it's really clipping through blocks.  They can fall through the farmland block, and walk through the trapdoor to get to their workstation.

**Comment by replaceitem** [comment]
Hmmmm that's odd then. Any other mods?

**Comment by cylian914** [comment]
i have the same issue in a goldfarm, player and zombie piglin just clip through after a moment. Here a list of my mods 
![Screenshot_20230331_164324](https://user-images.githubusercontent.com/73445993/229152952-7a81caa7-a193-4481-b032-fac8416d9b43.png)


it doesn't seem to do it on a server with only carpet mods

**Comment by 0o-Mi** [comment]
I had the same problem, removing the meteor client solved it.

**Comment by Fiz-Victor** [comment]
> I had the same problem, removing the meteor client solved it.

This should be fixed in the latest meteor build
