### ISSUE TITLE
By default, many commands available in survival

### ISSUE THREAD

**Issue by dhouck** [gnembon/fabric-carpet#169]
I haven’t checked the full list, but in a default single-player survival world with cheats disabled, I was still able to use a bunch of carpet commands by default, including `/draw`, which is definitely something that should need to be explicitly enabled.

**Comment by gnembon** [comment]
this is working as intended. Commands are enabled because you don't need to use them if you don't want to. If you play with other people, carpet provides ability to disable all the commands.

**Comment by dhouck** [comment]
In that case, why are some commands like `/carpet` itself not available?

I also don’t think that’s a good default; there’s a reason you can disable cheats when creating a world. I think it would make more sense to by default follow that with Carpet commands, except for a few commands like `/distance` which are just utility and don’t break the survival game. But if your position is that you should be able to run these commands unless configured otherwise, why the difference?
