### ISSUE TITLE
Fake players joining the server but not teleporting to me

### ISSUE THREAD

**Issue by SunneyDevs** [gnembon/fabric-carpet#1693]
Whenever i spawn a player it joins but doesn't get teleported to me.

**Comment by JacktheDevel0per** [comment]
What mc and carpet version? What other mods do you have? What command arguments are you using?

**Comment by SunneyDevs** [comment]
the version is 1.19.4 and iim just putting in /player test spawn, the server has a few other mods but they haven't bothered it before

**Comment by SunneyDevs** [comment]
i resolved the issue, it was one of the mods that i overlooked while skimming them
