### ISSUE TITLE
[Bug]Iron Golems Farm Stops Working

### ISSUE THREAD

**Issue by KaiXuan233** [gnembon/fabric-carpet#171]
After installing fabric and carpet on my 20w10a server, my iron golem farm stopped generating iron golems. When I switch back to vanilla, it worked again.
Here is what the farm looks like:
![2020-03-10_13 21 12](https://user-images.githubusercontent.com/36479623/76282208-0da82900-62d2-11ea-90b0-a6a0c7b9f973.png)

**Comment by gnembon** [comment]
This feels odd. can you provide that world somehow?

**Comment by KaiXuan233** [comment]
Sure.
Directly download from my server in Beijing: http://l-ee.cn/files/world_2020-03-11-21-54.zip
Download from OneDrive: https://1drv.ms/u/s!AsMXIzzu4A5fkZRlkMVbRDNPT62KHQ?e=6g69lV

**Comment by gnembon** [comment]
I lowered water levels in bubble columns, which gave villagers some time to sleep. This design doesn't allow for villagers to sleep. There is still the fourth tower where villagers lost their bed connection (vanillla bug). but the other three towers were fine. I highly doubt is a carpet issue
![2020-03-16_00 11 30](https://user-images.githubusercontent.com/41132274/76720196-e2cb3400-671a-11ea-91ef-c22c9eebed44.png)
