### ISSUE TITLE
`lightEngineMaxBatchSize` is disabled since 23w17a

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1711]
Tracking issue.

The actual call to set it was removed in 07033af7dd95efffffbe3af53e0fe61561704fc9.

Wondering if it still has uses with the new engine, though I've never known what it's used for exactly so I can't really judge.

**Comment by gnembon** [comment]
old engine was limited to 5 updates. New one default is 1000. Seems like this rule is not really needed with the new light engine.

Light engine is really NEW meaning that enything that used it is irrelevant at this point.
