### ISSUE TITLE
Server crashed when carpet bot goes through portal

### ISSUE THREAD

**Issue by ProClifo** [gnembon/fabric-carpet#1712]
Players on my server experienced an issue where they tried to transport a carpet bot through a nether portal, and it ended up crashing the server. Here is the server log and crash log:

https://mclo.gs/1d3vNTc
https://mclo.gs/vxe72vK

**Comment by silnarm** [comment]
Confirmed.
Introduced in 8c09946b.. [PR #1665, Fixing #1190]
`DistanceManager.removePlayer()` is being called twice with the same player and sectionPos.
My bad, will hopefully be able to investigate further on the weekend.
