### ISSUE TITLE
Carpet isn't working

### ISSUE THREAD

**Issue by T4rt4rus** [gnembon/fabric-carpet#1713]
I installed carpet with fabric and somehow it doesn't work, it just crashes. I have many other mods installed: preventer mod, distant horizons, itemscroller, litematica minihud, modmenu, optifabric, starlight and tweakeroo. If i launch my game without carpet it works perfectly fine, but if i put carpet into the mods folder it crashes. 
<img width="536" alt="Screenshot 2023-04-28 200850" src="https://user-images.githubusercontent.com/110504804/235222015-74bd41df-efc3-42a7-a48b-d2d55ac2bb5e.png">

**Comment by James103** [comment]
Can you please post the logs from starting the game with Carpet and your other mods installed?

**Comment by T4rt4rus** [comment]
Exit code 1
Logs:
[2023-04-28-7.log.gz](https://github.com/gnembon/fabric-carpet/files/11357000/2023-04-28-7.log.gz)
[2023-04-28-6.log.gz](https://github.com/gnembon/fabric-carpet/files/11357001/2023-04-28-6.log.gz)
[latest.log](https://github.com/gnembon/fabric-carpet/files/11357002/latest.log)
Those are all of today. Thamks alot!!

**Comment by James103** [comment]
Try removing Optifine and Optifabric. There are alternative performance mods including Sodium, Lithium and Starlight which can be used to get better performance, along with other mods that re-implement some other cosmetic features present in Optifine.

**Comment by T4rt4rus** [comment]
Thanks, I'll try that
Does it matter if my shader is for optifine or can i use that for sodium aswell?

**Comment by T4rt4rus** [comment]
OK so i did it with sodium, it was a disaster but atleast it started, I'll just try to get it to work with optifine, now i know what the issue was. Thank you!

**Comment by AnAaronNight** [comment]
OptiFine and OptiFabric are notoriously incompatible with the Carpet mod, unfortunately. I'm investigating what might be the issue, but I haven't found the root cause nor a solution yet.

**Comment by T4rt4rus** [comment]
I now installed a Server with carpet on it and used OptiFabric (and all the other mods) on my clients side. This works perfectly fine.
