### ISSUE TITLE
[BUG] in 1.16 snapshots pink carpets dont work properly

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#173]
When placing pink carpets in crimson forests and light level 15, it says that hoglins, piglins and pigmen can spawn, even though only hoglins should be able to spawn.
It meant that making my hoglin farm took twice as long as I was confused as to why it said that despite only hoglins spawning. PLease fix.

**Comment by gnembon** [comment]
fixed, waiting for release
