### ISSUE TITLE
not compatible with gravity api (fabric 1.19.4)

### ISSUE THREAD

**Issue by RefriZaddo** [gnembon/fabric-carpet#1731]
fix it pls gravity api is one of my favorite mods

**Comment by altrisi** [comment]
It'd be helpful if you provided the crash report.

**Comment by RefriZaddo** [comment]
wait how do i get the full report
when i was copying the report it ended with "... 11 more"

**Comment by RefriZaddo** [comment]
i use prism launcher

**Comment by RefriZaddo** [comment]
so do i copy it incomplete into pastebin?

**Comment by RefriZaddo** [comment]
@altrisi?

**Comment by altrisi** [comment]
The log seems very helpful, thanks.

I'll try to take a look when I have some time, a bit busy lately. 

Why did you close the issue?

**Comment by RefriZaddo** [comment]
oh um sorry i was trying a take 2

**Comment by RefriZaddo** [comment]
im back

**Comment by RefriZaddo** [comment]
DUDE I REOPENED IT

**Comment by RefriZaddo** [comment]
@altrisi i reopened it u can go on now (if ur not busy ofc)

**Comment by RefriZaddo** [comment]
dead issue 💀

**Comment by altrisi** [comment]
It's not, just haven't had time for a proper fix. If you want a workaround, open your carpet as if it was a zip and modify the `carpet.mixins.json` file inside by removing the line with `DirectionMixin`. I believe that should make the two work together (though 2 carpet features won't work).

**Comment by RefriZaddo** [comment]
does mumbo jumbo use those that dont work by modifying the json?

**Comment by RefriZaddo** [comment]
nvm it crashed again (code -1 - [log](https://pastebin.com/JgF6wSuZ))

**Comment by RefriZaddo** [comment]
apparently removing directionmixin broke more stuff

**Comment by RefriZaddo** [comment]
welp nvm ima play the game without any waves
i was just kynda excuted when i saw knarfy's videos about this mod

**Comment by RefriZaddo** [comment]
whoops sorry wrong issue in wrong repo

**Comment by RefriZaddo** [comment]
reopened it after i found out

**Comment by RefriZaddo** [comment]
anyway i got that new report there, it crashed because i disbaled directionmixin

**Comment by RefriZaddo** [comment]
nvm i updated minecraft and the mods and now it works

**Comment by JoakimThorsen** [comment]
@RefriZaddo for future reference, it would probably be appreciated if you try to contain your messages into one post at a time. Try focusing on adding all the relevant information in your first message, then editing if needed, rather than chain-replying 4 times in a row each time.
