### ISSUE TITLE
Optifabric doesnt work with Carpet in 1.19.4

### ISSUE THREAD

**Issue by Beppe0515** [gnembon/fabric-carpet#1732]
Why doesn't optifabric work with carpet in 19.4. I have the same problem as spekii ( on another post). I have tried both of the latest carpet mods with the correct optifabric and optifine installed, but it still doesnt work.
Both of the latest carpet mods are not working with optifabric. What do I do?

**Comment by altrisi** [comment]
I'd be helpful if you provided a crash report.

**Comment by Beppe0515** [comment]
If you're looking for the exit code, it is 1. If its not, i think its in the link provided. https://docs.google.com/document/d/1D3ESujyhpwVuP_WN6fWXf_rdLfHHNj-QKiSP5zrJK9k/edit?usp=sharing

**Comment by Beppe0515** [comment]
But now optifabric doesnt work even without carpet. And i havent modify the mods or anything since posting the first post

**Comment by Beppe0515** [comment]
I can't. It only provides me a crash report for incompatible mods. If i add the carpet mod to optifabric then the games crashes giving me an exit code of 1 and no crash report

**Comment by fanaas** [comment]
> 如果您提供崩溃报告，我会很有帮助。

[错误报告-2023-6-3_21.38.23.zip](https://github.com/gnembon/fabric-carpet/files/11642883/-2023-6-3_21.38.23.zip)

**Comment by altrisi** [comment]
According to that crash, seems to be optifabric's own compatibility mixins failing unless I'm reading that wrong, not carpet vs optifine here, so an issue on their side.

Going to close this then. My suggestion would be to use optifine alternatives instead.
