### ISSUE TITLE
carpet fixes/iCommon conflict 1 19 2 not working

### ISSUE THREAD

**Issue by Baton1469** [gnembon/fabric-carpet#1736]
I have an issue with my server on fabric, i installed carpet-fixes-1.19-1.12.2,carpet-shadow-1.9.6-MC1.19++build+1,fabric-api-0.75.1+1.19.2,fabric-carpet-1.19.2-1.4.84+v221018,iCommon-Fabric-1.19.2,Cardboard-1.19.2. How i can to fix it? Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.https://pastebin.com/VV57j2gi

**Comment by altrisi** [comment]
This isn't a Carpet issue, report it to carpet fixes (also the line you highlight isn't the cause).
