### ISSUE TITLE
hello, have a problem with carpet 1.19.3 in server

### ISSUE THREAD

**Issue by LioliGMMHLCR9** [gnembon/fabric-carpet#1738]
I recently make a pebble host minecraft server
of the version 1.19.3, the problem is that the carpet doesn't func at the server, I try the /carpet command but the carpet menu on chat does not appear, just only said that /carpet does not exist, how can I fix this?

**Comment by James103** [comment]
Do you have the latest version of Fabric Loader for 1.19.3 installed on the server (along with the mod)?

**Comment by LioliGMMHLCR9** [comment]
yes

**Comment by altrisi** [comment]
Resolved in Discord, comment here and I'll reopen the issue (or open a new one).
