### ISSUE TITLE
tnt minecart doesn't properly destroy blocks with optimized tnt

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#174]
![2020-03-11_01 15 12](https://user-images.githubusercontent.com/41132274/76381995-f7cc4f80-6335-11ea-9f1d-014a418f6e08.png)

**Comment by susanshopper** [comment]
If the TNT minecart was set off by an activator rail, it does not destroy rails and their support blocks, yet it should destroy other blocks.
