### ISSUE TITLE
carpet mod not working in 1.20.1

### ISSUE THREAD

**Issue by rexHK417** [gnembon/fabric-carpet#1742]
need help 
I install the latest version of carpet mod from modrinth

**Comment by mmodrow** [comment]
It's currently being discussed on the discord server.

If you're feeling brave, just open the .jar up with an archive tool like 7zip and edit the fabric.mod.json.

Look for the line `"minecraft": "1.20",` and replace it with ``"minecraft": "1.20.*",``. Then it starts and there are no obvious errors. Obviously this is a hacky way to get things working, but it might help for the time being.

**Comment by rexHK417** [comment]
oh thanks

**Comment by rexHK417** [comment]
So should I close it?

**Comment by mmodrow** [comment]
I'm no contributor, but I'd rather keep it open to have a proper out-of-the-box fix, that's tested etc.

**Comment by mmodrow** [comment]
Also I just noticed, you're talking about carpet mod, which should work out of the box. I was thinking of carpet-extra.

**Comment by rexHK417** [comment]
oh, but carpet mod still not working on my server for some reason

**Comment by mmodrow** [comment]
Then let's hope gnembon or one of the other contributors notices this. 😅

**Comment by altrisi** [comment]
Could you upload the crash report?

**Comment by rexHK417** [comment]
nvm it been fixed by some1 help
ig i messed with config
