### ISSUE TITLE
Reintroduce UpdateSuppressionFix For CCE(ClassCastException) Suppression

### ISSUE THREAD

**Issue by Arthur-Montgomery** [gnembon/fabric-carpet#1744]
Could you reintroduce rule UpdateSuppressionFix in carpet 1.19&1.20 for CCE suppression? (you can check lgna778's latest video for details) Since this kind of update suppression can work from 1.11 to the current latest version of 1.20, I think reintroduction is necessary. 
Also, can you change the earlier versions of carpet (like 1.17.1) so that UpdateSuppressionFix can prevent breaking when using CCE suppression?

**Comment by altrisi** [comment]
Going to close this as I think it's not application in current versions Carpet targets, though I don't know too much about the new update suppression so comment or open a new issue if I'm wrong.
