### ISSUE TITLE
Players spawned with /player are now labeled as 'Anonymous Player' in server list.

### ISSUE THREAD

**Issue by SkippyTheLost** [gnembon/fabric-carpet#1749]
In the most recent editions of carpet, when players spawn using /player <name> spawn and /player <name> shadow, they are consistently shown as 'Anonymous Player' in the server list.

![player spawned from /player command](https://github.com/gnembon/fabric-carpet/assets/31645256/393c3bea-738a-471c-9212-0b3015901db9)

Before, these players would be listed with their respective usernames. I have been unable to locate any documentation regarding this alteration or the reason behind it.

**Comment by altrisi** [comment]
It's likely related to the new recent `Allow Server Listings` option, it's likely fake players not being real ones default to disabled, or it was set to that when whatever method that now takes it was updated.

I don't think it's bad though, imo it makes sense for fake players to not show up there, especially when people spawn bots that aren't actually players on the server and it could cause confusion.
