### ISSUE TITLE
Server Crash while generating chunks- 1.19.2

### ISSUE THREAD

**Issue by arazadaz** [gnembon/fabric-carpet#1752]
Here's the crash report.

https://pastebin.com/vPCZkUCS

The main line of interest in the crash report is probably : 
`at net.minecraft.server.MinecraftServer.handler$cci000$carpet$modifiedRunLoop(MinecraftServer.java:8394)`

It should be noted that I have c2me installed as well as starlight. I also have 300+ other mods installed as well though.

**Comment by silnarm** [comment]
Please see https://github.com/gnembon/fabric-carpet/issues/1747.

In a nutshell: it was one of the other 300+ mods you have.

By the nature of the error (watchdog) we can't really tell you much about it, something was deadlocked or in an infinite loop.

**Comment by arazadaz** [comment]
I'll look into it more. Thanks. I'll close this for now.

**Comment by arazadaz** [comment]
Seems my actual server itself, not the MC server, but the machine running it was running out of memory which was causing it. Nice.
