### ISSUE TITLE
ai_trackers vilagers iron golem spawning box is offset

### ISSUE THREAD

**Issue by 0o-Mi** [gnembon/fabric-carpet#1760]
Its a 16 by 16 cube instead of 17 by 17

(quad farm crossection, 11 villager cell distance, green - current box, glass - actual box)
![2023-07-11 16_29_47-Kociarnia on local game](https://github.com/gnembon/fabric-carpet/assets/104528636/c3c2150b-ec5d-448d-a7d2-a640dfb39fff)

**Comment by silnarm** [comment]
Yes, it is one block short in +x and +z.

The box being added is from [-8,-6,-8] to [8,7,8] (relative to blockpos of villager), which on the positive (X & Z) axes only goes to the the block pos coordinate of the last spawnable block, but not 1 more to encompass it.

Interesting that the +Y offset is correct.
