### ISSUE TITLE
"carpet mod" has a serious server bug in 1.20.1 where players can summon dummies from whitelisted players.

### ISSUE THREAD

**Issue by ElainaTGBS** [gnembon/fabric-carpet#1765]
Hey, "carpet" has a serious server bug in 1.20.1 where players can summon dummies from whitelisted players.

**Comment by silnarm** [comment]
Not actually a bug. Carpet bots weren't really intended for survival servers in the first place, and there are several issues with their use there, this being one of them.

I have a script that wraps the player command (in the same manner as `playerme`, but specifically for bots) and fixes some of those issues, including this one. It needs a little love yet but I will dust it off and get it released somewhere soon.

**Comment by altrisi** [comment]
Only op (>=2) players should be able to summon whitelisted players.

**Comment by silnarm** [comment]
oh cool, didn't know those checks were there...
Just tested out now and can confirm working as expected.
