### ISSUE TITLE
1.20.1  Crash error code 1

### ISSUE THREAD

**Issue by Hellster90** [gnembon/fabric-carpet#1768]
When I try to run minecraft with the latest Carpet Mod it just crashes with exit code 1.
Other mods I use together seem to be fine (image attached as well as an image of the crash).
I know there were issues with Carpet and Optifabric in the past, not sure if it's possibly the same issue.
![Screenshot_362](https://github.com/gnembon/fabric-carpet/assets/61074300/c45ab71e-7888-4202-ace8-b1456c4f4266)
![Screenshot_361](https://github.com/gnembon/fabric-carpet/assets/61074300/8aada20e-c0b3-4f4e-a9fd-c7d1fc85932c)

**Comment by Fiz-Victor** [comment]
uninstall optifine.

**Comment by Hellster90** [comment]
> uninstall optifine. it has many incompatibilities between fabric mods

Optifine itself is not installed, it's purely there for Optifabric, if that makes any difference.

**Comment by altrisi** [comment]
Caused by optifine/bric. There's a build somewhere on their (optifabric's) PRs/issue tracker that makes them work together if you find it (though I'd still recommend using alternatives).
