### ISSUE TITLE
Scarpet 0/0 equality

### ISSUE THREAD

**Issue by rv3r** [gnembon/fabric-carpet#1776]
```
0/0 -> NaN
0/0 == 1 -> true
0/0 == -1 -> true
0/0 == 2 -> true
...
3/0 -> INFINITY
0/0 == 3/0 -> true
```
Bug or WAI?

**Comment by silnarm** [comment]
NaN equality has an issue (#1576), and PR to fix (#1577).

The Infinity one is actually the same, 0/0 => NaN == anything.

**Comment by altrisi** [comment]
Yes, this is a duplicate of #1576.

**Comment by ch-yx** [comment]
walk around:
you can create an function `is_nan(x)` by yourself.
if type(x) is number and str(x) is NaN
