### ISSUE TITLE
/player problem

### ISSUE THREAD

**Issue by Lele090909** [gnembon/fabric-carpet#1792]
I wnted to AFK at my farm with the /player attack but when I wrote /player there wasn't the command.

**Comment by Fiz-Victor** [comment]
If you are playing on a server, make sure server has installed carpet

**Comment by Arian04** [comment]
use `/carpet commandPlayer` to make sure the command is enabled (or if it's set to `ops`, make sure you're OP'd)

**Comment by altrisi** [comment]
The solutions above are correct, you likely either not have enough permissions to run it (you can change the permissions with the `commandPlayer` rule), or carpet isn't on the server.
