### ISSUE TITLE
Tickrate Resets on Server Restart

### ISSUE THREAD

**Issue by SirHodgeheg** [gnembon/fabric-carpet#1794]
Hi,
When setting a custom tick rate on my server using /tick rate X, the game tick rate value resets after restarting the server or stopping and starting it again. 
Is there a way to permanently change the tick rate?

**Comment by altrisi** [comment]
You could make a tiny scarpet script to run the tick rate command when the server starts, using `run('tick rate 12345')` (in an sc file).

**Comment by SirHodgeheg** [comment]
Hi,
Thanks you very much for the very quick response! However, I am very new to Mods and so that would be very difficult for me to figure out. Could you please explain how I could do this?

**Comment by replaceitem** [comment]
In the world folder of your server, create a folder called `scripts`, and create a new file there called `tickrate.sc` for example (needs to end in `.sc`). In that file, paste this line with the tick rate you want:

```js
run('tick rate 10')
```
This should then execute when the server starts.

**Comment by SirHodgeheg** [comment]
For some reason, this doesn't seem to work. Do I need to add Scarpet somewhere?

**Comment by replaceitem** [comment]
* Is the script located under `/world/scripts/tickrate.sc`?
* Make sure `/carpet setDefault scriptsAutoload true` is set
* If you type `/script load ` in chat, does the script name autocomplete?

**Comment by SirHodgeheg** [comment]
Thanks! It now works!

**Comment by altrisi** [comment]
Going to close this then.

**Comment by altrisi** [comment]
Related to #1818.
