### ISSUE TITLE
Wall blocks not preventing slimes/magma cubes from spawning when lagFreeSpawning is enabled

### ISSUE THREAD

**Issue by righteous-coder** [gnembon/fabric-carpet#180]
## Expected Behavior
When the game tries to spawn a slime or a magma cube on a block which has a wall block next to it, it fails because the wall block's collision box is sticking out. And the lagFreeSpawning option should not change this behavior.

## Current Behavior
The lagFreeSpawning option makes slimes and magma cubes able to spawn on such blocks.

## Steps to Reproduce
1. Create a flat world with non-spawnable blocks on the surface.
1. Enable the lagFreeSpawning option.
1. In a slime chunk place fully opaque blocks and wall blocks like in the screenshot below.
1. Slimes spawn.

![image](https://user-images.githubusercontent.com/55341250/77097619-67d48700-6a54-11ea-8242-3dcc1ffb26df.png)

## Environment
- Carpet mod: 1.3.14
- Minecraft: 1.15.2
- Fabric API: 0.4.24+build.279-1.15
- Fabric loader: 0.7.8+build.184

**Comment by gnembon** [comment]
yeah, that's obvious. I will evaluate if extra checks for blocks with extended collisions is worth the optimization - if yes - will adjust lagFreeSpawning, and if not - will remove it.

**Comment by gnembon** [comment]
at least the collosion part
