### ISSUE TITLE
New strongholds created using the `\plop` command cannot be found using ender pearls

### ISSUE THREAD

**Issue by JohnHadish** [gnembon/fabric-carpet#1807]
It would be convenient if strongholds created using the `\plop` command could be found using ender pearls. 

I have a server with some friends which we recently did a "soft reset" where we kept our current world and just reset spawn to 1 million blocks away from 0,0,0 to get a fresh start. I then added a new stronghold using `\plop` which is near our new spawn location. I want my friends to be able to find it naturally using ender pearls, but currently, ender pearls do not recognize the new stronghold. 

This is similar to, but slightly different to issue #1806. My current surface understanding of the subject (by looking at bug reports, not the actual code) is that ender pearls use the same code as the  `\locate` command when thrown: https://bugs.mojang.com/browse/MC-253394.

**Comment by altrisi** [comment]
This makes sense, for the eyes to find the plopped ones they'd need to load enormous amounts of chunks and then check everywhere for strongholds, which would be quite bad for performance.

There may be some mod that lets you make eyes point to specific locations, but I don't think Carpet is going to provide it (directly).

**Comment by gnembon** [comment]
Yeah, can't support it. Structures plopped via plop as well as vanilla `/place` are purely decorational.
