### ISSUE TITLE
[@: Can only manipulate existing players] keeps forming

### ISSUE THREAD

**Issue by Anson-MC** [gnembon/fabric-carpet#1814]
[@: Can only manipulate existing players]
I have added a player, and then I kill it, and then It log out and the console is like this
[@: Can only manipulate existing players]
[@: Can only manipulate existing players]
[@: Can only manipulate existing players]
[@: Can only manipulate existing players][@: Can only manipulate existing players]

**Comment by Anson-MC** [comment]
And if I add it in, it become good

**Comment by Anson-MC** [comment]
I mean the player

**Comment by altrisi** [comment]
Closing this as it shouldn't be an issue with Carpet and there's been no response for a few days.
