### ISSUE TITLE
[BUG] or [SUGGESTION] (IDK) Movable Cauldrons

### ISSUE THREAD

**Issue by DemonSeedxp** [gnembon/fabric-carpet#1816]
Minecraft: 1.19.2
Fabric: 0.14.22
Carpet: 1.4.84+v221018

I've discovered that the vanilla behavior of cauldrons being movable with/without something in its inventory gets broken by carpets game rule for `movableBlockEntities` being set to false.  

When the cauldron is empty it moves as it should, but with water inside it becomes an immovable object.

Which is confusing to me since having that rule as false is essentially Java's default configuration, except in Java they do move with fluids inside. 

This very much feels like a bug to me, as I thought carpets whole thing was "NOT" to alter the base game unless expressly asked to do so.
But honestly I can't be sure if that's intentional or not, thus explaining my less than confident thread title. (Which I'll gladly edit once confirmed either way)

All I know for sure is this has massively broken a giant project I've been working on because without cauldrons I have no other options for activating a circuit without an actively powered block, Which I have not allowed room for, so now I'm basically SOL.

So if this is a Bug, please fix it asap, and if it's intended behavior, please consider adding a toggle to restore vanilla behavior!

My back is against the wall here, the mod is just to damn useful to get rid of, but it's breaking my build, but it's to useful to... 

yeah, no good option to choose from as far as I can see! 

Please Help!

**Comment by Crec0** [comment]
I cannot reproduce this with the game and carpet version specified. It could be a mod conflict from some other mod.

**Comment by DemonSeedxp** [comment]
Well that's unfortunate. guess I've got some troubleshooting to do then. I do have a few other redstone focused mods installed, so guess that'd be the best place to start.  

Quick question,
     Is it possible to duplicate my entire instance where the mods are installed to use for testing so I don't have any problems with things getting stripped from my world, and or the dreaded datapack failure to load error due to mods getting pulled unexpectedly, or is making a world backup my only route forward?

**Comment by altrisi** [comment]
Cannot reproduce here either, it must be a bug with something else.
