### ISSUE TITLE
Villagers In Minecarts crossing End Gateway will dismount their carts 

### ISSUE THREAD

**Issue by rmkwulf1993** [gnembon/fabric-carpet#182]
Expected behavior is villager continues to loop back and forth without dismounting the cart can see it in the pag5zonda farm.

**Comment by gnembon** [comment]
does this happen with vanilla as well? Can you provide a screenshot of the setup?

**Comment by James103** [comment]
I just checked in vanilla, when a villager riding a minecart falls on top of or runs into the side of an end gateway portal, he doesn't dismount when passing through (1.15.2 Vanilla).

**Comment by DeadlyMC** [comment]
![image](https://user-images.githubusercontent.com/43000902/80096973-1c982180-8588-11ea-91fb-eb84a874e2a1.png)
Just tried out this setup with fabri-carpet - the villager doesn't dismount

**Comment by gnembon** [comment]
don't think how carpet would be affecting villagers and minecarts. It will be good to get some info about your setup and confirm its not a setup issue.

**Comment by gnembon** [comment]
probably not an issue.
