### ISSUE TITLE
Rule for toggling villager experimental feature

### ISSUE THREAD

**Issue by Adogs1** [gnembon/fabric-carpet#1820]
Suggest adjusting the experimental data package for villagers added in 1.20.2, where weapon merchants and villagers can use iron blocks to exchange for emeralds, to add it to the rules of the carpet because it is really convenient！ #1811

**Comment by altrisi** [comment]
The issue with a rule is that it wouldn't be especially useful given trades in existing villagers wouldn't change live when toggling the rule. And it's extra unnecessary complexity for toggling what already a toggle.

Given it's a toggle anyway, why not just use the existing one?

**Comment by ch-yx** [comment]
我看了你这个要求，最近写了一个很小的地毯插件。。。。还不太完善。
![图片](https://github.com/gnembon/fabric-carpet/assets/45825511/c87602fb-9f12-43a5-a566-4150bd39beca)
![图片](https://github.com/gnembon/fabric-carpet/assets/45825511/b5b9af61-2081-4dc7-aae0-e32df6f06810)
你这样就可以自己写成想啥样就啥样了。如何？

**Comment by Adogs1** [comment]
> 我看了你这个要求，最近写了一个很小的地毯插件。。。。还不太完善。 ![图片](https://user-images.githubusercontent.com/45825511/274832024-c87602fb-9f12-43a5-a566-4150bd39beca.png) ![图片](https://user-images.githubusercontent.com/45825511/274832032-b5b9af61-2081-4dc7-aae0-e32df6f06810.png) 你这样就可以自己写成想啥样就啥样了。如何？

**Comment by Adogs1** [comment]
> 我看了你这个要求，最近写了一个很小的地毯插件。。。。还不太完善。 ![图片](https://user-images.githubusercontent.com/45825511/274832024-c87602fb-9f12-43a5-a566-4150bd39beca.png) ![图片](https://user-images.githubusercontent.com/45825511/274832032-b5b9af61-2081-4dc7-aae0-e32df6f06810.png) 你这样就可以自己写成想啥样就啥样了。如何？

虽然这一点也不香草，但还只能先用着先吧，谢谢（能报告一下下载链接和使用教程吗?）

**Comment by ch-yx** [comment]
> > 我看了你这个要求，最近写了一个很小的地毯插件。。。。还不太完善。 ![图片](https://user-images.githubusercontent.com/45825511/274832024-c87602fb-9f12-43a5-a566-4150bd39beca.png) ![图片](https://user-images.githubusercontent.com/45825511/274832032-b5b9af61-2081-4dc7-aae0-e32df6f06810.png) 你这样就可以自己写成想啥样就啥样了。如何？
> 
> 虽然这一点也不香草，但还只能先用着先吧，谢谢（能报告一下下载链接和使用教程吗?）

i m writing some code to make it able to create a map item......now it cannot create map item.

i will tell you when i finished it.

**Comment by Adogs1** [comment]
Thanks

**Comment by Adogs1** [comment]
> 等我讲完了再告诉你。
Thanks

**Comment by ch-yx** [comment]
i recorded a video to render it.

https://www.bilibili.com/video/BV1GB4y1f7RS

**Comment by ch-yx** [comment]
> > 等我讲完了再告诉你。
> > Thanks

do you have any more suggestions? 你看完视频后是否还有其他需要我做的事情？
