### ISSUE TITLE
Minecraft crashes when attempting to open with carpet mod

### ISSUE THREAD

**Issue by StanTheManGaming** [gnembon/fabric-carpet#1823]
Does it require another mod alongside it to open? Or is it just not compatible with Optifine or Optifabric - the only other mods in the folder?

**Comment by Fiz-Victor** [comment]
Optifine is not recommended and known to cause problems to carpet

**Comment by altrisi** [comment]
Indeed, there's a problem in optifabric. They have a patch in a PR in their repo but they haven't merged or released it yet.
