### ISSUE TITLE
/player指令不应该能操控真人玩家的行动

### ISSUE THREAD

**Issue by CharNewbie01w** [gnembon/fabric-carpet#1824]
/player指令能操控真人玩家进行某些操作，其中包括丢出全部物品(/player @a dropStack all)，不清楚是否还有其他可能的行为，但无论如何，这都非常的不安全，建议./player指令识别玩家为假人还是真人，真人的话除非有操作权限，否则不应该执行操作

**Comment by altrisi** [comment]
Could the issue be in English? Thanks.

**Comment by James103** [comment]
Google Translate output for OP's comment:
> The `/player` command can control real players to perform certain operations, including dropping all items (`/player @a dropStack all`). It is unclear whether there are other possible behaviors, but in any case, this is very unsafe, so it is recommended. The /player command identifies whether the player is a dummy or a real person. If the player is a real person, the operation should not be performed unless he has the permission to operate.

**Comment by altrisi** [comment]
You can always up the `/player` required permissions, and non op players shouldn't be able to control other real players. `@a` also isn't a valid player target at the moment.

Being able to set actions to real players is needed if you want to then shadow yourself while having actions.
