### ISSUE TITLE
/counter command seems to stop working if hopper gets certain type of items 

### ISSUE THREAD

**Issue by Ka1nnn** [gnembon/fabric-carpet#1825]
So i tried the discord Player help forum made a post there, 0 response ig il try my luck here.

Hopper counters command **/counter** seems to stop working if the hoppers get a certain type of item into them, idk why but i have made a video of the issue

https://streamable.com/entvy1

i could not upload the video directly here it was too big in size, as you can see inputting bottles in the hopper will cause the /counter command to no longer work same with mob eggs, and prob other items too. i couldn't test every single one. 

For this test i have removed all other mods with only carpet in my mods folder even fabric api and my game version is 1.20.2 if any other information is needed i will glady provide :)

**Comment by altrisi** [comment]
Sorry, completely forgot to reply on Discord.

Could you run with `superSecretSetting` enabled and post the stacktrace in the log? It's likely to have more info (I can't try it myself right now so it could speed up finding a fix once I can)

**Comment by Ka1nnn** [comment]
https://mclo.gs/GiVUtE5

this is the log i hope i did it right i just enabled the setting and did what i previously did in the video and it showed that error

**Comment by altrisi** [comment]
I see, took me a bit to find, looks like Mojang changed some code somewhere that doesn't make carpet fail to build and we didn't notice, should be an easy fix.
Thanks!
