### ISSUE TITLE
Scarpet run() does not work

### ISSUE THREAD

**Issue by iTutFadU** [gnembon/fabric-carpet#1857]
`run()` returns empty result `[]` (2nd element in the returned list) for any command.

**Comment by ch-yx** [comment]
is that for compatibility with existing code?

**Comment by altrisi** [comment]
Works for me on 1.4.124, does it happen with only Carpet? (assuming you have more mods, you haven't provided much information)

**Comment by altrisi** [comment]
Going to close this, tho feel free to comment or open a new issue if it's still a problem.
