### ISSUE TITLE
[Suggestion] `chatLengthLimit` rule

### ISSUE THREAD

**Issue by unin-able** [gnembon/fabric-carpet#1858]
Add a `chatLengthLimit` or `maxChatLength` (whichever’s better) rule that can change the max limit of 256 characters in chat to any value greater than or equal to 256. (256 minimum is to prevent vanilla players from not realizing there is a character limit in chat) 

If a player has the mod installed, it should also change client side for them as well in the chat box. 

This would allow for very long `/give` commands with a bunch of NBT to be pasted in chat.

**Comment by CommandLeo** [comment]
This feature is present in [EssentialAddons](https://github.com/Super-Santa/EssentialAddons#maxchatlength)

**Comment by unin-able** [comment]
Ooh my bad, I saw that earlier and thought the mod was only client sided cause of the "Essential" naming
