### ISSUE TITLE
1.15.2 server crash

### ISSUE THREAD

**Issue by PanoptesDreams** [gnembon/fabric-carpet#186]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 26/03/20 6:12 PM
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_3321.method_14547(class_3321.java:63)
	at net.minecraft.class_3176.method_13951(class_3176.java:516)
	at net.minecraft.class_3176.method_3823(class_3176.java:179)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:628)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5241455224 bytes (4998 MB) / 5859966976 bytes (5588 MB) up to 5859966976 bytes (5588 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms4G -Xmx6G
	Fabric Mods: 
		adamantine: Adamantine 1.1.1
		adorn: Adorn 1.8.0+1.15.2
		alwaysdroploot: Always Drop Loot 3.6.0+mc1.14.4
		aquarius: Aquarius 1.4.0+1.15
		artifice: Artifice 0.6.0+1.15.2
		artis: Artis 1.2.0+1.15.2
		autoconfig1u: Auto Config v1 Updated 1.2.4
		bamboo-spikes-justfatlard: Bamboo Spikes 0.1.0
		better_wither_skeletons: Better Wither Skeletons 1.0.0
		betterthanmending: BetterThanMending 1.1.1
		bigbuckets: Big Buckets 1.1.0
		biow0rks: biow0rk5 0.4.0
		blue_endless_jankson: jankson +
		bowinfinityfix: Bow Infinity Fix rv8
		brokenxp: Broken XP 1.0.4
		bunch-o-trinkets: Bunch O' Trinkets 1.0.0
		cardinal-components-base: Cardinal Components API 2.3.0
		cardinal-components-block: Cardinal Components API 2.3.0
		cardinal-components-entity: Cardinal Components API 2.3.0
		cardinal-components-level: Cardinal Components API 2.3.0
		cardinal-components-world: Cardinal Components API 2.3.0
		carpet: Carpet Mod in Fabric 1.3.15
		chunkactivator: Chunk Activator 1.2.0+mc1.14.4
		clipboards: Clipboards 1.0.0+1.15.2
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 2.11.2
		coloredfire: Colored Flames 1.1.9r1+1.15.2
		compressedblocks: Compressed Blocks 0.3
		cotton: Cotton 1.0.2
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.6
		cotton-commons: Cotton Commons 1.0.0-rc.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.1
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.1
		craftingpad: Crafting Pad 1.0.4
		eggtab: Egg Tab 1.1.2+1.15-1.16
		enderbox: Ender Box 1.0.1
		endershulkers: Ender Shulkers 1.0.0+1.15.2
		endfestation: Endfestation 1.0.0
		expandedstorage: ExpandedStorage 3.8.34+1.15.2
		expandedstorageapi: ExpandedStorageAPI 0.0.4+1.15.2
		extradoors: ExtraDoors 1.6.0-1.15
		fabric: Fabric API 0.5.1+build.294-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825de7
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825de7
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-furnaces: Fabric Furnaces 1.2.0
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+d249f7b6d1
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabricessentials: fabricessentials 1.1.7
		fabricloader: Fabric Loader 0.7.8+build.189
		fairenchanting: FairEnchanting 1.1.2
		fatxporbs: Fat Experience Orbs 0.0.6
		fermion-modkeys: Fermion Modifier Keys 1.5.148
		firedchainmail: Fired Chainmail 1.0.0
		flonters: Flonters 1.0.2+1.15.1
		floradoubling: Flora Doubling 1.0.0
		gamemodeoverhaul: GamemodeOverhaul 1.15.2-1.0.1.6
		glassential: Glassential 1.15.1-1.1.3
		glowingbeds: Glowing Beds 1.0.2
		godown: Go Down 0.2.0+1.15
		goml: Get Off My Lawn 1.0.0-beta
		harvest: Harvest 1.0.4
		illuminations: Illuminations 0.4.0
		immersive_portals: Immersive Portals 0.20
		ironbarrels2: Iron Barrels 2 2.3.0
		jankson: Jankson 2.0.1+j1.2.0
		jargm: Just Another Redstone Gate Mod 1.1.1
		kayak: kayak 0.1.1.22
		kirin: Kirin UI 1.5.2-1.15.2
		kyrptconfig: Kytpt Config 1.0.0
		lakeside: Lakeside 1.0.0+1.15.2
		leaf-decay: Leaf Decay ${version}
		libblockattributes: LibBlockAttributes 0.6.6
		libblockattributes_core: LibBlockAttributes (Core) 0.6.6
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.6.6
		libblockattributes_items: LibBlockAttributes (Items) 0.6.6
		libcd: LibCapableData 2.3.0+1.15.2
		libgamerule: LibGamerule ${version}
		libgui: LibGui 1.5.1
		llamasteeds: Llama Steeds 2020.1.10
		mambience: MAmbience 1.0.0
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		me_zeroeightsix_fiber: fiber 0.8.0-SNAPSHOT
		minecraft: Minecraft 1.15.2
		ml3api: ML3API 1.3.3
		mo_glass: Mo Glass 1.2-MC1.15
		moenchantments: Mo'Enchantments 1.9.6
		mooblooms: Mooblooms 1.1.1
		moretotems: More Totems 1.0.0
		nbtcrafting: NBT Crafting 1.2.15+1.15.1
		netherhigher: netherHigher 1.0.2+build.3
		ninjaphenix-container-lib: NinjaPhenix's Container Library 0.1.5+1.15.2
		org_aeonbits_owner_owner: owner 1.0.8
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
		oysters: Oysters fabric-0.1.4-1.15.1
		oysterscooking: Oysters Cooking 0.2.3b
		passable-leaves: Passable Leaves 0.3.0
		permafrost: Permafrost 1.3.1+1.15.1
		playerabilitylib: Pal 1.0.0
		programmerartinjector: Programmer Art Injector 1.1.0
		quickshulker: Quick Shulker 1.1.3
		reach-entity-attributes: Reach Entity Attribute 1.0.0
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		shulkercharm: Shulker Charm 1.1.2+1.15.2
		simplystrawberrys: Simply Strawberries 1.0
		sit: Sit 1.15-4
		sleepvote: SleepVote ${version}
		smith_and_fletch: Smith And Fletch 1.0.0
		sneakthroughberries: Sneak Through Berries 1.0.1
		sonyikaarftl: Advanced Rotten Flesh to Leather 1.4.4
		soulshards: Soul Shards Respawn 1.2.0
		spiceoffabric: Spice of Fabric 1.2.3+1.15.2
		spinnery: Spinnery 2.0.0+fabric-20w06a
		statement: Statement 2.1.2+20w11a
		staticdata: Static Data 1.1.2
		statskeeper: Stats Keeper 1.1.4
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		strongandfairanvils: Strong and Fair Anvils 0.3.0+1.15
		terraform: Terraform 1.4.3+build.29
		terrestria: Terrestria 1.2.1+build.29
		the_bumblezone: The Bumblezone - Fabric 1.0.1-1.15.2
		the_loved_ones: The Loved Ones 1.0.0-1.15.2
		tinyconfig: TinyConfig 1.1.2
		tinyfuel: Tiny Fuel 0.2.1
		toughglass: Tough Glass 1.1.0
		towelette: Towelette 3.1.4+20w11a
		trapexpansion: Trap Expansion 1.3.1
		traverse: Traverse 2.1.11+build.23
		trinkets: Trinkets 2.4.1
		tweed: Tweed API 2.2.8
		universalcomponents: Universal Components 0.3.2+1.15.2
		vanilla-hammers: Vanilla Hammers 1.7.0
		vanilla-toolsets: Vanilla Toolsets 1.2.2
		varlight: VarLight 1.3
		villagerhats: Villager Hats fabric-1.15.0-1.0.0
		walljump: Wall-Jump! 1.3.3+1.15
		wildworld: Wild World 1.2.0+1.15
		wrenchable: Wrenchable 0.2.2+1.15.2
		wrenchanything: Wrench Anything 1.1.3+1.15.2
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by gnembon** [comment]
remove trinkets

**Comment by PanoptesDreams** [comment]
Yes that is the cause but is it your side or trinkets that needs to be fixed?
Your mod is almost essential but we also rely on trinkets for several other mods.
