### ISSUE TITLE
fillLimit is a thing in QuickCarpet but not in main Carpet

### ISSUE THREAD

**Issue by N1zle** [gnembon/fabric-carpet#1865]
I don't know if this is intended, if fillLimit was deprecated in more recent versions of Carpet, or if it only makes sense in QuickCarpet, but I am recently going into the rabbit hole of carpet addons/variations, and found this discrepancy out.

**Comment by altrisi** [comment]
`fillLimit` is a vanilla gamerule now (`commandModificationBlockLimit`), therefore it was deprecated and later removed in Carpet.
