### ISSUE TITLE
whatever happend to tick warp (and entities and health) ?

### ISSUE THREAD

**Issue by PlasmaHH** [gnembon/fabric-carpet#1867]
I probably have missed something but since the documentation  ( https://github.com/gnembon/fabric-carpet/wiki/Commands#usage-tick-warp-ticks-cmd ) still mentions them:

What happend to the tick warp, entities and health commands?

I haven't upgraded my setup setup for a while, now went to 1.20.4 along with fabric-carpet-1.20.3-1.4.128+v231205 and now I don't have the tick warp command anymore ( lan world with "allow cheats" ) but only some basic tick commands

**Comment by altrisi** [comment]
The `/tick` command is now in vanilla! Some things were renamed (`warp` to `sprint`), and the `health` and `entities` subcommands now are only available in `/profile` from Carpet (they were in both for a while).

Gnembon posted a gist with all the details of the change: https://gist.github.com/gnembon/256538acb59eb4eeea8205aaa0905599

Guess we need to update the wiki! Probably not fully remove it, so it's there for people in older versions.
