### ISSUE TITLE
Spawning more than 20 bots crashes the game. (FIXED, by turning off all drops and spawn gamerules) 

### ISSUE THREAD

**Issue by MrKorwaldski** [gnembon/fabric-carpet#1892]

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by MrKorwaldski** [comment]
Exit code -1073740791
![Screenshot 2024-04-08 010815](https://github.com/gnembon/fabric-carpet/assets/166341012/813cc380-1c0a-4071-918e-95a1b0938807)

**Comment by MrKorwaldski** [comment]
My drivers are up to date and im not using any Screen recording software.

**Comment by James103** [comment]
Can you please try reproducing this, then attach the `latest.log` once the game crashes?

**Comment by MrKorwaldski** [comment]
[crash-2024-04-08_01.20.06-server.txt](https://github.com/gnembon/fabric-carpet/files/14899328/crash-2024-04-08_01.20.06-server.txt)

**Comment by MrKorwaldski** [comment]
[latest.log](https://github.com/gnembon/fabric-carpet/files/14899339/latest.log)

**Comment by MrKorwaldski** [comment]
FIXED IT, set all drops and spawn gamerules to false.
