### ISSUE TITLE
tick warp may not cause dimenstions to be processed properly (nether based iron farms)

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#190]

**Comment by KaiXuan233** [comment]
There's a typo in the title :)

**Comment by ch-yx** [comment]
for me,chunks sometimes cannot be loaded when entering a server or changing dimension during tick warp.
I dont know if that is the same bug.

**Comment by gnembon** [comment]
that's a different issue. This bug relates to a very specific situation where chunks stay loaded one tick shorter when warping for whatever (yet to be figured out) reason. Chunks not wanting to load is another issue I would like to solve as well. Tick warp is a constant 'state of rush' and certain things in this game just won't happen if the game is lagging behind.
