### ISSUE TITLE
Carpet Fake player command error.

### ISSUE THREAD

**Issue by PeterFujiyu** [gnembon/fabric-carpet#1907]
carpet version is latest,fabric is latest.

[Server] [15:03:50] [Server thread/ERROR]: Encountered an unexpected exception
[Server] net.minecraft.class_148: Ticking player
[Server]        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:952) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Unknown Source) ~[?:?]
[Server] Caused by: java.lang.NullPointerException: Cannot invoke "dev.dubhe.gugle.carpet.tools.FakePlayerInventoryContainer.tick()" because the return value of "java.util.HashMap.get(Object)" is null
[Server]        at net.minecraft.class_1657.handler$dcl003$gca$tick(class_1657.java:15335) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1657.method_5773(class_1657.java:333) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[server-intermediary.jar:?]
[Server]        at carpet.patches.EntityPlayerMPFake.mixinextras$bridge$method_14226$24(EntityPlayerMPFake.java) ~[%3F%3F%3F%3Ffabric-carpet-1.20.3-1.4.128+v231205.jar:?]
[Server]        at carpet.patches.EntityPlayerMPFake.wrapOperation$ccn000$carpet-tis-addition$fakePlayerTicksLikeRealPlayer_delayedPlayerEntityTick(EntityPlayerMPFake.java:1054) ~[%3F%3F%3F%3Ffabric-carpet-1.20.3-1.4.128+v231205.jar:?]
[Server]        at carpet.patches.EntityPlayerMPFake.method_5773(EntityPlayerMPFake.java:167) ~[%3F%3F%3F%3Ffabric-carpet-1.20.3-1.4.128+v231205.jar:?]
[Server]        at net.minecraft.class_3218.method_18762(class_3218.java:761) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1937.method_18472(class_1937.java:492) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3218.method_31420(class_3218.java:399) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3218.method_18765(class_3218.java:363) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.redirect$bek000$carpet-tctc-addition-1_20_4$onTickingWorld(MinecraftServer.java:4399) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.mixinextras$bridge$redirect$bek000$carpet-tctc-addition-1_20_4$onTickingWorld$287(MinecraftServer.java) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.wrapOperation$zki000$carpet-ams-addition$tickWorlds(MinecraftServer.java:3418) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.mixinextras$bridge$wrapOperation$zki000$carpet-ams-addition$tickWorlds$288(MinecraftServer.java) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.wrapOperation$cih000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:7913) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948) ~[server-intermediary.jar:?]
[Server]        ... 5 more
[Server] [15:03:50] [Server thread/ERROR]: This crash report has been saved to: /home/container/server/./crash-reports/crash-2024-05-01_15.03.50-server.txt

**Comment by altrisi** [comment]
That doesn't seem caused by Carpet, but an extension ("gugle"?).
