### ISSUE TITLE
Missing feature in 1.20.4

### ISSUE THREAD

**Issue by huoyan1231** [gnembon/fabric-carpet#1911]
![image](https://github.com/gnembon/fabric-carpet/assets/53113734/87e47755-6e56-4027-a5e0-d53a7773b357)

**Comment by altrisi** [comment]
`/tick` is now a vanilla command, without some carpet specific stuff. You're looking for `/profile`.

More info: 
https://gist.github.com/gnembon/256538acb59eb4eeea8205aaa0905599
