### ISSUE TITLE
[Suggestion] reducedSpawnChunks

### ISSUE THREAD

**Issue by bencrazyalchemist** [gnembon/fabric-carpet#192]
Not sure how best to implement this but you get the idea. It could be a numerical value to adjust the main spawn chunk level (22 default) or could be a spawn chunk radius. Either way would be an easy way to reduce lag and reduce the task of clearing / soawnproofing spawn chunks.

**Comment by gnembon** [comment]
you can disable spawn chunks altogether with disableSpawnChunks. Why would you need anything in between?

**Comment by bencrazyalchemist** [comment]
Because spawn chunks are useful for many things like mob switches and anything else you want running 24/7 without a permaloader.

**Comment by supersaiyansubtlety** [comment]
I would find it useful to be able to have only one spawn chunk, so small farms could be there but lag would be reduced.

**Comment by gnembon** [comment]
According to slicedlime there is a reason why spawn chunks had to be this size. It probably has something to do with the current ticket system for chunk loading. I would vote for not changing that. Also - keeping rules simple makes sense in the long run. You can have variable player sleeping, but all what everyone really cares about it one player sleeping, or spawn chunks - most people either don't care, or have them removed, hence a simple feature for that. Thoughts?

**Comment by bencrazyalchemist** [comment]
I guess that's fair, and with portal permaloaders few things truly require spawn chunks.  I agree with supersaiyansubtlety tho, it would be nice to disable the spawn chunks but have a 5x5 or 7x7 remain loaded in the middle. Another helpful option would be to when the world starts up load the entire spawn chunks, then let it unload naturally. This would give players the ability to setup things that require permaloading (like a mobswitch or an iron farm) automatically without the need to manually reset them every time there is a restart.

**Comment by supersaiyansubtlety** [comment]
I definitely still think the feature would be nice, but if it requires significant internal changes to the game I don't think it's worth it.

**Comment by bencrazyalchemist** [comment]
Actually I just realized if I want this effect I can manualy /forceload a chunk at spawn and turn on disableSpawnChunks

**Comment by gnembon** [comment]
I guess its just a number. I can remove the current rule and change it to a numerical setting

**Comment by gnembon** [comment]
Quick glance on the commit explains why I was hesitant of doing it.
