### ISSUE TITLE
[Bug]Carpet is incompatible with Iris.

### ISSUE THREAD

**Issue by esuity** [gnembon/fabric-carpet#1933]
The game crashes when it starts with carpet and the newest iris.I don't know if it is carpet's fault.

**Comment by esuity** [comment]
More information:https://github.com/IrisShaders/Iris/issues/2367

**Comment by Poopooracoocoo** [comment]
Also reported in #1931

**Comment by helpimnotdrowning** [comment]
this is fixed by Iris in https://github.com/IrisShaders/Iris/commit/a4cc37ce7bc960b7aa28e5ea54fccb4ddbfed347

**Comment by helpimnotdrowning** [comment]
fixed in Iris 1.7.2 https://modrinth.com/mod/iris/version/1.7.2+1.21
