### ISSUE TITLE
[Request] TNT dupe patch

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/fabric-carpet#197]
I'd like an option to disable TNT duping. 
Wither cages, along with pushable dispensers and renewable sand from carpet extra, make it far less necessary.

**Comment by gnembon** [comment]
I would also like tnt duping to be removed from the game but this quirk is totally voluntary - you can use regular tnt and dispensers if you want instead. Tnt duping requires a special setup that you don't have to build if you don't want to.

**Comment by supersaiyansubtlety** [comment]
I mostly agree with that viewpoint, but I still think a patch could be useful to enforce a server ban on TNT duping. 
It would also take  away the temptation of TNT duping : P
