### ISSUE TITLE
The game doesnt launch with the mod installed

### ISSUE THREAD

**Issue by NotFractured33** [gnembon/fabric-carpet#1984]
The game starts to launch, but then crashes. 1.21
[crash-2024-08-20_07.09.56-client.txt](https://github.com/user-attachments/files/16668904/crash-2024-08-20_07.09.56-client.txt)

**Comment by Castor24** [comment]
Same for me

**Comment by NotFractured33** [comment]
@Castor24 Solved, lithium was conflicting with carpet.
