### ISSUE TITLE
Some commands print no output

### ISSUE THREAD

**Issue by pazgold31** [gnembon/fabric-carpet#199]
I don't know if Im doing something wring, 
Im using fabric-carpet-1.15.2-1.3.9+v200206 (seems to be the latest version) on minecraft 1.15.2, when I try to run the /counter command I get no output (I have hopper facing to wool.
Same thing happend when I tried the /tracking command.
I do have everything enabled in the carpet option.

**Comment by pazgold31** [comment]
So I looked into it and the problem seems to be happening only on a specific superflat world?

**Comment by gnembon** [comment]
check your gamerules if you didn't disabled output of commands.
