### ISSUE TITLE
Game Crashed 1.21

### ISSUE THREAD

**Issue by 00vvlc** [gnembon/fabric-carpet#1991]
The game crashes with carpet and extra carpet, I have no idea why. I leave you the log

https://mclo.gs/Om5CE5G

**Comment by 0xnim** [comment]
Duplicate of #1988

Please close Issue

**Comment by 0xnim** [comment]
Did you get the fixed pr?

**Comment by 0xnim** [comment]
Anyone stubling on this. 

https://github.com/gnembon/fabric-carpet/pull/1937
The build to this pr is available

**Comment by 00vvlc** [comment]
> Did you get the fixed pr?
> 

Yes, modifying indium, that mod brings conflict
