### ISSUE TITLE
explosionNoBlockDamage issue

### ISSUE THREAD

**Issue by PolZol** [gnembon/fabric-carpet#200]
The command "explosionNoBlockDamage" does not work on a server with the lithium mod installed, even though it is enabled TNT is still able to destroy blocks normally.

**Comment by gnembon** [comment]
unable to fix. Lithium takes ownership of the entire explosion code making it not reasonable to expect carpet to have influence over it. Use optimized tnt explosions from carpet and don't use lithium if you need that function.
