### ISSUE TITLE
[Suggestion] Modifying Shulker End City Spawn Rates

### ISSUE THREAD

**Issue by Jaycee733** [gnembon/fabric-carpet#202]
I love the idea of shulker's respawning in End Cities, however their spawn rates are too high for my liking, could there be a way to change their spawn rates?

(Sorry if there is one already that I don't know about)

**Comment by Ghoulboy78** [comment]
I guess you could do with scarpet:
```
__on_tick()->(
    probalility=0.50//modifiable
    
    for(entity_selector('@e[type=shulker,tag=!keep]')
        if(rand(1000)>probability*1000,
            modify(_,'kill'),
            modify(_,'tag','keep')
        )
    )
);
```
and then `probability` is the fraction of shulkers (comparing to the amount you have right now) that you feel is tolerable. i.e: if you choose 0.7, then 30% of shulkers will be killed.

**Comment by gnembon** [comment]
yeah, just instead of 'kill' -> 'remove'
