### ISSUE TITLE
disabling fillUpdates does not prevent observers from activating when loading a structure

### ISSUE THREAD

**Issue by Modiseus** [gnembon/fabric-carpet#21]
If you disable fillUpdates and load a structure that contains an observer the observer will still activate. The same does not happen when using fill, setblock or clone.
### How to reproduce
- Disable fillUpdates
- Use a structure block to save a structure containing a observer
- Load said structure. The observer will activate

![load_observer](https://user-images.githubusercontent.com/6494883/58716746-feeb2800-83c9-11e9-9fb4-0284c54d8e29.png)

Observers also activate when a structure is place next to them.
![load_block](https://user-images.githubusercontent.com/6494883/58716768-0e6a7100-83ca-11e9-876c-f3636a463d7c.png)

**Comment by gnembon** [comment]
hmmm.....

**Comment by gnembon** [comment]
should be fixed next time its released

**Comment by Modiseus** [comment]
Thanks, it now works properly in 1.14.4-pre3.
