### ISSUE TITLE
[Suggestion] Can put .sc files into datapacks?

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#218]
I dunno if it can be done, but it would save programmers a lot of hassle to have to download datapack and scarpet app and then run em both. Maybe when you load a datapack which has a scarpet app in it it should also automatically load scarpet app, or maybe the datpack guy has to specifically load form datapack in the form: `script load datapackname:filename/appname` same way with the `/function` command?

**Comment by gnembon** [comment]
hmm, makes sense. But the app data would still need to reside in /scripts floder, or what

**Comment by Ghoulboy78** [comment]
i dunno how appdata works man, so idk if its even possible

**Comment by Ghoulboy78** [comment]
but btw, is app data necessarily an nbt string, or can it be like any old string that you sorta decompile with your own code?

**Comment by Ghoulboy78** [comment]
never mind, this one is necessary
