### ISSUE TITLE
Fake players increase the mobcap regardless of their gamemode

### ISSUE THREAD

**Issue by maxwoedl** [gnembon/fabric-carpet#219]
**Environment:**
Minecraft:  1.15.2
Carpet version: 1.15.2-1.3.15+v200318
Mode: Singleplayer and "open to LAN"

**Issue:**
When you spawn a fake player and set it's gamemode to spectator (for example to load an area) the mobcap still increases by 70 like it's in survival / creative mode.

![image](https://user-images.githubusercontent.com/17431634/79244546-4e6a0380-7e77-11ea-80d0-9545acb0d2aa.png)

**Comment by gnembon** [comment]
that's normal - works like that in regular game. Use /gamerule spectatorsGenerateChunks false to disable that. just make sure not to stay in spectator with that disabled when closing the world - weird vanilla quirk
