### ISSUE TITLE
If the recipe book is open and a craft operation causes you to die, the game crashes.

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#228]
Minecraft 1.15.2
LWJGL 3.2.2
Fabric 0.8.2+build.194
Carpet Mod 1.3.19

When you die while attempting to craft something while the recipe book is open, the game crashes (`java.lang.NullPointerException: Ticking screen`).

Last four crash reports:
[crash-2020-04-16_18.58.42-client.txt](https://github.com/gnembon/fabric-carpet/files/4490242/crash-2020-04-16_18.58.42-client.txt)
[crash-2020-04-16_18.59.55-client.txt](https://github.com/gnembon/fabric-carpet/files/4490243/crash-2020-04-16_18.59.55-client.txt)
[crash-2020-04-16_19.10.51-client.txt](https://github.com/gnembon/fabric-carpet/files/4492754/crash-2020-04-16_19.10.51-client.txt)
[crash-2020-04-16_19.19.23-client.txt](https://github.com/gnembon/fabric-carpet/files/4492755/crash-2020-04-16_19.19.23-client.txt)

Steps to reproduce:
1. Have some XP on you.
2. Go near a crafting table and have some gold, iron, or any other craftable item materials on you.
3. Run: `/script run death_handler(player) -> modify(player,'health',0);`
4. Run: `/script run __on_statistic(player, category, event, value) -> (
print(player+' | '+category+' | '+event+' | '+value);
run('xp add @p -'+max(1,floor(value)));
if(run('xp query @p levels')==0&&run('xp query @p points')==0,death_handler(player));
)`
5. Open the crafting table and recipe book.
6. Craft as much as you want until the player dies from losing all of his/her XP.
7. The game crashes.

Edit: Also happens with the following items:
* Crafting Table (as originally stated)
* Furnace

**Comment by James103** [comment]
A similar crash also occurs when you leave the recipe book open and **opening the crafting table UI** causes you to crash: [crash-2020-04-17_12.09.05-client.txt](https://github.com/gnembon/fabric-carpet/files/4494312/crash-2020-04-17_12.09.05-client.txt)

**Comment by Ghoulboy78** [comment]
Umm, I think it is fixd, I followed reproduction steps and it didn't work. it didnt crash

**Comment by Ghoulboy78** [comment]
i take it back, i was just doing it wrong

**Comment by gnembon** [comment]
tried as all - coudn't reproduce. 1.16. running carpet only (in the ide). Did you have other mods installed as well?

**Comment by James103** [comment]
Java 8 Update 241
Minecraft 1.15.2 or 20w16a
Carpet Mod 1.3.19b
Fabric Loader 0.8.2+build.194
LWJGL 3.2.2
(The crash may only happen on specific versions of the above software, therefore you should try to have the exact same version. This includes Java)

1. Create new world in Creative mode with cheats on.
2. Look straight down.
3. `/setblock ~ ~-1 ~ crafting_table`
4. Open the crafting table.
5. Open the recipe book.
6. Close the crafting table UI.
7. `/script run __on_statistic(p,a,b,c) -> modify(p, 'health', 0)`
8. Open the crafting table.
9. Crash (player dies while recipe book open) -> [crash-2020-04-19_20.03.47-client.txt](https://github.com/gnembon/fabric-carpet/files/4500696/crash-2020-04-19_20.03.47-client.txt)

**Comment by gnembon** [comment]
got it. forgot the 'open recipe book' step.

**Comment by gnembon** [comment]
ok, its a vanilla issue that never has a chance to surface cause dead players cannot access crafting table. That's a sideeffect of a scripting language where you expose the possible behaviours to less intended cases. I will try to find a workaround. If I manage to reproduce in-game without scripting, will definitely report that to the Mojang team.

**Comment by Ghoulboy78** [comment]
yes you can test in vanilla man. I think it sohuld just be a case of having a load of repeaters and then pressing a button which leads to command with `/kill gnembon` and then quickly rush over to ur recipe buk and then it's a simple matter of opening before rpeater reaches command block

**Comment by Ghoulboy78** [comment]
but alas, that does not reproduce bug, as I guess player exits gui before dying, which is how you skirt around this bug in vanilla

**Comment by Ghoulboy78** [comment]
after that complex explanation, I actually read gnembon's message and saw that, lo and behold, he'd summarized it using about 77.2% of the text I used to write the same thing.

**Comment by gnembon** [comment]
will probably handle that specific usecase in the API with a note what it causes. Would probably be enough to send a close screen to the player when health is 0, or maybe deferring setting that health to 0 to the end of tick as sufficient. The bug is properly client side, but carpet should assume there is vanilla player on the other side

**Comment by gnembon** [comment]
`/script run __on_statistic(p, a, b, c) -> modify(p, 'health', 0)`
simpler to reproduce
