### ISSUE TITLE
Suggestion: Query and modify player's hunger

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#230]
It would be nice if Scarpet can query and modify a player's 
* [x] food level (`query(e, 'hunger')` and `modify(e, 'hunger', value)`)
* [x] saturation level (`query(e, 'saturation')` and `modify(e, 'saturation', value)`)
* [ ] exhaustion level (`query(e, 'exhaustion')` and `modify(e, 'exhaustion', value)`)

This is so Scarpet apps can add abilities that directly cost food points rather than having to go through the vanilla food system or the Hunger effect. Currently, there is no way to directly change a player's food level as in-game NBT editing doesn't work on players.

**Comment by gnembon** [comment]
makes sense

**Comment by Ghoulboy78** [comment]
Finished

**Comment by Ghoulboy78** [comment]
tho @James103 wtf does exhaustion do?

**Comment by James103** [comment]
Exhaustion is basically the progress until next food point loss. By default 1 food point and 4 exhaustion points are subtracted per tick while exhaustion is at least 4.

**Comment by Ghoulboy78** [comment]
hmm, i dont think so, cos exhaustion is at most 4. You can't set it to higher than 4

**Comment by James103** [comment]
> exhaustion is at most 4. You can't set it to higher than 4

This is because when exhaustion is higher than 4, it resets and a food point is deducted from your hunger bar.

**Comment by Ghoulboy78** [comment]
no, no. If you look at code, it will never do any subtracting from food points. It just directly sets exhaustion to 4. If u want I can show code snippet

**Comment by Ghoulboy78** [comment]
at least the way i'm doing it, it's like this:
```java
public void addExhaustion(float exhaustion) {
    this.exhaustion = Math.min(this.exhaustion + exhaustion, 40.0F);
}
```
Wait what? maybe ur right. I take back that previous comment

**Comment by Ghoulboy78** [comment]
nvm, I got it

**Comment by Ghoulboy78** [comment]
ok, I got it, thanks
