### ISSUE TITLE
test if the following expression has issues client entity synchronization

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#236]
server and client:
`modify(_,'mount',spawn('bat',pos(_)))`
where _ is an armorstand for example?

**Comment by Ghoulboy78** [comment]
No problem, @gnembon !

**Comment by gnembon** [comment]
the question was from BisUmTo where his app didn't work properly (rendering the tnts)
```
__config() -> m( l('stay_loaded', 'true'),l('scope', 'global'));

__flying_tnt(tnt) -> (
    e=spawn('bat',pos(tnt));
    modify(tnt,'mount',e)
);

__on_tick() -> (
    for(
        entity_selector('@e[type=tnt,nbt={Fuse:79s}]'),
        __flying_tnt(_);
    )
);
```
it might be just a sideeffect of extra mods added to tnt class

**Comment by Ghoulboy78** [comment]
it works good, so it must be some other mod which interferes (which I see, after skimming through the discord unread messages, you seem to have realized)
