### ISSUE TITLE
[Suggestion] You should be able to do modify(player_name,'gamemode','gamemode_name')

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#237]
and same for the `gamemode_id`. Its there for `query(player,'gamemode')`, so I don't see why it shouldn't be a thing. I may even submit pr to fix it myself.

**Comment by Ghoulboy78** [comment]
actually, I just tried for 1 hour, and found it is like soo hard. I'll have to try again tomorrow, with a fresh brain

**Comment by gnembon** [comment]
Ok, will let you do it. You can look for the hint in the /c /s commands.

**Comment by Ghoulboy78** [comment]
thanks for the hint man

**Comment by Ghoulboy78** [comment]
123rd closed issue!
