### ISSUE TITLE
flippinCactus only inverts direction of dispensers

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/fabric-carpet#239]
I've noticed that right clicking a dispenser with a cactus only makes it face the direction opposite its current direction, rather than cycling through 4 different directions like it does with other blocks.

**Comment by gnembon** [comment]
that has been this way by design to flip hoppers, dispensers etc - things that can be placed facing 6 directions, and for blocks that inherently face only 4 directions, like side hoppers or repeaters - to rotate them. 

tldr, its WAI

**Comment by supersaiyansubtlety** [comment]
Can I ask why? It doesn't seem like the most useful behavior.
