### ISSUE TITLE
Remember previous Night Vision and Conduit Power effects when doing "/c" and "/s"

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#240]
Currently (Carpet Mod 1.3.19 in MC 1.15.2), doing `/c` then `/s` clears any Night Vision and Conduit Power effects you may have. I would like if, similar to a beacon, `/c` and `/s` remembered any Night Vision and Conduit Power effects you may have prior to using those commands.

**Comment by Ghoulboy78** [comment]
Yah, I've tried for about 1 and a half to 2 hours now, I have concluded that it is impossible. For whatever reason, the player just seems either not get the effect at all, or it doesn't get removed in survival. It's madness

**Comment by gnembon** [comment]
not needed. In general /c and /s commands are not needed. Scarpet has all the tools to provide these functions in a customizable app. Once the dust settles over the covid covfefe, I want to publish a scarpet app for that.

**Comment by Ghoulboy78** [comment]
or ill make it man, I already did for another issue. I will make it myself, and btw, @gnembon , the covid covfefe is probably gonna die out in another ~8-9 months cos 2 vaccines ae being developed in UK and US, but theyre undergoing clinical trials, which will take for ever, if you know about vaccine trials.

**Comment by Ghoulboy78** [comment]
I have one which keeps effects, and tps you back to start location, and gives u back any effects. Should I add to the apps which come with fabric-carpet or do pr to scarpet repo? Also, @gnembon , do please tell me if you have any other functionality in mind for me to add.

**Comment by Ghoulboy78** [comment]
also, currently, you by default get tped back, but can also choose with /cam tpback false to not get tped back to start location.

**Comment by Ghoulboy78** [comment]
and im working on adding functionality so that if you want you can check for, say, if you are dying. It will be similar checks to the ones I put on the Minerva datapack, if you want you can see (It's in datapack form, but I made it quite intuitive, [here](https://github.com/MinervaMc/Datapacks/blob/master/spectator/data/spectator/functions/spectator.mcfunction))

Ill add this, with an option to disable these checks, all in the next few days

**Comment by gnembon** [comment]
I would suggest PR ing to scarpet apps.

**Comment by Ghoulboy78** [comment]
i have

**Comment by gnembon** [comment]
https://github.com/gnembon/scarpet/blob/master/programs/survival/cam.sc
