### ISSUE TITLE
investigate what prevents trees from plopping after 20w17a

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#246]

**Comment by James103** [comment]
In case of upgrading old worlds to this snapshot, most likely heightmap corruption causing the game to think there are movement-blocking and light-blocking blocks in places where there shouldn't and vice versa. This potentially breaks placement of certain structures, including trees.

See https://bugs.mojang.com/browse/MC-179858

**Comment by gnembon** [comment]
No it was the new tree generator - They added check not to generate them under sea level. Fixed already.
