### ISSUE TITLE
[Bug] /players leave minecarts when going through end gateways

### ISSUE THREAD

**Issue by BatmenzDW** [gnembon/fabric-carpet#247]
/player goes through gateway while in minecart, comes out the other side out of the minecart

**Comment by Ghoulboy78** [comment]
d you mean carpet fake players?

**Comment by BatmenzDW** [comment]
yeah

**Comment by gnembon** [comment]
Dang cheaty iron farms

**Comment by Ghoulboy78** [comment]
"Do not apass judgements on others, you you may be judged yourself"

**Comment by BatmenzDW** [comment]
No, he's right, that's exactly what I was doing

**Comment by Ghoulboy78** [comment]
I got that as well, I was just quoting Brian for fun

**Comment by gnembon** [comment]
Fixed in 1.17

Won't fix in 1.16.4
