### ISSUE TITLE
Honey blocks do not move player entities when also moving a block entity.

### ISSUE THREAD

**Issue by Necrosapien** [gnembon/fabric-carpet#248]
**Behavior:** 
Honey blocks do not move player entities when they are also moving a block entity such as a dispenser, furnace, etc.

**Expected behavior:** 
Players would be moved along with the honey blocks, like they are when no moveable block entity is attached to the flying machine.

**Steps to reproduce:**
1) Enable moveableBlockEntities with '/carpet moveableBlockEntities true'
2) Create a flying machine using honey blocks and sticky pistons with a moveable block entity attached to the structure, as in the attached image.
3) Stand on top of the honey blocks and activate the machine

This was tested on Carpet Mod version: 1.3.9+v200206
![example](https://user-images.githubusercontent.com/31381047/80161573-73a4f300-8596-11ea-86f6-5ab8db65b878.png)

**Comment by Ghoulboy78** [comment]
test on the most recent version

**Comment by DeadlyMC** [comment]
Just tried your setup, with the latest version...nothing happens like u said
Player stays intact on the honey block

**Comment by DeadlyMC** [comment]
![2020-04-25_19 36 45](https://user-images.githubusercontent.com/43000902/80281932-31adb580-872c-11ea-9e55-7fd6d4a5be51.png)

**Comment by Ghoulboy78** [comment]
ah well. until it gets fixed, just add an extension, i guess

**Comment by DeadlyMC** [comment]
Are u running any other mods?

**Comment by Necrosapien** [comment]
Checked with the person who's running the creative server we tested this on and they are pretty sure it's got Lithium & Phosphor. I cannot replicate this in single-player, even with Lithium.

**Comment by Ghoulboy78** [comment]
with phosphor?

**Comment by Necrosapien** [comment]
Tried adding Phosphor and no change. Seeing as I cannot replicate this other than that server I can close the issue unless someone else can confirm it.
