### ISSUE TITLE
scoreboard() function can't reset scoreboard values with null

### ISSUE THREAD

**Issue by replaceitem** [gnembon/fabric-carpet#255]
the `scoreboard(objective, key, value)` function in scarpet isn't able to reset scoreboard values, which makes it impossible to reset scoreboard values with a key that contains spaces. since the `scoreboard()` function does accept keys with spaces, but the `/scoreboard` command doesnt, there is currently no way to reset such keys.
So setting a scoreboard key with a value of `null` should reset that value like `/scoreboard players reset` does.

**Comment by Ghoulboy78** [comment]
you can do it:`scoreboard('Score_name',player,null)`

**Comment by Ghoulboy78** [comment]
ah no wait you can't

**Comment by Ghoulboy78** [comment]
hmph, easier said than done. I can't do it, cos the resetPLayerScore mthod doesn't like being called, and when I copy pasta code, new code won't be called, etc.
