### ISSUE TITLE
Overlay should show artificial village boundaries

### ISSUE THREAD

**Issue by lougehrig10** [gnembon/fabric-carpet#258]
Yes, I understand that the overlay script shows structure boundaries, but the code itself has specific parameters it uses to identify if an area is a village. Can we get the overlay script to show boundaries for artificially created/updated villages?

**Comment by gnembon** [comment]
there is no such things like villages anymore. Each villager acts independently and everything is dynamic these days. Overlay is supposed to overlay boundaries of world-gen structures.

**Comment by atyshka** [comment]
@gnembon Can you elaborate? According to the minecraft wiki, there are things like village censuses that determine whether new villagers can spawn based on "number of beds within the village boundaries"
