### ISSUE TITLE
How do I make a fake player attack interval each second?

### ISSUE THREAD

**Issue by Teemoo0** [gnembon/fabric-carpet#259]
I want to try making him use our afk Raid farm, however, I don´t know hot to make him attack each second with the /player Steve attack interval since the game doesn´t detect the command. We are on fabric carpet 20w18a

**Comment by gnembon** [comment]
/player Steve attack interval 20
it needs number of ticks in between.

**Comment by Apfelklatsch** [comment]
> /player Steve attack interval 20
> it needs number of ticks in between.

And how can you stop the attack interval ?
Because iam stuck and don´t know how to disable it.
