### ISSUE TITLE
Effect timers always run at the same speed visually, causing large desyncs with "/tick"

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#262]
I don't know if this is already been fixed, but as of Carpet Mod 1.3.20 in Minecraft 1.15, effect timers do not visually tick down faster or slower than normal even when the game is running faster or slower than normal due to lag, `/tick warp`, `/tick rate`, and `/tick superHot`.

For example, if you give yourself 20 minutes of an effect, then do `/tick warp 24000`, it's possible for the effect to run out even when the timer is at `19:30`. And no, a command is not clearing the effect, it's just the timer hitting zero.

**Comment by Ghoulboy78** [comment]
Behaviour is still there in most recent release (1.3.22)

**Comment by gnembon** [comment]
not sure how to replicate that:
![2020-05-12_20 47 14](https://user-images.githubusercontent.com/41132274/81756340-d6045b80-9491-11ea-81a7-023e11e29729.png)

**Comment by gnembon** [comment]
seems like effects tick down like world ticks

**Comment by James103** [comment]
The screenshots you attached show the internal data, which is stored in the player NBT server-side. The following shows both the server-side effect time (in the form of a bossbar where each notch represents one minute) and the client-side effect time (as numbers on the inventory screen):

Before tick warping:
![image](https://user-images.githubusercontent.com/37945304/81756847-8d917180-9482-11ea-8f3a-96f8d2c17dae.png)

After `/tick warp 6000` (5 minute desync):
![image](https://user-images.githubusercontent.com/37945304/81756865-9d10ba80-9482-11ea-9b21-c437e439f7dc.png)

4 real-life minutes later (the effect will run out server-side within 5 seconds):
![image](https://user-images.githubusercontent.com/37945304/81756986-f547bc80-9482-11ea-9ebe-98f28d576d90.png)

**Comment by gnembon** [comment]
ok, seems like its only a cosmetic bug - when effect runs out, server clears it. Client can track if the effect is running out slower when server lags out, but when the server runs faster - it keeps real life pace of seconds. I will try to find a reason for that but it doesn't seem to be that important

**Comment by gnembon** [comment]
ok, won't fix. Client status effects are ticked down according to client speeds. Part of the appeal of tick methods is that client handling is capped at 20tps, so clients won't be going crazy slow/fast as tick rate, but at normal speeds. Ticking down potions is part of it. potions are cleared / applied from the server anyways, so practically this has no difference.
