### ISSUE TITLE
[Suggestion] Ability to turn off sticky pistons dropping blocks

### ISSUE THREAD

**Issue by muzikbike** [gnembon/fabric-carpet#264]
We can turn on and off quasiconnectivity, so why not this as well?

**Comment by Ghoulboy78** [comment]
Why would you even need to though? Unless you want to build something for bedrock on java edition?

**Comment by gnembon** [comment]
thanks for suggestion, but it won't be really useful for anybody. Add a repeater on 2 before the piston to behave like that.
