### ISSUE TITLE
[Suggestion] Rotatable crafting blocks

### ISSUE THREAD

**Issue by tarkel-price** [gnembon/fabric-carpet#266]
I'm not sure if this fits within the scope of the project or how much work it would entail, but I think that adding the ability to rotate crafting blocks such as smithing tables, cartography tables, fletching tables, and the like would make it much easier to decorate with them and seems like something that should already be in the vanilla game. Anvils, furnaces (and their variations), grindstones, looms, stonecutters, and barrels are all already rotateable and used as decoration, so why not the other villager workstations?

Whether this suggestion fits or not I just wanted to say thank you for all the amazing work you put into carpet! It makes minecraft a better game.

**Comment by gnembon** [comment]
crafting tables that's not something you can rotate. This can be only reliably modded by adding a modded block that copies crafting tables but can be rotated. Otherwise it would only cause problems
