### ISSUE TITLE
[Suggestion] Detect professional bloc

### ISSUE THREAD

**Issue by Lolor63** [gnembon/fabric-carpet#268]
Add a way to detect the professional bloc of the villager,
By the track command and a new item, like the system to detect bed but for professional block, with a radius they can detect or not =)

**Comment by Ghoulboy78** [comment]
You can do that easily with scarpet.

**Comment by Ghoulboy78** [comment]
i thought bloc as in the profession carrier, like white robes for cartographer and librarian. It's just cos both bloc and block are english words

**Comment by Lolor63** [comment]
Yes you're right, i will try on scarpet, i have to do some researsh to do that but well, i tell you if i succeed..
For the bloc or block, i don't what is good, it's like a compost bloc for a farmer villager, sorry i'm not an english man =)

**Comment by Ghoulboy78** [comment]
dont worry, and I'm making the app myself rn. It's not trivial

**Comment by Ghoulboy78** [comment]
itt give you what I have, if u wanna do it, and I gotta go rn

**Comment by Ghoulboy78** [comment]
btw, bloc and block are completely different. EU is a trade **bloc**, composter is a farming **block**

**Comment by Ghoulboy78** [comment]
and do tell me when you got the app please, I wanna see it.
And then close this issue

**Comment by Ghoulboy78** [comment]
For the particle line you can use `particle_line(particle type, pos1, pos2)`

**Comment by Ghoulboy78** [comment]
Never mind, I did it myself:
Gnembon, this may be useful, so I'll add (at some point) to the scarpet repo!
```
__on_player_uses_item(player, item_tuple, hand)->(
    entity=query(player,'trace',20,'entities')||null;
    if(type(entity)!='entity'||entity~'type'!='villager'||item_tuple:0!='blaze_rod',return());
    brain= entity~'nbt':'Brain';
    mem=brain:'memories';
    pos=mem:'"minecraft:job_site"':'"pos"'||null;
    if(!pos,return());
    l(x,y,z)=nbt(pos):'[]';
    particle_line('happy_villager',pos(entity),l(x+0.5,y+0.5,z+0.5),0.1);
);
```

**Comment by gnembon** [comment]
yes, that's great. I would remove that `return()` cause you don't want to have exception thrown and caught every time a player uses an item.

**Comment by Ghoulboy78** [comment]
done!

**Comment by Lolor63** [comment]
Hi @Ghoulboy78, woa that's perfect, I tried without success since someone day, thank you for your job!

**Comment by Ghoulboy78** [comment]
no worries man, you'll get there too!

**Comment by Ghoulboy78** [comment]
Actually, @Lolor63 try it now, with the exta line at the bottom to see exactly which villager

**Comment by Ghoulboy78** [comment]
that last edit is so that I don't entity trace avry time I use item, only if clicking with blaze rod

**Comment by Lolor63** [comment]
I've just try, but I don't know how to active this script 😕

**Comment by Ghoulboy78** [comment]
so you open a command block
then you type `/script run __on_player_uses_item(player, item_tuple, hand)->(if(item_tuple:0=='blaze_rod',entity=query(player,'trace',20,'entities')||null;if(type(entity)=='entity'&&entity~'type'=='villager',brain=entity~'nbt':'Brain';mem=brain:'memories';pos=mem:'"minecraft:job_site"':'"pos"'||null;if(!pos,return());l(x,y,z)=nbt(pos):'[]';particle_line('happy_villager',pos(entity),pos(player));particle_line('happy_villager',pos(entity),l(x+0.5,y+0.5,z+0.5),0.1))))`

and then activate once, then break command block.
It should work, @Lolor63

**Comment by Lolor63** [comment]
yes i do that but after i have to right clic a pnj with a blaze rode right?

**Comment by Ghoulboy78** [comment]
whats pnj? you have to click from a distance, or it fails, and u open villager gui. If you click jobless villager, nothing happens. If you click villager with job, it makes particle line to the workstation

**Comment by Lolor63** [comment]
It's what i do, but nothing happens, i thing i do something wrong...

**Comment by Ghoulboy78** [comment]
what i thought. Put it into a .sc file- If you don't know what that is. go to https://www.youtube.com/watch?v=XQprFbtVAV8
gnembon explains here

**Comment by Ghoulboy78** [comment]
for the .sc file copy the first code i posted, up above https://github.com/gnembon/fabric-carpet/issues/268#issuecomment-626889587

**Comment by Lolor63** [comment]
Nothing more, i've tried his eventtest script, work properly,
I just found a gnembon script for villager but don't work for me

**Comment by Lolor63** [comment]
i'm on a 20w19a server, something change maybe?

**Comment by Ghoulboy78** [comment]
do you have discord?

**Comment by Lolor63** [comment]
yes @Lolor63_, i'll be avaible tonight, have to go to work now =)

**Comment by Ghoulboy78** [comment]
r u on any technical server? cos then it's easier to find you
if not just, like, join scicraft and then I'll dm you

**Comment by Lolor63** [comment]
i've join scicraft
