### ISSUE TITLE
[Help] adding quotations to a list

### ISSUE THREAD

**Issue by Zempt77** [gnembon/fabric-carpet#276]
I need to add turn all the items in a list into strings.

**Comment by gnembon** [comment]
wdym in the list into strings, you mean `map(list, str(_))`?

**Comment by Zempt77** [comment]
like if i had a list "list" and it consisted of the numbers 1, 2 and 3, i want to be able to convert them all into strings, '1', '2' and '3'

**Comment by Zempt77** [comment]
I just tried map() and it worked. Sorry, still new to scarpet.
