### ISSUE TITLE
Build error Nullable

### ISSUE THREAD

**Issue by NicklasE99** [gnembon/fabric-carpet#28]
Branch: master

Performed:
git clone https://github.com/gnembon/fabric-carpet.git
cd fabric-carpet/
./gradlew genSources eclipse
./gradlew build

Build error:

/home/ne/gits/fabric-carpet/src/main/java/carpet/mixins/WorldChunk_movableTEMixin.java:5: error: package com.sun.istack.internal does not exist
import com.sun.istack.internal.Nullable;
                              ^
/home/ne/gits/fabric-carpet/src/main/java/carpet/mixins/WorldChunk_movableTEMixin.java:42: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class WorldChunk_movableTEMixin
/home/ne/gits/fabric-carpet/src/main/java/carpet/mixins/WorldChunk_movableTEMixin.java:69: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class WorldChunk_movableTEMixin

**Comment by gnembon** [comment]
can we just get rid of these @ Nullable annotations, @DeadlyMC? I noticed that even in the Fabric API instead of annotations they just add /* nullable */ comment instead.

**Comment by DeadlyMC** [comment]
It can be added as a dependency in the **build.gradle** file `compile "com.google.code.findbugs:jsr305:3.0.2"`

**Comment by gnembon** [comment]
that dependency is useful to have to remove some errors from loom code, but we will remove them from the mixins to stay 'compatible' with the way fabric mods are developed.

**Comment by gnembon** [comment]
removed Nullable annotations
