### ISSUE TITLE
Tick warp completed instantly when entering escape menu. [Single Player]

### ISSUE THREAD

**Issue by solonovamax** [gnembon/fabric-carpet#281]
When entering the escape menu (pressing the esc key), then the tick warp is completed instantly at some absurd rate like 36704 tps.

It will essentially skip the remainder of the tick warp, as the game is frozen.

Possibly causes #282.

Reproducing:
- run a tick warp command
- press the `esc` key
- the remainder of the tick warp has now been skipped.

**Comment by James103** [comment]
`/tick warp 3600 tick warp 3600` skips the second `tick warp 3600`, but still prints it as having completed at real-life days/weeks per second.
`/tick warp 3600` then going to the Nether or End (or vice versa) skips the tick warp in the same way as you mentioned.

**Comment by Ghoulboy78** [comment]
that's inevitable, cos you'e pausing the game, and not just in like a tick freeze. All chunks save, and ticks stop processing

**Comment by Ghoulboy78** [comment]
@solonovamax I'm 90% sure this is WAI

**Comment by Ghoulboy78** [comment]
Correction, I am 100% sure this is WAI
