### ISSUE TITLE
Villagers lose AI at the end of a tick warp

### ISSUE THREAD

**Issue by solonovamax** [gnembon/fabric-carpet#282]
After a tick warp, villagers seem to lose their AI. They can still be pushed, damaged, etc. but they won't pathfind to their work blocks, nor will they work.

This doesn't seem to always happen, so there may be some other factor that is causing this. Possibly related to #281.

Reproducing
- run a tick warp command
- allow tick warp to finish
- villagers no longer have AI

**Comment by Ghoulboy78** [comment]
Trying hard, cannot reproduce

**Comment by solonovamax** [comment]
I was trying to reproduce it, but could not do it successfully.

I sometimes got it when not trying to reproduce it, but just simply testing an automatic carrot farm.

**Comment by gnembon** [comment]
probably not a valid issue anyways.
