### ISSUE TITLE
Crash when using fake player

### ISSUE THREAD

**Issue by Devon7925** [gnembon/fabric-carpet#285]
I am using 1.15.2. Here is the log: https://pastebin.com/KPR9YVu1
That also includes an error from earlier in the log. I thought it might be relevant.
I was testing a datapack at the time if that matters at all.

**Comment by James103** [comment]
Do you have the offending datapack? If so, can you please upload it here?

**Comment by Ghoulboy78** [comment]
datapacks are unlikely to have much to do with it

**Comment by importnetminecraft** [comment]
Here is the link https://github.com/importnetminecraft/MissileWars-2. I doubt it will be much help because its big. I suspect the crash has to do with using commands to teleport fake players through dimensions or something like that.

**Comment by gnembon** [comment]
yes - currently players can only be moved between dimensions once - that raises an exception in logs, but doesn't crash the game. Attempting to move them twice causes crash.

Also - dimension handling has changed in 21a again, so its an issue that needs solving twice.

**Comment by gnembon** [comment]
very likely fixed in 1.17 by rewriting handling of entities.
