### ISSUE TITLE
[Bug] Mobs other than husks can spawn in desert temples when huskSpawningInTemples is set to true

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#287]
I don't seem to be able to see what causes this, though maybe it's cos when you do
```java
@Override
public List<Biome.SpawnEntry> getMonsterSpawns()
{
    if (CarpetSettings.huskSpawningInTemples)
    {
        return MONSTER_SPAWNS;
    }
    return Collections.emptyList();
}
```
It adds the Monster spawns to the regular spawns you would find in a desert temple

**Comment by gnembon** [comment]
![2020-05-22_00 44 17](https://user-images.githubusercontent.com/41132274/82629246-76aaf780-9bc5-11ea-9799-071ebf9939b2.png)
??
is that 20w21a with old (pre 2021) structures in it? Then its a vanillla bug.

**Comment by rintaun** [comment]
yeah, I'm also getting endermen spawning in my shulker farm where they didn't previously. I assume that's a vanilla issue since nothing related to spawning changed in carpet

**Comment by Ghoulboy78** [comment]
@gnembon no, I was in 20b

**Comment by gnembon** [comment]
might have been related to the ongoing structure changes. I changed the mixins completely in 21a. Please confirm its working / broken on 21a. What's version that enderman spawn in your bits @rintaun ?

**Comment by rintaun** [comment]
@gnembon my issue is in 21a

I had 1-high platforms of soul sand; endermen never spawned on the top platform.  in 21a, endermen spawn on the top platform so I added the slabs seen in the screenshot

![image](https://user-images.githubusercontent.com/82698/82684447-9de2e280-9c20-11ea-9b95-e806195214ac.png)

**Comment by rintaun** [comment]
ah, yeah my issue is definitely caused by https://bugs.mojang.com/browse/MC-184740 fwiw. probably not the same as what this one is describing

**Comment by gnembon** [comment]
yes, they forgot to rename structures appropriately in 21a, and old structures are not recognized.
