### ISSUE TITLE
Carpet Client or so-called CarpetGUI

### ISSUE THREAD

**Issue by X-Green** [gnembon/fabric-carpet#290]
I think there should be a kind of client mod that cooperates with Carpet.
E.g.
Reading the pos info from loggers such as projectile logger; render a box at the place so that it would be easier to understand;
Render a chunk loading map from the packets sent by Carpet Server;
.......

While it might be realized in other mods, I still want it to be Carpet Client. Also, the real carpet client hasn't been officially released XD.

P.S. I hope it would be like: "WorldEdit and WorldEditCUI"

**Comment by gnembon** [comment]
yes, its being worked on, but not a priority for anybody it seems so its left as is.

For the time being I am planning to bring some client-synch options and a few custom packets to control UI and in-world client elements from the server via scarpet

**Comment by X-Green** [comment]
hmm...
I'm planning to make a mod which fulfils the feathers I mentioned above, about rendering specific boxes or shadows according to logger/command feedbacks, just like [x:xxx,y:xxx, z:xxx] working in VoxelMap.
So I wonder is there some fixed format for info such as position, in CM, just as : 
    A position vec in logger is always printed in format "[type=Pos, x=100.0, y=100.0, z=100.0]"
Or some kindof better readable-and-recognizable message format?

**Comment by Ghoulboy78** [comment]
@X-Green As to the world edit, I currently am working on a scarpet app which does it with relative high efficiency, if you want I'll send you the link to the repo

**Comment by gnembon** [comment]
currently the only way to display client specific renders is via particles, which is fine, but gets super laggy. My plan was to utilize custom particle code that would send particle data to non-carpet clients and custom efficient render requests to carpet clients.

**Comment by gnembon** [comment]
![2020-06-03_01 03 47](https://user-images.githubusercontent.com/41132274/83594694-44d75080-a536-11ea-8ad0-a056e8c67e06.png)
I think first steps towards it are done? Technically the internal requests for these can already be used - here with the overlay app.
Closing I guess.
