### ISSUE TITLE
[Semi Bug] Carpet spawned players glitch out when riding pigs/striders

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#293]
When riding a pig, the player cannot change direction with the `/player x look` command, and when attacking the pig, it remains facing the same way as the player, if the player has a carrot on a stick in their hand. If they don't the pig responds to my actions, like running around when I whack it, and breeding. But the `/player x look` still dont work.

With striders, it is different. The `/player x look` command works, and the strider will change direction provided the player has a warped fungus on a stick. If the player doesn't have a warped fungus on a stick, behaviour of the strider is similar to that of the pig, except `/player x look` works.

**Comment by gnembon** [comment]
big bug is game crashing.

This is not even a bug - just inconsistency and lack of feature completion.

**Comment by gnembon** [comment]
is this only affecting 1.16, or 1.15 as well (pig-wise)

**Comment by Ghoulboy78** [comment]
ah.

**Comment by Ghoulboy78** [comment]
and btw it's also affecting 1.15 according to the guy in the SciCraft Discord

**Comment by gnembon** [comment]
that should be fixed.
