### ISSUE TITLE
Player connect and disconnect event 

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#294]
I think it could be useful to have events to handle player connection and disconnection (e.g. to save/load data related to that player, or to edit the player entity before it gets unavailable, if possible?).
It could be called something like `__on_player_connects(player)` and `__on_player_disconnects(player)`.
It could work based on similar (same) functionality already available for [Carpet extensions](https://github.com/gnembon/fabric-carpet/blob/e7170ddef9e4331e4ceb4f134d4969f37d24993d/src/main/java/carpet/CarpetServer.java#L103).

**Comment by James103** [comment]
`__on_player_connects(player)` could also be used to display a welcome or welcome back message when the player joins the server, give players a starting kit when they join, and/or to run offline progress on the player's finances or other stats, in addition to just handling save/load for the player.

**Comment by Ghoulboy78** [comment]
actually, this totally already works. I have almost got the app working

**Comment by Ghoulboy78** [comment]
Actually, this is so cool, imma add it to the scarpet repo
```
//gnembon/fabric-carpet #294
//By: Ghoulboy

//Global variables
global_players=l();

global_new_players=l();

global_left_players=l();

//Events
__on_tick()->(
    players=entity_selector('@e[type=player]');
    for(players,//Cos if not it will only check in that dimension
        if(global_players~_==null,//Checks for new players. When it's loaded, will print all currently logged on players.
            print('Welcome, '+_);
            global_players:length(global_players)=_;
            put(global_new_players,null,_),
            delete(global_new_players:(global_new_players~_))
        )
    );

    for(global_players,//Cos if not it will only check in that dimension
        if(players~_==null,//Checks for players left.
            print('Good bye, '+_);
            delete(global_players:(global_players~_));
            put(global_left_players,null,_),
            delete(global_left_players:(global_left_players~_))
        )
    );
)
```

**Comment by Ghoulboy78** [comment]
Ofc, you can also do other stuff besides printing the player's name

**Comment by Ghoulboy78** [comment]
Tried and tested, even works with multiple players leaving and joining in the same tick. You can quite clearly see why.
