### ISSUE TITLE
app custom commands disappear after /reload in 20w22a

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#309]
Considering that /reload should actually reload the apps of just re-register their commands

**Comment by Ghoulboy78** [comment]
I thought /reload was only for datapacks?

**Comment by ImUrX** [comment]
It's how the code actually works

**Comment by gnembon** [comment]
pre 21a - reload was ONLY for datapacks
since 22a - reload is for absolutely everything, including commands
since apps are like datapacks really, reloading datapacks will mean reloading apps as well.

Also a shortcut to clear temporary issues - messed up something, just type /reload.
