### ISSUE TITLE
Ticking entity client crashing

### ISSUE THREAD

**Issue by ruyuto** [gnembon/fabric-carpet#311]
[Crash Log](https://pastebin.com/gAg1UfRz)
Happens on MC 1.15.2 with only fabric-carpet 1.3.27 installed on both my server and client, after updating from carpet 1.3.25.

Client crashes whenever I jump. Flying around in spectator/creator mode does not cause the crash. When connecting to the same server using a client without carpet installed, the crash does not occur.

After deleting my playerdata on the server world, the crashes stop happening. Running the world on singleplayer also does not cause any crashes. Running carpet 1.3.25 on both client and server also did not cause any crashes.

**Comment by James103** [comment]
> After deleting my playerdata on the server world, the crashes stop happening

Do you have a backup of said playerdata that you can share? Something may be corrupt there.

**Comment by gnembon** [comment]
yeah, that would be helpful. otherwise I can't replicate that

**Comment by gnembon** [comment]
or a world download - even better

**Comment by spocane** [comment]
I too had this happen, although for me it seemed to only happen while wearing an elytra, and then jumping.

**Comment by gnembon** [comment]
I know what you all had in common - enabled antiCheatDisabled rule. Will fix - obvious bug
