### ISSUE TITLE
[Suggestion] Villagers bartering

### ISSUE THREAD

**Issue by Cordain** [gnembon/fabric-carpet#312]
As Minecraft 1.16 introduces bartering with piglins, it would be nice to apply this functionality to the villagers.

I see it as a way to obtain renewable emeralds or other items automatically, just like while trading with them. As long as piglin bartering doesn't involve player and creation of "bartering chamber" is possible, it is an option. This could even make some items, like rotten flesh, more usable.

**Comment by Ghoulboy78** [comment]
It's already there in carpet extra I believe.  /carpet villagerAutoTrader

**Comment by Ghoulboy78** [comment]
no it isn't but this is: https://github.com/Ghoulboy78/scripts/blob/master/Finished%20ideas/villagerAutoTrader.sc

**Comment by Ghoulboy78** [comment]
@gnembon u can close now

**Comment by Cordain** [comment]
Sorry for no response, I didn't get any notifications.
Thanks for helping me with this! I really need to get into scarpet...
