### ISSUE TITLE
Suggestion: Piglin bartering limit

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#313]
As of Minecraft 1.16, you can now barter with piglins. and obtain some pretty good loot from them. Some players (that have lots of gold) may find that this is too overpowered and they can't explain why the piglins have so much stuff to sell for gold. Therefore, I propose the following:

* Carpet Option: `piglinBarterDailyLimit`
* Min Value: -1
* Max Value: 1000
* Default Value: -1
* Suggested Values: -1, 0, (some positive values)
* What it does: If this value is set to -1, this limiter is disabled. If this value is set to 0, piglins will not give anything in return for bartering no matter what. Else, this represents how many times you can barter with a piglin before that piglin will stop giving you stuff in return for your gold.

Every 20 minutes, you can barter with a piglin X times, where X is the limit defined in the above setting. But if you try to barter with a piglin X+1 times within 20 minutes (or attack the piglin), the piglin will not give anything in return for 10 minutes, starting from the last time you attacked or tried to barter with the piglin.

**Comment by Ghoulboy78** [comment]
maybe something for carpet-extra?

**Comment by James103** [comment]
Discussion will continue in gnembon/carpet-extra#101.
