### ISSUE TITLE
[suggestion] serverTime() Function

### ISSUE THREAD

**Issue by scuttstorm** [gnembon/fabric-carpet#314]
Per Gnembon's suggestion in Discord I am making this bug tracker to suggest that a serverTime() function be added to return actual server time. This could be very useful for timekeeping even across server resets and outages.

**Comment by gnembon** [comment]
wait, isn't that world world_time is for?

**Comment by scuttstorm** [comment]
world_time() looks like it returns game server tick time, not physical server time. For my purposes, I'm writing a script that keeps track of chest inventories players access over time, as well as a few other things. An administrative tool. It would mimic similar tools from Core Protect and the like. Saving this data by date would be ideal.

**Comment by gnembon** [comment]
so to summarize you want an actual time(), but instead of having a unreliable java nanotime, you want a universally acclaimed unix_time(), potentially with date() function to parse the date

**Comment by scuttstorm** [comment]
Yessir.
