### ISSUE TITLE
carpet smoothClientAnimations can create pushable ghost players on death

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#317]
As of Carpet Mod 1.3.22 in Minecraft 1.15.2, if you die and respawn in the same dimension and don't log out, there is a chance that an invisible ghost player located at your previous death location remains, pushing you away from it.

This is especially apparent in (for example) parkour challenges (but also applies elsewhere), where the more times you fail, the harder the task gets.

To (possibly) reproduce:
1. Install fabric-carpet-1.15.2-1.3.22+v200506 and carpet-extra-1.15.2-1.3.23.
2. In a test world, place a repeating command block with the command `kill @p`, and place a pressure plate on it.
3. Go into survival mode. Stand 1 block directly north of the command block/pressure plate, and face south. Set your spawnpoint (`/spawnpoint`) there.
4. Do `/gamerule doImmediateRespawn true`.
5. Do `/tick warp 72000`.
6. Do `/carpet smoothClientAnimations true`.
7. Walk onto the pressure plate. You will die a bunch of times (around 8-10 to be exact).
8. Attempt to walk onto the pressure plate again. You will notice that you are pushed away from it.

**Comment by James103** [comment]
The issue may be specific to the carpet-extra mod, since I have seen it reproduced in 1.15.2 with the main carpet mod being version 1.3.27.

**Comment by gnembon** [comment]
Yeah that's what I have noticed. Will attempt to try with carpet-extra tomorrow.

**Comment by gnembon** [comment]
Can't make it happen. Also not really sure why this would happen at all.

**Comment by James103** [comment]
I'm closing this because it can't be reproduced anymore as far as I can tell.
