### ISSUE TITLE
Scarpet __command() cannot have arguments

### ISSUE THREAD

**Issue by SirGavith** [gnembon/fabric-carpet#324]
When in scarpet, the __command() method cannot have arguments, in minecraft it tells you that you have too many characters, and will not accept any arguments. However, when you do this with a subcommand, it works fine. For example, there's no way to do /speed 10 by having __command(speedLevel) or anything like that, but if you had a subcommand called effect with an arg called speedlevel, you could do /speed effect 10 or /speed effect whatever.

**Comment by gnembon** [comment]
well, subcommands are technically arguments for the root command, right?

There is already a ticket to rebuild that but that would require some more changes to the language.
