### ISSUE TITLE
[suggestion] support optional argument in scarpet

### ISSUE THREAD

**Issue by aur3l14no** [gnembon/fabric-carpet#325]
I don't know if there is a workaround currently. I believe it will save lots of duplicated codes.

**Comment by Ghoulboy78** [comment]
not really. You can however make, say 1 func which takes 5 args, then 1 which takes 4 args and executes the first with a predefines value for the 5th variable, and so on. Unlike in Java, you can't have 2 funcs with the same name.

**Comment by gnembon** [comment]
Don't see this being a problem, since you can submit args list as a list (one argument) or a map (named arguemnts)

but I can see this being added, just need to come up with a proper syntax for that. I would be part of adding command types for the better system commands support.

**Comment by SirGavith** [comment]
The documentation has optional args in functions with a question mark, which seems pretty intuitive to me

**Comment by Ghoulboy78** [comment]
@SirGavith that is is in-built functions. This issue is about user-defined funcs, which are different
