### ISSUE TITLE
crash with mods using reach entity attributes

### ISSUE THREAD

**Issue by DbpGaming** [gnembon/fabric-carpet#326]
[crash report](https://pastebin.com/QmkuWZAH)

a crash happens when you use carpet mod with [tiered](https://github.com/Draylar/tiered), in this [issue](https://github.com/Draylar/tiered/issues/5) the dev said it was a mixin conflict with the [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes) library, don't know if this falls under carpet mod or that library to fix, but from what i've seen, and the dev of tiered said it seems like it should be reported here

**Comment by gnembon** [comment]
well, that's not true. Carpet has lowered priority of its mixins for that and made them optional. The error message indicates problem in the other mod library.

Carpet cannot do more about it to be honest. - now it boils down to which mod loads first.
