### ISSUE TITLE
Jumping while running /perimeterinfo causes you to be pushed away.

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#328]
As of Carpet Mod 1.3.28 in Minecraft 1.15, if you run the /perimeterinfo command and jump at the same time, you are pushed away. This is because the entity spawned during the subroutines involved in the /perimeterinfo command have actual collision.

If you are standing on a single block more than 24 meters above you, or if you are standing on a slab surrounded by lava, **this can cause you to die.**

To reproduce:
1. On a flat surface (preferably a superflat world), place any slab, and surround it with lava.
2. Stand on the slab, but not directly at the center of the block.
3. Run `/perimeterinfo ~ ~ ~ zombie`.
4. You will die ("Player tried to swim in lava").

A possible solution would be to make the entity intangible not only to the server, but also the client as well.

I also notice: Running the `/perimeterinfo' command a bunch of times can cause desyncs. For example, you may survive being in lava for longer than you should, or you may end up refilling your oxygen less than a second after surfacing from drowning.

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/5ed55ecf9e07bdcb98b803a4c845771f68c3c08f
