### ISSUE TITLE
/log unsubscribes with server restart

### ISSUE THREAD

**Issue by Kempyte** [gnembon/fabric-carpet#33]
I have carpet running on a 1.14.2 server, and I like having it show the tps in the tab screen (/log tps), but everytime the server restarts it unsubscribes us from it and we have to type /log tps again. Also everytime I restart, my scoreboard I have set up to also show in the tab screen reverts to this custom datapack one, tho then again that could just be a "feature" of that datapack.

**Comment by gnembon** [comment]
carpet doesn't store player related information permanently, meaning when the server restarts all the information about who signed up for what is gone. I hope carpet allows you to easily find issues with the server so it doesn't need to restart that often.
