### ISSUE TITLE
Can't access /carpet in singleplayer

### ISSUE THREAD

**Issue by JanDaniel86** [gnembon/fabric-carpet#333]
I am unable to access /carpet while being able to use /c, /log, etc with no problem while in a survival, cheats off world. Carpet features also don't work in the survival world even if changed permanently from a creative world (like flippinCactus). 
![image](https://user-images.githubusercontent.com/67115620/85046760-6f2a3e80-b1c3-11ea-8278-373997e25cbb.png)
![image](https://user-images.githubusercontent.com/67115620/85046807-849f6880-b1c3-11ea-99a5-787cad374bef.png)
![image](https://user-images.githubusercontent.com/67115620/85046884-9da81980-b1c3-11ea-80e5-c4f41f51b771.png)

**Comment by JanDaniel86** [comment]
Thanks, it's there a way to make it not require such privileges? Or do I just turn on cheats?

**Comment by gnembon** [comment]
its part of 'cheats'. Commands is by definition of the game settings - cheats.
