### ISSUE TITLE
In Release Candidate 1 of 1.16, set_biome seems to have no effect, even when relogging.

### ISSUE THREAD

**Issue by alexis-evelyn** [gnembon/fabric-carpet#334]
Testing biome setting in 1.16 Release Candidate 1 does not change my biome. Not in a flat world, nor a regular world. No error messages were produced.

The command I tried to run was `/script scan -12 55 81 -12 55 81 -75 61 145 set_biome(_, 'plains')`.

**Comment by gnembon** [comment]
well, its just the documentation is lacking. 

set biome is inconsistent as biomes are in the game. For the OW and the end, you have to set it at Y=0 ad affects entire column. In the nether is block based.

**Comment by gnembon** [comment]
need to update docs on that first

**Comment by alexis-evelyn** [comment]
Nice. I just switched the y value to 0 and it works. Thanks!
