### ISSUE TITLE
1.16 Release Candidate 1 - /tick warp seems to have no effect on crop growth

### ISSUE THREAD

**Issue by alexis-evelyn** [gnembon/fabric-carpet#335]
I'm able to speed up redstone/minecarts/etc... just fine using /tick warp, however, crops seem unaffected. The only way I can get crops to grow faster is by using the vanilla gamerule change for randomTickSpeed.

**Comment by James103** [comment]
Do crops still grow **at all** when using /tick warp? (Test with a large tick warp and a large field for best results)

**Comment by alexis-evelyn** [comment]
They do grow when using /tick warp, however, the daylight cycle and crops do not operate at the same speed as the redstone does.

Here's a video of what it looks like for me: https://youtu.be/vic0pK6_e90

I was expecting the crops to look like this: https://www.youtube.com/watch?v=Lt-ooRGpLz4&t=244s&ab_channel=gnembon. The redstone definitely works fine, but crops and the daylight cycle don't?

**Comment by gnembon** [comment]
well, your tick rate from your screen is 20-30ms at times, so the game can only go twice as fast. Crops do grow, just not as fast.

Also the fact that the growth age shows 0  is normal - the server will not send unnecessary updates to save on network traffic.

**Comment by alexis-evelyn** [comment]
Oh. Thanks. I don't suppose I can speed it up faster then.
