### ISSUE TITLE
Suggestion: Documentation on how to compile Carpet

### ISSUE THREAD

**Issue by alexis-evelyn** [gnembon/fabric-carpet#338]
I've tried compiling the 1.16 branch of this repo and while successful, Fabric doesn't like it because the access widener file is set to named and not intermediary. I've tried to pull the access widener file from the existing release of the rc.1 jar and have even tried changing named to intermediary of the access widener file that came from the 1.16 branch, however, gradle does not want to compile it after I make any changes to the file. I'm not sure how to modify the file so I can produce a jar that can work with fabric.

**Comment by alexis-evelyn** [comment]
I figured out it was remapJar I needed to run to build a functional version of carpet. It looks to be working properly as I can use carpet even while in a custom dimension.

I suggest specifying to compile with remapJar through gradle on the ReadMe documentation. Thanks!

**Comment by Ghoulboy78** [comment]
then write it urself no?

**Comment by gnembon** [comment]
Its a general guidelines on how to compile other fabric mods - carpet has nothing unique about its process, but a few tips on how to do that would be a great addition to the wiki

**Comment by Ghoulboy78** [comment]
Can't you just link to fabric wiki page?

**Comment by Ghoulboy78** [comment]
ah well there is no fabric wiki page...

**Comment by Ghoulboy78** [comment]
I'll make don't worry be happy

**Comment by Ghoulboy78** [comment]
https://github.com/gnembon/fabric-carpet/wiki/How-to-compile-Carpet-Mod
@alexis-evelyn good enough?

**Comment by Jeppelelle** [comment]
> https://github.com/gnembon/fabric-carpet/wiki/How-to-compile-Carpet-Mod
> @alexis-evelyn good enough?

Almost, there is no mentioning how to build for a different Minecraft version, i downloaded the master to see if i could get Optifine to work for 1.18, however if i do ./gradlew remapJar it only builds the 1.17.1 version

I tried to update .properties & build.grade according to: https://fabricmc.net/versions.html

No luck, after that the compiler complains about: "Unsupported access widener format (v2)"

So yeah, a small extension to that help doc could be how to compile a version that differs from the default

**Comment by epicbuilder2007** [comment]
> > https://github.com/gnembon/fabric-carpet/wiki/How-to-compile-Carpet-Mod
> > @alexis-evelyn good enough?
> 
> Almost, there is no mentioning how to build for a different Minecraft version, i downloaded the master to see if i could get Optifine to work for 1.18, however if i do ./gradlew remapJar it only builds the 1.17.1 version

1.18 and 1.18.1 source files seem to be non-existent, while changing 1.17.1 (happens to some other mods too) or 22w03a  files don't work. Hopefuly a 1.18 branch exists soon.
