### ISSUE TITLE
Scarpets events to its own class

### ISSUE THREAD

**Issue by replaceitem** [gnembon/fabric-carpet#347]
> any way i could add a scarpet event?
> the events are stored in an enum, i couldnt find any way to add a constant with mixins, or anything else

> Yeah, enums bad. Will refactor to its own class and container, but after stable 1.16.x, because it doesn't make sense to do it right now and fight with merging 1.15 all the time. Pls make a ticket for that so we don't forget

[Discord link](https://discordapp.com/channels/211786369951989762/573613501164159016/724949204857782323)

**Comment by gnembon** [comment]
fixed
