### ISSUE TITLE
Corals Placed In Flowing Water By Dispensers Do Not Create Source Blocks

### ISSUE THREAD

**Issue by Yttiricon** [gnembon/fabric-carpet#348]
When using a dispenser (in any orientation) to place a coral of any type inside of flowing water, the coral is placed inside of an air bubble instead of in its waterlogged state (as when placed by a player). 
![2020-06-24_18 31 06](https://user-images.githubusercontent.com/59745661/85604191-f6a30200-b648-11ea-9f33-4c8c60b97157.png)
![2020-06-24_18 31 23](https://user-images.githubusercontent.com/59745661/85604326-1a664800-b649-11ea-9357-54b64efcbcf5.png)

**Comment by TheCatSaber** [comment]
Isn't this an issue with dispenserPlacesBlocks from carpet-extra?

**Comment by Yttiricon** [comment]
Oops. I thought this was part of the standard carpet mod package.
