### ISSUE TITLE
Conflicts with Tiered (or Reach Entity Attributes it uses)

### ISSUE THREAD

**Issue by Samekichi** [gnembon/fabric-carpet#349]
Carpet is conflict with mod Tiered as the game crashes when entering a world. The issue has been reported to Tiered's author and it seems to be a conflict between Carpet and Reach Entity Attributes. ([Here's the previous report to Tiered. ](https://github.com/Draylar/tiered/issues/5) )
Would be glad to see this being fixed cuz I love using both of the mods. Thx!

**Comment by Mattabase** [comment]
The crash still happens even using fabric-carpet-1.16.1-1.4.0+v200623_build2

[crash-2020-08-07_01.48.46-client.txt](https://github.com/gnembon/fabric-carpet/files/5039571/crash-2020-08-07_01.48.46-client.txt)
