### ISSUE TITLE
[Suggestion] Jukebox functionality

### ISSUE THREAD

**Issue by PossessedRyd** [gnembon/fabric-carpet#351]
I really love the moveable tile entities change and i dont know if carpet would even be the right place for this but i think itd be nice for hoppers to be able to interact with jukeboxes, leading to automated music systems being possible

**Comment by altrisi** [comment]
This is already possible with carpet-extra!
See the dispensersPlayRecords rule in [gnembon/carpet-extra](https://github.com/gnembon/carpet-extra).

**Comment by Ghoulboy78** [comment]
then close?
