### ISSUE TITLE
ops Permission Level Not in Autocomplete in 1.4

### ISSUE THREAD

**Issue by crdtrd** [gnembon/fabric-carpet#355]
Don't know if you know this or not, but the ops permission level for command settings added in 1.4 is not in autocomplete.

**Comment by Ghoulboy78** [comment]
WAI

**Comment by gnembon** [comment]
well, not necessarily WAI. It makes sense to add ops to the list of suggestions.

**Comment by Ghoulboy78** [comment]
I'll do
