### ISSUE TITLE
[Suggestion] Reintroduce commandCameraMode

### ISSUE THREAD

**Issue by kyroschow** [gnembon/fabric-carpet#357]
1.16 allows using F3+N to switch between spectator mode, but it has the some limitations:
1. Non oped players cannot use F3+N
2. F3+N does not give the night vision and conduit power effect

commandCameraMode does provide some extra functionality, so I don't think there's a rush to remove it.

**Comment by James103** [comment]
Have you heard of this? https://github.com/gnembon/scarpet/blob/master/programs/survival/cam.sc
It's basically a Scarpet replacement for `commandCameraMode` (`/c` and `/s`).

**Comment by kyroschow** [comment]
@James103 Just installed the script on my server, and it works!
Thank you!
