### ISSUE TITLE
/c and /s not working in 1.16.1

### ISSUE THREAD

**Issue by ulysse42** [gnembon/fabric-carpet#358]
I updated a 1.15.2 world to 1.16.1, and /c and /s do not work anymore. The shortcuts didn't work either in a brand new 1.16.1 world.

![Capture d’écran du 2020-07-01 01-26-51](https://user-images.githubusercontent.com/27727165/86186687-fd92ae80-bb39-11ea-863c-e1993590dcf6.png)

I have the following mods installed :

![Capture d’écran du 2020-07-01 01-28-49](https://user-images.githubusercontent.com/27727165/86186782-3cc0ff80-bb3a-11ea-94d8-8bb90be467f2.png)

Edit :  I tried to remove other mods and same result

**Comment by James103** [comment]
Have you heard of this? https://github.com/gnembon/scarpet/blob/master/programs/survival/cam.sc
It's basically a Scarpet replacement for `commandCameraMode` (`/c` and `/s`).

**Comment by LuisVervaet** [comment]
/c and /s were removed since you can now do F3 + F4 and F3 + N

**Comment by ulysse42** [comment]
oh right thanks both !
