### ISSUE TITLE
Renewable Lava

### ISSUE THREAD

**Issue by BeLikePanda** [gnembon/fabric-carpet#363]
Magma blocks should be like gravel and randomly it gets replaced with a lava source when broken. This could be affected by Fortune and Silk Touch.

Since Magma Blocks have the texture of lava and netherrack one could expect it to cool down to just netherrack too (when brocken without silktouch)

Please post feedback in the comments so this suggestion is good enough for implementation into carpet!

**Comment by gnembon** [comment]
renewable lava is already part of carpet-extra.
