### ISSUE TITLE
[Scarpet Suggestion] Showing command argument names instead of <args...>

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#365]
This is more of an aesthetic feature, but since the function's argument's names are already shown to the user when running the command with an incorrect amount of arguments, would it be possible to show those names while writing? Like when doing a command like `/scoreboard objectives add smth`, that shows `<objective> <criteria> [<displayName>]`.
It would definitely help end users to know what to write for each argument without looking at a help page or something.

May depend in #221

**Comment by Ghoulboy78-Alt** [comment]
It is being worked on, and anyways if you get wrong number of srgs it will show which arg s have which names

**Comment by altrisi** [comment]
I think this is basically fixed in the new command system (not tested though). Will reopen if it's not the case.
