### ISSUE TITLE
scarpet: create_marker() armor stands are not markers

### ISSUE THREAD

**Issue by mwappner** [gnembon/fabric-carpet#372]
In some contexts its useful to have the Marker tag set to true for armor stands that are intended to be markers. I think `create_marker()` should set that. Main reason I've encountered is having the marker glow, so that it shows though walls. Doing that without `Marker:1b` results in the body of the stand also glowing, not just the block in its head.

**Comment by gnembon** [comment]
well, funnily - that option was always there, just I never documented that in the API docs. This should cover that. I also adjusted the Y position for markers so it shows up properly.
