### ISSUE TITLE
[Bug] SpawnReporter.registerSpawn null pointer exception crash

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/fabric-carpet#384]
This crash seems to happen on my server when my friend and I are exploring in a boat (maybe chunk-gen related?).
[crash-report.txt](https://hastebin.com/imihesapip.php)

fabric-carpet-1.16-1.4.0+v200623.jar
windows 10
fabric loader 0.9.0 build 204

**Comment by gnembon** [comment]
well, the crash report suggests its an ancient version:
```
Minecraft Version: 1.14.4
carpet: Carpet Mod in Fabric 1.0.5
```

**Comment by supersaiyansubtlety** [comment]
Not sure why that is, I'm definitely on 1.16.1 and that fabric-carpet jar name is copy/pasted from my mods folder. Maybe I had an old version of NotEnoughCrashes or something. 
Anyways, I haven't been able to reproduce it since posting this, so I'll close it.
