### ISSUE TITLE
Cant get 1.16.1 to work 

### ISSUE THREAD

**Issue by Xwicked-knightX** [gnembon/fabric-carpet#386]
With the latest fabric API when i add this to my mods game crashes on startup with no crash log and the normal log isnt much more help

**Comment by gnembon** [comment]
make sure its a 1.4.0 version of carpet

**Comment by Xwicked-knightX** [comment]
That is the version I'm trying to use

**Comment by RdSt14** [comment]
I also noticed that when I downloaded the pre-release of Optifine with Carpet, the game cannot launch. 

Mods used:
Fabric API
MiniHUD
Optifabric
Malilib
Inventory Sorter
Phosphor
Carpet

All of these mods except Carpet works well with the 5th pre-release of Optifine.

**Comment by RdSt14** [comment]
Yeah. Optifine indeed.
