### ISSUE TITLE
/perimeterinfo counts nether wart block as potential spawnable space

### ISSUE THREAD

**Issue by robot4jarvis** [gnembon/fabric-carpet#387]
When using the comand /perimeterinfo, it includes all nether wart blocks as spawnable space, despite any mob can spawn on it (at least in the nether).
This happened in Minecraft 1.16.1 with Carpet Mod, Fabric, Litematica, MaLibLib and MiniHud.
![2020-07-21_12 55 27](https://user-images.githubusercontent.com/68592809/88047497-03d0e500-cb52-11ea-80c5-6d7d28a6905c.png)

**Comment by gnembon** [comment]
because they are. 

You have to provide specific mob to test properly for spawning, like 
`/perimeterinfo ~ ~ ~ piglin`
This way a specific mob will be used to test for spawnability.
