### ISSUE TITLE
new style container brackets notation don't cause the same compiler warnings as functional notation

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#388]
m() m()
 - reports missing operator between function invocation

but 

{} {} 
 - doesn't report it in place but fails in general validation of the parse tree.

**Comment by Ghoulboy78** [comment]
True I noticed

**Comment by Ghoulboy78** [comment]
Also if there is no semicolon after the map, dunno about list, it will give the error: 
```
Too many variables in app.sc
Error loading app
```

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/0e24940b78c1cb01c7231f49e8bf53622c7d0b62
