### ISSUE TITLE
Client speed increase

### ISSUE THREAD

**Issue by likseBSMC** [gnembon/fabric-carpet#392]
Carpet Version: 1.4.0 build 2
Fabric Version: Latest (1.16.1)
Mods: fabric-carpet
Issue: Can only decrease client speed but cannot increase it (/tick rate ...) with smoothClientAnimations set to true.

**Comment by Ghoulboy78** [comment]
WAI

**Comment by gnembon** [comment]
it would be crazy to play with increased client speed. Its WAI to be this way.
