### ISSUE TITLE
import() symbols do not allow upper case letters

### ISSUE THREAD

**Issue by SirGavith** [gnembon/fabric-carpet#395]
When using import  `import(foo,Bar);` , no function is defined as Bar, but using `import(foo,bar);` it will work as expected.
It does not matter if the function in the library file is capitalized, nor if the use in the main file is capitalized, just the symbol in `import()`

**Comment by Ghoulboy78** [comment]
that it because it always defaults to lowercase. Same for script names.

**Comment by gnembon** [comment]
but you can technically use uppercases in the scripts - which is just stylistic for scarpet to use snake case.

Will try to support mixed case literals.

**Comment by gnembon** [comment]
Made function names case-sensitive throughout. 
Still have an opinion that mixing snake and camel cases lead to mess and certain portions of the language already lean towards snake case (default '_' and other '_\w' variables, or 'global_*' vars), but if one wants to mix in upper case - let it be.

Module names are still lowercased internally.
https://github.com/gnembon/fabric-carpet/commit/2c7c7d9bc66c79bfbbc38897ac6235709fbcb38c
