### ISSUE TITLE
Server/client crashes after initiating /spawn tracking command

### ISSUE THREAD

**Issue by Rebilium** [gnembon/fabric-carpet#399]
crash report for further details :
[crash-2020-08-01_21.50.14-server.txt](https://github.com/gnembon/fabric-carpet/files/5011215/crash-2020-08-01_21.50.14-server.txt)
[crash-2020-08-01_21.46.22-server.txt](https://github.com/gnembon/fabric-carpet/files/5011217/crash-2020-08-01_21.46.22-server.txt)

if more details are needed i can submit within short period of time
Thank you.

**Comment by dhouck** [comment]
Iʼm getting this with just `/tick warp`, and the logs indicate itʼs probably because there are too many sounds at a time.  Minecraft 1.16.1, Carpet 1.4.0 build 2.

**Comment by gnembon** [comment]
this takes care of it
https://github.com/gnembon/fabric-carpet/commit/815c75b82703b4fad166dd8c25c5b9f114ec8749
