### ISSUE TITLE
Server SpawnReporter.registerSpawn nullpointer crash

### ISSUE THREAD

**Issue by Faustvii** [gnembon/fabric-carpet#402]
I don't really know what caused the crash, of if it's caused by Carpet, just saw Carpet mentioned in the stacktrace.

These two lines were just before the crash in the server log.

```
[23:03:32] [Server thread/WARN]: Block entity invalid: minecraft:mob_spawner @ class_2338{x=-575, y=38, z=-1123}
[23:03:32] [Server thread/WARN]: Block entity invalid: minecraft:chest @ class_2338{x=-574, y=38, z=-1125}
```

[crash-2020-08-03_23.04.31-server.txt](https://github.com/gnembon/fabric-carpet/files/5020124/crash-2020-08-03_23.04.31-server.txt)

**Comment by gnembon** [comment]
is there anything you have done to make it happen, or it just happened naturally?

**Comment by Faustvii** [comment]
I'm unsure of the exact details since I wasn't playing when the crash on the server happened, but I believe it just happened naturally, the two people who were on the server was just running around/flying with Elytra when it happened, in already generated chunks.
