### ISSUE TITLE
Minecraft can't start with Optifine and Carpet

### ISSUE THREAD

**Issue by EthicalJ** [gnembon/fabric-carpet#405]
The Carpet mod and Optifabric is incompatible. When ever I have optifabric in my mods folder with carpet then Minecraft is unable to start, but when Carpet is without Optifabric then Minecraft can start; and vice versa.

**Comment by gnembon** [comment]
did you download build-2 version of 1.4.0, or you are using the old 1.4.0?

**Comment by EthicalJ** [comment]
> did you download build-2 version of 1.4.0, or you are using the old 1.4.0?

I am using fabric-carpet-1.16-1.4.0+v200623 and optifabric-1.1.0-beta2 and OptiFine_1.16.1_HD_U_G2.

**Comment by gnembon** [comment]
yep - download _build2 version

**Comment by rubikgamer9** [comment]
Can I have a link to build 2? I can't seem to find it

**Comment by Beppe0515** [comment]
Why doesn't optifabric work with carpet in 19.4. I have the same problem as spekii. I have tried both of the latest carpet mods with the correct optifabric and optifine, but it still doesnt work. 
Both of the latest carpet mods are not working with optifabric. What do I do?

**Comment by malino-dev** [comment]
Update of it (still? again?) not working for:
- MC 1.20.1
- OptiFine_1.20.1_HD_U_I5
- Optifabric-Mod-Fabric-1.20.1
- fabric-carpet-1.20-1.4.112+v230608.jar
