### ISSUE TITLE
creativeNoClip is server-wide, not per-player

### ISSUE THREAD

**Issue by Terrain2** [gnembon/fabric-carpet#406]
Exactly as the title says, my friend disabled noclip with /carpet creativeNoClip false, and i suddenly stopped noclipping, i enabled it for myself with /carpet creativeNoClip true, and he started noclipping like me

**Comment by James103** [comment]
What version of Carpet mod and Minecraft were you running? Can you reproduce this in the latest Minecraft and Carpet mod versions?

**Comment by Terrain2** [comment]
Yes, i was using carpet version 1.4.7+v200806 in minecraft 1.16.2-pre3, i.e. latest snapshots/versions of minecraft, fabric and carpet

**Comment by gnembon** [comment]
well, all settings are affecting all players, its WAI at this point.

**Comment by Terrain2** [comment]
what is WAI? Working As Intended?

**Comment by tajemniktv** [comment]
Is it possible to somehow override this setting on the client-side? 
I'm playing on a server that has this setting enabled and it's really useful, but I somehow can't get used to it and switch to that way of flying
