### ISSUE TITLE
/script run & invoke returns incorrect "success count"

### ISSUE THREAD

**Issue by Terrain2** [gnembon/fabric-carpet#408]
# Description
The ``/script run`` and ``/script invoke`` commands will always return 1, even if that script snippet shows a syntax error when ran by a player

Here's [a video](https://www.youtube.com/watch?v=eguOIUt67Rg) showing this issue

# Steps to reproduce and expected/actual result
- /script run print(1+1
  - shows an error indicating the command was not successful
- /script run run('script run print(1+1')
  - runs the command above (which doesn't compile) from a scarpet script
  - does not print anything (because it never ran)
  - does not give any indication of any kind of error to the script

Expected result: 0, to indicate the command was unsuccessful (success rate 0)
Actual result: 1, which usually means the command was successful (success rate 1)

# Code Analysis
It seems the ``/script run`` command will always return 1 no matter what, https://github.com/gnembon/fabric-carpet/blob/13f0b2399e691e8c51831edf5906e21ac8d8041c/src/main/java/carpet/commands/ScriptCommand.java#L437-L446

i suggest to make the handleCall function return a bool as to whether the expression actually ran https://github.com/gnembon/fabric-carpet/blob/13f0b2399e691e8c51831edf5906e21ac8d8041c/src/main/java/carpet/commands/ScriptCommand.java#L380-L385

or if there was a ``CarpetExpressionException`` it would return false https://github.com/gnembon/fabric-carpet/blob/13f0b2399e691e8c51831edf5906e21ac8d8041c/src/main/java/carpet/commands/ScriptCommand.java#L399-L404

and then change the ``/script run`` command to return that bool, as an int (see first code snippet)

Same thing goes for ``/script invoke`` https://github.com/gnembon/fabric-carpet/blob/13f0b2399e691e8c51831edf5906e21ac8d8041c/src/main/java/carpet/commands/ScriptCommand.java#L408-L411 https://github.com/gnembon/fabric-carpet/blob/13f0b2399e691e8c51831edf5906e21ac8d8041c/src/main/java/carpet/commands/ScriptCommand.java#L430-L435

**Comment by Ghoulboy78** [comment]
Then why not propose a fix? Ig just adding a `return 0` after:
```
catch (CarpetExpressionException e) 
 { 
     host.handleErrorWithStack("Error while evaluating expression", e); 
 } 
```
shoud work?
