### ISSUE TITLE
client side commands?

### ISSUE THREAD

**Issue by JohnyDL** [gnembon/fabric-carpet#409]
I understood from the video I could install and issue client-side commands to have my own Player Character do a thing (use continuous and attack continuous) without needing Carpet installed server-side, is this still supported in 1.16.x? if so how do I do this?

**Comment by altrisi** [comment]
I'm almost sure it's the other way around. You can do that without having carpet in the client side, but in the server.

**Comment by Ghoulboy78** [comment]
yeah, and the comands are all listed in the video. Those that aren't are so simple they dont need an explanation.

**Comment by JohnyDL** [comment]
I tried typing "/player JohnyDL Attack" into my client with the mod installed which should be enough to keep sending to the server for my PC to do that action over and over I get that I can't spawn other players in to do things without it being server side but the way I understood the explanation was that I can do it instead of having to you know run an auto hotkey script and be unable to use my PC

**Comment by Ghoulboy78** [comment]
the command is `/player JohnyDK attack continuous`, and you have to type `/player JohnyDL shadow` for the server to do actually do it, cos it doesnt always work. But that only works on a server.

**Comment by JohnyDL** [comment]
ah so I do need the server side ... damn... the server runners aren't willing to install carpet for me (apparently not compatible with spigot/paper something... I wasn't listening)

**Comment by Ghoulboy78** [comment]
yeah, it isnt

**Comment by Ghoulboy78** [comment]
tho tbh carpet provides a lot more performance improvements that paper/spigot, and with scarpet you can recreate most plugins...

**Comment by TCasseBloc** [comment]
But that requires to have a dev, who wants to recreate all plugins from scratch in Scarpet, and who probably want to be paid.

**Comment by JohnyDL** [comment]
Yeah and they run core protect and all sorts of other things, if it was one click they'd switch in an instant but since it isn't they're not willing

**Comment by gnembon** [comment]
carpet is a primarily a server side mod. There are no plans of making fake client side players or controling client side players on servers with local scarpet.
