### ISSUE TITLE
carpet Just isn't working

### ISSUE THREAD

**Issue by T0nyPlayz** [gnembon/fabric-carpet#411]
i have installed the capet mod onto my server mod files and launched the game as well as the minecrafts mods files but when i try to execute a command that is related to the carpet mod the server doesn't recognise the command

**Comment by altrisi** [comment]
Check that you are running the Fabric Loader in the server and that you are launching the server from the fabric server launch jar instead of the vanilla server.jar.

**Comment by altrisi** [comment]
Is this still an issue?

**Comment by gnembon** [comment]
works for me
