### ISSUE TITLE
[Suggestion] 1.16.2 worldgen hot-reload/live view

### ISSUE THREAD

**Issue by ZenithRogue** [gnembon/fabric-carpet#412]
### I am suggesting a special mode for creators to be able to hot-reload world generation settings.

1.16.2 introduces a bunch of changes to custom world generation, and it can be difficult for creators to customize these settings, due to the nature of reloading for each of these changes.

This special mode would be specifically designed for creators to make on the fly changes to world generation (through their standard text editors, not a built-in editor), at which point, the chunks would be reset, allowing you to see the effects without a full reload.

**Comment by ZenithRogue** [comment]
I apologize in advance if this is not the correct place for a suggestion such as this. This mod just seemed to be the most relevant

**Comment by Ghoulboy78** [comment]
I think the reset_chunk() function in scarpet should be able to do something similar to what you ask.

**Comment by TCasseBloc** [comment]
though you still need to reload your world because of that bug : https://bugs.mojang.com/browse/MC-187938

**Comment by Ghoulboy78** [comment]
idk, cos scarpet's reset_chunk() func should (in theory) be able to circumvent that bug.

**Comment by TCasseBloc** [comment]
No, because you still need to update the modified files via reloading the datapacks.

**Comment by Ghoulboy78** [comment]
ah. I hadnt read the bug report properly ig

**Comment by gnembon** [comment]
I would suggest to wait until mojang makes up their mind what they want from custom dimensions. reset chunk `should` work there.
