### ISSUE TITLE
FillUpdate working incorrectly on servers in 1.16

### ISSUE THREAD

**Issue by nnnik** [gnembon/fabric-carpet#414]
Starting with Minecraft 1.16 Observers get powered when they are placed by SetBlock/Fill or similar commands.
In my understanding of FillUpdate it should deactivate this behavior.
Yet it does not do that and observers still fire when being placed by command, despite fillUpdate being set to false.

This video showcases the issue:
https://streamable.com/z6b215

**Comment by James103** [comment]
Are you able to reproduce this without Carpet mod? If so, has this already been reported to the [Mojang bug tracker](https://bugs.mojang.com/)?

**Comment by nnnik** [comment]
This is the same issue reproduced with a vanilla client and a vanilla server.
https://streamable.com/55ixo8
I do not concern myself with the Mojang bug tracker since it would involve concerning myself with the moderators - people whose only task it is to reject vital bug reports based on formalities.

**Comment by gnembon** [comment]
I think its fixed, @nnnik. Correct?

**Comment by gnembon** [comment]
reopen if needed.

**Comment by nnnik** [comment]
Have to check

**Comment by nnnik** [comment]
The fix povided seems to cover all cases I could account for.
