### ISSUE TITLE
Suggestion: Global scarpet scripts

### ISSUE THREAD

**Issue by TrueCP6** [gnembon/fabric-carpet#416]
Scarpet scripts that could be loaded and ran from any world.

**Comment by Ghoulboy78** [comment]
what point? just copy paste script no? It's easier that way.

**Comment by TrueCP6** [comment]
Its a pain when you use the same script on every new world you create. It saves the user time and effort.

**Comment by gnembon** [comment]
I can feel you. Technically you can have a carpet extension providing more built-in apps, which you can make yourself.

**Comment by Ghoulboy78** [comment]
looking into it rn

**Comment by MatthewOverall** [comment]
I agree it would be nice to have global settings and global scripts at the root of the server rather than inside the world folder. When we are playing a game mode where we re-create the world multiple times, it's a pain reloading conf files.

**Comment by gnembon** [comment]
closing this one, just because there is another higher on the list and planned. 

Merging with #577
