### ISSUE TITLE
ai_tracker labels are invisable

### ISSUE THREAD

**Issue by MMK21Hub** [gnembon/fabric-carpet#424]
## Steps to reproduce
1. `/script load ai_tracker`
2. Toggle `/ai_tracker villager_breeding` on
3. Switch to *Fabulous!* graphics

## Expected behaviour
The label would be visible

## Actual behaviour
The label is invisible

## Attatchments
![Fancy](https://user-images.githubusercontent.com/50421330/90872472-99030b80-e394-11ea-90dc-f41febcd8b8f.png)
![*Fabulous!*](https://user-images.githubusercontent.com/50421330/90872496-a3250a00-e394-11ea-85f7-61463c1eb379.png)

**Comment by Ghoulboy78** [comment]
if you know that, then close this no? @MMK21Hub?
