### ISSUE TITLE
Suggestion: New Carpet rule: 1.12chunkLoading

### ISSUE THREAD

**Issue by susanshopper** [gnembon/fabric-carpet#427]
This carpet rule, when set to true, reverts the chunk loading mechanics to 1.12.2 mechanics. This fixes MC-159109 and MC-147818. This is useful for remotely activating ender pearl stasis chambers and for ender pearl cannons.

**Comment by Ghoulboy78** [comment]
Seee https://github.com/vktec/chonk

**Comment by susanshopper** [comment]
What versions is it compatible with? If it is not compatible with 1.16.1, how do you make it so?

**Comment by Ghoulboy78** [comment]
too hard to do with new chunk ticket system. If you really have that hard time, just dont update. And anyways, newer chunkoading methods are more reliable.

**Comment by susanshopper** [comment]
Sorry for not knowing that is hard with the new ticket system. The alternative is to use chonk. So how can chonk be made compatible with 1.16.2?

**Comment by bencrazyalchemist** [comment]
just dm vktec in discord and ask

**Comment by susanshopper** [comment]
Thanks

**Comment by DragonEggBedrockBreaking** [comment]
chonk is now updated to 1.16 btw
