### ISSUE TITLE
[Suggestion] Command for counter rates

### ISSUE THREAD

**Issue by Vonr** [gnembon/fabric-carpet#428]
Syntax: /counter <color> rates <namespaced_item_id(s)/all> <time unit>
Sends the number of specified items of that can be collected on average in the specified time for the specified color.
Useless for the most part but lets me be lazier when calculating rates.

**Comment by Ghoulboy78** [comment]
Kindly explain how this would be used? You are using the counter because you don't know the rates, and you wanna find out.

**Comment by Ghoulboy78** [comment]
ah no wait I misunderstood big time lol. you want to be able to see rates for a specific item.

**Comment by Ghoulboy78** [comment]
lemme see

**Comment by Ghoulboy78** [comment]
working on it.

**Comment by Ghoulboy78** [comment]
got a solution, ill check tomorrow if it works

**Comment by Advait-Sen** [comment]
@gnembon wrong issue!

**Comment by Ghoulboy78** [comment]
@gnembon wrong issue!
