### ISSUE TITLE
Singleplayer not working

### ISSUE THREAD

**Issue by mhnu18** [gnembon/fabric-carpet#432]
Singleplayer worlds already created or new crash and say "locked by another running instance of minecraft" even though there aren't any other instances

**Comment by James103** [comment]
What version of Minecraft and Carpet mod are you running, and is your account somehow in use by another session?

**Comment by mhnu18** [comment]
Im using 1.16.1 and used fabric-carpet-1.16-1.4.0+v200623, and no it isnt i tried logging out from everywhere and changing my password but it still happens

**Comment by James103** [comment]
Does multiplayer still work? I.e. are you still able to connect to any servers?

**Comment by mhnu18** [comment]
yes im able to connect to multiplayer with it just not singleplayer

**Comment by James103** [comment]
Did you try the following?
* Test in vanilla 1.16.1
* Test in vanilla 1.16.2
* Test in 1.16.2 with Carpet mod 1.4.9

**Comment by mhnu18** [comment]
im sorry for the late response, i've just tested some things and it seems the issue was with another mod not being compatible with carpet
thank you for your help
