### ISSUE TITLE
Suggestion: light updates toggle

### ISSUE THREAD

**Issue by ItsEmpa** [gnembon/fabric-carpet#434]
I think as you can toggle InteractionUpdates with carpet it would be pretty cool to also be able to contorl light updates, so that designing farms that use lightning supression can be made easily.

**Comment by Ghoulboy78** [comment]
just build the machine. If you know how to use, it's super simple. Watch vktec's vid if u dont know

**Comment by fghsgh** [comment]
please check previous issues before submitting a new one: #415

**Comment by ItsEmpa** [comment]
alright, sorry i couldn't find that i'll close this one then
