### ISSUE TITLE
Suggestion: Redstone Dust on Bottom Slabs

### ISSUE THREAD

**Issue by VampireMonkey** [gnembon/fabric-carpet#435]
Redstone can be placed on Top Slabs but no on Bottom Slabs, even tho it wouldn't exceed a full block's worth of space.

Would be super cool as Carpet already allows for Pushable Block Entities, having Redstone on Bottom Slabs would be a great addition!

**Comment by altrisi** [comment]
That wouldn't be compatible with a vanilla client/server, and Carpet servers are accessible by vanilla clients and worlds loaded with Carpet compatible with vanilla servers.

**Comment by gnembon** [comment]
you can't have two blocks in the same space. You can have two liquids, but redstone is not a liquid. Feels weird. I bet there are dedicated mods to do that.
