### ISSUE TITLE
Suggestion: Comparator Detect Redstone Lamps and Pistons

### ISSUE THREAD

**Issue by VampireMonkey** [gnembon/fabric-carpet#436]
Having Comparators be able to Detect whether a Redstone Lamp is On or Off and Pistons being extended or not would be super useful and would fit well into carpet mod.

**Comment by bencrazyalchemist** [comment]
![image](https://user-images.githubusercontent.com/36512467/92207446-d5337300-ee4e-11ea-87e4-8e6abe84b22f.png)
hmm... interesting idea but i kinda feel like it is too much of a modification, and doesn't really open any new doors or fix major annoyances.

**Comment by gnembon** [comment]
yeah, not sure you need to have a block to detect that at all. Valid idea, but I suggest a pass
