### ISSUE TITLE
Suggestion: Ability to query and modify an entity's air level

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#437]
As of Carpet mod 1.4.0 for Minecraft 1.16.1 (and by extension Carpet mod 1.4.9 for Minecraft 1.16.2 due to relevant code not being touched), there is no way to query or modify an entity's air level via the Scarpet entity API.

I would like if there were two new functions `query(e, 'air')` and `modify(e, `air`, number)` that directly affected an entity's air level. If an entity's air level is set to zero every game tick, then the entity will take drowning damage even if the entity can normally breathe in air, while if an entity's air level is set to non-zero values every game tick, then the entity will not take drowning damage.

**Comment by gnembon** [comment]
good idea
