### ISSUE TITLE
[Bug] __onclose() is triggered after carpet bots are dead

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#442]
It means I cant make a scarpet app to reload them.

EDIT: At least, not easily.

**Comment by gnembon** [comment]
explain

**Comment by Ghoulboy78** [comment]
Basically, I had a script which was along the lines of:
```
__on_close()->(
    botmap={};
    bots=filter(entity_selector('@a'),_~'player_type'=='fake');
    for(bots,
        put(botmap,_,{
            'x'->_~'x',
            'y'->_~'y',
            'z'->_~'z'
        })
    );
    write_file('bots','nbt',botmap)//and this is what I was asking u about earlier with parse_nbt(), cos i thought I needed to to parse_nbt here
);
```

But when I went and saw the .nbt file, it had 0 entries. which means that the Alex bot that I had spawned in had despawned before that function ran.

**Comment by Ghoulboy78** [comment]
And even when I did a hackfix with __on_tick(), it still didnt work, cos that also gets called after the bots are dead.

**Comment by Ghoulboy78** [comment]
so Instead I had to add a command which did it for me, which was annoying cos then it wasnt automatic upon server crash.

**Comment by altrisi** [comment]
Confirmed to happen, but only in Singleplayer (maybe the player list is instantly deleted due to MC thinking there should be noone else, and disconnect events aren't called).

In a server, however, I can get the bots and their positions at `__on_close()`, which is expected since onClose is hooked before forcing the disconnection of all players.

**Comment by altrisi** [comment]
As a workaround, you can save them on every `__on_player_connects()` (if it's a bot) into a list and remove them at `__on_player_disconnects()` if it's a registered bot, and just save the list/map into a file at `__on_close()`. Of course then they will be saved at spawn position only, except if you maybe `schedule()` position updates every some time (or just make a command to do it manually).
Preparing snippet... (this message will be edited then).

**Comment by gnembon** [comment]
so you are hoping that `__on_close()` for apps is called before the system kicks out players when its crashing, amirite?

**Comment by Ghoulboy78** [comment]
Yep

**Comment by Ghoulboy78** [comment]
end question

**Comment by Ghoulboy78** [comment]
Closed now
