### ISSUE TITLE
[Scarpet Suggestion] Multiple log levels for Scarpet logger() function

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#445]
Currently, the `logger()` function in Scarpet always uses the `error` log type, and there is no way to change it.
My suggestion would be an argument to specify the "severity" of the message to be logged, since currently the only way to change this is by using `print()` instead of `logger()`, which would use the regular `info` log type, but would also print the message in chat in most cases, and still `debug`, `warn` and `fatal` are unreachable.

(names based in the vanilla launcher's output log viewer)

**Comment by gnembon** [comment]
good idea

**Comment by Ghoulboy78** [comment]
working on it

**Comment by gnembon** [comment]
cool. Won't be touching it then. 
suggest
logger(msg) or logger(level, msg) where level ~ {'debug', 'warn', 'fatal', 'info', 'error'}

**Comment by Ghoulboy78** [comment]
yeah, thinking smth like that
