### ISSUE TITLE
"Nametags" not showing up for /ai_tracker

### ISSUE THREAD

**Issue by LFGaming** [gnembon/fabric-carpet#447]
When using /ai_tracker on a server with carpet but with a client without carpet, i am not able to see the information that normally is in the nametags, like velocity and villager buddy's etc. It does work however for the /track command, is there something i missed or does it just not work?

**Comment by Ghoulboy78** [comment]
it's not in the nametag, it's shown above the villager as something separate.

**Comment by LFGaming** [comment]
i get that, but i don't know how to call it, and with nametag i thought it would be a good word for describing that thing above the mob.

**Comment by Ghoulboy78** [comment]
and anyways, its meant not to work on non-carpet clients, i believe gnembon is working on it rn.

**Comment by LFGaming** [comment]
ah, okay then. then ill wait, shall i then close this issue?

**Comment by gnembon** [comment]
there was an issue where these information woud't show with fabulous graphics. Change to high, or wait for newer version.
