### ISSUE TITLE
Different behaiour with item frames player command

### ISSUE THREAD

**Issue by mrpopot** [gnembon/fabric-carpet#451]
When using the player command to have a carpet bot both attack and use continuously it behaves slightly differently versus an afk player with held down left+right click buttons. Unsure if this is an actual issue.  https://www.youtube.com/watch?v=m4rNZjyxLms

**Comment by Ghoulboy78** [comment]
maybe it has to do with the other mods you had?

**Comment by mrpopot** [comment]
It behaves the exact same with no other mods beside carpet mod

**Comment by gnembon** [comment]
this doesn't look right. Will take a look at some point

**Comment by altrisi** [comment]
Look taking started at #532 and code started at 083792ae96da09eecab01b241a14b4ca2dd15063

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/083792ae96da09eecab01b241a14b4ca2dd15063 fixed it

**Comment by gnembon** [comment]
@mrpopot did you mean the itemframe item spins faster, or that it you couldn't interact with it in some circumstances? I fixed the inability to interact and that was connected to different treating of itemframes server side and client side, but if that's the rate of interactions, currently the approach is to mimick players clicking quickly

**Comment by mrpopot** [comment]
Appears to be the implementation that is the problem as its not replicating the "hold" style of left+right mouse buttons that you would see in an afk vanilla player(using f3+t reload to hold buttons, or script)

**Comment by gnembon** [comment]
@mrpopot mind taking a look at this one:
https://github.com/gnembon/fabric-carpet/actions/runs/354697915
I can still see differences between remote clients, but should be good now.

**Comment by mrpopot** [comment]
Can confirm at least in instances involving items frames, with above build removes issues. Using attack continuous and use continuous now acting with item frames just like an afk player would. Closed issue.
