### ISSUE TITLE
Bug - Optifine and carpet mod causing slow particle animations

### ISSUE THREAD

**Issue by Red-Rook** [gnembon/fabric-carpet#453]
Something is causing a bug with particle animations between carpet mod and optifine. I have noticed it since updating from 1.16.1 to 1.16.2. When I run MC without carpet mod and with optifine along with all my other mods i do not get the bug, but when i run only carpet and optifine i have the bug. 
Description of the bug;
All particle animations are slow and seem to skip frames, more noticeable when using a potion and observing effect particles and when breaking blocks. Might be hard to notice at first, but if you compare carpet mod + optifine with optifine and other mods without carpet mod you can see the difference. 
I have a intel core i7700HQ and GeForce GTX 1050 
I very much appreciate your mod and am a huge fan of your farms and vids, I hope I can help get this bug resolved for myself and other players. All mods are the latest versions as of this post.

**Comment by gnembon** [comment]
Well, got fixed in this one https://github.com/gnembon/fabric-carpet/commit/137a87298c518246c7564faffde1d4930130a2c8

Will leave this one so no new ones are created and close when released 1.4.10
