### ISSUE TITLE
FlippinCactus doesn't work for rails?

### ISSUE THREAD

**Issue by KrisCris** [gnembon/fabric-carpet#454]
I have seen some people use it in videos but I can't do it in my game.

**Comment by KrisCris** [comment]
minecraft 1.16.2 with the latest version of carpet.

**Comment by KrisCris** [comment]
(powered rail)

**Comment by BisUmTo** [comment]
Bug confirmed for me too
![1ec123fa80e7058a3809a946566a91fa](https://user-images.githubusercontent.com/31419791/92414214-90138780-f153-11ea-8533-0f7f624ef600.gif)

**Comment by gnembon** [comment]
must have been some unlucky rename in the mappings, so it went unnoticed

**Comment by KrisCris** [comment]
Btw, I can't flip hoppers which initially pointing down, is that intended?
