### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by VickScarlet** [gnembon/fabric-carpet#456]
Minecraft Version: `1.16.2`
Carpet Version: `1.4.9`
this is crash report [https://paste.ubuntu.com/p/M6Gn2SVZBV/](https://paste.ubuntu.com/p/M6Gn2SVZBV/)

**Comment by James103** [comment]
Are you able to reproduce this in MC 1.16.3-RC1 and Carpet version 1.4.10? If so, can you please post the corresponding logs here?

**Comment by VickScarlet** [comment]
It is on playing the server crashes suddenly, maybe reproduce it not easy, I will try it.

**Comment by gnembon** [comment]
Have seen that in the past, but wasn't easy to reproduce. Easy to prevent, but I would want to be able to fix the logic rather than patch the NPE.

**Comment by gnembon** [comment]
So any detail is welcome
 - any specific moment it crashes (start of the server), or just randomly
 - I assume spawn tracking must be on
 - is it for specific mob, what are the conditions of the area (any specific mobs not spawning etc.)

**Comment by VickScarlet** [comment]
server is up 3 days, I think it is randomly.
I think this seed maybe useful `level-seed=32932572289994442`.
when before crash, only my friend in game, sayed he find the parrot, then server crash.

**Comment by altrisi** [comment]
Could reproduce it in the given seed and given position (x=-2474.67, y=68.25, z=377.22), while in a tickwarp to make it occur sooner (to make it even faster, have a repeating command block running /kill @e[type=!player] to free the mobcaps).
May it be related to ocelots, since they spawn with the hostile conditions in jungles (the area is a jungle)?

**Comment by altrisi** [comment]
It seems to be directly related to Ocelots!
Testing in a superflat world, jungle biome, y>63, daytime (only ocelots spawn because of full passive mobcap), instant crash after starting spawn tracking.
Preset: `minecraft:bedrock,62*minecraft:dirt,minecraft:grass_block;minecraft:jungle`

**Comment by James103** [comment]
Is it just related to Ocelots or does the crash also affect cats naturally spawning in villages?

**Comment by gnembon** [comment]
but noone was doing `/spawn tracking start`?

**Comment by altrisi** [comment]
@gnembon Yes, the crash happens after starting the /spawn tracking (instantly in the flat world).
@James103 No, it doesn't happen with village cats, just tested.

**Comment by James103** [comment]
Can reproduce in Carpet mod 1.4.0 and MC 1.16.1, so either a regression or the bug has been there for more than a few weeks as of now. [Log and crash report (version info included)](https://gist.github.com/James103/f2b26336b9031983731c436e4926784e)

**Comment by altrisi** [comment]
Relates to (is duplicated by) #399 and #402

**Comment by gnembon** [comment]
Ok, that explains it and I know exactly what is going on. Good bug tracking skills, @altrisi
