### ISSUE TITLE
[Suggestion] Ability to set hopper/hopper minecart speed

### ISSUE THREAD

**Issue by God-ly** [gnembon/fabric-carpet#457]
/carpet hopperSpeed <int> and /carpet hopperMinecartSpeed <int> will specify how quickly hoppers and hopper minecarts can grab items from other containers. <int> can go from 1 to 20. For example, /carpet hopperSpeed 8 and /carpet hopperMinecartSpeed 1 is the default. This setting functions on the same mechanic and can override /carpet hopperMinecart8gtCooldown <boolean>.

**Comment by gnembon** [comment]
not sure why this would be necessary - It not like piston push limit that faster hoppers enable something new and unique.

**Comment by God-ly** [comment]
- Allows users to focus less on the item collection mechanism and more on the farm, while not making the item collection mechanism obsolete like with hopperCounters.
- Makes item collection and item distribution systems more efficient and more compact.
- Less laggy due to items not having to flow around a gigantic sorting system of an item-heavy farm.
- There is a carpet gamerule called hopperMinecarg8gtCooldown, which makes hopper minecarts act like hoppers. What if we did the opposite and made hoppers act like hopper minecarts? What if we did that and then added more flexibility with the gamerule?
- Allows new possibilities in map making, especially to do with timing. For example, you only need one stack of items to measure a minute inside a hopper clock and can make more specific time measurements like 12.55s (use 251 items) without any additional redstone.
- Big quality-of-life addition that many want and virtually all would appreciate.
Could go in carpet-extra if you feel that this is not a unique enough change, but is quite a useful feature to have.

**Comment by God-ly** [comment]
Also, how do you set the right crafting recipe in autoCraftingDroppers?

**Comment by Ghoulboy78** [comment]
see his vid

**Comment by altrisi** [comment]
Relates to gnembon/carpet-extra#74 and gnembon/carpet-extra#85

**Comment by God-ly** [comment]
Yeah, but Gnembon, are you planning to implement this into carpet?

**Comment by Ghoulboy78** [comment]
A lot of the fun in the challenge to build a farm is the challenge of building a storage system that can cope with the output

**Comment by susanshopper** [comment]
Well, you can set the cool down of the hoppers in pure vanilla by using the data command to modify the cool down. You can even speed up the hopper cool down even without using any commands, by powering and depowering the hopper every other game tick.

**Comment by God-ly** [comment]
How do you do the commands thing, using /setblock or /give?

**Comment by Ghoulboy78** [comment]
for what, the hopper minecart or the hopper?

**Comment by Ghoulboy78** [comment]
hopper miecart idk, but for the hopper, as susanhopper said, just power and depower evry gt

**Comment by susanshopper** [comment]
Just use /data on the hopper block.

**Comment by God-ly** [comment]
What's the data field name for hoppers to get them to transfer one item per tick? (Idc about hopper minecarts)
/data merge block ~ ~ ~ {(What?)}

**Comment by James103** [comment]
Run `data merge block ~ ~ ~ {TransferCooldown:0}` every time you want to force the hopper to transfer an item. To get a hopper to transfer 1 item per tick, run the above command repeatedly. 
Run `data merge block ~ ~ ~ {TransferCooldown:X}` to pause a hopper's item transfer for X ticks.

**Comment by God-ly** [comment]
oof, putting it on a repeating command block is going to be very laggy, there's no way to have it stay at 0 without resetting it every time?

**Comment by susanshopper** [comment]
If you are worried about lag, then how about a carpet rule which says optimizedCommandBlocks?

**Comment by gnembon** [comment]
I believe one of the extensions have that already, but I don't see a strong reason to have that in carpet.
