### ISSUE TITLE
[Suggestion] Rule to allow attempts to place fire on air

### ISSUE THREAD

**Issue by buildartifacts** [gnembon/fabric-carpet#461]
I'm not sure whether this would be better in extras or normal.
If it is possible, it would be a nice feature to be able to be able to bring back the usage of flint and steels/fire charges anywhere. Since 1.13, there isn't anything that behaves exactly how fire did with block updates. It would be nice to be able to reliably trigger BUDs/observers without any unwanted side effects (for example, placing a block can cause problems in flying machines).

**Comment by gnembon** [comment]
hmm, but that could easily be done with scarpet as an app, right?

**Comment by Ghoulboy78** [comment]
```
__on_player_right_clicks_block(player, item_tuple, hand, block, face, hitvec) ->(
    pos=pos(pos_offset(face))
    if(face!='up' && ['fire_charge','flint_and_steel']~item_tuple:0 && block(pos)=='air',
        set(pos,'fire');schedule(0, _()->set(pos,'air'))
    )
)
```

I think this is good

**Comment by susanshopper** [comment]
Just like you do not need a carpet rule for ender pearls loading chunks by themselves, you do not need a carpet rule for placing fire in air. Just use scarpet.

**Comment by gnembon** [comment]
yep
