### ISSUE TITLE
Hopper counters "/counter <color?>" command, does not work on client when logged into server.

### ISSUE THREAD

**Issue by Darth-Novii** [gnembon/fabric-carpet#470]
Counter <color?> command does nothing. Outputs nothing into chat or otherwise when entered from client. When entered from server window it displays the intended results.

**Comment by Darth-Novii** [comment]
Rrunning the 1.16.2 version for other reasons.

**Comment by gnembon** [comment]
since that feature modifies behaviour of hoppers is disabled by default.
Use `/carpet hopperCounters true` or `/carpet setDefault hopperCounters true` to enable it

**Comment by Darth-Novii** [comment]
"/carpet hopperCounters" was set to "true" at the time this issue was experienced.

**Comment by Darth-Novii** [comment]
Again, it leaves no error like it does when the command is disabled. It returns nothing at all to chat. I can post screen shots if needed.
