### ISSUE TITLE
/c command not working

### ISSUE THREAD

**Issue by LDH23M** [gnembon/fabric-carpet#475]
I don't know if I done something wrong but on 1.4.11 my /c and /s commands is not working and it used to in the earlier version for minecraft 1.13

**Comment by James103** [comment]
`commandCameraMode` has been removed. For a workaround, use `F3+F4` or `F3+N` for a vanilla way, or download https://github.com/gnembon/scarpet/blob/master/programs/survival/cam.sc and add it to the `scripts` folder of whatever worlds you want to use it on.

**Comment by Ghoulboy78** [comment]
You'd think the memo would've gotten round by now...

**Comment by gnembon** [comment]
/c  and /s were the workaround. F3-N and F3F4 is the Mojang solution.
