### ISSUE TITLE
Shulkers can spawn on redstone components

### ISSUE THREAD

**Issue by Xendergo** [gnembon/fabric-carpet#476]
I haven't noticed this happen on repeaters though, so I assume it has to do with the redstone not having a collision box?

I've also noticed them spawning in 1 high places where they wouldn't be able to open their shell, which I assume shouldn't happen given this quote on the shulker's wiki page

>  However, if the block the shulker occupies becomes something other than air or the shulker finds itself not adjacent to any solid block, **or the shell cannot open**, it attempts to teleport

**Comment by gnembon** [comment]
Shulkers and a few other mobs are meant to spawn in different conditions than other mobs - I haven't come up with it - its Mojang.
