### ISSUE TITLE
[Suggestion] Rule allowing for a new witch farm.

### ISSUE THREAD

**Issue by RamsaKd** [gnembon/fabric-carpet#477]
Add a feature that allows for more expandable witch hut that is also more expandable by technical means than the current which hut based farms. Maybe something like a wither rose that allows only witches to spawn near them or something like a iron farm where certain conditions increase witch spawning. This could be the items in witch huts like if a crafting table and a cauldron next to each other with a flower pot with a mushroom in it with different sky light levels on either side of it similar to how old iron farm doors worked. Just an idea thanks for reading it.

**Comment by gnembon** [comment]
You can always make a bounding box of a witch hut larger just by manipulating of its dimensions in nbt of that chunk. Not sure why you need a mod to do that.
