### ISSUE TITLE
Your thoughts are too deep

### ISSUE THREAD

**Issue by skrrtskrrtman** [gnembon/fabric-carpet#48]
When running the script I `/script run if (query(player(), 'holds') == epic, print('epic'));` the cryptic error "your thoughts are too deep" is shown what is that error and what does it mean?

**Comment by gnembon** [comment]
First of all, 
player ~ 'holds'
returns a triple, so a list of l(item, count, nbt), and epic in this case is undefined, so '0'.
You would probably want to use 
get( (player() ~ 'holds'), 0) == 'diamond_pickaxe' 
which is equivalent to:
get( query(player(), 'holds'), 0) == 'diamond_pickaxe' 

Second of all - that bug has already been fixed and will be out next update.

**Comment by gnembon** [comment]
should be fixed. Check versions 1.14.4-pre5+
