### ISSUE TITLE
[Suggestion] Carpet rule for switching TNT duplication. 

### ISSUE THREAD

**Issue by susanshopper** [gnembon/fabric-carpet#480]
This carpet rule is a switch for TNT duplication. This carpet rule is called “TNTduplicationswitch”. There are 3 options. The 3 options are: “1.12”, “1.13”, and “fixed”. The “1.12” option brings back 1.12 TNT duping, in which rail blocks can be used to update TNT for duplication, even though the coral fan option is also available in this setting. The “1.13” option is the default setting, which is the current TNT duping that uses coral fans to duplicate TNT, but rails cannot be used. The “Fixed” option removes all types of TNT duplication whatsoever.

**Comment by Ghoulboy78** [comment]
I get the removing TNT duping alltogether, but why 1.12 mechanics ...

**Comment by susanshopper** [comment]
Minecraft servers that are upgrading from 1.12-1.15 sometimes need to use their 1.12 dupers until they get the coral fans. Also, there are Youtubers that want to demonstrate how the 1.12 duper’s worked and the 1.13 dupers in the same video, but they do not want to switch versions at the middle of the video. There were 11 TNT duper modules that can dupe only 10 now after 1.13. But, increasing the piston push limit might break some contraptions, so this rule is useful.

**Comment by Ghoulboy78** [comment]
#StopLazy

**Comment by susanshopper** [comment]
Youtubers do not want to switch versions at the middle of the video for a good reason. Switching versions might waste some time.

**Comment by Ghoulboy78** [comment]
And that's why we have splicing. Videos are edited for a reason.

**Comment by altrisi** [comment]
Anyway if you want to disable TNT duping at all, you can use [Carpet-TIS-Addition](https://github.com/TISUnion/Carpet-TIS-Addition)'s [`tntDupingFix`](https://github.com/TISUnion/Carpet-TIS-Addition#tntDupingFix) rule.

I don't really see a reason to add the 1.12 way back, would have (almost?) no uses, and would definitely not be simple to implement considering their uses.
