### ISSUE TITLE
Error in wiki documentation "Home" page: "The playlist does not exist."

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#487]
As seen in the title, the link to view the playlist from the Home page of the wiki returns a 404 error "The playlist does not exist". 

[Here is the offending wiki link](https://github.com/gnembon/fabric-carpet/wiki#a-small-youtube-playlist-showcasing-the-capabilities-of-scarpet) and [here is the offending hyperlink](https://www.youtube.com/playlist?list=PL-XC9-ChVmOoY_Qaub1YPhQcrJMRbjOqg).

**Comment by gnembon** [comment]
well, I don't remember adding and its wiki, so feel free to delete it, or point to my modding playlist from the channel

**Comment by James103** [comment]
Thank you for letting me know. I fixed the link in both languages of the Home page.
