### ISSUE TITLE
[Suggestion] Villager Bartering

### ISSUE THREAD

**Issue by VampireMonkey** [gnembon/fabric-carpet#488]
Piglin Bartering can be fully automated, i was thinking that the last trade selected trade in the villager's trading screen should allow them to pickup items for that trade and drop their selling item.

So dropping a stack of potatoes at a farmer that has a potato trade you have selected will make them pickup the potatoes and drop the emeralds like if they were a piglin, this would allow fully automatic villager trading like piglin bartering.

**Comment by altrisi** [comment]
Similar to Carpet 1.12's `villagerAutoTrader` rule (at [EntityVillager.java](https://github.com/gnembon/carpetmod112/blob/staging/patches/net/minecraft/entity/passive/EntityVillager.java.patch) | [desc](https://github.com/gnembon/carpetmod112/blob/419d14d6d5553828ac354bc89e6b05ceab73bf92/carpetmodSrc/carpet/CarpetSettings.java#L883)), which hasn't been ported (at least yet), although it didn't prefer the last trade selected, and with the new villager changes it may need a lot of reworking.

**Comment by Ghoulboy78** [comment]
I infact made a scarpet app with that funcionality, I will link if I can find it

**Comment by Ghoulboy78** [comment]
https://github.com/Ghoulboy78/scripts/blob/master/Finished%20ideas/villagerAutoTrader.sc

This uses zombie villagers to add some challenge and not interfere with existing system. It took some brainstorming with me and gnembon and is probably rather outdated by now.

**Comment by Ghoulboy78** [comment]
Actually Its broken rn, I will post link when I fix it, unless u want rn

**Comment by Ghoulboy78** [comment]
@VampireMonkey here, the app works now. You can close the issue. Myself and gnembon decided to do a script, cos in Java doing it is an absolute mess.

**Comment by gnembon** [comment]
dunzo I guess. That's what scarpet is for. 

Did you PR that to scarpet appstore?

**Comment by Ghoulboy78** [comment]
o ye i ddint
