### ISSUE TITLE
Server crash when fake players go into a portal

### ISSUE THREAD

**Issue by Gamepiaynmo** [gnembon/fabric-carpet#49]
Error message: java.lang.IllegalStateException: Removing entity while ticking!
[crash-2019-07-07_13.22.30-server.txt](https://github.com/gnembon/fabric-carpet/files/3365301/crash-2019-07-07_13.22.30-server.txt)
It is a 1.14.3 server with the latest version of fabric-carpet.

**Comment by gnembon** [comment]
Thanks for pointing that out. Should be fixed next update.

**Comment by gnembon** [comment]
should be fixed as of 1.14.4-pre5+
