### ISSUE TITLE
question: is hostile detection really based on feet not eyes?

### ISSUE THREAD

**Issue by end-user** [gnembon/fabric-carpet#494]
I was looking at the hostile detection in the ai tracker and noticed that the detection sphere is based on the feet block, not the head height.  Is that correct?  That puts the sphere slightly smaller at eye level, yet eye angle is tracked for most "attention" tasks.

**Comment by Ghoulboy78** [comment]
ye, but the feet thing is for all entities, so hostiles jsut inherit from upper classes.

**Comment by Ghoulboy78** [comment]
@end-user u can close now
