### ISSUE TITLE
[Suggestion] Chains pulling blocks (like two-sided slime) 

### ISSUE THREAD

**Issue by 1nVitr0** [gnembon/fabric-carpet#495]
Since horizontal changes have been introduced, it would be great if chains would be able to pull blocks.

They should behave just like any other block when being pushed by a piston. But when they are pulled by a piston / slime block / honey block / another chain, they should be able to pull blocks on the direction they are facing.

I think it would fit perfectly into vanilla Minecraft and be tremendously useful.

Not exactly sure what should happen when they are moved sideways. If modeled like a two-sided slime block, they should also move blocks attached to the ends of the chain. **Even better would be, if the would just pull / push blocks, not move them sideways**. This would make it possible to create fully retractable chains with just 2 pistons by pushing the first chain to the side.

**Comment by Ghoulboy78** [comment]
Would be hard, and may be better suited for carpet-extra maybe?

**Comment by gnembon** [comment]
good idea - should not be a big deal since MBE already define side-stickiness. For this reason it might be hard to implement it on carpet extra, since carpet core is already supporting this kind of behaviour.
