### ISSUE TITLE
Pistons Redirect Redstone

### ISSUE THREAD

**Issue by awesomecoder3000** [gnembon/fabric-carpet#500]
I think that it would be nice if there was a feature that would allow players to redirect redstone signals into pistons.
(ex: when player does `/carpet Pistons_Redirect true`, then all redstone dust redirects into pistons next to them)

**Comment by altrisi** [comment]
Relates to gnembon/carpet-extra#133

**Comment by awesomecoder3000** [comment]
I know, and I could not get the script to work.

**Comment by altrisi** [comment]
Fixed in gnembon/carpet-extra@53095872dbd3d43950ffc8a6109c1f8ea011e0f6.
You can wait for the next Carpet extra release or get the latest [dev build](https://github.com/gnembon/carpet-extra/actions?query=workflow%3A%22Development+Builds%22).
(you can probably close this issue).

**Comment by awesomecoder3000** [comment]
Thanks!
