### ISSUE TITLE
Suggestion: Let "Player" have a follow command

### ISSUE THREAD

**Issue by awesomecoder3000** [gnembon/fabric-carpet#501]
I think it would be helpful to have a follow command for "Player", like `/player Alex follow Steve` then " Then, Alex will follow Steve

**Comment by Ghoulboy78** [comment]
I think that would be better as a script maybe?

**Comment by awesomecoder3000** [comment]
Maybe, should I instead put this suggestion on the Scarpet repository?

**Comment by Ghoulboy78** [comment]
Then maybe gnembon should decide

**Comment by awesomecoder3000** [comment]
I agree

**Comment by gnembon** [comment]
problem is that is not as simple as tp one to another. You are expecting an animal level of pathfinding applied to a player. Possible, but that would cause more internal malarchy then the problems its solving.
