### ISSUE TITLE
[Suggestion] Allow scarpet to manipulate players?

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#506]
I think it may be potentially very good if scarpet could do such things as make a player walk, or jump or place a block.
This wouldn't be too hard to pull off, especially if added to the `modify()` function.

On the other hand this could be very buggy on the client and not be worth it, and perhaps be out of the scope of a scripting language?

**Comment by gnembon** [comment]
well you can test how it works right now using player commands and try them on yourself. In most cases it just doesn't look good, but works. Adding just a portion of controls would honestly look weird / unfinished, but you can always `run('player .. ')`, right?

**Comment by Ghoulboy78** [comment]
ye, I thought as much. Ill see if it's worth it and then update

**Comment by Ghoulboy78** [comment]
nah it aint
