### ISSUE TITLE
[Bug] Player Bots not propelled upwards by slime (also non-related boat issue)

### ISSUE THREAD

**Issue by HunsingerTheMatist** [gnembon/fabric-carpet#507]
As stated in the title, players that are spawned in (bots) do not get propelled upwards (or sideways) by slime pushed into them. Instead, they glitch into the slime block. If the bot is in a minecart, this issue does not occur. To replicate, spawn a bot above (or to the side of) a slime block. Then activate a piston to push the slime into the bot.

While looking into this bug, I also noticed that bots sitting in boats behave oddly. The boat is not affected by gravity while the bot is in it. Once the bot leaves the boat, though, both begin falling. To replicate, spawn a boat in mid-air supported by one block. Spawn a bot in and have them sit in the boat. Then break the block that is supporting the boat.

Minecraft version used: 1.16.3
Carpet version used: fabric-carpet-1.16.3-1.4.11+v200910

If any additional information is needed, I will try my best to supply it. Thanks. :)

![2020-10-24_12 50 40](https://user-images.githubusercontent.com/57552074/97088129-d1c19a00-15fc-11eb-9d0a-322aa718d938.png)
![2020-10-24_13 16 24](https://user-images.githubusercontent.com/57552074/97088136-df771f80-15fc-11eb-9cd8-db265627e8eb.png)

**Comment by gnembon** [comment]
k, problem is that if the boat is controlled server side - the boat movement on slimeblocks looks like with any other entity mounted, but different than for players. Since fake players are server side creatures, I am fine with leaving them with a proper server side behaviour. Other than that should be all fixed.
