### ISSUE TITLE
FlippinCactus doesn't work with chains

### ISSUE THREAD

**Issue by fezboy** [gnembon/fabric-carpet#509]
Expected behavior: when right clicked with cactus, chains should toggle between X, Y, and Z axes.

Observed behavior: chain doesn't change on right click with cactus

This would be great to have, especially with the addition of chainStone!

**Comment by Ghoulboy78** [comment]
Cactus only flips, not rotates. So it will go from facing north to facing south, facing west to facing east, and facing up to facing down (and vice versa). It doesn't rotate. That can be implemented as a scarpet app if you want, which actually may be rather cool. Actually @gnembon I could just replace it with a scarpet app couldn't I?

**Comment by fezboy** [comment]
Cactus rotates hoppers and repeaters, so i figured that rotating chains would fit in also. It's up to yall though.

Here's a demo of what i implemented in the pull request, for context:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31973884/97152493-392b3700-172e-11eb-926c-304a5003af89.gif)

**Comment by gnembon** [comment]
yeah - makes sense. cactus is like a debug stick that only does selected things that make sense. Besides, cactus was way earlier. Makes sense to work on chains since they only have 3 states
