### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Conando025** [gnembon/fabric-carpet#51]
maybe I'm really stupid, but iI have no ides howe to install it. So my wish for the future would be, that ther is an instruction how to install scarpet (and one that updates when the method changes)

**Comment by bnjw5jhyxn** [comment]
> maybe I'm really stupid, but iI have no ides howe to install it. So my wish for the future would be, that ther is an instruction how to install scarpet (and one that updates when the method changes)

The [fabric download page](https://www.fabricmc.net/use/) has a link to an installation guide that covers both fabric and mods that use it (like this mod). You can download the mod [here](https://github.com/gnembon/fabric-carpet/releases).

**Comment by gnembon** [comment]
added note about it in the readme. Consider closed
