### ISSUE TITLE
Set logger's name to Carpet

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#522]
Pass a String with the logger name at:
https://github.com/gnembon/fabric-carpet/blob/9e4e2766879e2c0903e0352e8a001aa0272bad3b/src/main/java/carpet/CarpetSettings.java#L40

Makes "output viewers" show "Carpet" (or any other string) instead of `carpet.CarpetSettings` (class name, `CarpetSettings` depending on output viewer) as the logger name (doesn't change log files, so no need to remove the prefixes in some messages).

Viewers affected by this include the Vanilla launcher output viewer (shown in second column) and some IDEs output viewer (at least it appears in Eclipse).

I was going to [make a PR](https://github.com/gnembon/fabric-carpet/compare/master...altrisi:patch-1), but didn't do it to prevent conflicts (and because just adding a String in a PR seems overkill), since CarpetSettings is one of the most (if not the most) edited files of the repo.

**Comment by gnembon** [comment]
haven't touched that file since... chain stones. Good idea -> make a PR ;)
