### ISSUE TITLE
Rule changes always call Carpet's SettingsManager even from extensions

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#525]
https://github.com/gnembon/fabric-carpet/blob/45506d22f7ae2451779eda7a44a55182f2c1bc9b/src/main/java/carpet/settings/ParsedRule.java#L159

This is currently blocking namespacing in my Scarpet `__on_carpet_rule_change()` event for #519.

Will probably fix it soon.

**Comment by altrisi** [comment]
Should I also fix rule changing being locked if main Carpet SettingsManager is locked?

It is caused by basically the same.

**Comment by altrisi** [comment]
Both will be fixed.

**Comment by gnembon** [comment]
But that's good as it is, right? this way you subscribe in one place for all rules. Namespace can be pulled from each rule individually as you have added the manager reference to each rule.

**Comment by altrisi** [comment]
Actually this technically fixes an issue with the example extension where it would tell the player is cheating (editing carpet's rules instead of example mod's rules) when changing rules from their custom SettingsManager. Completely unrelated? Yes.
