### ISSUE TITLE
[Scarpet bug?] Player drop events are triggered when player doesn't actually drop anything

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#527]
When pressing Q/Ctrl+Q without items. Both single and stack. (tested in sp).
May be intended.

**Comment by Ghoulboy78** [comment]
I think its intended cos it still sends a packet to the server, then realises there is nothing to drop. I may be mistaken.

**Comment by gnembon** [comment]
Didn't know about it, but the docs don't say any different as it is:
```
Triggered when the game receives the request from a player to drop one item or full stack from its inventory
```
I thought to update the docs, but the docs are right.

**Comment by altrisi** [comment]
That does make sense, yeah, but since there is not many real feedback from it (it just tells who did that), I thought that at least having it only trigger if it is really dropping something would make it more useful.
Not because I really use it, I just found it when testing `event_test` for Scarpet rules and thought it would be nice to report it.

**Comment by gnembon** [comment]
yeah, this is very much so intended - gives much more abilities for limited inputs that server gets from clients.
