### ISSUE TITLE
Add per player mob spawns option

### ISSUE THREAD

**Issue by filips123** [gnembon/fabric-carpet#528]
In vanilla multiplayer Minecraft, although mobcap is dependent on the number of players, spawning will still be done per server. This means that some players/locations will take a very big percentage of the mobcap, while others almost won't have any mobs, making mob farms very unreliable.

PaperMC solved this by introducing [`per-player-mob-spawns`](https://paper.readthedocs.io/en/latest/server/configuration.html#per-player-mob-spawns) which will make that mob spawning will be counted per-player ([more detailed explanation by PaperMC developer on Reddit](https://www.reddit.com/r/admincraft/comments/entadj/do_you_recommend_perplayermobspawns_or_not/fe5hnbj/), [PaperMC patch source code that implements this](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0376-implement-optional-per-player-mob-spawns.patch)).

Is it possible to implement something like this in Carpet (or carpet-extra)? This would be very helpful for people who use Fabric on their server and need mods, as I wasn't able to find any updated existing mod with similar functionality.

**Comment by Ghoulboy78** [comment]
But that messes with how mobcaps is itself calculated, which unlike most people think is not by the amount of players online but actually the number of chunks loaded.

**Comment by gnembon** [comment]
you can't find a mod with that for a reason - it messes up with fundamentals of mob spawning. If you want that feature from paper - you probably need to run it on paper.
