### ISSUE TITLE
Can add event handlers with __on_. Cannot dishandle. Hwy?

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#530]
pls add event_handler() to add, and remove event handlers.

kthxbai

**Comment by altrisi** [comment]
Relates to #244

**Comment by gnembon** [comment]
hmm, could be all added at the same time. My main complain is that if I made so that you can attach and detach player events, then all built-in apps can be loaded by default with carpet settings and don't cause any checks unless triggered, if you know what I mean.

**Comment by gnembon** [comment]
done

**Comment by altrisi** [comment]
You forgot to close #244 too
