### ISSUE TITLE
[Scarpet Suggestion] Static variables

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#534]
Didn't really check how difficult this would be to add, but basically having the ability to create "static" global variables (something like `static_` instead of `global_`), that are shared among all instances of an app with the `player` scope.

~Maybe also "static" events/funcs, that basically can accept events from the global scope and only have access to those "static" variables (this one would probably be even worse, but just throwing it here). A method to accessing instance specific functions from there would probably be even worse to add, but may be useful to call all instances to update on the given change.~

They would have a few use cases, probably, but I can't really remember any of them right now. May update if I remember.

_NOTE:_ The `system_variable` functions exist, yes, but it's not quite the same, since those are shared among all apps, not only the current one. Also, the main scope of this issue are the variables, ~the events/funcs are there only as an extra suggestion that I think has less uses.~

**Comment by Ghoulboy78** [comment]
Hmm, wouldn't it be easier to just have a global var in a global app and deal with the player-specific stuff using maps? Im not sure, just suggesting.

**Comment by altrisi** [comment]
I mean, yes, by for example using the `system_variable`s, but idk, it's either making things available for every app, which could clash in the rare occurrence of 2 apps having using the same name, and having two apps for the events is just, well, having two apps for the functions of one, and you still have to deal with workarounding a communication method between both to call each other.

To use in an API I would definitely use system variables and register things in there instead, but just to communicate from an app to itself (at least variables), idk, I feel like there should be a native way from within the app's scope. Just throwing the suggestion.

**Comment by gnembon** [comment]
I was debating that at first but settled on player and global scope apps. If you understand what scope does, its easy to grasp that. For
 - player scope: this means no static_ variables only global_'s
 - global scope: its like global_ variables are player keyed maps of statics
We would then only need one type of app, but there are several issues with it
 - what if player calls some function as a result of its action that handles on_tick event - that event doesn't know that that player needs to be 'ticked'.
 - the content of a variable will change based on a player (threadlocal), while sharing other resources. This may be confusing. Therefore I think stating explicitly app scope in '__config()' (which will mean more in the future, as it does right now), makes more sense as still allow for both approaches but sets better expectations with the programmer.

Having said that 'static_' variables can be added while keeping previous functionality, For 'global scope' apps it woudn't not make difference if its static or global var, and for player scoped apps you would get the desired effect. That would then make more sense to work with non-player events in player based apps (on_tick), but would be hella confusing. Another consideration (small one) would be performance - another variable store to check every time you use a variable.

That would probably needed a thick section of readme to explain all of that, but may be worth it.

Thoughts?

**Comment by gnembon** [comment]
What @Ghoulboy78 refers to is the following scheme
```
__config() -> {'scope' -> 'global'};

global_foo = 5;    // statics
global_bar = {player('Steve') -> 6, player('Alex') -> 7} // globals
__on_player_did_something(p) ->
(
   global_foo; // -> 5;
   global_bar:p  // -> 7, Alex
    baz = 8; // local
)
```

**Comment by gnembon** [comment]
To summarize - the reason why this is a good idea is that it makes sense if the design of the apps was different. Problem is that for the language itself (imagine, minecraft doesn't exist, but scarpet does) that would be hard to explain and confusing in general. Lets stick with what it is right now. The use of system variables for this reason makes sense and would serve as a direct replacement for globally static variables. Apps shouldn't talk through system variables, but through events anyways.
