### ISSUE TITLE
Scarpet language: No -= to complement +=

### ISSUE THREAD

**Issue by Meeni-mc** [gnembon/fabric-carpet#535]
The Scarpet language has the `+=` operator, but it doesn't have `-=`. Should be there for simetry's sake.

It also does not have `++` or `--`. That's not a big deal, but the error message when one does use it is very cryptic (complaining about extraneous `;` in a completely different place).

**Comment by gnembon** [comment]
there will not be a ++ or -- support due to the parser its using. `-=` could be added but would not have intuitive usecase for collections or strings. For numbers you can always do `foo += -5` instead of `foo -= 5`
