### ISSUE TITLE
Wrong behaviour of /perimeterinfo with slabs

### ISSUE THREAD

**Issue by jonathan-matai** [gnembon/fabric-carpet#538]
When placing a bottom slab on a spawnable block the /perimeterinfo command still regards it as a valid spawn (Number 2 in image). In my example /perimeterinfo shows valid spawns for 2 and 4, although only 4 can actually spawn mobs

![image](https://user-images.githubusercontent.com/41783814/98845074-793c2a80-244d-11eb-89c8-a8ec90fa0ba8.png)

**Comment by James103** [comment]
What version of Carpet mod and Minecraft are you using?

**Comment by jonathan-matai** [comment]
I have tested the issue in Carpet Mod 1.4.14 (Minecraft Verison 1.16.4), I will test the issue in the latest version to but since there is nothing mentioned in the patch notes I have little hope

**Comment by gnembon** [comment]
did you try with a mob, like a zombie? Technically a slab is a valid spot, just when you try with a mob, it collides. Nowhere in the code it says that mobs can't spawn on slabs.

That's one reason I don't like slabs, as they make game more checks for you.

**Comment by jonathan-matai** [comment]
Ah ok, I did not know that. I just tried the command without a specific mob type. If i run the command with a mob it works as expected, so I'll close this.

**Comment by jonathan-matai** [comment]
Not an issue, slabs don't stop mobs from spawning, the just don't spawn because they collide with the slab
