### ISSUE TITLE
Suggestion: API function to query and modify player's XP stats

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#539]
Something like:
`query(e, 'xp_level')`: Gets the player's XP level.
`query(e, 'xp_points')`: Gets the player's progress to next XP level (as a fractional number from 0-1)
`query(e, 'score')`: Gets the player's score (a number that's displayed on the death screen).
`modify(e, 'xp_level', number)`: Sets the player's XP level.
`modify(e, 'xp_points', number)`: Sets the player's progress to next XP level (as a fractional number from 0-1)
`modify(e, 'score', number)`: Sets the player's score.

An example use case is to provide an alternative XP system different from the standard XP level formula.

**Comment by Ghoulboy78** [comment]
Dibs

**Comment by gnembon** [comment]
@Ghoulboy78 what about https://github.com/gnembon/fabric-carpet/pull/540/files#r528473979
