### ISSUE TITLE
Extension's rules aren't syncronized with clients

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#546]
Currently, `ServerNetworkHandler` only sends rules from Carpet's `SettingsManager`.
https://github.com/gnembon/fabric-carpet/blob/15239ecb0f92879196ff383c22a5f5e0003db73c/src/main/java/carpet/network/ServerNetworkHandler.java#L80

This basically means that rules from other `SettingsMangers` will never* be received by clients from remote servers.

There are various ways to solve this:
- Send all rules to clients by appending them with the current `withRule` method and then loop through all `SettingsManager` instances in the client (probably performance intensive in the client if extensions have many rules/many custom managers, but would keep compatibility)
- Change the protocol so it also sends the `SettingsManager` `identifier` with each rule (or another way to identify it) and find `SettingsManager` by that identifier in the client. May, however, probably break when connecting old clients/servers (would it?).

Maybe a good way would be to add the latest to the 1.17 branch (if it breaks), since most versions are basically incompatible with the previous. _May_ provide a PR at some point

_* Technically, those are sent in the `updateRuleWithConnectedClients` method, since it is called from any`SettingsManager`, but those aren't properly added in the client since it only checks if that rule exist in Carpet's._

**Comment by Fallen-Breath** [comment]
I'll suggest to keep compatibility. There are people who use client to connect to servers in different minecraft versions / carpet versions by mods or plugins or whatever things. If it's not backwards compatible it will restrict the client carpet version that people can use.

Performance issue should be fine since even rule synchronization is not something that will happen quite often.

**Comment by Fallen-Breath** [comment]
Ah wait, why would extension have its own SettingsManager. Extension only need to let carpet's setttingManager to parse its own setting class, which will add its all ruls into carpet's setting manager. For example [this](https://github.com/gnembon/carpet-extra/blob/c402a39ecf208311ba243f7a5f6778950c5d2055/src/main/java/carpetextra/CarpetExtraServer.java#L34-L35) is how carpet extra does:

```java
// let's /carpet handle our few simple settings
CarpetServer.settingsManager.parseSettingsClass(CarpetExtraSettings.class);
```

It's also the same in [fabric-carpet-extension-example-mod](https://github.com/gnembon/fabric-carpet-extension-example-mod/blob/32f25e50202826d44334136e958fb8864c5ac042/src/main/java/carpet_extension/ExampleExtension.java#L26-L27)

If the extension follow the way like the 2 examples above there's no issue of syncing extensions rules to the client

**Comment by altrisi** [comment]
Yeah, but for example Skyblock ([here](https://github.com/skyrising/skyblock/blob/501c19706dd338143e6e34638e4978e9ca2b698a/src/main/java/skyblock/SkyBlockExtension.java#L36)) (and other extensions, it is documented) registers its own SettingsManager, that basically never sees the client.

Code in the CarpetExtension interface:
https://github.com/gnembon/fabric-carpet/blob/f787910c706f6f85d2ec23a196776ec63cdd3d39/src/main/java/carpet/CarpetExtension.java#L43-L47

It's basically a way to get a custom command managed just like Carpet, and according to the docs, should be managed just like Carpet.

Also in the example mod, see the next 2 lines from your link.

**Comment by Fallen-Breath** [comment]
Ah ye, that's a thing

**Comment by gnembon** [comment]
Yeah, its for other extensions using their own command trees. Merged btw

**Comment by altrisi** [comment]
@gnembon This issue wasn't fixed by my PR, the PR included allowing client-side rules (like nofog that can work without carpet in server) to work for other `SettingsManager` instances, but it didn't resolve this issue, since it didn't touch the protocol at all.

This is still an issue.

**Comment by altrisi** [comment]
Ok found a way of fixing this without breaking compatibility, will send a PR SoonTM.
