### ISSUE TITLE
chainStone doesn't pull anvil from above/below

### ISSUE THREAD

**Issue by Symon-Cysko** [gnembon/fabric-carpet#549]
Anvils do not currently allow you to pull them from their top or bottom faces.  Tried this with other falling blocks (i.e. sand, gravel, concrete powder) to be sure this wasn't intentional, and they are pulled, and subsequently fell as would be expected, so I assume this may have been an oversight. On a related note, perhaps anvils shouldn't fall when attached from above since the chain is "anchored" to them.

**Comment by altrisi** [comment]
Aren't anvils unmovable?

**Comment by gnembon** [comment]
anvils can be pushed only when they are in motion - its always been like that - Try with slime - won't work either.

**Comment by Symon-Cysko** [comment]
Huh... Can't believe I hadn't realized that before now. Well that's embarrassing. I still think anvils anchored to chains would be interesting though.
