### ISSUE TITLE
Getting warnings while building. Something is not imported right?

### ISSUE THREAD

**Issue by TIVJ-dev** [gnembon/fabric-carpet#55]
Enviroment:
Tested with following JDKs: jdk-12.0.1, jdk1.8.0_151, jdk1.8.0_211

Gradle version:
Gradle 5.4
Build time:   2019-04-16 02:44:16 UTC
Revision:     a4f3f91a30d4e36d82cc7592c4a0726df52aba0d
Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Windows 10 10.0 amd64

Files: Carpet Fabric Mod alpha v19_06_24+ source code, and with `gradle genSources idea` (I use IntelliJ Idea) done.

Issue: When compiling with `gradle build`, I get 13 warnings: https://pastebin.com/c0HANDHp

If I use the fabric-carpet-1.14.4-1.0.0+v190714.jar from build/libs and put it to the mods folder of a fabric server. Log: https://pastebin.com/1vehgS4H

**Comment by gnembon** [comment]
First of all these warning are apparently normal - they are issues with mixin system - not affecting the final product.
Second of all: seems like you are trying to patch 1.14.3 server with 1.14.4 mod:
```
[14:39:54] [main/INFO]: Loading for game Minecraft 1.14.3
[14:39:55] [main/INFO]: [FabricLoader] Loading 2 mods: fabricloader@0.4.8+build.155, carpet@1.14.4
```
That ain't gonna work.

**Comment by TIVJ-dev** [comment]
Yeah. That might havce been the problem. I totally forgot to adjust the version.
