### ISSUE TITLE
1.4.17 Carpet events in /script run __on_ have weird names

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#552]
As you can see, the event names suggested in `/script run __on_` have names of the form `__on_carpet.script.CarpetEventServer$Event$<event number>@<event hash>`, which is different compared to 1.4.12 which has proper human-readable event names, which means they don't work with `/script run`.

Example image:
![image](https://user-images.githubusercontent.com/37945304/99292989-9e42eb80-2807-11eb-8b8d-3ec71accebc7.png)
Modlist (MC 1.16.4):
![image](https://user-images.githubusercontent.com/37945304/99293074-bb77ba00-2807-11eb-8bf5-909cb8062856.png)

**Comment by Ghoulboy78** [comment]
blimey, how didn't I notice that? That is a carpet-only issue.

**Comment by altrisi** [comment]
Can also confirm for latest commit.
May have been introduced by 55643632ca414dbf25ec131d75ac248cbafd3d3d

You can still use them by their human readable name, they just won't be suggested, but they work.

**Comment by gnembon** [comment]
oups
