### ISSUE TITLE
Unable to use ai_tracker commands [20w46a]

### ISSUE THREAD

**Issue by an-accident** [gnembon/fabric-carpet#556]
![2020-11-18_21 21 32](https://user-images.githubusercontent.com/48416874/99584369-292d0d00-29e5-11eb-812c-0ba261da4370.png)

**Comment by altrisi** [comment]
Can you try it in the latest development build? There were recent changes to the ai_tracker app for 1.17 that _may_ (or may not) have fixed it.

https://github.com/gnembon/fabric-carpet/actions/runs/370598388

If it still doesn't work, could you give more context about what you did (what command, what was around, anything you find relevant)?

Thanks!

**Comment by an-accident** [comment]
Issue seems to be resolved with this build. No errors encountered.
