### ISSUE TITLE
[Suggestion] Add /player command to select which hotbar slot to use

### ISSUE THREAD

**Issue by NoahFriendo** [gnembon/fabric-carpet#557]
I was recently trying to figure out why a fake player I summoned would not hold an item I dropped in its hand. I eventually realized it was because I had previously used that account on my server, and I had logged off while having a different hotbar slot selected. It would be nice if there was a command such as `/player <name> select [slot]` so that I could make the player hold the item without having to give them dummy items to fill up some of the slots.

**Comment by gnembon** [comment]
that would only work for fake players, but that's a valid thing to expect.

**Comment by altrisi** [comment]
Actually, it could work with regular players too by sending them a `HeldItemChangeS2CPacket` (yarn).

Never understood why does it exist, but it does.

**Comment by gnembon** [comment]
Yeah, its needed for item pickup for suvival players. Its server who controls that. Then its easy peasy
