### ISSUE TITLE
[Proposal/Discussion] Remove CLIENT category from smoothClientAnimations

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#558]
Since dcb048c986d266c16026d50974be8ca36892762d, `smoothClientAnimations` rule no longer has any effect on the client except from making it run slower when the tickspeed is slower than 20.

That can be considered, of course, a reason to call it a `CLIENT` rule. However, Carpet will consider any rule marked with `CLIENT` as a rule that can be toggled client-side only (that is, without Carpet present in the server), allowing to turn it while not connected to a valid Carpet server and adding the following to the wiki:

> Its a client command so can be issued when connecting to non-carpet servers. In client-server setting it will only affect the executing player, so each player needs to type it separately for the desired effect

(which, now that I'm seeing it, is also incorrect since currently Carpet (client) will prioritise using and changing the rule value of the server, but that's another issue)

Since the tickspeed that Carpet uses can only be set with the `/tick` command, and that is not available when connecting to a carpet-less server, that renders the `smoothClientAnimations` rule with no "client-side only effect".

Thoughts? Should the `CLIENT` category from it be kept or removed?

**Comment by gnembon** [comment]
'technically' tick speed can be changed with other mods, like gamespeed mod, and carpet is notified about it. Technically gamespeed takes care of that, but carpet will only trigger that.
