### ISSUE TITLE
[Proposal][Discussion]Datapack that adds the overlay scripts

### ISSUE THREAD

**Issue by henryozen** [gnembon/fabric-carpet#562]
I like probably many other people that use your Carpet Mod use realms and there is no way to add plugins. Seeing as how the Carpet Mod works is client-side, is there a way to use data packs in place of scripts to make it usable through a realm?

**Comment by gnembon** [comment]
overlay works purely server side and only sends shape information to clients. In many cases client doesn't even have the required information to create these shapes, like client have no information about structures - its just blocks for the client. That's not possible unfortunately.

**Comment by altrisi** [comment]
BTW Carpet is (mostly) server-side, not client-side.
