### ISSUE TITLE
support for inventory slot argument in commands - may need to justify extended inventory support (horses etc.) 

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#564]

**Comment by Ghoulboy78** [comment]
is there rly a InventorySlotArgument.java? isn't it just an int?

**Comment by altrisi** [comment]
Technically yes, it later remaps the slot to an int. But in the command it displays with fancy strings like `hotbar.1`, `inventory.25`, `armor.chest`, `enderchest.12`, `weapon.offhand`, etc for players.

There is also names for containers, like `container.37`, for villagers, like `villager.6`, and then for horses there is `horse.saddle`, `horse.armor` and `horse.chest`.

Yarn name: `ItemSlotArgumentType`.

**Comment by gnembon** [comment]
yes, I want it to return type of entity/block with a valid slot to use with inventory api.
this makes so that all the vanilla containers/inventories supported by it should be supported by `inventory_*` in the API
