### ISSUE TITLE
[Internal] Messenger uses its own Logger

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#567]
Instead of using base `CarpetSettings` logger, `Messenger` gets (and uses) its own logger.

https://github.com/gnembon/fabric-carpet/blob/5a8aad44c2adf8b85473457b9ee10a4617e073c2/src/main/java/carpet/utils/Messenger.java#L32

Not really a big deal, but it's a thing.

BTW why is the global logger in `CarpetSettings` instead of `CarpetServer`? (since it's theoretically the "main class", isn't it?)

**Comment by gnembon** [comment]
¯\_(ツ)_/¯

Reason logger is in CarpetSettings is that in mixins where you typically need to import settings class, you already have it imported. But messenger - no idea why it was this way.

**Comment by altrisi** [comment]
Oh, that makes sense.

**Comment by gnembon** [comment]
Oh, and the reason in Messenger its their own logger is to not depend on carpet at all - you could just use that class wherever. That's why.
