### ISSUE TITLE
Crash when exploring world

### ISSUE THREAD

**Issue by shouxd** [gnembon/fabric-carpet#574]
https://pastebin.com/qgw3qPAY crash file

**Comment by altrisi** [comment]
How do you know it is caused by Carpet and not any other mod?

**Comment by shouxd** [comment]
A kind mod from Fabric discord server explained to me that net.minecraft.server.MinecraftServer.handler$bhp000$modifiedRunLoop. modifiedRunLoop is a method in Carpet

**Comment by gnembon** [comment]
yes, but that is a main server loop - so all crashlogs will have that. I am more concern about the actual function that crashed. Will check if that's carpet responsible for it

**Comment by gnembon** [comment]
method tickChunk on ServerWorld class (calling directly the randing) does not belong to carpet, check probably some other mods.
Also carpet doesn't have any calls to nextInt that could be wrongly bounded
