### ISSUE TITLE
Add the ability to store global user scripts

### ISSUE THREAD

**Issue by vakokako** [gnembon/fabric-carpet#577]
I love scarpet and use it whenever I want to test something in creative. The problem is every script I write ends up in the specific world save folder. 

There are already built-in scripts provided by carpet that you can load from any world. Would be very nice to have a place to store a user-created library of scripts, e.g. in `~/.minecraft/scripts/` folder.

**Comment by altrisi** [comment]
Relates directly to (duplicating/is duplicated by) #416.

Could be done by adding a check for script files present in [`FabricLoader#getConfigDir`](https://github.com/FabricMC/fabric-loader/blob/25c9313571e1c99597705d9ee1d1b3be1cb6e681/src/main/java/net/fabricmc/loader/FabricLoader.java#L150-L163)`/carpet/scripts` at [`CarpetScriptServer#listAvailableModules(true)`](https://github.com/gnembon/fabric-carpet/blob/07dce7bc2e30d196ab2856c6a7f88d62b74335b2/src/main/java/carpet/script/CarpetScriptServer.java#L166). Probably prioritising scripts in world folder against config when loading them (at `#getModule`). That would also allow for global scripts in servers (where the same server path is reused but world is changed).

Also relates slightly to #211.
