### ISSUE TITLE
1.4.19 release for 20w48a has broken link

### ISSUE THREAD

**Issue by fezboy** [gnembon/fabric-carpet#578]
At https://github.com/gnembon/fabric-carpet/releases/tag/v1.4-homebound the link "[download carpet 1.4.19 for 20w48a(1.17)](https://github.com/gnembon/fabric-carpet/releases/download/v1.4-homebound/fabric-carpet-20w4a-1.4.19+v201125.jar)" is broken. 

It currently links to https://github.com/gnembon/fabric-carpet/releases/download/v1.4-homebound/fabric-carpet-20w4a-1.4.19+v201125.jar, whereas it should link to https://github.com/gnembon/fabric-carpet/releases/download/v1.4-homebound/fabric-carpet-20w48a-1.4.19+v201125.jar

(the difference being the 8 in 20w48a in the filename)

**Comment by gnembon** [comment]
simplest fix
