### ISSUE TITLE
Scheduled functions in Scarpet tick during /tick freeze deep

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#581]
May be intended. Happens both in regular and deep freezes (maybe stopping them in deep ones but not in regulars, if intended?).

Relates to #398

From https://github.com/gnembon/fabric-carpet/issues/581#issuecomment-735455786:

My view of this:

PROS:
- Functions or apps that rely on actual ticks would always get accurate information
- It seems logical ("makes sense") that processing stops when the `Game is frozen`
- If shapes expiry time is also paused, would not affect debuggers with shapes, but may even make them better in case they vary based on execution number
- Apps that get data from the environment would not incorrectly update (e.g. app getting info from ticking command blocks)

CONS:
- Functions wouldn't run when the `Game is frozen` (not really a con in most cases, it's basically the premise of the issue)
- If shapes expiry time is not paused, would make debuggers useless when frozen
- Carpet-less clients wouldn't be sent new particles for shapes in debuggers, including regular particles

Tickrate is synced with clients, so shapes expiry time could be easily paused. Therefore the only con I see would be the last one.

Maybe making it be deep-only to allow compatibility if someone really needs the feature, but that would also make it harder to find, and I personally can't find any use case. Please comment one if you have it.

EDIT: Ok I found one: Actually controlling a `freeze`, something like temporary freezing the game for x ticks.

<details>
<summary>Messed up poll</summary>

## What do you think?

(clickable)

[![](https://api.gh-polls.com/poll/01ERWVFZ2RDDB4H7WJ37J1CWDN/Always%20freeze%20Scarpet%20schedules)](https://api.gh-polls.com/poll/01ERWVFZ2RDDB4H7WJ37J1CWDN/Always%20freeze%20Scarpet%20schedules/vote)
[![](https://api.gh-polls.com/poll/01ERWVFZ2RDDB4H7WJ37J1CWDN/Freeze%20Scarpet%20schedules%20on%20deep%20freeze)](https://api.gh-polls.com/poll/01ERWVFZ2RDDB4H7WJ37J1CWDN/Freeze%20Scarpet%20schedules%20on%20deep%20freeze/vote)
[![](https://api.gh-polls.com/poll/01ERWVFZ2RDDB4H7WJ37J1CWDN/Never%20freeze%20Scarpet%20schedules)](https://api.gh-polls.com/poll/01ERWVFZ2RDDB4H7WJ37J1CWDN/Never%20freeze%20Scarpet%20schedules/vote)

</details>

In progress PR:
- [x] Stop tick functions from datapacks
- [x] Stop tick events and freeze schedules in Scarpet
- [x] Sync frozen state to the client
  - [x] Make the required packet info
  - [x] Handle that new packet info
  - [x] Find a way to tick the client's `TickSpeed` in servers (to make `tick step` and maybe `tick superHot` render properly)
  - [x] Add 1 to duration of shapes every client tick if frozen

The PR should actually also make freezes look good/better in servers.

**Comment by gnembon** [comment]
hmmm

**Comment by altrisi** [comment]
May break apps that provide shapes _if their expiry time is still ticked in the client_.

**Comment by gnembon** [comment]
Its something that is not right or wrong here unfortunately. I think I should use deep frozen state in these kinds of situations.

**Comment by altrisi** [comment]
My view of this:

PROS:
- Functions or apps that rely on actual ticks would always get accurate information
- It seems logical ("makes sense") that processing stops when the `Game is frozen`
- If shapes expiry time is also paused, would not affect debuggers with shapes, but may even make them better in case they vary based on execution number
- Apps that get data from the environment would not incorrectly update (e.g. app getting info from ticking command blocks)

CONS:
- Functions wouldn't run when the `Game is frozen` (not really a con in most cases, it's basically the premise of the issue)
- If shapes expiry time is not paused, would make debuggers useless when frozen
- Carpet-less clients wouldn't be sent new particles for shapes in debuggers, including regular particles

Tickrate is synced with clients, so shapes expiry time could be easily paused. Therefore the only con I see would be the last one.

Maybe making it be deep-only to allow compatibility if someone really needs the feature, but that would also make it harder to find, and I personally can't find any use case. Please comment one if you have it.

**Comment by gnembon** [comment]
So what's wrong with deep freeze supporting freezing of datapacks and apps?

**Comment by altrisi** [comment]
Oh idk about datapacks, I think those (the `minecraft:tick` thing) should be frozen too, but not sure where to mix for that. I'd say those should be actually frozen in both types, since the `tick` event in scarpet doesn't run at all when frozen (does it?).

Will have to investigate if closing both.

**Comment by altrisi** [comment]
I've asked the question in discord just because this was marked as rfc.

**Comment by altrisi** [comment]
Wait. Should on what freezes should `__on_tick()` be frozen? Thought it didn't tick when game was frozen.
