### ISSUE TITLE
make default permission for all commands be 'ops'

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#582]
by community consensus

**Comment by altrisi** [comment]
Does all commands also include non-harmful ones like `/profile`, `/distance` or `/log`?

**Comment by Ghoulboy78** [comment]
what does /profile do?

**Comment by Ghoulboy78** [comment]
and will this be done with the scarpet apps replacing the old comamnds?

**Comment by Ghoulboy78** [comment]
cos ive almost finished the work on the /draw command, and the /distance was done alredy.

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/f9bce2b50e5af426a16f2c4b431cdfb66836d270

booyah
