### ISSUE TITLE
Everyone on server has access to /draw

### ISSUE THREAD

**Issue by Obydux** [gnembon/fabric-carpet#584]
On the 20w48a version of Carpet when using it on a server everyone gets permissions to /draw command. I tried without Carpet and non-OPs lost their access to /draw.

**Comment by replaceitem** [comment]
The /draw command is from carpet itself, and by default it is available to everyone, so if you remove Carpet, nobody has access to /draw (it doesnt exist)
You can change that with `/carpet commandDraw ops` to enable that command only for OP's
However this will likely change with #582 to be only available to ops by default

**Comment by gnembon** [comment]
yes, there is #582 that was almost unanimously agreed on in favour of keeping the previous behaviours. Essentially duplicates #582
