### ISSUE TITLE
events in player scoped apps that are dynamically set, should be independent from other players.

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#596]
Events are shared between app instances in per player apps. This means that one player will affect handling of events of other player. Since handlers can be dynamically added / removed, that breaks apps isolation.

Fixing it means all events should be keyed with host AND target and acted upon appropriately.

This entails that creating a new player host for apps requires copying of all events to the child host.

It probably makes sense that global host events in player apps are not executed as irrelevant.

This also means that all 'global' events, like 'tick' should now be able to execute on player hosts, making global events somewhat more useful, with a warning that with multiple players on, that will execute multiple times, once for each player.

**Comment by Ghoulboy78** [comment]
how could it be dynamically set?

**Comment by Ghoulboy78** [comment]
like can u give an example?

**Comment by gnembon** [comment]
this is the example:
https://github.com/gnembon/fabric-carpet/blob/9bdc0c31e461d52c9186ba3f00e5293e9e23194e/src/main/resources/assets/carpet/scripts/distance_beta.sc#L36

right now if one player changes that, it affects all players using this app.

**Comment by Ghoulboy78** [comment]
ah makes sense.

**Comment by gnembon** [comment]
I want all settings apps, that should be turned on by default (like distance), to have no effect by themselves on the game, so like with the distance, it can be loaded, but it should not be listening to any events, only when a player requests that.

**Comment by altrisi** [comment]
But in this specific case (distance), wouldn't the events (eg places block) be toggled globally since they depend in a rule, that is already global?

(not against the issue)
