### ISSUE TITLE
[Game crashes]crash when optifine is installed

### ISSUE THREAD

**Issue by MarinaMarissa** [gnembon/fabric-carpet#605]
mods:
fabric-api-0.23.1+1.15.jar
fabric-carpet-1.15.2-1.4.8+v200811.jar
OptiFabric-v1.0.1.jar
preview_OptiFine_1.15.2_HD_U_G5_pre1.jar

latest.log
[latest.log](https://github.com/gnembon/fabric-carpet/files/5642793/latest.log) (I deleted nothing except the file paths)

**Comment by gnembon** [comment]
its an old version you have. that issue was fixed later. If you need to stay in 1.15.2 - try some lower version for that to work, but I recommend you drop optifine for better client side mods, like sodium.
