### ISSUE TITLE
[bug] optimizeTNT results in incorrect entity behavior

### ISSUE THREAD

**Issue by Fallen-Breath** [gnembon/fabric-carpet#616]
As is shown in the video: https://youtu.be/KIx3PhF37es

The wrong behaviors of boost tnt can even be different after switch on optimizeTNT (all tnts go up far / go a up a little bit)

This issue doesn't occur in mc 1.15.2 + fabric carpet 1.4.8

WDL if needed:
[optTNT qwq.zip](https://github.com/gnembon/fabric-carpet/files/5652549/optTNT.qwq.zip)

## Environment
- mc 1.16.4
- fabric-loader 0.10.6+build.214
- fabric-carpet 1.4.20

**Comment by altrisi** [comment]
Seems like the bug with TNT in snapshots that was fixed by adding a specific check for TNT entities, related to eye height.

I think I fixed it. Making PR

**Comment by altrisi** [comment]
@Fallen-Breath Could you try with https://github.com/gnembon/fabric-carpet/actions/runs/406049293 and make sure it doesn't break anything else? I may have broken something else, I'm not an expert in explosion code. Hopefully I haven't. (it will be built in a second, else use the artifact in my fork)
