### ISSUE TITLE
Support for detecting explosions in scarpet

### ISSUE THREAD

**Issue by CommandLeo** [gnembon/fabric-carpet#621]
I would like to have an `__on_explosion` scarpet event added

**Comment by BisUmTo** [comment]
At the moment (as far as I know) it's impossible to detect an explosion before it happens.
I wrote a pull request to add the `_on_explosion()` event.

**Comment by gnembon** [comment]
funilly that would be reprecated when #602 gets in effect, which actually might take longer then we think (release of 1.17)

**Comment by altrisi** [comment]
Wasn't this merged in #620?
