### ISSUE TITLE
[Mod conflict] Library of Exile+Carpet+WorldEdit=crash

### ISSUE THREAD

**Issue by RDKRACZ** [gnembon/fabric-carpet#625]
Weird, I can run Carpet and WorldEdit mod without crash but when I add Library of Exile to mods then mc crashes.
Running Library of Exile with WorldEdit without Carpet doesn't crash.

crash report - https://hatebin.com/balwmiqfud

**Comment by RDKRACZ** [comment]
https://github.com/RobertSkalko/Library-of-Exile/issues/1

**Comment by altrisi** [comment]
Seems like the causer _may_ be [CardinalComponent's Chunk API](https://github.com/OnyxStudios/Cardinal-Components-API), not "Library of Exile" itself (may be a better place to report, but check if that's the case first), but I'm not sure. It seems to prevent Carpet from finding the method it's trying to mix into.

**Comment by gnembon** [comment]
well, just recently WE added some initial support for non-updatable setblocks, mixing into the same place with redirect - that will not end well.

**Comment by altrisi** [comment]
True, it has actually been confirmed there.

Well, then this relates to EngineHub/WorldEdit#1605, which is "scheduled" to be fixed in WE 7.2.2.

**Comment by Ghoulboy78** [comment]
this is another reason why we r making WorldEdit for scarpet. It's WIP, but idrc, it works.

**Comment by Ghoulboy78** [comment]
ok, this is fixed on WE's side, we can close her too now.

**Comment by Ghoulboy78** [comment]
k, you can close now @RDKRACZ
