### ISSUE TITLE
[Suggestion] Port FastMovingEntityOptimization from carpet mod 1.12 to fabric-carpet

### ISSUE THREAD

**Issue by fxmorin** [gnembon/fabric-carpet#627]
Any large scale tnt cannon setup, crashes servers. Running the same setups using the 1.12 carpetMod FastMovingEntityOptimization works flawlessly. We are working on a shaped perimeter for Scicraft when we update to 1.16+ although currently running the shaped perimeter crashes the server.

**Comment by James103** [comment]
1. Are you able to reproduce this crash in vanilla MC 1.16?
2. Are you able to reproduce this crash (and/or associated lag) when the server is running the latest release of the [Lithium](https://github.com/jellysquid3/lithium-fabric/) mod?

**Comment by fxmorin** [comment]
Yes and Yes,
I've already checked the code and talked to 2No2Name. This is not an issue of if its possible or if its the issue, its just something that needs to get added.

**Comment by Fallen-Breath** [comment]
I have ported the rule `optimizedFastEntityMovement` to [Carpet-TIS-Addition](https://github.com/TISUnion/Carpet-TIS-Addition#optimizedFastEntityMovement) and it's ok if it's necessary to port to fabric-carpet. 

there's another rule `optimizedTNTHighPriority` to make carpet's explosion optimization overwrite lithium's explosion optimization, with lithium and these 2 rules there will be a huge performance boost to a cannon

**Comment by fxmorin** [comment]
@Fallen-Breath Want to make a pull request for that run in fabric-carpet. That would be really helpful, thanks.

**Comment by gnembon** [comment]
Available in TIS addition.
