### ISSUE TITLE
[enhancement] Add /modded command to check what is different from vanilla

### ISSUE THREAD

**Issue by aria1th** [gnembon/fabric-carpet#636]
You can check what setting is modified with /carpet list, but its op-required command. Many mods / plugins / even server launchers frequently make mechanism different from vanilla, which makes people ask about "why this does not work". But if those things explain what is different from vanilla, there would be a lot less people who asks about it. 
Unfortunately spigot / paper / other mods does not explain about what is different / modified, but server side mods- modifications should expose itself to client side whenever possible, to notice player what can go different from their single player / other server experience. 
I tried to make this with some scripts, but not able to obtain file access to config file.

example: 
/modded
-> show modified values

/modded (autocomplete)
 - detailed description
 
 /modded shulkerSpawningInEndCities
 - shulkers will be able to respawn in end city.

**Comment by altrisi** [comment]
To access raw Carpet rules in Scarpet you can use `system_info('world_carpet_rules')`, although that gives you the whole list of changed and default rules, and doesn't print the description.

But I think you can get the output of the `carpet` command via `run()`? (at least I just tested `run('carpet')` and it seems to work).

Then you could parse the output to get what's changed by removing the header, footer, options, etc, and even get the descriptions by later running `carpet <feature>`.

**Comment by gnembon** [comment]
```
__command() ->
(
   out = run('carpet'):1;
   if (length(out) > 3,
      for(slice(out, 1, -2), print(_));
      null
   ,
      'vanilla'
   )
)
```
can use that for real quick solution

(except it uses a negative indexing solution for slice, which I just added so its not released so just replace that with `slice(out, 1, length(out)-2)` for now.
