### ISSUE TITLE
How do I install programs?

### ISSUE THREAD

**Issue by Pintodog** [gnembon/fabric-carpet#639]
I cannot find anywhere where I am meant to put the programs I download. Can someone help?

Thanks,
-Pinto

**Comment by altrisi** [comment]
If you mean installing Scarpet apps, there is a wiki article [here](https://github.com/gnembon/fabric-carpet/wiki/Installing-carpet-scripts-in-your-world).

If you mean how to install Carpet mod or Carpet extensions, you need to [install Fabric](https://fabricmc.net/use/) and then add Carpet (and extensions if desired) into the `mods` folder.

**Comment by gnembon** [comment]
yeah, wiki page covers it pretty well - tldr - create a folder 'scripts' in your world and plop them there.
