### ISSUE TITLE
A conflict occurred with the WorldEdit during loading the world

### ISSUE THREAD

**Issue by acaciachan** [gnembon/fabric-carpet#645]
[latest.log](https://github.com/gnembon/fabric-carpet/files/5746000/latest.log)
(I also submitted the error report to WordEdit on GitHub)

**Comment by James103** [comment]
Duplicate of #625

**Comment by interestingLSY** [comment]
Do not use worldedit 7.2.1, use 7.2.0 instead.

**Comment by Ghoulboy78** [comment]
@acaciachan fixed

**Comment by DragonEggBedrockBreaking** [comment]
So should this be closed now? Due to both being a duplicate *and* fixed in development releases of WE?

**Comment by naturecodevoid** [comment]
Is it fixed in 7.2.3?

**Comment by DragonEggBedrockBreaking** [comment]
> Edit: Just tested and it is fixed! 🎉

Then I guess this issue should be closed?

**Comment by gnembon** [comment]
closing
