### ISSUE TITLE
[Suggestion] AFK fish farm "unpatch"

### ISSUE THREAD

**Issue by Cypphi** [gnembon/fabric-carpet#647]
Basically the title, since AFK fish farms are patched in 1.16, or at least way harder to make, it would be cool to have a feature to re-add AFK fishing. This could be a feature on the mod until 1.17 comes out, because then AFK fishing will most likely be way easier.

**Comment by James103** [comment]
Have you tried downloading [the following datapack](https://vanillatweaks.net/share/#CZ9jEY) from VanillaTweaks called "Classic Fishing Loot"?
Note: Please unzip the file once, as you will find another ZIP file titled `classic fishing loot v1.1.0.zip`. Put that file in the world's datapacks folder.

**Comment by Cypphi** [comment]
> Have you tried downloading [the following datapack](https://vanillatweaks.net/share/#CZ9jEY) from VanillaTweaks called "Classic Fishing Loot"?
> Note: Please unzip the file once, as you will find another ZIP file titled `classic fishing loot v1.1.0.zip`. Put that file in the world's datapacks folder.

Yeah, I've seen that one, I think I'll use it but I prefer mods since I don't like running datapacks since they somehow feel cheaty to me. Like, if the chances aren't correct that's cheating for me. But I'll check it out :)
And a mod would just be way easier...

**Comment by gnembon** [comment]
no - a datapack is just easier. If it doesn't need to be modded - shouldn't
