### ISSUE TITLE
[Bug] movableBlockEntities can delete items in a chest if the piston is unloaded at the wrong moment

### ISSUE THREAD

**Issue by manyrandomthings** [gnembon/fabric-carpet#648]
Steps to recreate:

Put a chest/barrel/furnace/etc with items in front of a piston
Run `/tick freeze`
Power the piston
Run `/tick step 2`
Save and quit
Load world
Items in the chest are missing

**Comment by gnembon** [comment]
even with setDefaults set - so something with loading is messed up.

**Comment by gnembon** [comment]
to specify - doesn't happen with `/tick step 1` - the piston is saved and loaded. With `tick step 2` BE is saved, but not loaded back up (loading code 'fromTag' doesn't even execute).

**Comment by James103** [comment]
Have you tried reproducing with `/tick step 3` and/or `/tick step 4`? What results do you get?

**Comment by gnembon** [comment]
welp, it takes a piston 3 ticks to push the block to I guess nothing special. 1 and 2 are the 'movement' ticks. While 1 uses both fromTag and toTag and works correctly, with 2 tileentity is not being saved with toTag. Haven't look deeper - not really have time right for these things.

**Comment by manyrandomthings** [comment]
This appears to be fixed for 1.17+ since carpet 1.4.39
