### ISSUE TITLE
Consider adding back the bedrock breaking "feature" with dragon egg from previous MC versions.

### ISSUE THREAD

**Issue by Yggdraszil** [gnembon/fabric-carpet#65]

**Comment by gnembon** [comment]
Its a 'bug' that got fixed by refactoring the code, meaning it would be quite awkward to reimplement. Having said that, carpet-extra, as an extension of carpet, could be the target for such feature. Feel free to suggest the implementation and PR to https://github.com/gnembon/carpet-extra
