### ISSUE TITLE
[Parity] No server-side way to disable observers

### ISSUE THREAD

**Issue by IDMCtech** [gnembon/fabric-carpet#653]
would be a nice feature, I did not really know where to suggest this so I thought I would create a ticket for it

**Comment by altrisi** [comment]
Wdym parity? With what?

**Comment by gnembon** [comment]
well, the only moment I would understand when that would happen is on placing the observer and that's already covered under `/carpet interactionUpdates false`

**Comment by IDMCtech** [comment]
ok thanks! that works as well xd
