### ISSUE TITLE
[Scarpet bug] `slice()` misses last character

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#657]
(tested in latest commit)

When you run `slice(str,index)`, the result will be missing the last character. Using `length(str)` as end position makes it return the empty string.

```py
slice('helloworld', 2) -> 'lloworl'
str = 'helloworld'; slice(str, 2) -> 'lloworld'
str = 'helloworld'; slice(str, 2, length(str)) -> ''
str = 'helloworld'; slice(str, 2, length(str) - 1) -> 'lloworl'
```

It was introduced in 7ad6de64ffc4af41c915b699ebb547d6191604cd (worked correctly after locally reverting that commit).

**Comment by gnembon** [comment]
oups
