### ISSUE TITLE
Commands are available for non-op players

### ISSUE THREAD

**Issue by TIVJ-dev** [gnembon/fabric-carpet#66]
Commands /draw, /tick, /spawn, /track, /info, /distance, /script, /c and /s are available for non-op players.
However, I think /s, /c, /track, /info and /distance should be available for everyone. Possibly /script too.

**Comment by gnembon** [comment]
/carpet command controls which commands are available and that command requires an op status. Operators can disable any of these commands via a carpet rule. This is intended to be like this.
