### ISSUE TITLE
Incompatible with Fabric API on server

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/fabric-carpet#67]
When I try to start my server with only carpet and fabric API in my mods folder I get a crash on start. 
[log.txt](https://github.com/gnembon/fabric-carpet/files/3468869/log.txt)

**Comment by gnembon** [comment]
fabric-carpet doesn't need fabric-API, and that error message you get by running fabric-API. Maybe you got some outdated fabric-API (for whatever you need it for, since you don't need it for carpet)

**Comment by supersaiyansubtlety** [comment]
Oh, I think you were right and my API was outdated. Sorry about that.
