### ISSUE TITLE
World Loading Screen hangs up at 0%

### ISSUE THREAD

**Issue by itzApexis** [gnembon/fabric-carpet#670]
Hey,
I just downloaded carpet mod and my already existing world hangs up in the loading screen at 0%. 
I already tested if the reason is any datapack or other mod installed but it doesnt seem to be the problem

**Comment by gnembon** [comment]
well, I can only assert that my world goes past 0%.

You would need to provide more to this, like what's happens in the output log - maybe you are trying to load wrong mod version to the wrong game version.

**Comment by itzApexis** [comment]
Where can i find the output log exactly?

Von meinem iPhone gesendet

**Comment by buildartifacts** [comment]
if you have worldedit, it might be the cause because that was the problem for me

**Comment by altrisi** [comment]
Go to your minecraft folder (normally %appdata%/.minecraft) and in the `logs` folder, get the one called `latest` (supposing this happened in your latest session).

**Comment by itzApexis** [comment]
> if you have worldedit, it might be the cause because that was the problem for me

already tried just using fabric and carpet mod

**Comment by itzApexis** [comment]
After deinstalling MC and removing every left over data of mc related stuff, now it seems to be fixed
