### ISSUE TITLE
Husks do not spawn in pyramids with the feature enabled.

### ISSUE THREAD

**Issue by nnnik** [gnembon/fabric-carpet#68]
It seems like the husks spawning in temples feature does not result in a noticeable change of vanilla behavior.  
Normal mobs spawn everywhere in the pyramids bounding box - husks only spawn with sky access in it.

Steps to reproduce:
- create new world in single-player (irrelevant which world type) 
- enable husk spawning in carpet and enable it by default
- find a pyramid and display its bounding box (for example with miniHUD)
- make multiple spawn floors inside the bounding box and clear the surrounding world to get a perimeter
- watch as hostile mobs of all types spawn in the bounding box but husks only with sky access

**Comment by gnembon** [comment]
So I did observe that husks only spawn with sky access - default vanilla behaviour, but other mobs were not able to spawning there. I changed to they don't need sky access in the temples with the rule turned on. This will be pushed with 1.0.4 I guess
