### ISSUE TITLE
Incompatibility with fabrication

### ISSUE THREAD

**Issue by drakosoldier298** [gnembon/fabric-carpet#688]
https://gist.github.com/drakosoldier298/00b71976e5a2df03664f7b37e930adcc
This is a log from a server on apex so custom.jar is fabric

**Comment by altrisi** [comment]
I'd say this seems more like the current WorldEdit conflict (therefore, this would be a duplicate of #625, and all its duplicates).

As a workaround before this is fixed, you should use WorldEdit 7.2.0 (or lower) instead with Carpet.

**Comment by Ghoulboy78** [comment]
well it0s fixed now @drakosoldier298, update to newest version of WE

**Comment by altrisi** [comment]
Note that the WE version which fixed this hasn't been released yet.

**Comment by gnembon** [comment]
fixed in 7.2.3, so closing.
