### ISSUE TITLE
[Suggestion] Permanent Carpet rules by default

### ISSUE THREAD

**Issue by SINBRO** [gnembon/fabric-carpet#689]
It would be very nice if there was a setting (a Carpet rule, I guess) to make all rule changes apply permanently. I personally (and probably a lot of people) want most rule changes to stick anyway.
It's especially annoying to manually make every change permanent upon new world creation.

**Comment by gnembon** [comment]
good news - if you copy your favourite config from your last world into `.minecraft/config/carpet/default_carpet.conf` then it will be used for all new worlds you create

**Comment by SINBRO** [comment]
I was gonna say it's still quite a lot of effort for a lazy gamer, but that's actually very nice, thanks
