### ISSUE TITLE
Can't check for item names in Scarpet

### ISSUE THREAD

**Issue by Zedespook** [gnembon/fabric-carpet#69]
`/script run print(get(player() ~ 'holds', 0))`

I use the command above, I don't know if I use it incorrectly, but even if I change the number, the message is the same on every third number. I don't know what I'm doing wrong, I checked the documentation, and I still don't know how to get the name of an item.

**Comment by gnembon** [comment]
name is hidden inside item's NBT (inside third element returned with 'holds'). You can still check it, but its more complex

**Comment by gnembon** [comment]
Btw, you have already created issue about it, and I replied to it:
https://github.com/gnembon/fabric-carpet/issues/61

**Comment by Ghoulboy78** [comment]
what a waste of issue 69
