### ISSUE TITLE
Missing issues tag in fabric.mod.json.

### ISSUE THREAD

**Issue by RDKRACZ** [gnembon/fabric-carpet#690]
The homepage tag redirects to issues instead. Both should be in use.

**Comment by altrisi** [comment]
Note that the `issues` field (like all other metadata fields) is completely optional according to the `fabric.mod.json` spec.

I suppose this issue is because by default ModMenu displays the `issues` field in its button instead of the `sources` one (which is actually more common), right?

**Comment by RDKRACZ** [comment]
> I suppose this issue is because by default ModMenu displays the `issues` field in its button instead of the `sources` one

Yes. Just wanted to make any use of these buttons since they are there.
