### ISSUE TITLE
[Feature request] Add commandWorldManipulation setting

### ISSUE THREAD

**Issue by ruru4143** [gnembon/fabric-carpet#695]
I would like to have a command which disables all non-informational commands.
something similar to this:

```
## commandWorldManipulation
Enables commands which manipulates the world like `/tick warp`, `/spawn test` or `/spawn mobcap set` 
* Type: `String`  
* Default value: `ops`  
* Suggested options: `true`, `false`, `ops`  
* Categories: `COMMAND`  
* Additional notes:  
  * It has an accompanying command  
  * Can be limited to 'ops' only, or a custom permission level  
```

A alternative name would be commandEnableCheaty or something similar.

Why? I want to enable all informational commands, but some subcommands (like `/spawn test`) are non-informational

**Comment by gnembon** [comment]
I disagree that /spawn is non-cheaty - you can control spawning with it, like bump it up. 

I suggest blocking both tick and spawn for non-ops and build a custom command with scarpet to execute a subset of both.
