### ISSUE TITLE
Incompatibility StructureBlockBlockEntity_limits mixin in 1.4.25 with tweakeroo

### ISSUE THREAD

**Issue by kohanis** [gnembon/fabric-carpet#697]
Using carpet 1.4.25 with tweakeroo (tested only latest, 1.16.4-0.10.0-dev.20210118.163914 atm, but it should be long-time functionality) causing crash on init:
`Critical injection failure: Constant modifier method outlineRenderDistanceLimit(D)D in carpet.mixins.json:StructureBlockBlockEntity_limitsMixin failed injection check, (0/1) succeeded. Scanned 1 target(s)`

**Comment by Heitzenberg** [comment]
Fixed with the latest Tweakeroo build.

**Comment by kohanis** [comment]
Yep, checked
