### ISSUE TITLE
couldn't start server

### ISSUE THREAD

**Issue by Haocen2004** [gnembon/fabric-carpet#698]
log span this thing and server not responding, including /stop and linux kill command 
`[19:14:39] [Server thread/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldChunk_fillUpdatesMixin->@Redirect::onAdded(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V with priority 1000, already redirected by worldedit.mixins.json:MixinWorldChunk->@Redirect::setBlockStateHook(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V with priority 1000`
minecraft@1.16.5,  java@8, fabricloader@0.11.1, fabric-api-base@0.2.0+ab87788d3a

**Comment by Firigion** [comment]
That's an incompatibility with WorldEdit. Either use WE 7.2.0, or 7.2.3, when it releases. .1 and .2 are incompatible.

**Comment by gnembon** [comment]
7.2.3 is available, so closing
