### ISSUE TITLE
[BUG]player can't connect to the server

### ISSUE THREAD

**Issue by shenjackyuanjie** [gnembon/fabric-carpet#699]
[归档.zip](https://github.com/gnembon/fabric-carpet/files/5936987/default.zip)
mods and fabric-server-laucher is up here
and server.jar is 1.15.2
logs are 
[latest.log.zip](https://github.com/gnembon/fabric-carpet/files/5936994/latest.log.zip)
i tested to ping authserver.mojang.com and sessionserver.mojang.com
all can
fabric loader 1.11.1 and 1.10.8 all have save BUG

**Comment by shenjackyuanjie** [comment]
sorry , but this BUG suddly appered today
after i try the new's fabric loader

**Comment by shenjackyuanjie** [comment]
and i just test with some older API and carpet
Seems the problme is at high level API

**Comment by shenjackyuanjie** [comment]
fabric api 0.14.0 is ok
with the same carpet i just show
fabric api 0.28.5 have bug
carpet is the same

**Comment by altrisi** [comment]
If you are only running Carpet, you don't require fabric API.

I don't think Carpet for 1.15 is still supported, but that seems like a timed out and not anything else (the timed out may be caused by a bug, though. Maybe try reporting to Fabric API, since that's the only thing you changed).

**Comment by shenjackyuanjie** [comment]
> If you are only running Carpet, you don't require fabric API.
> 
> I don't think Carpet for 1.15 is still supported, but that seems like a timed out and not anything else (the timed out may be caused by a bug, though. Maybe try reporting to Fabric API, since that's the only thing you changed).

well my friend told me that
hi's server running on 1.16.5
also have this bug

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/119056363-27c4b780-b9fd-11eb-856f-0d35b50fcc20.png)
i've try 1.16.4 now
also have same issue

**Comment by shenjackyuanjie** [comment]
the pic i've show have no bug
but is update carpet or API any more will cause the bug

**Comment by gnembon** [comment]
can't reproduce with just fabric api and carpet. Do you mind zipping all the mods for testing - cause its probably not just API - carpet interaction

**Comment by shenjackyuanjie** [comment]
well
i've tested now 
is ok now/
