### ISSUE TITLE
[scarpet] Add item category list

### ISSUE THREAD

**Issue by Firigion** [gnembon/fabric-carpet#705]
Add a new functionality to scarpet to list all items in a category (like `weapons` or `building_blocks`). This could be added to `item_list(tag?)`, which queried with a category instead of a tag lists all items in said category, to `item_category(item?)`, with the same idea, or to a new function `item_category_list(category?)`, which would return the list of available categories when not given an argument, or list the items in the given category.

**Comment by gnembon** [comment]
technically you could just create your own list statically using `item_list` and `item_category`. See no reason to add extra API method just for that.
