### ISSUE TITLE
Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by Frostium** [gnembon/fabric-carpet#706]
I was working on making a fabric mod pack and I found I couldn't have immersive portals and carpet mod together. I'm not sure whats causing this and if there is a way to make them compatible (I could even fix it myself if it was simple enough)

**Comment by James103** [comment]
Can you post the game logs on Pastebin or Github Gist, and link to the logs here?

**Comment by altrisi** [comment]
And the crashreport, ofc.
