### ISSUE TITLE
[Scarpet bug] New vibration and dust_color_transition particles don't work

### ISSUE THREAD

**Issue by ajloveslily14** [gnembon/fabric-carpet#708]
The new vibration particle, and the new dust_color_transition particle in the game don't work with the particle() function. Am I right to assume this is because they have to be manually added in because they take parameters?

**Comment by altrisi** [comment]
Try adding the parameters at the end of the string. The way the particle parser works is by literally calling Minecraft's `/particle` "particle name" argument parser, which accepts/requires those parameters in that string (unless they changed it in 1.17).

**Comment by ajloveslily14** [comment]
The format for vibration is `/particle vibration originx originy originz endx endy endx traveltimeinticks` When I run `particle('vibration 0 0 0 1 1 1 20',0,0,0)` it works.
