### ISSUE TITLE
Crashing while ticking forwards

### ISSUE THREAD

**Issue by SHsuperCM** [gnembon/fabric-carpet#71]
I cannot seem to tick forwards in sp while I'm in spectator with another NPC player(/player) afking.
After a few seconds passing with /tick active(both rate and warp) the game crashes spewing these:
Log:
https://pastebin.com/raw/By0aL9GB
Crash-Report:
https://pastebin.com/raw/Dxh2kt2N

**Comment by gnembon** [comment]
The crash indicates that its one of the client side mods, presumably optifine, althought its hard to tell. I am surprised it all even runs with that many mods. Its hard to even replicate the issue, especially that the crash is not on the carpet side. Try using the mods that you actually need, not all of them. Please let me know if you could figure out which mod is actually causing the crashing - that would be more helpful.

**Comment by SHsuperCM** [comment]
Yep, it was optifine.. Everything else runs perfectly and hadn't had a crash yet doing the same with the rest of the mods..
I guess I will switch between optifine and carpet when I need to test things vs regular playing. Thanks!
