### ISSUE TITLE
Incompatibility with vanilla server when using structure block

### ISSUE THREAD

**Issue by Fallen-Breath** [gnembon/fabric-carpet#712]
## How to reproduce

1. Join a vanilla server, or any server without fabric carpet, with a client with fabric carpet (>=1.4.25) installed on the client
2. Place a structure block, switch to save mode, edit anything e.g. structure size, press done
3. You gets kicked by the server

![image](https://user-images.githubusercontent.com/28978806/107867431-bd5c2280-6eb5-11eb-83ea-f60e29171d24.png)

## Analyze

In commit e32b37dcf1b5021bf4c373f138d6a7a943931fc6 from PR #664, a couble of extra int fields are added to the end of UpdateStructureBlockC2SPacket, which inceases the length of the packet, resulting in vanilla server packet logic raising an exception in `net.minecraft.network.DecoderHandler#decode`

**Comment by gnembon** [comment]
That's a very serious issue.
