### ISSUE TITLE
Server Crash while exiting a Lan server.

### ISSUE THREAD

**Issue by Philipp766** [gnembon/fabric-carpet#726]
I just had a crash on my singleplayer world. I had opened it to lan, because i had to tweak something and when i quit it crashed. 
I tested it 4 more times and it didnt crash. Maybe I just quit at the wrong moment or something.
[crash-2021-02-20_11.22.16-server.txt](https://github.com/gnembon/fabric-carpet/files/6014638/crash-2021-02-20_11.22.16-server.txt)

**Comment by gnembon** [comment]
Thanks for this report - that would probably be hard to catch otherwise.

**Comment by Philipp766** [comment]
No problem :) im always happy to report anything wrong and funky to improve it.
