### ISSUE TITLE
Camera mode glitch

### ISSUE THREAD

**Issue by TheVirusWar** [gnembon/fabric-carpet#73]
Upon returning to survival via /s command, the player can see in dark. Doesn't fix via restart/reload.
Also, I've noticed if you enter the camera mod via /c and return to survival via /gamemode survival, you can see in dark and breath underwater. Water breathing is fixed with using /s, but night-vision stays.

All modifications I have are FabricAPI, Fabric-Carpet, Optifabric, Optifine.
Fabric-Carpet is v19_07_14 for 14.4-sunny.

New to this mod, so it could be I'm doing something wrong.

**Comment by TheVirusWar** [comment]
Quick update. 
After a third save reload (save and exit, then enter the world again), it got fixed.

**Comment by gnembon** [comment]
its been fixed in recent versions. Please update your carpet for that.
