### ISSUE TITLE
query(e, 'fire') is documented as if it was available, but is actually not available.

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#730]
Currently (even as far back as 885f579d6cad6886cc70491a8e948c0c2b69279e), the option `fire` for `query(e, property)` is not available, even though it is documented as if it was available on the scarpet documentation. The option `fire` for `modify(e, property)` is actually available in Scarpet though.
https://github.com/gnembon/fabric-carpet/blob/386afc1079b833d47b333a423ff5f0d388eefbc0/src/main/java/carpet/script/value/EntityValue.java#L465

**Comment by altrisi** [comment]
No longer requires mixing.
