### ISSUE TITLE
Logging multiple hoppercounters is broken

### ISSUE THREAD

**Issue by Hnaguski** [gnembon/fabric-carpet#736]
When attempting to run `/log counter white,black` I get the following error:
```
[14:29:07] [main/INFO]: [CHAT] [14:29] Expected whitespace to end one argument, but found trailing data
[14:29:07] [main/INFO]: [CHAT] [14:29] ...nter white,black<--[HERE]
```
Subscribing to a single counter works as expected.
I am running minecraft 1.16.5 and doing a small amount of testing seems to have revealed the issue has been in carpet since 1.4.25.

**Comment by gnembon** [comment]
Due to extra arguments for this call, the format cannot accept comma character and you need to quote it properly. The command suggestion is right. Use `/log counter "white,black"` now
