### ISSUE TITLE
[suggestion] integrate commands with LuckPerms permissions

### ISSUE THREAD

**Issue by andrewzah** [gnembon/fabric-carpet#747]
Now that [LuckPerms supports Fabric](https://github.com/lucko/LuckPerms/pull/2029) it would be nice to have granular permissions for carpet commands instead of just limiting certain ones to OP, etc.

**Comment by altrisi** [comment]
99% sure this is not going to happen. 

BTW you can set more granular permissions to commands by using `0-4`, which are vanilla permission levels (specified in ops file).

LuckPerms may support to redirect that, ask them whether they do.

**Comment by gnembon** [comment]
Sounds like a unnecessary thing. Btw - you can fully control what happens when player type a command with scarpet apps.

**Comment by FarLanderCraft** [comment]
Unfortunate, it would be pretty handy if I could change permissions for specific carpet commands. (Please don't reopen. ;-; )
