### ISSUE TITLE
[SUGGESTION] Spawner activation range

### ISSUE THREAD

**Issue by srnyx** [gnembon/fabric-carpet#752]
It would be awesome if you could implement a feature to change the default spawner activation range from 16 to any number!

**Comment by gnembon** [comment]
its a vanilla feature, no need to mod this in - just customize RequiredPlayerRange in the tag.

**Comment by srnyx** [comment]
> its a vanilla feature, no need to mod this in - just customize RequiredPlayerRange in the tag.

That doesn't apply to every spawner, only to cheated in ones.
I wanted to change it for all spawners (as I use a silk spawners mod).
