### ISSUE TITLE
[Suggestion] Markdown support in Rule descriptions

### ISSUE THREAD

**Issue by RubixDev** [gnembon/fabric-carpet#759]
I thought of basic markdown support for the rule descriptions, so things like [this](https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/CarpetSettings.java#L877) would display properly ingame and maybe being able to write in **bold** and *italic*.

**Comment by Ghoulboy78** [comment]
hmm, maybe with the system already used in format() function or smth?

**Comment by Ghoulboy78** [comment]
Any markdown thing would have to be added to that, before it gets translated. In all instances of a rule description being displayed to the player, that appears to be the method used to get it (which makes sense if u think about it)

https://github.com/gnembon/fabric-carpet/blob/ddd3873427f9b4d075069d3c4ea413f3d2235fcf/src/main/java/carpet/settings/ParsedRule.java#L288-L291

**Comment by gnembon** [comment]
mmmmmm... 
primary reason for these messages is to display them properly in chat. Markdown is secondary. That would be a lot of work for very little benefits.
