### ISSUE TITLE
Issue storing integer values of look vector in NBT data motion vector

### ISSUE THREAD

**Issue by xMGZx** [gnembon/fabric-carpet#763]
![image](https://user-images.githubusercontent.com/40220050/111005475-e35fd000-8358-11eb-9acb-aaa3c4acfc29.png)
![image](https://user-images.githubusercontent.com/40220050/111005846-94ff0100-8359-11eb-911d-ab4d2d96423c.png)

For some reason, when I try to store a player's look vector into a motion vector of another entity, I rarely get this error message that seems to only occur when any coordinate of the vector is an integer number.

**Comment by James103** [comment]
Can you try using the floating point version `0.0d` instead of the integer `0` when storing to NBT?

**Comment by xMGZx** [comment]
I don't have physical control over the 0 exactly, so unfortunately I cannot do that. This is the line of code that's wrong, could it be that the "wspeed" value being an integer is causing this issue?
```
wprojectile_tag:'Motion' = (e~'look') * wspeed;
```

**Comment by James103** [comment]
Do you get the same error if you replace the above line with the following (which assumes `wspeed is 1`)?
```
wprojectile_tag:'Motion' = (e~'look')
```
If you don't get the error, then it is likely caused by `wspeed` being an integer.

**Comment by xMGZx** [comment]
No, the issue still occurs without `wspeed`.

**Comment by James103** [comment]
As a workaround, can you try filtering out those zeroes and replacing them with a really small floating point number (like 0.000000001)?

**Comment by xMGZx** [comment]
I already thought about doing that, but this is a bug nonetheless lol

**Comment by xMGZx** [comment]
Seems to actually occur when _any_ of the three values are integer values, not just zero.

**Comment by gnembon** [comment]
its all intended - and its a restriction of the NBT tags to store only one type in a list. In newer parts of MC points are stored as maps like `{X:...,Y:...,Z:...}` so its not a problem.
To do it properly, pass a string as value:
https://github.com/gnembon/fabric-carpet/blob/255cb6b96ad750a33a355cbd61a1299c21f7751b/src/main/resources/assets/carpet/scripts/camera.sc#L673
