### ISSUE TITLE
[Suggestion] Add a 'formerlyKnownAs' attribute to rules

### ISSUE THREAD

**Issue by RubixDev** [gnembon/fabric-carpet#764]
This would be what I'm thinking of:
```java
/**
 * A list of names the rule previously had to allow loading older config files.
 */
String[] formerlyKnownAs() default {};
```
It would allow renaming rules without breaking the loading of old config files.

**Comment by gnembon** [comment]
At first I thought, that sounds like a good idea, but later, I figured, that this might be too much complexity for some lazy people now wanting to change their config files once in a blue moon
