### ISSUE TITLE
Compatibility issue upon creating worlds with Gunpowder.

### ISSUE THREAD

**Issue by jbjornberg** [gnembon/fabric-carpet#765]
**The game crashed whilst mouseclicked event handler**
https://pastebin.com/j8QTWGG1

The game boots up, the issue begins whenever you try to create or load an existing world.

The Developer of Gunpowder has already said that they won't be attempting to fix this incompatibility..
https://github.com/Gunpowder-MC/Gunpowder/issues/95

It isn't the end of the world if I can't use both of these mods, and I completely understand if you can't be bothered just like the dev of Gunpowder, but I figured I'd bring it to your attention just in case you'd be willing to give it a go. Thanks.

**Comment by altrisi** [comment]
Problem is a redirect in CommandManager that has the same target in both. It is used to enable the command stacktrace when some secret settings are enabled, which IMO doesn't need to be required in any of them (aka a require 0 could be added in both, further improving compatibility with other mods that decide to redirect the same).

**Comment by altrisi** [comment]
Could you try if the build from PR #766 fix your issue?

**Comment by jbjornberg** [comment]
I will try this for sure! I downgraded like you mentioned in the response to Gunpowder. I appreciate you a lot for not writing it off and saying something like "Gunpowder causes a lot of issues." lol

I'll try that and let you know how it goes, but a temporary solution for me was downgrading all of my Gunpowder mods to the December 2020 Release versions.

**Comment by jbjornberg** [comment]
fabric-carpet-1.16.5-1.4.29+v210315 worked with all of the latest Gunpowder mods. All of my 170+ mods are now working perfectly in conjunction with Carpet & GP. Thank you!
