### ISSUE TITLE
crops dont grow in increased tick rate / tick warp

### ISSUE THREAD

**Issue by hgmrick** [gnembon/fabric-carpet#769]
Apparently it breaks all random ticks in the newest version

**Comment by gnembon** [comment]
please elaborate what does it mean 'the newest version' (carpet version and mc version)

**Comment by hgmrick** [comment]
Carpet Mod v1.4.29 for 1.16.5 minecraft version 1.16.5

**Comment by altrisi** [comment]
Cannot reproduce (in 1.16.5 on cf03536)

**Comment by gnembon** [comment]
You could have been in spectator or something like that. Can't reproduce, works just fine for me.
