### ISSUE TITLE
"sunny.jar Is a Fabric mod and cannot be loaded."

### ISSUE THREAD

**Issue by KernalKeen** [gnembon/fabric-carpet#77]
I open minecraft it says this. Idk... help please

**Comment by DeadlyMC** [comment]
Considering the other issue u made i believe u r using forge to load the mod 
https://github.com/gnembon/fabric-carpet/issues/76

**Comment by gnembon** [comment]
follow https://fabricmc.net/use/ to install carpet mod as any other fabric mod. Also please you the latest released version for your MC version.
