### ISSUE TITLE
`com.sun.nio.zipfs.ZipPath` is not present in newer Java versions

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#770]
Latest commit (1a47f433) introduced the new support for zip files directly in the file read functions.

However, while it seems to be present in Java 8, my IDE and Gradle running Java 11 is complaining about it not existing.

This is probably because of `ZipPath` being part of internal/proprietary/whatever APIs and therefore not guaranteed to be kept through versions. There should probably some way to do the same without using those APIs, haven't really looked at it.

For information's sake, what seems to be the equivalent of `com.sun.nio.zipfs.ZipPath` in Java 11 is `jdk.nio.zipfs.ZipPath`, but it is also part of internal APIs and probably shouldn't be used either, since it may have already changed in newer Java versions.

This probably causes `ClassDefNotFoundExceptions` or similar, haven't really launched it because of that.

**Comment by altrisi** [comment]
Once again didn't really look at it, but maybe something checking in [`Path#getFileSystem()`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#getFileSystem--) for the needed properties/whatever?

**Comment by gnembon** [comment]
Ok, that import is not really needed - could just pass a boolean to the static method. Should be a simple fix.

**Comment by gnembon** [comment]
done
https://github.com/gnembon/fabric-carpet/commit/53f6a49b8df1977bc43e1d68f385fe7e3638a043
