### ISSUE TITLE
Configurable fake player's view distance

### ISSUE THREAD

**Issue by FlandiaYingman** [gnembon/fabric-carpet#777]

**Comment by altrisi** [comment]
It is already configurable, just change your view distance.

Fake players are just normal players for the server, so there's not really a super-easy way of changing that.

If you want a chunkloaded area, just use a vanilla portal loader instead, there you can design your loaded distance.

**Comment by Hadron67** [comment]
Do you mean changing view distance *only* for the fake players but not real players? Well this is actually doable, but will likely cause conflict with other mods.

**Comment by gnembon** [comment]
yeah - sounds like a bad idea. The purpose of fake players is to keep the behaviour of normal players as much as possible. They are not meant to act like 'bots', or 'world interaction upgrades'. If you can use them as such, so be it.
