### ISSUE TITLE
When i have "locked" at top of conf file it locks even for me, the OP (Server Use)

### ISSUE THREAD

**Issue by Copyablemite4** [gnembon/fabric-carpet#778]
Is there anyway where i can see the /carpet command but other players cannot since they are not OP?

**Comment by altrisi** [comment]
`locked` is to completely block it, even for ops.

The `/carpet` command is already op only (permission level 2) if you don't lock it.

**Comment by gnembon** [comment]
Well, that's the point of locked setup so only admins can tinkle with it, not ops. This applies to creative servers where the assumption is that everyone gets ops and you, as an admin, may want to fix some carpet setup.
Also - most settings allow you enable them for ops only. 

Locked setup is probably not what you are looking for here.
