### ISSUE TITLE
Game crashes when pushing modded blocks

### ISSUE THREAD

**Issue by 3prm3** [gnembon/fabric-carpet#782]
https://gist.githubusercontent.com/natanfudge/b855b13c1974d14e2ba6bd8dfad611c2/raw/45df721f4625a48cac747d24b7f40cf1f94ac418/crash.txt

**Comment by 3prm3** [comment]
@gnembon

**Comment by altrisi** [comment]
No, the crash is because it seems there is an incompatibility with `blastrod`, which seems to be completely overwriting the piston handling code, therefore Carpet mixin failing to find its target.

Also, any specific reason to ping??

**Comment by James103** [comment]
@3prm3 Can you try removing `blastrod` from your active mods folder then restarting the game?

**Comment by 3prm3** [comment]
> No, the crash is because it seems there is an incompatibility with `blastrod`, which seems to be completely overwriting the piston handling code, therefore Carpet mixin failing to find its target.
> 
> Also, any specific reason to ping??



> @3prm3 Can you try removing `blastrod` from your active mods folder then restarting the game?

k

**Comment by 3prm3** [comment]
> > No, the crash is because it seems there is an incompatibility with `blastrod`, which seems to be completely overwriting the piston handling code, therefore Carpet mixin failing to find its target.
> > Also, any specific reason to ping??
> 
> > @3prm3 Can you try removing `blastrod` from your active mods folder then restarting the game?
> 
> k

it works now
