### ISSUE TITLE
/player for certain players

### ISSUE THREAD

**Issue by DillonB07** [gnembon/fabric-carpet#783]
I do not want to give every person on my server the ability to use /player.
How do I specify certain players(without giving op of course)?

**Comment by DillonB07** [comment]
Thank you. This will be useful.

**Comment by gnembon** [comment]
Another option is to disable player command for all players (ops only), and write a wrapper scarpet app to perform certain allowed actions.

**Comment by gnembon** [comment]
Got two options already for that :)
