### ISSUE TITLE
Add spawn chunk location to system_info

### ISSUE THREAD

**Issue by Kaedenn** [gnembon/fabric-carpet#785]
I do not see a way to query the spawn chunks in scarpet. I propose adding that information to `system_info`, seeing that other mutable values (eg. `game_difficulty`) are already present.

Examples:
```
// Location of the spawn chunk, in chunk coordinates:
l(cx, cz) = system_info():'spawn_chunk';
// Location of the spawn chunk, in world coordinates:
l(wx, wz) = map(system_info():'spawn_chunk', 16*_);
```

**Comment by gnembon** [comment]
agree, there should be `system_info('world_spawn_point')`

**Comment by gnembon** [comment]
`chunk_tickets(system_info('world_spawn_point'))`
