### ISSUE TITLE
[Scarpet Suggestion] Querying player language

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#787]
It would be nice, and it is sent in `ClientSettingsC2SPacket`. It is not really saved anywhere, but the packet is passed to the `ServerPlayerEntity` in `setClientSettings`.

I'm a total noob in Mixin, so I'll probably not try to implement this at least Soon™.

**Comment by gnembon** [comment]
Good idea



... but
some players may want to remain anonymous. That's why there is 'ping' for players, but not 'ip'. Language stays in the gray zone between these two.
Something to consider. I am fine one way or the other.

**Comment by gnembon** [comment]
thoughts?
I am on the fence of the language thingy, but on the 'its fine' side.

**Comment by Ghoulboy78** [comment]
Then would you mind me working on this? Im curious to learn more about packets, so I would be interested to do this one if u don't mind...
