### ISSUE TITLE
[Suggestion] Global Defaults for All Worlds

### ISSUE THREAD

**Issue by God-ly** [gnembon/fabric-carpet#789]
It would change the default value for carpet.conf settings applicable to each world, something like /carpet setGlobalDefault.

**Comment by gnembon** [comment]
you can put your default config file in `.minecraft/config/carpet/default_carpet.conf` and it will be applied to every newly created world.

**Comment by obj-obj** [comment]
I put a config file there, created a new world, and it didn't apply the config...
Guess ill just manually copy the config
