### ISSUE TITLE
Tick freezing: Mounting anything softlocks the game

### ISSUE THREAD

**Issue by Hibiii** [gnembon/fabric-carpet#792]
I wanted to make a haha funni Superhot-only minecart station, but instead I found that when you ride a minecart in frozen ticks or Superhot, it softlocks the client in a way only restoring normal ticking with commands would revert.

- You can't unmount because that's checked tickwise on the server.
- You can't remove the minecart by punching it because it is your vehicle and you can't attack your own vehicle.
- If you've just mounted the cart, you'll be stuck sitting mid-air, where you were standing.
- You cannot wiggle a minecart around or move a boat or trot on a horse.
- You can't look around. If you do, you'll be met by intense screen shaking.

The game is, gameplay-wise, unrecoverably softlocked because the player has no velocity, but the vehicle has all of it. While this is a non-fatal bug normally, it is on a Superhot no-cheats world.

**Comment by gnembon** [comment]
ok, that didn't work the first time. Something changed.

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/cd9a5b96c2a6197dac493ce5e1cb81924d7833b9
