### ISSUE TITLE
[Scarpet Suggestion] create_recipe() and create_loot_table()

### ISSUE THREAD

**Issue by BisUmTo** [gnembon/fabric-carpet#795]
`create_recipe(name, content, datapack?, zipped?)`
Add functions to add a new recipe/loot_table with the specified name and content (from a map*).
by default it will be generated in the `script_name` unzipped datapack, but it is possible to change it.

  *example of map:
```sci
{
  'type' -> 'minecraft:smithing',
  'base' -> {
    'item' -> 'minecraft:deepslate_coal_ore'
  },
  'addition' -> {
    'item' -> 'minecraft:stone'
  },
  'result' -> {
    'item' -> 'minecraft:coal_ore'
  }
}
```

**Comment by gnembon** [comment]
isn't that only a wrapper around a datapack? This is why I removed 'custom_dimension' since it is just a datapack? Trying to be more generic here.

**Comment by gnembon** [comment]
nah...

**Comment by gnembon** [comment]
suggesting updating the docs to include an example recipe and loottable modification instead of adding a function. Do you have a good examples of such?

**Comment by BisUmTo** [comment]
I'll make a pool request this evening 😉
