### ISSUE TITLE
Namespace issues between carpet extension mods.

### ISSUE THREAD

**Issue by 1schlick** [gnembon/fabric-carpet#802]
The carpet extension mods [Carpet TIS Addition](https://github.com/TISUnion/Carpet-TIS-Addition) and [minitweaks](https://github.com/manyrandomthings/minitweaks) both have a game rule called "renewableDragonEgg".

In the TIS version, dragon eggs dupe themselves when they are in a puddle of dragon's breath. In the minitweaks version, a dragon egg regenerates whenever the Ender Dragon is killed.

I have both of these mods because they both have some very useful game rules, but I would prefer to use the minitweaks version of renewableDragonEgg. Unfortunately, it is unlisted and only the TIS version of renewableDragonEgg is available. This is a problem.

There should be some way to differentiate between two different game rules based on the mod they come from. For example, if I wanted to refer to the TIS version of renewableDragonEgg, I would type TIS:renewableDragonEgg and if I wanted to refer to the minitweaks version of renewableDragonEgg, I would type minitweaks:renewableDragonEgg.

**Comment by altrisi** [comment]
Extensions can technically provide their own command instead, but I see that. However, currently there is no distinction between extensions when they add themselves to the command, IIRC the last to add their settings wins.

Relates to #702

**Comment by gnembon** [comment]
I think that's an overkill, if extensions want to make their own rulesets, then they can get their own command for that as altrisi said. If there are two rules of the same name, it means they do the same thing either repeating itself, or they should be called differently. Plugging into the /carpet command is optional and meant to be used when you add a few options. 

Treat `/carpet` as the namespace then.
