### ISSUE TITLE
Signs can be pushed/pulled with MBE on

### ISSUE THREAD

**Issue by BigBiBoi** [gnembon/fabric-carpet#803]
Not sure if intentional, but signs can be pushed/pulled by pistons with movableBlockEntities on.  Possible bug?  If intentional, is there a way to stop them from being able to be moved?

**Comment by DragonEggBedrockBreaking** [comment]
Signs are block entities, and are therefore pushed. You can stop them being pushed with immovable objects, like obsidian.

**Comment by BigBiBoi** [comment]
Yeah, I understand they're block entities, I just meant if carpet is trying to emulate Bedrock's MBEs, they shouldn't be on the list.  Should've made that clear, sorry.

**Comment by gnembon** [comment]
well, MBE are not really following anyone else's implementation. Try to push a doublechest in bedrock and see what happens there. Carpet restricts stuff made out of obsidian and other blocks that are explicitly non-pushable. Only exception is spawners for gameplay reasons. Pushing signs is fine.

**Comment by DragonEggBedrockBreaking** [comment]
In addition to what gnembon said, I believe the classifications of what is a block entity are different on bedrock and on java.
