### ISSUE TITLE
Failed to setup Fabric server environment

### ISSUE THREAD

**Issue by Petersilie2** [gnembon/fabric-carpet#81]
When I start the fabric server it crashes with this stack trace: https://pastebin.com/raw/W53e2usD
I have no other fabric mods installed, but the server can start with other mods when fabric-carpet is not present. I am running the newest fabric version on Minecraft 1.14.4 with fabric-carpet 1.0.8.

**Comment by DeadlyMC** [comment]
Could u provide the exact name of the jar file u placed in your mods folder? (Also 1.1.0 is out, u should update ;)  )

**Comment by Petersilie2** [comment]
1.1.0 throws the same error for me. I tried it with fabric-carpet-1.14.4-1.1.0+v190927.jar and fabric-carpet-1.14.4-1.0.8+v190918.jar, both throw the same error. I also tried some other jars, but I'm not sure if they threw the same error.

**Comment by DeadlyMC** [comment]
Hmm weird r u sure u have setup the fabric server properly? Maybe start from scratch and follow the guide from https://fabricmc.net/wiki/install
