### ISSUE TITLE
scarpet should have native support for json and b64 de/serializers

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#811]
maybe rename for consistency?
parse_nbt -> decode_nbt

then 

decode_b64(string) -> string
encode_b64(string) -> string
decode_json(string) -> value
encode_json(value) -> string

**Comment by Ghoulboy78** [comment]
wdym b64? also the json stuff would be pretty easy ngl, cos of parseJSON function in Value.java (or whatever it's called, I cant remember)

**Comment by altrisi** [comment]
b64 == base64.
