### ISSUE TITLE
Fake player can't go through End exit portal

### ISSUE THREAD

**Issue by SINBRO** [gnembon/fabric-carpet#82]
When a fake player tries to go through End exit portal, it (player, ya) disapears. It has position (right above the portal), but is not avilable for any interaction and is not visible.
P.s. End gate in Overworld works fine
1.14.4 server, carpet 1.0.8

**Comment by gnembon** [comment]
fixed by minecraft 1.17

**Comment by gnembon** [comment]
won't fix for 1.16.4 anyways, so closing.
