### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by candddddaa** [gnembon/fabric-carpet#822]
i installed carpet mod but when i open the game it keep crashing

**Comment by James103** [comment]
Do you have the crash report? If so, can you please attach the crash report here?

**Comment by candddddaa** [comment]
nope it gave exit code 0

**Comment by James103** [comment]
Exactly what mods do you have installed in your Minecraft instance? Also note the Minecraft and Fabric Loader versions if possible.

**Comment by candddddaa** [comment]
![image](https://user-images.githubusercontent.com/54152298/115229770-1d707e80-a11c-11eb-97da-a67cfc8a7b60.png)
![image](https://user-images.githubusercontent.com/54152298/115229859-3a0cb680-a11c-11eb-98e6-42f60e44418e.png)

**Comment by James103** [comment]
Can you try starting the game again and creating or joining a world? If that crashes (or after exiting the game), can you please attach the resulting latest.log (and crash report if any)?

**Comment by candddddaa** [comment]
[latest.log](https://github.com/gnembon/fabric-carpet/files/6335711/latest.log)
and no crash reports

**Comment by Ghoulboy78** [comment]
Does it close when you start a world, or upon loading up, or exactly when?

**Comment by candddddaa** [comment]
i cant open the game it crashes

**Comment by candddddaa** [comment]
hello ?

**Comment by Ghoulboy78** [comment]
well your sodium fabric is for version 1.16.3, so maybe that's the issue?

**Comment by candddddaa** [comment]
nope i deleted sodium but it doesnt change

**Comment by altrisi** [comment]
I think I've seen this before.

Update Fabric Loader (aka install a newer version).

**Comment by candddddaa** [comment]
i found the bug

**Comment by gnembon** [comment]
so?
