### ISSUE TITLE
Crash when entering single player world

### ISSUE THREAD

**Issue by Fallen-Breath** [gnembon/fabric-carpet#827]
MC version: 21w16a

fabric carpet: 1.4.33+v210421

Crash report: https://paste.ubuntu.com/p/wk9TCQDWyS/

**Comment by James103** [comment]
Did you get this crash with only Fabric Loader and Carpet mod installed?

**Comment by Fallen-Breath** [comment]
> Did you get this crash with only Fabric Loader and Carpet mod installed?

yes, with only fabric loader and fabric carpet

**Comment by gnembon** [comment]
weird..
anyways, sometimes fails, sometimes doesn't. 
I updated the file in releases.
