### ISSUE TITLE
with /player doing an action once while doing the action continuously causes a crash.

### ISSUE THREAD

**Issue by 12mylea** [gnembon/fabric-carpet#83]
This is what exactly I did on a superflat world.
/player gnembon spawn
/player gnembon look down
/player gnembon jump continuous
Drop a glass block to him
/player gnembon place continuous
/player gnembon place once

Then the game crashed, saying something about entity ticking (I can't remember exactly).

**Comment by gnembon** [comment]
what actions. Please specify commands that you have run and situation it was used in.

**Comment by gnembon** [comment]
can you send the stack trace that pops out?

**Comment by gnembon** [comment]
ok - replicated myself

**Comment by gnembon** [comment]
should be fixed in the next update.
