### ISSUE TITLE
player command does with floodgate

### ISSUE THREAD

**Issue by MrGeorgen** [gnembon/fabric-carpet#832]
When using [floodgate](https://github.com/GeyserMC/Floodgate-Fabric) an
unexpeted error occurs. The console does not show any error

**Comment by altrisi** [comment]
What error appears if you hover over the unexpected error message?

**Comment by MrGeorgen** [comment]
![image](https://user-images.githubusercontent.com/65063405/116004035-376cfe00-a601-11eb-8044-8cd7e018bd74.png)

**Comment by Camotoy** [comment]
This has been fixed on Floodgate's end.
