### ISSUE TITLE
[Scarpet] Exception handling doesn't work without enough stack deepness

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#861]
I was testing exceptions again, and just found that running `try(throw())` gets out of the stack.

Making the call indirect through a function call, like `try(throw_it());throw_it()->(throw())` also doesn't work.

Due to recent findings I think with enough deepness it would work, cause it did in my previous testing.

~If I recall correctly, that should get handled, shouldn't it? (since it's the definition of user defined)~

**Comment by altrisi** [comment]
Actually, I think this is something I found when making the catchable exceptions (cause nothing is being caught):

I _think_ `throw` needs to be a lazy-ish function (like a new ContextFunction). Not sure why, but if it wasn't then the try wouldn't always catch it. RN tested directly in the try and indirectly through a function call.

This was reverted in 74bd0bb81e40d1a2f7e588bfb56143962542a4b1

**Comment by gnembon** [comment]
![Capture](https://user-images.githubusercontent.com/41132274/118214364-f751ac00-b445-11eb-9ef3-3a5038de8c09.PNG)
Nice catch - probably this try and catch are in a completely ridiculous place and they should capture the exception when its thrown.

**Comment by gnembon** [comment]
surrounding eval

**Comment by gnembon** [comment]
I will give it more thought since its a clutch place to make changes so need to be 100% sure about it.
