### ISSUE TITLE
[Suggestion] Persistent fake players

### ISSUE THREAD

**Issue by TheDoddsy** [gnembon/fabric-carpet#862]
I find that one of the best features of 1.12 carpet is that fake players do not leave when the server is stopped, this helps especially in singleplayer when quite often you can leave and join a world quite often and have to repeatedly respawn the players

**Comment by gnembon** [comment]
https://github.com/gnembon/scarpet/blob/master/programs/utilities/keepalive.sc

Put it in the world scripts folder and you should be gucci.

**Comment by TheDoddsy** [comment]
Thanks for the answer!
Great work on carpet mod and your videos!
