### ISSUE TITLE
[Scarpet] Error in shapes library

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#863]
Tried to `import()` `draw_sphere` from the shapes library, this happened. @Ghoulboy78 since you wrote it.

```
Error while evaluating expression:         );
     HERE>> )
    positions
'positions' is not allowed after ')' in shapes at line 96, pos 5
```

Seems like a missing semicolon.

**Comment by Ghoulboy78** [comment]
That's weird, cos it parsed fine when I wrote and used it...

**Comment by gnembon** [comment]
I will fix it cause I am at it, but @Ghoulboy78 you might want to give it a check - you may have been editing your local file which took priority, meaning there might be some other differences you are not aware of.
