### ISSUE TITLE
`/script run run('...')` prepends `/execute positioned 0 0 0 rotated 0 0` to the inner command

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#866]
Basically, whenever you run a command from `/script run`, instead of running through the executor of the outer command like other commands do, the inner command instead runs as if the player was located at the coordinates (0, 0, 0) with rotation of (0, 0).

This means that `/script run run('tp ~ ~5 ~')` wouldn't move you up by 5 blocks, it would instead take you to the coordinates (0, 5, 0) with rotation of (0, 0).

In addition, the command `/script run run('tp @p ^10 ^ ^')` would now teleport you to the coordinates (10, 1e-39, 0) as the local coordinates are based off a rotation of (0, 0) instead of your actual rotation (the y-coordinate of 1e-39 is due to floating point error).

Modlist (MC 1.16.5):
```
Mods:
  [✔️] attribute-fix-fabric-1.0.1
  [✔️] carpet-extra-1.16.5-1.4.27
  [✔️] clientcommands-2.4.10
  [✔️] DisableCustomWorldsAdvice-1.2
  [✔️] fabric-api-0.31.0+1.16
  [✔️] fabric-carpet-1.16.5-1.4.35+v210505
  [✔️] itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029
  [✔️] litematica-fabric-1.16.4-0.0.0-dev.20210120.213004
  [✔️] lithium-fabric-mc1.16.5-0.6.4
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
  [✔️] minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
  [✔️] modmenu-1.16.8
  [✔️] NoFog-1.16.2b1-Fabric
  [✔️] notenoughcrashes-3.2.0-fabric
  [✔️] phosphor-fabric-mc1.16.3-0.7.1+build.11
  [✔️] shulkerboxtooltip-2.3.5+1.16.5
  [✔️] tweakeroo-fabric-1.16.4-0.10.0-dev.20210209.145902
  [✔️] Xaeros_Minimap_21.5.0_Fabric_1.16.5
  [✔️] XaerosWorldMap_1.13.1_Fabric_1.16.5
```

**Comment by gnembon** [comment]
Oh, I know what's going on, For whatever reason the execution of the commands is centered around the origin of the script execution point (which is zerozero for most scripts, and only varies for `/script scan` and alike). This might be a really old dependency. I will try to figure out when is might be used and fix it.
