### ISSUE TITLE
When you do /tick freeze, chunk loading tickets are still calculated in real time.

### ISSUE THREAD

**Issue by PrimePlatypus12** [gnembon/fabric-carpet#867]
As the title mentions, when you do /tick freeze chunk loading tickets are calculated in real time. This means that if you freeze the game for over 15 seconds nether portal chunk loaders will stop functioning until they are reloaded. I'm not really sure why this happens because chunk loading tickets seem to adjust fine when you slow down the game with /tick rate.

**Comment by James103** [comment]
Can you try doing `/tick freeze deep` instead of a regular `/tick freeze`?

**Comment by PrimePlatypus12** [comment]
It froze the chunk tickets properly, thanks for the help I guess I just never noticed a deeper freezing option before lol
