### ISSUE TITLE
Carpet not working with Gunpowder mod 

### ISSUE THREAD

**Issue by SlimeBoi2006** [gnembon/fabric-carpet#871]
Hello, The other day I tried to add the gunpowder mod to my server. Unfortunately this caused my server to freeze up and not start up. Is there any fix to make these two mods compatible?

https://mcpaste.io/2c0459b4ec348f3c

**Comment by altrisi** [comment]
Yes, this was fixed long time ago, you just have to update your Carpet.

Duplicate of #765.

**Comment by SlimeBoi2006** [comment]
Thank You!
