### ISSUE TITLE
Issue with starting worlds

### ISSUE THREAD

**Issue by aipimfrito** [gnembon/fabric-carpet#887]
I installed Carpet, like, today, and the mod was functioning perfectly; all my worlds were normal. But then I tried to add some mods for testing, which I removed after, and my worlds woudn't load. They are stuck at 0%. I tried to join them with Optifine, everything was normal.
I went to check the logs and this appeared hundreds of times in a few seconds before I restarted my computer (I coudn't quit the game): 
**[Server thread/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldChunk_fillUpdatesMixin->@Redirect::onAdded(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V with priority 1000, already redirected by worldedit.mixins.json:MixinWorldChunk->@Redirect::setBlockStateHook(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V with priority 1000**
There is "carpet" in the middle of the log, then I assumed it could be an issue with the mod. It may also be WorldEdit, but I already had it before.

**Comment by gnembon** [comment]
update your world edit and you should be good.
