### ISSUE TITLE
Async ViewDistance - Sentence

### ISSUE THREAD

**Issue by DeZoWaRe** [gnembon/fabric-carpet#893]
Hi, I have a cool idea!
Your plugin generates chunks, but if you can implement visibility like this plugin, it will be a breakthrough!

https://www.spigotmc.org/resources/fartherviewdistance.84950/

**Comment by altrisi** [comment]
I don't think that really fits into Carpet...

I'd suggest you to use the bobby client mod instead. Client-side but may be good enough. Else that behaviour would be better for a standalone mod IMO given it's not really simple.
