### ISSUE TITLE
[Question] Is this supposed to fall-through?

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#895]
Was bored and passed google's errorprone in commandline (was awful)
https://github.com/gnembon/fabric-carpet/blob/d3c3c8e1572715a0e50b2bb25c637a64984f0117/src/main/java/carpet/script/Expression.java#L853-L856
https://github.com/gnembon/fabric-carpet/blob/d3c3c8e1572715a0e50b2bb25c637a64984f0117/src/main/java/carpet/script/CarpetScriptHost.java#L744-L752

**Comment by gnembon** [comment]
never heard of that. Once 1.17 is out and stabl-ish, I should do the full sweep

**Comment by gnembon** [comment]
yeah, these have no effect. Don't matter. You can do good to errorprone if you want to, but maybe on 1.17 when its stable. Not sure if there are plans for starting snapshots immediately after 117
