### ISSUE TITLE
__on_tick() seems to be too fast sometimes.

### ISSUE THREAD

**Issue by poombus** [gnembon/fabric-carpet#907]
I don't know how to replicate this, all I know is that it usually happens when there are multiple players on the server (real and fake).

Say I have a scoreboard objective that increases by 1 every second.

```
__on_tick() -> (
    scoreboard('ticks','val',scoreboard('ticks','val')+1);
    if(scoreboard('ticks','val')%20==0,
       scoreboard('seconds','val', scoreboard('seconds','val')+1);
    );
);
```

However, having players on the server seems to speed up how fast `scoreboard('seconds','val')` increases (faster than a second). The more players there are, the faster it counts up.

**Comment by James103** [comment]
Is the app on `player` scope? If so, `__on_tick` gets executed once per tick **per player**.

**Comment by poombus** [comment]
As in running `/script load SCRIPT global`? I thought that might've been it, but it still counts too fast.

Or am I misunderstanding how to change the scope of the app.

**Comment by poombus** [comment]
Ah, I looked at the docs a bit more closely.

I see you need to change the scope in __config().

I thought you changed it by adding/omitting "global" when running the `/script load command` lmao.

Thanks for that @James103.
