### ISSUE TITLE
X, Y, Z properties of players/entities are all the same

### ISSUE THREAD

**Issue by shinyb123** [gnembon/fabric-carpet#91]
The location of players/entities is x, x, x instead of x, y, z.

Noticed that by running /camera start and seeing in chat "Started path at -211 -211 -211".

**Comment by gnembon** [comment]
yeah, its fixed already - in camera app its only visual - the actual coords are using 'position' feature which was unaffected.

**Comment by shinyb123** [comment]
Weird. I added another point and played the camera, and got teleported way below the bedrock (Because the X coordinate was negative).
