### ISSUE TITLE
[Bug] "/player <player> use continuous" doesn't fire crossbows or bows

### ISSUE THREAD

**Issue by CarbonGhost** [gnembon/fabric-carpet#911]
When using the player command to use a bow or crossbow continuously the player will not fire the crossbow/release the bow. The same problem occurs with tridents.
Running on Carpet 1.4.40.

**Comment by gnembon** [comment]
well, you have to stop drawing them in infinity and release them at some point, right?

**Comment by CarbonGhost** [comment]
Seems like they should shoot after drawing, every other use. Unless this would break functionality of some sort.

**Comment by 4winyt** [comment]
It's just simulating constantly holding down the right mouse button, it wouldn't shoot and reload if a player did that.

**Comment by gnembon** [comment]
yeah, just after use continuous, do use once for shot, or use continuous for shot and reloading.
