### ISSUE TITLE
[Bug] Some issue

### ISSUE THREAD

**Issue by spiiross** [gnembon/fabric-carpet#912]
Hi,
I'd like to ask about the command 'onePlayerSleeping' is it removed or missing ?.
The dragon egg breaking bedrock  feature is not working in 1.17 bellow world level 0, Also y0 bedrock removal should be updated .

**Comment by James103** [comment]
> I'd like to ask about the command 'onePlayerSleeping' is it removed or missing ?.

You should instead use `/gamerule playersSleepingPercentage`. A value of either 0 or 1 is sufficient to emulate the old one player sleeping behavior (use 0 if you don't mind immediately skipping nights or if your server sometimes has >100 players online at once).

**Comment by spiiross** [comment]
> You should instead use `/gamerule playersSleepingPercentage`. To emulate the old one-player-sleeping behavior, use a value of 0, as in `/gamerule playersSleepingPercentage 0`.
Thank you.

**Comment by spiiross** [comment]
> You should instead use `/gamerule playersSleepingPercentage`. To emulate the old one-player-sleeping behavior, use a value of 0, as in `/gamerule playersSleepingPercentage 0`.

Nice ,Thank you.

**Comment by altrisi** [comment]
gnembon/carpet-extra#215 should fix the dragon egg issue in Carpet extra once merged and released, you can get the artifacts from the PR if you want the fix earlier (Checks->PR builds->Artifacts->first jar in the zip).

**Comment by spiiross** [comment]
Great, thank you for the info.
