### ISSUE TITLE
renewableIce bug

### ISSUE THREAD

**Issue by BlueDinoKing** [gnembon/fabric-carpet#916]
Instead of making ice, carpet dupes the anvil and makes packed ice out of 2-4 ice
![image](https://user-images.githubusercontent.com/80439860/121755476-22263300-cacc-11eb-9a78-ba9ab7b85f46.png)

**Comment by BlueDinoKing** [comment]
https://www.youtube.com/watch?v=dHlXAviOb7I&ab_channel=SilasK

example

**Comment by altrisi** [comment]
Isn't renewableIce a Carpet Extra feature? Then this should be reported in that repo instead. Definitely seems to be bugged though.

**Comment by BlueDinoKing** [comment]
> Isn't renewableIce a Carpet Extra feature? Then this should be reported in that repo instead. Definitely seems to be bugged though.

https://www.youtube.com/watch?v=nmqNDkjmJ7c&ab_channel=ilmango don't think so

**Comment by gnembon** [comment]
the ice feature has just been fixed in carpet-extra. Probably next week there will be another release, but for now you can get it via action artifacts:
https://github.com/gnembon/carpet-extra/suites/2980900706/artifacts/67262536
