### ISSUE TITLE
Carpet incompatibility with Optifabric

### ISSUE THREAD

**Issue by jacobmichaelis** [gnembon/fabric-carpet#923]
Just updated to 1.17 using Fabric. Everything works but only if I remove fabric-carpet-1.17-1.4.40+v210608.jar or optifabric-1.11.1.jar from my mods folder. Otherwise I get the generic game crash message in the launcher. There seems to be an incompatibility between those mods. For reference I'm also using  preview_OptiFine_1.17_HD_U_G9_pre21.jar. Would like to use these in tandem again. Thanks.

**Comment by James103** [comment]
Do you have a crash report or Minecraft logs from reproducing this issue? If so, can you please post them here?

**Comment by AustinVW2002** [comment]
I'm pretty confident we have the same problem because im using the same files as him above. hope this helps
----------------------------------------------------------------------------------------------------------------------------------
[00:01:44] [main/INFO]: Loading for game Minecraft 1.17
[00:01:45] [ForkJoinPool-1-worker-13/WARN]: Non-Fabric mod JAR at "C:\Users\123ta\AppData\Roaming\.minecraft\versions\fabric-loader-0.11.5-1.17\mods\preview_OptiFine_1.17_HD_U_G9_pre21.jar", ignoring
[00:01:45] [main/INFO]: [FabricLoader] Loading 51 mods:
	- carpet@1.4.40
	- fabric@0.35.1+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.1.0+1d383bb63d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b44633d
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.8+a02b44633d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-networking-api-v1@1.0.11+b7ab61213d
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afa3d
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
	- fabric-rendering-fluids-v1@0.1.13+a02b44633d
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-structure-api-v1@1.1.10+be9da3103d
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabricloader@0.11.5
	- java@16
	- minecraft@1.17
	- mm@2.2
	- modmenu@2.0.2
	- optifabric@1.11.1
[00:01:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/123ta/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[00:01:45] [main/INFO]: Compatibility level set to JAVA_16
[00:01:45] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value

**Comment by gnembon** [comment]
related to https://github.com/Chocohead/OptiFabric/issues/245

this time the case manifested itself on the optifabric side. Not the problem with optifabric - probably optifine changed again something. Lets say what optifabric devs say here.

**Comment by jacobmichaelis** [comment]
@AustinVW2002 yes this looks like the same issue. Just a little more info:

```
[main/INFO]: Loading for game Minecraft 1.17
[ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "C:\Users\<hidden>\AppData\Roaming\.minecraft\mods\preview_OptiFine_1.17_HD_U_G9_pre21.jar", ignoring
[main/WARN]: Warnings were found!  Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121d5, also found 0.4.7+b7ab61213d
[main/INFO]: [FabricLoader] Loading 55 mods: fabric-renderer-api-v1@0.4.3+676f40fa3d, fabric-keybindings-v0@0.2.2+36b77c3e3d, fabricloader@0.11.3, fabric-structure-api-v1@1.1.10+be9da3103d, fabric-containers-v0@0.1.12+a02b44633d, fabric-dimensions-v1@2.0.10+a02b44633d, fabric-object-builder-api-v1@1.10.9+b7ab61213d, java@16, fabric-game-rule-api-v1@1.0.6+a02b44633d, fabric-api-base@0.3.0+a02b44633d, fabric-rendering-data-attachment-v1@0.1.5+a02b44633d, mm@2.2, fabric-textures-v0@1.0.6+a02b44633d, tweakeroo@0.10.0-dev.20210608.211857, fabric-rendering-fluids-v1@0.1.13+a02b44633d, litematica@0.0.0-dev.20210608.211719, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, fabric-lifecycle-events-v1@1.4.4+a02b44633d, fabric-renderer-registries-v1@3.2.0+a02b44633d, minihud@0.19.0-dev.20210609.185508, carpet-extra@1.4.40, fabric-loot-tables-v1@1.0.4+a02b44633d, fabric@0.35.1+1.17, carpet@1.4.40, fabric-particles-v1@0.2.4+a02b44633d, fabric-networking-v0@0.3.2+92519afa3d, fabric-api-lookup-api-v1@1.1.0+1d383bb63d, fabric-networking-blockentity-v0@0.2.11+a02b44633d, fabric-screen-handler-api-v1@1.1.8+a02b44633d, minecraft@1.17, fabric-command-api-v1@1.1.1+a02b44633d, fabric-screen-api-v1@1.0.4+198a96213d, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, fabric-renderer-indigo@0.4.8+a02b44633d, fabric-crash-report-info-v1@0.1.5+be9da3103d, fabric-item-api-v1@1.2.4+a02b44633d, fabric-events-interaction-v0@0.4.8+a02b44633d, fabric-entity-events-v1@1.1.0+a02b44633d, fabric-rendering-v0@1.1.2+92519afa3d, fabric-key-binding-api-v1@1.0.4+a02b44633d, fabric-rendering-v1@1.6.0+a02b44633d, fabric-resource-loader-v0@0.4.7+b7ab6121d5, malilib@0.10.0+dev.22, fabric-content-registries-v0@0.2.2+a02b44633d, fabric-tag-extensions-v0@1.1.4+a02b44633d, fabric-biome-api-v1@3.1.11+c345aea83d, optifabric@1.11.1, fabric-commands-v0@0.2.2+92519afa3d, fabric-registry-sync-v0@0.7.10+e2961fee3d, fabric-mining-levels-v0@0.1.3+92519afa3d, fabric-networking-api-v1@1.0.11+b7ab61213d, fabric-events-lifecycle-v0@0.2.1+92519afa3d, fabric-item-groups-v0@0.2.10+b7ab61213d, fabric-models-v0@0.3.0+a02b44633d, fabric-object-builders-v0@0.7.3+a02b44633d
[main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/<hidden>/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[main/INFO]: Compatibility level set to JAVA_16
[main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
```

I upgraded my local Java to 16 and still nothing. But that's really just a warning. Seems the real issue is a conflicting dependency on  fabric-resource-loader-v0.

**Comment by Blueil** [comment]
Use the [alpha version of optifabric](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3358050), seems like chocohead fixed it with their latest commit
