### ISSUE TITLE
Empty required options in wiki rule list

### ISSUE THREAD

**Issue by RubixDev** [gnembon/fabric-carpet#926]
On [the wiki page with all carpet rules](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings) for the rules `creativeFlyDrag` and `creativeFlySpeed` it shows it would be strict, but does not list options, as seen in this screenshot:

![image](https://user-images.githubusercontent.com/35602040/122105905-938e1a80-ce19-11eb-81e8-e106f70f315f.png)

**Comment by Firigion** [comment]
You should be able to edit htose yourself, no? It's just a Wiki.

**Comment by altrisi** [comment]
Yes, but it would be reset on release since it's automatically updated to add new rules or rule changes.
