### ISSUE TITLE
Villagers do not trade with carpet installed (1.17)

### ISSUE THREAD

**Issue by thisjaiden** [gnembon/fabric-carpet#927]
When using carpet with Minecraft 1.17, villagers do not respond to being right clicked by players. This prevents trading entirely. Villagers seem to be functional besides this, going to workstations and doing tasks.

**Comment by altrisi** [comment]
I think this was an issue with the legacy track command, try resetting your villager trackers (`/track`).

**Comment by thisjaiden** [comment]
This indeed fixed my problem. Thank you.
