### ISSUE TITLE
[Suggestion] Q on recipe to craft and drop

### ISSUE THREAD

**Issue by d1gress** [gnembon/fabric-carpet#93]
Pressing Q (drop keybind) on a craftable recipe will put it into the crafting slots and drop the result.

**Comment by Ghoulboy78** [comment]
that's already there in ctrlQcrafting isn't it?

**Comment by Vonr** [comment]
thats only for control q

**Comment by Vonr** [comment]
unless something changed

**Comment by Ghoulboy78** [comment]
idk, go test

**Comment by Vonr** [comment]
you do realise this ussue is 6 months old right

**Comment by Ghoulboy78** [comment]
oh jeez ur right

**Comment by bencrazyalchemist** [comment]
Also that's impossible to do bc carpet is a server mod and dosent affect the client

**Comment by gnembon** [comment]
Amen
