### ISSUE TITLE
Scarpet suggestion: Add query and modify actions for `TicksFrozen`

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#932]
Currently (Minecraft 1.17, Carpet mod 1.4.40), there is no way to `query(...)` or `modify(...)` the value of `TicksFrozen` in any way. A workaround is to use `/data merge entity` commands to modify the `TicksFrozen` value, but that does not work on players.

For example, I would like to make players and mobs slowly freeze to death if they are currently holding blue ice. The mobs part would work fine as I can just use commands, but the player part would require its own separate action under the `query` and `modify` functions to work properly.

**Comment by gnembon** [comment]
noun (like 'fire') would be 'freeze', 'frost', 'freezing'?
immune_to_freeze? susceptible_to_freeze? -frost, -freezing

is_freezing is already good for is_burning antonym

**Comment by James103** [comment]
For example,
`query(e, 'is_freezing')` checks whether the entity is currently taking freeze damage.
`query(e, 'frost')` returns the entity's `TicksFrozen` value.
`modify(e, 'frost', value)` writes `value` to the entity's `TicksFrozen` tag.
