### ISSUE TITLE
[Scarpet][Feature Request] Intercepting and reacting to player chat

### ISSUE THREAD

**Issue by Scarabytes** [gnembon/fabric-carpet#937]
Hey :)

I was browsing through the Scarpet API docs and noticed, that there is no event for when a player sends a chat message.  
Would it be possible to add that or is the only way for player chat to be processed by Scarpet via the command system?  
Regarding that, can one define more than one top-level command per app? For instance `/myapp` and `/myapp_admin`?

**Comment by gnembon** [comment]
currently its one command per app. I don't thing there is nothing that wouldn't allow you to branch off into `/myapp admin ...`

**Comment by d-Pixie** [comment]
Second the suggestion of adding `player_chat` and/or `server_chat` interception. I also couldn't find it in the source 🙂

**Comment by replaceitem** [comment]
This is now possible with #1312 and #1497
