### ISSUE TITLE
(creative mode) Carpet bots fall after being spawned in 1.17

### ISSUE THREAD

**Issue by JonasStorm** [gnembon/fabric-carpet#938]
If I recall correctly, in the carpet mod tutorial it was described as the way to get creative mode carpet bots to fly, and due to this you can't get a flying carpet bot.
This is not true for the newest version of carpet in 1.16.4

**Comment by gnembon** [comment]
well, the most reliable method I use and works right now is spawn them in spectator and switch to creative - then they will fly. Spawning in creative on survival places them on the ground. This worked in the past and works now. Lemme see if I can do something to set its flying status to borrow from the player that spawns them.
