### ISSUE TITLE
[Startup Crash] Can't start fabric server with carpet mod

### ISSUE THREAD

**Issue by Carbon-Key** [gnembon/fabric-carpet#94]
**Preface:**
I'm afraid I couldn't find any guidelines on how to post an issue here so I hope I have formatted this in a useful way! If this is the wrong place to write this, please kindly direct me to the proper location.

I'd be more than happy if someone responded to this with a "It's simple dummy, don't you know how to do anything!? Just do X!"

**Issue:**
I can't for the life of me get the carpet mod working on a server. I can start up the world and join it with clients just fine with nothing in the mods folder but, as soon as I add the carpet jar, it can no longer start up the server. 

I am just not familiar enough with fabric and carpet to know why these mixins would be having an issue.

**Fabric and Carpet versions/files:**
I am trying to use version 1.1.3 (fabric-carpet-19w42a-1.1.3+v191016.jar) for MC 1.14.4 with the vanilla fabric-server version from "fabric-installer-0.5.1.36.jar" (loader 0.6.3+build.167).

**Operating system/java version:**
I'm trying to run it on Ubuntu Server 18.04.3 using Java SE Runtime 1.8.0_181-b13.

**Log file:**
[https://pastebin.com/n6EFz8nL](url)

Any help you could offer (even if it is pointing me somewhere else) would be greatly appreciated.

Thanks!

**Comment by gnembon** [comment]
Yeah - make sure you are using 1.14 version of the mod for 1.14 game. You are trying to run 1.15 version of the carpet mod on a 1.14 server. Please download proper mod jar file.

**Comment by Carbon-Key** [comment]
Oh, excellent! I knew it must be me doing something stupid!

I misunderstood and thought it was a combined jar, I've spotted 1.1.3 for 1.14.4 in the list now.

Thanks so much! Your mod and youtube videos are awesome! :D
