### ISSUE TITLE
1.17 optifine and carpet cannot run at the same time

### ISSUE THREAD

**Issue by night-sword** [gnembon/fabric-carpet#941]
I don’t know because optifine is the development version or how
I use OptiFine HD U G9 pre21 and optifabric
Can not play with carpet (the latest version v1.4.40)

**Comment by James103** [comment]
Do you have the full logs and crash report? If so, can you please post them here?

**Comment by Blueil** [comment]
https://github.com/gnembon/fabric-carpet/issues/923

**Comment by night-sword** [comment]
> [解決方案](https://github.com/gnembon/fabric-carpet/issues/923#issuecomment-864507146)

Thanks, this is a great help to me, and it makes the game run successfully
