### ISSUE TITLE
Carpet player cause crashes when update suppressing

### ISSUE THREAD

**Issue by senseiwells** [gnembon/fabric-carpet#942]
When carpet players interact (placing, breaking blocks etc.) with update suppressors it causes crashes.

Normally any updates caused by a player bypass this crash however this is not the case for the carpet players.

To reproduce just have an update suppressor, spawn a carpet player and have it place a block next to the suppressor.

Tested on fabric carpet 1.16.5 1.4.40

**Comment by gnembon** [comment]
can you send a crash report?

**Comment by senseiwells** [comment]
[crash-2021-06-22_09.16.04-server.txt]
(https://github.com/gnembon/fabric-carpet/files/6692910/crash-2021-06-22_09.16.04-server.txt)

**Comment by gnembon** [comment]
Please try with this jar:
https://github.com/gnembon/fabric-carpet/actions/runs/961294266

It should resolve this issue.

**Comment by senseiwells** [comment]
Yes, issue resolved.
