### ISSUE TITLE
Several other entities are classified as living entities even though they aren't.

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#947]
Similar to in #933, there are a couple of other entities that are classified as living entities even though they shouldn't.
* Marker
* Shulker Bullet
* (Possibly) Armor Stand

The first two are not living entities for obvious reasons, while the last one has some characteristics of a living entity (mainly HP, attributes, armor, and the ability to have potion effects applied), it is not actually a living entity. All three of the above entities fail when used in `/perimeterinfo ~ ~ ~ <entity to test>`.

**Comment by gnembon** [comment]
Thanks. Main problem is technical and internal, but long story short: we needed to list all types that belong to specific categories and these were missing. Will fix it.
