### ISSUE TITLE
onePlayerSleeping setting was remove in minecraft1.17

### ISSUE THREAD

**Issue by a1637850680** [gnembon/fabric-carpet#952]
i can‘t use onePlayerSleeping setting in carpet 1.4.40 for minecraft 1.17，it always tips unknown rule

**Comment by James103** [comment]
The game rule provided by Carpet mod has been superseded by the corresponding game rule in vanilla. Use the following command to achieve a similar effect:
`/gamerule playersSleepingPercentage 0`

**Comment by a1637850680** [comment]
haha，thx my bor，it works ！

**Comment by altrisi** [comment]
If the issue was resolved, please close it!
Thanks!
