### ISSUE TITLE
Minecraft failed to enter a world in the latest version

### ISSUE THREAD

**Issue by NanJack1998** [gnembon/fabric-carpet#955]
after i update the latest version of carpet,whenever i enter a world ,only a crash report instead

here's the crash report
https://paste.ubuntu.com/p/NFYGckWWgB/

**Comment by James103** [comment]
Can you try disabling WorldEdit mod and then (re)loading a world?

**Comment by altrisi** [comment]
You are using an old version of WorldEdit, this bug was fixed long time ago on their side.

**Comment by NanJack1998** [comment]
thanks, i will have a try
