### ISSUE TITLE
Repeating command block executing `/script run` spams Minecraft Log

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#963]
Currently (as of Carpet mod ac24a67c006ea40a87187d930d089cd1c14bffb1 and Minecraft 1.17.1-pre1), when a repeating command block executes `/script run` with any valid script code and `/carpet scriptsOptimization` is turned on, the command block causes the script compiler to output the following line to the Minecraft Log every tick:
```
Input code size for system chat: # nodes, # deep
```
https://github.com/gnembon/fabric-carpet/blob/d29adf3a4875c34b04cbb2f7b4ff2a3ae3061025/src/main/java/carpet/script/Expression.java#L1077

Both `/carpet scriptsDebugging` and `/gamerule commandBlockOutput` are turned off, but the message still gets printed to the Minecraft Log regardless. Whether that message gets printed could depend on either of the two above rules, or another Carpet mod rule.

**Comment by gnembon** [comment]
dully noted
