### ISSUE TITLE
[scarpet] 'int' Integer command argument type acting as string and ignoring the 'suggest' options.

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [gnembon/fabric-carpet#964]
Carpet 1.4.40, Carpet-extra 1.4.40, Minecraft Release 1.17
Below script's 'world size' argument acts as a string and gives these three suggestions (not options): "", "quoted phrase", and word.
The script is loaded as a file, not as a command, and is a .sc file, not a .txt file.
[simulator_load_cellular.txt](https://github.com/gnembon/fabric-carpet/files/6726492/simulator_load_cellular.txt)

**Comment by altrisi** [comment]
I think this is #936, which is fixed in the upcoming version.

Until that the workaround is to not use a `_` in custom argument names.

**Comment by gnembon** [comment]
yeah, you would need to define 'size' argument type, but that is technically enabled for 1.4.41, so closing. So either define it as 'size' or use .41 on 1.16.5 or wait I guess till 1.17.1
