### ISSUE TITLE
MC-2025 Fix

### ISSUE THREAD

**Issue by LucasVon** [gnembon/fabric-carpet#97]
Hello, adding this here as requested on CurseForge. I'd love to see the fix for [MC-2025](https://bugs.mojang.com/browse/MC-2025) added again on Carpet. Extremely persistent bug that has returned on the latest versions.

Thank you in advance!

**Comment by gnembon** [comment]
The fix for that will be added to carpet-extra repo, since it requires permanently to add tags to all entities, which steps on the carpet mod paradigms of not changing permanently the world data in any way.
