### ISSUE TITLE
[Feature] Nether Superflat

### ISSUE THREAD

**Issue by Tokara1** [gnembon/fabric-carpet#970]
Add the possibility of the nether generating as Superflat when ovw is set to superflat.
Since for my taste making stuff in the nether in testing worlds is annoying because you cant superflat generate the nether and have to edit the world out eg for farms.  
Incase there is a mod or tool for this i missed it.

**Comment by Firigion** [comment]
I know this is not exactly wht you asked for, but in vanilla you can set a superflat world to a single biome and make that biome a nether biome of your choosing. There's also a free superflat nether in every world: on top of the bedrock ceiling.

**Comment by gnembon** [comment]
I get that. Definitely something that could be done via datapacks
