### ISSUE TITLE
"Player" has a bug

### ISSUE THREAD

**Issue by AbrasiveBoar902** [gnembon/fabric-carpet#973]
It will crash if I use player command to update the update suppression(like put a block nearby)

**Comment by James103** [comment]
Likely a duplicate of #942 
Quoting from @gnembon (original comment at https://github.com/gnembon/fabric-carpet/issues/942#issuecomment-866115658):
> Please try with this jar:
> https://github.com/gnembon/fabric-carpet/actions/runs/961294266
> 
> It should resolve this issue.

**Comment by gnembon** [comment]
Please try with 1.4.42
