### ISSUE TITLE
Crash at launch with Fabric API

### ISSUE THREAD

**Issue by Tre5et** [gnembon/fabric-carpet#978]
When trying to launch Carpet 1.4.41 or 1.4.42 with Farbric API 0.36.0 the game doesn't start and returns to the launcher creating the following crash log:
[crash-2021-07-03_21.49.14-client.txt](https://github.com/gnembon/fabric-carpet/files/6758979/crash-2021-07-03_21.49.14-client.txt)

**Comment by gnembon** [comment]
1.4.41 and 42 are not for 1.17.0 - use 1.17.1 (rc) with them.

**Comment by gnembon** [comment]
left open for visibility, cause that's a second report already
