### ISSUE TITLE
Crash at start in version 1.4.8 in mc 1.15.2

### ISSUE THREAD

**Issue by Peter-JY** [gnembon/fabric-carpet#979]
Minecraft 1.15.2 crashed when I start it. It has some mods, including BBOR, Volex Map, Tweakeroo, and so on. 

If I don’t add fabric-carpet, the game can run normally. But after I add this mod, the game crashes without any reports (from fabric).

I will put the logs here.

[Crash Report of 1.15.2+Fabric-loader-0.11.6.zip](https://drive.google.com/file/d/1h9CPr_045ZO4rnR57jzwrOh_5DlhFznh/view?usp=sharing)

**Comment by gnembon** [comment]
1.15 is no longer supported and provided as is. Compatibility with other mods is not guaranteed.

**Comment by Peter-JY** [comment]
Oh, I've found that this is caused by Optifabric Mod.

**Comment by Fallen-Breath** [comment]
This fork of fabric-carpet 1.15.2 works with optifabric + OptiFine_1.15.2_HD_U_G6 if you still need that

https://github.com/Fallen-Breath/fabric-carpet/releases/tag/1.4.8-fallensfork.1%2Bv210821
