### ISSUE TITLE
Shulker boxes losing names (most likely because of stackableShulkerBoxes)

### ISSUE THREAD

**Issue by CapixKW** [gnembon/fabric-carpet#98]
When I place a renamed shulker box and then break it with nothing inside, the shulker box looses its name. Pretty sure it's beacasue of stackableShulkerBoxes, cause I don't think anything else in carpet changes shulker boxes and it doesn't occur on server without Carpet.

**Comment by gnembon** [comment]
likely so - this should not happen and I will get to it soon.

**Comment by gnembon** [comment]
Pushed the fix, should be fixed in the next update. Shulkerbox will clear its nbt only when its entirely empty
