### ISSUE TITLE
Incompatibility with Fabric API 0.36.0

### ISSUE THREAD

**Issue by Rodorenn** [gnembon/fabric-carpet#981]
When running both Carpet 1.4.42 and Fabric API 0.36.0 Minecraft crashes at startup.  

Minecraft version: 1.17
Fabric loader version: 0.11.6
Fabric API version: 0.36.0
Carpet version: 1.4.42

When running Fabric API alone, game launches successfully.   When running Carpet alone, game launches successfully.  When running both mods together, game crashes with attached crash report.

[crash-2021-07-05_07.43.54-client.txt](https://github.com/gnembon/fabric-carpet/files/6764241/crash-2021-07-05_07.43.54-client.txt)

**Comment by gnembon** [comment]
1.4.42 is listed for 1.17.1, not 1.17.0

**Comment by carles34** [comment]
so what version do we have to use to play on the 1.17.0? can u paste the link please

**Comment by James103** [comment]
Carpet mod 1.4.40 is the last Carpet mod version to support 1.17.0.
https://github.com/gnembon/fabric-carpet/releases/download/1.4.40/fabric-carpet-1.17-1.4.40+v210608.jar

**Comment by gnembon** [comment]
ditch 1.17
