### ISSUE TITLE
[Script download] Loading suggestions async

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#985]
Currently, the app store and its subfolders are fetched synchronously, halting the game thread. This can be a problem if internet connection is slow. Given the suggestions are not crucial and shouldn't cause problems if being loaded asynchronously, it probably would be a good idea to make them async.

I'll try this one SoonTM.

**Comment by James103** [comment]
> Currently, the app store and its subfolders are fetched synchronously, halting the game thread. This can be a problem if internet connection is slow.

Is there a timeout in place for this, so that the game/server does not freeze for too long and to prevent `java.lang.Error: Watchdog` crashes caused by it taking more than 60 seconds to fetch remote resources for the suggestions?

**Comment by altrisi** [comment]
Only the timeout provided by Java's old `URLConnection`, if any.
