### ISSUE TITLE
[Feature] Slow amethyst bud breaking

### ISSUE THREAD

**Issue by goodideagiver** [gnembon/fabric-carpet#988]
A new carpet rule to disable pickaxe breaking speed on `minecraft:budding_amethyst` that would let you break amethyst buds without being scared of accidentally breaking budding amethyst block
![obraz](https://user-images.githubusercontent.com/55458485/124824355-8ecd0a00-df72-11eb-943b-1f4a399005a0.png)

**Comment by James103** [comment]
You could use a data pack to remove block `minecraft:budding_amethyst` from tag `#minecraft:mineable/pickaxe`, but by default, doing that would also need to reset the contents of the tag back to the default list (minus the aforementioned block), which may be unwanted for some players.

**Comment by gnembon** [comment]
yeah, datapackable

**Comment by gnembon** [comment]
also 100% scarpetappable, so no need for custom rule. Feel free to request / propose such an app to be added to the appstore.

**Comment by James103** [comment]
Scarpet app one-liner that implements what you're looking for:

Method 1: `/script run` command:
```
/script run __on_tick() -> (player = player();if(player~'trace' == query(player, 'trace', 4.5, 'blocks') && player~'trace' == 'budding_amethyst',modify(player, 'effect', 'mining_fatigue', 1, 2, false, false)));
```
Method 2: Standalone app (create an app with the following code and load it):
```
__on_tick() -> (
	player = player();
	if(player~'trace' == query(player, 'trace', 4.5, 'blocks') && player~'trace' == 'budding_amethyst',
		modify(player, 'effect', 'mining_fatigue', 5, 2, false, false)
	)
);
```
