### ISSUE TITLE
[BUG] Non-empty ShulkerBox can stack in player Inventory.

### ISSUE THREAD

**Issue by plusls** [gnembon/fabric-carpet#989]
https://github.com/gnembon/fabric-carpet/blob/c9b8511e1bed74b82e0d19d87f05dcaef89af428/src/main/java/carpet/mixins/Slot_stackableSBoxesMixin.java#L20

I think it should use `InventoryHelper.shulkerBoxHasItems` to check empty shulkerbox.

**Comment by gnembon** [comment]
kinda useful, but kinda OP as well. Will adjust
