### ISSUE TITLE
[Bug][Scarpet] Crash on accessing biome(block, 'foliage_color')

### ISSUE THREAD

**Issue by Crec0** [gnembon/fabric-carpet#992]
**Issue**
Earlier report #870 fixed the issue but with the carpet release 1.4.41 and onward (didn't test before them) all features work fine but `'foliage_color'`. When accessing `foliage_color`, it will crash the server. WAI in single player

**Crash report**
[crash_report.txt](https://github.com/gnembon/fabric-carpet/files/6793015/crash-2021-07-09_10.23.10-server.txt)

**Comment by James103** [comment]
Looks like you were on a dedicated server and the server tried to access client-side code, causing the crash.

**Comment by gnembon** [comment]
yeah, client function. Thanks for noticing that
